Repository rust-lang/crates.io, pull requests merged in 2018-04, with the labels that each got.

#1308 Update `ember-cli-clipboard` to v0.9.0
  package-lock.json
  package.json
Labels: A-ember

#1310 Update `ember-page-title` to v4.0.3
  app/templates/application.hbs
  package-lock.json
  package.json
Labels: A-ember

#1305 Add `ember-cli-template-lint` dependency
  .template-lintrc.js
  app/templates/application.hbs
  app/templates/components/api-token-row.hbs
  app/templates/components/badge-appveyor.hbs
  app/templates/components/badge-circle-ci.hbs
  app/templates/components/badge-codecov.hbs
  app/templates/components/badge-coveralls.hbs
  app/templates/components/badge-gitlab.hbs
  app/templates/components/badge-is-it-maintained-issue-resolution.hbs
  app/templates/components/badge-is-it-maintained-open-issues.hbs
  app/templates/components/badge-maintenance.hbs
  app/templates/components/badge-travis-ci.hbs
  app/templates/components/crate-row.hbs
  app/templates/crate/version.hbs
  app/templates/dashboard.hbs
  app/templates/team.hbs
  app/templates/user.hbs
  package-lock.json
  package.json
Labels: A-ember

#1307 Update `ember-keyboard` to v3.0.2
  package-lock.json
  package.json
Labels: A-ember

#1311 Replace eslint-plugin-ember-suave with eslint-plugin-ember.
  .eslintrc.js
  package-lock.json
  package.json
Labels: A-ember

#1315 ESLint: fix “ember/use-brace-expansion” error.
  .eslintrc.js
  app/components/email-input.js
  app/controllers/index.js
  app/controllers/search.js
Labels: A-ember

#1320 Update ESLint configuration to match ember-cli blueprint
  .eslintrc.js
  package.json
  tests/.eslintrc.js
Labels: A-ember

#1319 ESLint: fix “ember/new-module-imports” error.
  .eslintrc.js
  mirage/factories/category.js
Labels: A-ember

#1317 ESLint: fix “ember/avoid-leaking-state-in-ember-objects” error.
  .eslintrc.js
  app/controllers/me/index.js
  app/models/crate.js
  app/routes/dashboard.js
  app/routes/index.js
  tests/acceptance/crate-test.js
Labels: A-ember

#1321 app-version: Use `SOURCE_VERSION` env var if available
  config/environment.js
  package-lock.json
  package.json
Labels: A-ember

#1318 ESLint: fix “ember/no-capital-letters-in-routes” error.
  .eslintrc.js
  app/router.js
Labels: A-ember

#1316 ESLint: fix "ember/no-on-calls-in-components" error.
  .eslintrc.js
  app/components/rl-dropdown.js
  app/styles/app.scss
Labels: A-ember

#1313 Update `ember-data` to v2.18.2
  package-lock.json
  package.json
Labels: A-ember

#1195 Replace `ember-ajax` with `ember-fetch`
  app/adapters/application.js
  app/components/email-input.js
  app/controllers/dashboard.js
  app/controllers/index.js
  app/controllers/me/index.js
  app/routes/confirm.js
  app/routes/crate/version.js
  app/routes/github-authorize.js
  app/routes/github-login.js
  app/routes/logout.js
  app/services/session.js
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#1333 Don't use Diesel CLI 1.0.0
  .travis.yml
Labels: S-waiting-on-review

#1342 Add missing `<title>` tag
  app/index.html
Labels: A-ember, C-bug

#1343 Remove obsolete `ember-cli-shims` dependency
  package-lock.json
  package.json
Labels: A-ember
