Repository rust-lang/crates.io, pull requests merged in 2019-12, with the labels that each got.

#1933 Convert more endpoints to `ok_true()`
  src/controllers/user/me.rs
  src/controllers/version/yank.rs
Labels: S-waiting-on-review

#1918 Move 3 backend routes to `/api/private/session`
  app/routes/github-authorize.js
  app/routes/github-login.js
  app/routes/logout.js
  src/controllers/user/session.rs
  src/router.rs
  src/tests/user.rs
Labels: S-waiting-on-review

#1945 Query GitHub teams directly by name
  src/models/team.rs
  src/tests/http-data/team_add_owners_as_team_owner
  src/tests/http-data/team_add_team_as_non_member
  src/tests/http-data/team_add_team_mixed_case
  src/tests/http-data/team_crates_by_team_id_not_including_deleted_owners
  src/tests/http-data/team_nonexistent_team
  src/tests/http-data/team_publish_not_owned
  src/tests/http-data/team_publish_owned
  src/tests/http-data/team_remove_team_as_named_owner
  src/tests/http-data/team_remove_team_as_team_owner
Labels: S-waiting-on-review

#1944 Remove bors-ng config; we now use rust-lang's main bors
  bors.toml
  docs/ARCHITECTURE.md
Labels: S-waiting-on-review

#1720 Rename "Game engines" to "Game Development"
  src/boot/categories.toml
Labels: S-waiting-on-author

#1949 Filter crate dependencies by kind properly
  app/controllers/crate/version.js
  app/templates/crate/version.hbs
  mirage/fixtures/dependencies.js
  tests/acceptance/crate-test.js
Labels: S-waiting-on-review

#1953 Upgrade `jemallocator`
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
Labels: S-waiting-on-review

#1954 Fix the broken link in `CONTRIBUTING.md`
  docs/CONTRIBUTING.md
Labels: S-waiting-on-review

#1957 Replace deprecated `ember-cli-qunit` with `ember-qunit`
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#1958 Update `ember-concurrency` to v1.1.3
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#1960 dependency-lint: Disable `generateTests` option
  config/dependency-lint.js
Labels: A-ember, S-waiting-on-review

#1971 Add dependabot configuration file
  .dependabot/config.yml
Labels: S-waiting-on-review

#1956 Disable the background_threads jemallocator feature
  Cargo.toml
Labels: S-waiting-on-review

#1991 Limit the branches that travis builds on
  .travis.yml
Labels: S-waiting-on-review

#1989 Update `ember-cli-babel` to v7.13.2
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#1947 Add Verions Owner Actions to the API
  src/controllers/krate/metadata.rs
  src/controllers/user/me.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/metadata.rs
  src/models/action.rs
  src/models/version.rs
  src/tests/krate.rs
  src/views.rs
Labels: S-waiting-on-author

#2015 mirage/fixtures/crates: Adjust fixture order
  mirage/fixtures/crates.js
Labels: A-ember, S-waiting-on-review

#1996 Disable database triggers during import
  src/tasks/dump_db/dump-import.sql.hbs
Labels: S-waiting-on-review

#2008 build.svg -> pipeline.svg to correctly display GitLab pipeline badge
  app/templates/components/badge-gitlab.hbs
Labels: S-waiting-on-review

#2026 DEPRECATION: Passing actions to components as strings is deprecated.
  app/templates/catch-all.hbs
Labels: S-waiting-on-review

#2029 routes/github-authorize: Fix `queryParams` code
  app/routes/github-authorize.js
Labels: A-ember, C-bug, S-waiting-on-review

#1994 Link directly to cargo install page
  app/templates/index.hbs
Labels: I-papercut, S-waiting-on-review

#2016 Use the percy media query method to hide the downloads graph from percy
  app/styles/app.scss
Labels: S-waiting-on-review

#2038 editorconfig: Adjust indent size for Ember-related files
  .editorconfig
Labels: A-ember, S-waiting-on-review

#2036 Extract `application` serializer
  app/serializers/api-token.js
  app/serializers/application.js
  app/serializers/crate-owner-invite.js
  app/serializers/crate.js
  app/serializers/dependency.js
  app/serializers/version-download.js
Labels: A-ember, S-waiting-on-review

#2040 template-lint: Use `octane` preset
  .template-lintrc.js
Labels: A-ember, S-waiting-on-review

#2035 Remove obsolete `FetchAdapter` mixin
  app/adapters/application.js
Labels: A-ember, S-waiting-on-review

#2039 rl-dropdown-component: Replace `component.$()` call with `$(component.element)`
  app/mixins/rl-dropdown-component.js
Labels: A-ember, S-waiting-on-review

#2043 ESLint: Enable disabled rules
  .eslintrc.js
  app/components/badge-maintenance.js
  app/controllers/crate/version.js
  app/mixins/authenticated-route.js
  app/mixins/pagination.js
  app/mixins/rl-dropdown-component.js
  app/routes/crate/version.js
  tests/unit/mixins/pagination-test.js
Labels: A-ember, S-waiting-on-review

#2044 Migrate `ember-data` imports to new module import paths
  app/adapters/api-token.js
  app/adapters/application.js
  app/adapters/crate-owner-invite.js
  app/models/api-token.js
  app/models/category-slug.js
  app/models/category.js
  app/models/crate-owner-invite.js
  app/models/crate.js
  app/models/dependency.js
  app/models/keyword.js
  app/models/owned-crate.js
  app/models/team.js
  app/models/user.js
  app/models/version-download.js
  app/models/version.js
  app/serializers/application.js
Labels: A-ember, S-waiting-on-review

#2045 Fix an icon link that was generating bad URLs
  config/manifest.js
Labels: A-ember, S-waiting-on-review

#2048 adapters/application: Pass `User-Agent` header to backend in fastboot mode
  app/adapters/application.js
Labels: A-ember, S-waiting-on-review

#2047 Add missing `ember-web-app` tags
  app/index.html
Labels: A-ember, S-waiting-on-review

#2051 Use absolute path for GIT_REPO_URL file:// URL
  .env.sample
Labels: S-waiting-on-review

#2031 Enable debug MALLOC_CONF options on CI
  .github/workflows/ci.yml
  .travis.yml
Labels: S-waiting-on-review

#2060 CI: Enable GH Actions on master branch
  .github/workflows/ci.yml
Labels: S-waiting-on-review

#2058 CI: Add docs to GH Actions workflow and add `RUST_BACKTRACE=1`
  .github/workflows/ci.yml
  .travis.yml
Labels: S-waiting-on-review

#2061 Increase background job timeout for tests
  src/tests/util.rs
Labels: S-waiting-on-review

#2063 Fix fastboot check in nginx erb template
  config/nginx.conf.erb
Labels: S-waiting-on-review

#2074 restore crate prefixes to browser-tab titles
  app/index.html
Labels: S-waiting-on-review

#2064 Consolidate logging into a single `println!()`
  src/middleware/log_request.rs
Labels: S-waiting-on-review
