Repository rust-lang/crates.io, pull requests merged in 2019-04, with the labels that each got.

#1725 Update `ember-cli-meta-tags` to v5.3.0
  package-lock.json
  package.json
Labels: A-ember

#1726 Update `qunit-dom` to v0.8.4
  package-lock.json
  package.json
Labels: A-ember

#1727 Update ESLint setup
  .eslintignore
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
Labels: A-ember

#1729 Update `ember-page-title` to v4.0.5
  package-lock.json
  package.json
Labels: A-ember

#1730 Use `ember-cli-dependency-lint` to warn about duplicate addons
  .travis.yml
  package-lock.json
  package.json
Labels: A-ember

#1721 Ignore auto instead of staging.tmp on Travis CI
  .travis.yml
Labels: S-waiting-on-author

#1733 Update `ember-fetch` to v6.5.1
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#1732 Update `ember-cli` to v3.9.0
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review
