Repository rust-lang/crates.io, pull requests merged in 2020-02, with the labels that each got.

#2170 Remove obsolete `Promise` global override
  app/initializers/set-global-promise.js
Labels: A-ember, S-waiting-on-review

#2175 updates postgresql setup instructions
  docs/CONTRIBUTING.md
Labels: S-waiting-on-review

#2157 Ensure the update_downloads job doesn't run concurrently
  src/tasks.rs
  src/tasks/update_downloads.rs
Labels: S-waiting-on-review

#2186 Replace `tempdir` with `tempfile`
  Cargo.lock
  Cargo.toml
  src/git.rs
Labels: S-waiting-on-review

#2187 Remove use of private items
  src/router.rs
Labels: S-waiting-on-review

#2090 Add computer-vision slug
  src/boot/categories.toml
Labels: S-waiting-on-review

#2189 Expose `crate_owners.created_by`
  src/tasks/dump_db/dump-db.toml
Labels: S-waiting-on-review

#2184 Revert status badge to travis
  README.md
Labels: S-waiting-on-review

#2193 Make crate stats look more consistent
  app/components/crate-row.hbs
Labels: S-waiting-on-review

#1864 Switch to async/await for bin/server and tests
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/bin/on_call/mod.rs
  src/bin/render-readmes.rs
  src/bin/server.rs
  src/github.rs
  src/s3/Cargo.toml
  src/s3/lib.rs
  src/tasks/dump_db.rs
  src/tests/all.rs
  src/tests/http-data/krate_good_badges
  src/tests/http-data/krate_good_categories
  src/tests/http-data/krate_ignored_badges
  src/tests/http-data/krate_ignored_categories
  src/tests/http-data/krate_new_krate
  src/tests/http-data/krate_new_krate_git_upload
  src/tests/http-data/krate_new_krate_git_upload_appends
  src/tests/http-data/krate_new_krate_git_upload_with_conflicts
  src/tests/http-data/krate_new_krate_records_verified_email
  src/tests/http-data/krate_new_krate_too_big_but_whitelisted
  src/tests/http-data/krate_new_krate_twice
  src/tests/http-data/krate_new_krate_weird_version
  src/tests/http-data/krate_new_krate_with_dependency
  src/tests/http-data/krate_new_krate_with_readme
  src/tests/http-data/krate_new_krate_with_token
  src/tests/http-data/krate_new_with_renamed_dependency
  src/tests/http-data/krate_publish_after_removing_documentation
  src/tests/http-data/krate_publish_after_yank_max_version
  src/tests/http-data/krate_publish_new_crate_rate_limited
  src/tests/http-data/krate_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/http-data/krate_publish_records_an_audit_action
  src/tests/http-data/krate_unyank_records_an_audit_action
  src/tests/http-data/krate_uploading_new_version_touches_crate
  src/tests/http-data/krate_yank_max_version
  src/tests/http-data/krate_yank_records_an_audit_action
  src/tests/http-data/krate_yank_works_as_intended
  src/tests/http-data/owners_new_crate_owner
  src/tests/http-data/team_add_owners_as_team_owner
  src/tests/http-data/team_add_team_as_non_member
  src/tests/http-data/team_add_team_mixed_case
  src/tests/http-data/team_crates_by_team_id_not_including_deleted_owners
  src/tests/http-data/team_nonexistent_team
  src/tests/http-data/team_publish_not_owned
  src/tests/http-data/team_publish_owned
  src/tests/http-data/team_remove_team_as_named_owner
  src/tests/http-data/team_remove_team_as_team_owner
  src/tests/http-data/version_version_size
  src/tests/record.rs
  src/uploaders.rs
Labels: S-waiting-on-review

#2206 Bump eslint-plugin-ember from 7.7.2 to 7.8.1
  app/controllers/crate/version.js
  app/mixins/rl-dropdown-component.js
  app/routes/crate/version.js
  package-lock.json
  package.json
Labels: S-waiting-on-review

#2207 Don't return `Ok` if update handler isn't run
  src/git.rs
Labels: S-waiting-on-review

#2205 Introduce new lockfile format
  Cargo.lock
Labels: S-waiting-on-review

#2195 Update `tempfile` and `uuid` to remove `rand` v0.5
  Cargo.lock
Labels: S-waiting-on-review

#2210 helpers/format-num: Simplify implementation using `Intl.NumberFormat`
  app/helpers/format-num.js
Labels: A-ember, S-waiting-on-review

#2212 Increase the default thread count to 5 in development
  src/bin/server.rs
Labels: S-waiting-on-review

#2209 Refactor `RlDropdown` components
  app/components/dropdown.hbs
  app/components/dropdown.js
  app/components/dropdown/content.js
  app/components/dropdown/trigger.js
  app/components/rl-dropdown-container.hbs
  app/components/rl-dropdown-container.js
  app/components/rl-dropdown.js
  app/mixins/rl-dropdown-component.js
  app/templates/application.hbs
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#2214 Enable sorting crates by most recently added
  app/controllers/category/index.js
  app/controllers/crates.js
  app/controllers/keyword/index.js
  app/controllers/me/crates.js
  app/controllers/search.js
  app/controllers/team.js
  app/controllers/user.js
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/me/crates.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
  src/controllers/krate/search.rs
  src/tests/krate.rs
  tests/acceptance/search-test.js
Labels: S-waiting-on-review

#2232 models/crate: Add tests for `inviteOwner()` / `removeOwner()`
  tests/models/crate-test.js
Labels: A-ember

#2224 Remove jQuery
  app/adapters/application.js
  config/optional-features.json
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#2225 Use `Vec::with_capacity()` as possible
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/tasks/dump_db/gen_scripts.rs
Labels: S-waiting-on-review

#2223 Update `parking_lot` to 0.10
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2234 Include crate name and version in the publish API's log entries
  src/controllers.rs
  src/controllers/krate/publish.rs
  src/middleware.rs
  src/middleware/log_request.rs
Labels: S-waiting-on-review
