Repository rust-lang/crates.io, pull requests merged in 2020-01, with the labels that each got.

#2085 Remove obsolete `ember-component-attributes` dependency
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#2086 manually run dependabot for caniuse-lite
  package-lock.json
Labels: S-waiting-on-review

#2071 Fix cache control headers set for S3 uploads
  src/uploaders.rs
Labels: S-waiting-on-review

#2088 Fix a deprecation warning during `ember build`
  app/templates/components/api-token-row.hbs
Labels: S-waiting-on-review

#2066 Add more logging to background jobs
  src/bin/background-worker.rs
  src/bin/enqueue-job.rs
  src/tasks/dump_db.rs
  src/tasks/update_downloads.rs
Labels: S-waiting-on-review

#2089 Bump a few more backend dependencies
  Cargo.lock
Labels: S-waiting-on-review

#2097 styles: Remove unused `#install-downloads` styling
  app/styles/app.scss
  app/styles/install.scss
Labels: A-ember, S-waiting-on-review

#2093 Update rustc used in production
  RustConfig
Labels: S-waiting-on-review

#2095 Fix `event.clearSelection is not a function` error
  app/components/crate-toml-copy.js
Labels: A-ember, C-bug, S-waiting-on-review

#2104 Extract shared `Pagination` component
  app/components/pagination.hbs
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crate/reverse-dependencies.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2099 Bump a few more backend dependencies
  Cargo.lock
Labels: S-waiting-on-review

#2107 Remove rustfmt customization that has no impact
  .rustfmt.toml
Labels: S-waiting-on-review

#2101 Tweak <noscript> text and placement
  app/index.html
  app/styles/app.scss
Labels: S-waiting-on-review

#2108 Remove default null setting of the all_keywords parameter
  app/controllers/application.js
Labels: S-waiting-on-review

#2110 Remove empty `vendor` folder
  vendor/.gitkeep
Labels: A-ember

#2112 mirage: Split route handlers into multiple files
  mirage/config.js
  mirage/route-handlers/-utils.js
  mirage/route-handlers/categories.js
  mirage/route-handlers/crates.js
  mirage/route-handlers/keywords.js
  mirage/route-handlers/summary.js
  mirage/route-handlers/teams.js
  mirage/route-handlers/users.js
Labels: A-ember, S-waiting-on-review

#2121 Pagination: Fix `.active` link styling
  app/components/pagination.module.scss
Labels: A-ember, S-waiting-on-review

#2122 Add `qunit-console-grouper` dev dependency
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#2124 tests/search: Use `ember-keyboard` test helpers
  tests/acceptance/search-test.js
Labels: A-ember, S-waiting-on-review

#2125 mirage: Add basic route handler for `builds.json` API from docs.rs
  mirage/config.js
  mirage/route-handlers/docs-rs.js
Labels: A-ember, S-waiting-on-review

#2123 mirage/crate: Remove unused `withVersion` trait
  mirage/factories/crate.js
Labels: A-ember, S-waiting-on-review

#2128 mirage: Add `keyword` factory
  mirage/factories/keyword.js
  tests/acceptance/keyword-test.js
Labels: A-ember, S-waiting-on-review

#2130 mirage/crates: Return 404 if specified crate can't be found
  mirage/route-handlers/crates.js
Labels: A-ember, S-waiting-on-review

#2136 Fix error handling for mirage request handlers
  mirage/route-handlers/crates.js
Labels: A-ember, S-waiting-on-review

#2098 Disable nginx access logs on Heroku
  config/nginx.conf.erb
Labels: S-waiting-on-review

#2155 Resolves issue 2143
  app/components/crate-list-newest.hbs
  app/templates/crate/version.hbs
  tests/acceptance/crate-test.js
  tests/acceptance/front-page-test.js
Labels: S-waiting-on-review

#2159 testem: Increase start timeout for GitHub Actions CI
  testem.js
Labels: A-ember, S-waiting-on-review

#2139 tests/mirage/crates: Fix test suite title
  tests/mirage/crates-test.js
Labels: A-ember

#2158 ESLint: Use `babel-eslint` parser to allow decorators and field initialization
  .eslintrc.js
  package-lock.json
  package.json
Labels: A-ember

#2165 router: Convert to ES6 class
  app/router.js
Labels: A-ember, S-waiting-on-review

#2154 Update `version_downloads.counted` last to minimize lock contention
  src/tasks/update_downloads.rs
Labels: S-waiting-on-review
