Repository rust-lang/crates.io, pull requests merged in 2020-11, with the labels that each got.

#2993 Use `clap` for CLI argument parsing
  Cargo.lock
  Cargo.toml
  src/bin/delete-crate.rs
  src/bin/delete-version.rs
  src/bin/populate.rs
  src/bin/render-readmes.rs
  src/bin/test-pagerduty.rs
  src/bin/transfer-crates.rs
  src/bin/verify-token.rs
Labels: S-waiting-on-review

#2994 Use `ember-link` for links in lists
  app/components/crate-row.hbs
  app/components/front-page-list/item.hbs
  app/templates/index.hbs
  package.json
  yarn.lock
Labels: S-waiting-on-review

#2940 crate.reverse-dependencies: Show error notification if data loading fails
  app/routes/crate/reverse-dependencies.js
  app/templates/crate/reverse-dependencies.hbs
  tests/acceptance/reverse-dependencies-test.js
Labels: A-frontend, S-waiting-on-review

#2996 Use `dialoguer` crate for command line confirmations
  Cargo.lock
  Cargo.toml
  src/bin/delete-crate.rs
  src/bin/delete-version.rs
  src/bin/dialoguer/mod.rs
  src/bin/transfer-crates.rs
Labels: S-waiting-on-review

#2810 Move away from deprecated team membership API
  Cargo.lock
  Cargo.toml
  src/bin/backfill-org-ids.rs
  src/models/team.rs
  src/tests/http-data/team_add_owners_as_team_owner
  src/tests/http-data/team_add_team_as_non_member
  src/tests/http-data/team_add_team_mixed_case
  src/tests/http-data/team_crates_by_team_id_not_including_deleted_owners
  src/tests/http-data/team_publish_not_owned
  src/tests/http-data/team_publish_owned
  src/tests/http-data/team_remove_team_as_named_owner
  src/tests/http-data/team_remove_team_as_team_owner
Labels: S-waiting-on-review

#3017 Remove TravisCI config
  .travis.yml
Labels: S-waiting-on-review

#3022 CI: Upgrade to ubuntu-18.04
  .github/workflows/ci.yml
Labels: S-waiting-on-review

#3021 Apply clippy suggestions for comparison_to_empty
  src/controllers/user/me.rs
  src/middleware/normalize_path.rs
  src/middleware/require_user_agent.rs
  src/s3/lib.rs
  src/tests/all.rs
Labels: S-waiting-on-review

#3023 Update `sentry` to v0.21.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#3011 Implement `crates-admin` binary
  script/ci/prune-cache.sh
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/dialoguer.rs
  src/admin/mod.rs
  src/admin/on_call.rs
  src/admin/populate.rs
  src/admin/render_readmes.rs
  src/admin/test_pagerduty.rs
  src/admin/transfer_crates.rs
  src/admin/verify_token.rs
  src/bin/crates-admin.rs
  src/bin/monitor.rs
  src/lib.rs
Labels: S-waiting-on-review

#2190 Remove unused `version_authors.user_id`
  migrations/2020-02-14-183929_remove_version_authors_user_id/down.sql
  migrations/2020-02-14-183929_remove_version_authors_user_id/up.sql
  src/schema.patch
  src/schema.rs
  src/tasks/dump_db/dump-db.toml
Labels: S-waiting-on-review

#3025 `cargo update`
  Cargo.lock
  src/bin/server.rs
Labels: S-waiting-on-review

#3015 template-lint: Enable `a11y` preset
  .template-lintrc.js
Labels: A-frontend, S-waiting-on-review

#3032 Update to new rustc stable and `cargo update`
  Cargo.lock
  RustConfig
Labels: S-waiting-on-review

#3045 Keep only latest search API request
  app/controllers/search.js
Labels: S-waiting-on-review

#2998 Added Accessibility category
  src/boot/categories.toml
Labels: S-waiting-on-review

#3043 Fix broken pluralizations
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/keywords.hbs
  mirage/serializers/category.js
  mirage/serializers/keyword.js
  tests/acceptance/categories-test.js
Labels: A-frontend, C-bug, S-waiting-on-review

#2980 FollowButton: Add error notifications when network requests fail
  app/components/follow-button.hbs
  app/components/follow-button.js
  tests/acceptance/crate-following-test.js
Labels: A-frontend, S-waiting-on-review
