Repository rust-lang/crates.io, pull requests merged in 2020-03, with the labels that each got.

#2236 Update `env_logger` to 0.7
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2231 Add a log message to add_crate background job
  src/git.rs
Labels: S-waiting-on-review

#2235 Log inner chained errors
  src/controllers.rs
  src/controllers/krate/publish.rs
  src/middleware/log_request.rs
  src/router.rs
  src/util/errors.rs
Labels: S-waiting-on-review

#2246 Run `cargo update -p web-sys --aggressive`
  Cargo.lock
Labels: S-waiting-on-review

#2251 Add tests for the API token list
  app/components/api-token-row.hbs
  app/routes/login.js
  app/services/session.js
  app/templates/me/index.hbs
  tests/acceptance/api-token-test.js
  tests/helpers/visit-ignoring-abort.js
Labels: A-ember, S-waiting-on-review

#2255 Update transitive `ember-in-element-polyfill` dependency to v0.2.2
  package-lock.json
Labels: A-ember, S-waiting-on-review

#2256 Update hex to 0.4
  Cargo.lock
  Cargo.toml
  src/controllers/krate/publish.rs
Labels: S-waiting-on-review

#2259 Update handlebars to 3.0.1
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2260 Update quote and failure versions
  Cargo.lock
Labels: S-waiting-on-review

#2141 Use a modern font stack inspired by Bootstrap 4
  app/styles/app.scss
Labels: S-waiting-on-review

#2267 Create a new DB pool when rebuilding the worker
  src/background_jobs.rs
  src/bin/background-worker.rs
Labels: S-waiting-on-review

#2268 Reduce `futures` dependencies size
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
  src/tests/record.rs
Labels: S-waiting-on-review

#2202 Add rustless.org to documentation blocklist
  src/models/krate.rs
Labels: S-waiting-on-review

#2253 Display teams on the crate owners page
  app/controllers/crate/owners.js
  app/models/team.js
  app/templates/crate/owners.hbs
  mirage/route-handlers/crates.js
  tests/acceptance/crate-test.js
Labels: S-waiting-on-review

#2271 Update `futf` to 0.1.4
  Cargo.lock
Labels: S-waiting-on-review

#2279 package.json: Sort contents according to the npm documentation order
  package.json
Labels: S-waiting-on-review

#2280 tests/api-token: Add Percy snapshot
  tests/acceptance/api-token-test.js
Labels: A-ember, S-waiting-on-review

#2281 LinkToDep: Convert to template-only component and CSS modules
  app/components/link-to-dep.hbs
  app/components/link-to-dep.js
  app/components/link-to-dep.module.scss
  app/styles/app.scss
  app/templates/crate/version.hbs
Labels: A-ember, S-waiting-on-review

#2282 Remove unused/redundant CSS classes
  app/components/category-list.hbs
  app/components/crate-list-name-only.hbs
  app/components/crate-list-newest.hbs
  app/components/keyword-list.hbs
  app/styles/crate.scss
  app/templates/crates.hbs
  app/templates/search.hbs
Labels: A-ember, S-waiting-on-review

#2283 Convert application-wide CSS to CSS modules
  app/index.html
  app/styles/app.scss
  app/styles/application.module.scss
  app/styles/application.scss
  app/templates/application.hbs
Labels: S-waiting-on-review

#2284 Convert more code to use CSS modules
  app/components/api-token-row.hbs
  app/components/api-token-row.module.scss
  app/components/crate-row.hbs
  app/components/crate-toml-copy.hbs
  app/components/crate-toml-copy.module.scss
  app/styles/app.scss
  app/styles/category-slugs.module.scss
  app/styles/components/crate-toml-copy.scss
  app/styles/crate.scss
  app/styles/crate/version.module.scss
  app/styles/crate/version.scss
  app/styles/me.scss
  app/styles/me/index.module.scss
  app/templates/categories.hbs
  app/templates/category-slugs.hbs
  app/templates/category/index.hbs
  app/templates/crate/owners.hbs
  app/templates/crate/version.hbs
  app/templates/crates.hbs
  app/templates/dashboard.hbs
  app/templates/data-access.hbs
  app/templates/install.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/me/index.hbs
  app/templates/me/pending-invites.hbs
  app/templates/policies.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
  tests/acceptance/crate-test.js
Labels: A-ember, S-waiting-on-review

#2285 crates: Fix missing `letter` condition
  app/templates/crates.hbs
Labels: A-ember, S-waiting-on-review

#2286 Revert "application: Simplify max width assignment"
  app/styles/application.module.scss
Labels: A-ember, S-waiting-on-review

#2287 Simplify dropdown styling and fix dropdown trigger semantics
  app/components/dropdown/content.js
  app/components/dropdown/trigger.js
  app/styles/crate.scss
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2290 Migrate services to native classes
  app/services/fetcher.js
  app/services/flash-messages.js
  app/services/redirector.js
  app/services/search.js
  app/services/session.js
Labels: S-waiting-on-review

#2288 Extract `FollowButton` component
  app/components/follow-button.hbs
  app/components/follow-button.js
  app/controllers/crate/version.js
  app/helpers/or.js
  app/routes/crate/version.js
  app/templates/crate/version.hbs
  tests/acceptance/crate-following-test.js
Labels: A-ember, S-waiting-on-review

#2289 Migrate serializers to native classes
  app/serializers/api-token.js
  app/serializers/crate-owner-invite.js
  app/serializers/crate.js
  app/serializers/dependency.js
  app/serializers/version-download.js
Labels: S-waiting-on-review

#2293 FollowButton: Convert to Glimmer component
  app/components/follow-button.js
  package-lock.json
  package.json
Labels: A-ember, S-waiting-on-review

#2294 Convert `@id` arguments to `id` attributes
  app/components/owned-crate-row.hbs
  app/templates/application.hbs
  app/templates/crate/owners.hbs
Labels: A-ember, S-waiting-on-review

#2278 Update dependencies to remove some packages
  Cargo.lock
Labels: S-waiting-on-review

#2295 Bump to the latest stable rustc
  RustConfig
Labels: S-waiting-on-review

#2296 CI: Don't run nightly for GH Actions    
  .github/workflows/ci.yml
Labels: S-waiting-on-review

#2297 Remove more unused CSS declarations
  app/styles/app.scss
  app/styles/home.scss
Labels: A-ember

#2298 crate.version: Convert to CSS modules
  app/components/download-graph.js
  app/styles/app.scss
  app/styles/crate/version.module.scss
  app/styles/crate/version.scss
  app/templates/crate/version.hbs
Labels: A-ember, S-waiting-on-review

#2301 Move categories footer styling into CSS module
  app/styles/app.scss
  app/styles/categories.module.scss
  app/templates/categories.hbs
Labels: A-ember, S-waiting-on-review

#2300 application: Convert `application.scss` to CSS module
  app/styles/app.scss
  app/styles/application.module.scss
  app/styles/application.scss
  app/templates/application.hbs
Labels: A-ember, S-waiting-on-review

#2302 Add basic tests for the dashboard page
  tests/acceptance/dashboard-test.js
Labels: A-ember, S-waiting-on-review

#2303 dashboard: Migrate to CSS modules
  app/components/crate-downloads-list.hbs
  app/components/crate-downloads-list.module.scss
  app/styles/app.scss
  app/styles/dashboard.module.scss
  app/styles/dashboard.scss
  app/styles/home.scss
  app/styles/index.module.scss
  app/styles/me.scss
  app/templates/dashboard.hbs
  app/templates/index.hbs
Labels: A-ember, S-waiting-on-review

#2269 Update swirl
  Cargo.lock
  Cargo.toml
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/db.rs
  src/git.rs
  src/render.rs
  src/tasks/update_downloads.rs
  src/tests/util.rs
  src/util/errors.rs
Labels: S-waiting-on-review

#2304 Remove unused `id=crates` assignments
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2310 Move `abbr` styling into CSS module
  app/styles/app.scss
  app/styles/application.module.scss
Labels: A-ember, S-waiting-on-review

#2312 keywords: Remove unused `vers` CSS class assignment
  app/templates/keywords.hbs
Labels: A-ember, S-waiting-on-review

#2311 Use CSS module for `CrateRow` component
  app/components/crate-badge.hbs
  app/components/crate-row.hbs
  app/components/crate-row.module.scss
  app/styles/crate.scss
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2313 mirage/fixtures: Remove broken GitLab badge
  mirage/fixtures/crates.js
Labels: A-ember, S-waiting-on-review

#2314 Extract `ResultsCount` component
  app/components/results-count.hbs
  app/components/results-count.module.scss
  app/styles/crate.scss
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crate/reverse-dependencies.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2317 team: Remove unnecessary `.wide` wrapper element
  app/templates/team.hbs
Labels: A-ember, S-waiting-on-review

#2316 version: Move `quick-links` CSS class into CSS module
  app/styles/crate.scss
  app/styles/crate/version.module.scss
  app/templates/crate/version.hbs
Labels: A-ember, S-waiting-on-review

#2318 search: Remove unnecessary `#no-results` wrapper elements
  app/templates/search.hbs
Labels: A-ember, S-waiting-on-review

#2319 styles/me: Remove unused style declarations
  app/styles/me.scss
Labels: A-ember, S-waiting-on-review

#2320 Remove unused `.small-text` CSS class assignments
  app/components/email-input.hbs
  app/templates/crate/owners.hbs
Labels: A-ember, S-waiting-on-review

#2322 me: Move `me-profile` CSS classes into CSS module
  app/styles/me.scss
  app/styles/me/index.module.scss
  app/templates/me/index.hbs
Labels: A-ember, S-waiting-on-review

#2321 Move more CSS code from `crate.scss` to CSS modules
  app/styles/crate.scss
  app/styles/crates.module.scss
  app/styles/search.module.scss
  app/templates/crates.hbs
  app/templates/search.hbs
Labels: A-ember, S-waiting-on-review

#2323 crate.owners: Use CSS module for styling
  app/styles/crate/owners.module.scss
  app/templates/crate/owners.hbs
  tests/acceptance/crate-test.js
Labels: A-ember, S-waiting-on-review

#2324 Add acceptance tests for `/me/pending-invites` and `/accept-invite/:token` routes
  app/components/pending-owner-invite-row.hbs
  app/templates/accept-invite.hbs
  app/templates/me/pending-invites.hbs
  tests/acceptance/invites-test.js
  tests/acceptance/token-invites-test.js
Labels: A-ember, S-waiting-on-review

#2327 Dropdown::Trigger: Use CSS module
  app/components/dropdown/trigger.hbs
  app/components/dropdown/trigger.js
  app/components/dropdown/trigger.module.scss
  app/styles/app.scss
  app/templates/application.hbs
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2326 Remove unused `ValidatedInput` component
  app/components/validated-input.hbs
  app/components/validated-input.js
Labels: A-ember, S-waiting-on-review

#2330 Fix missing owned crates after authentication
  app/components/owned-crate-row.hbs
  app/routes/me/index.js
  app/services/session.js
  app/templates/application.hbs
  tests/bugs/2329-test.js
Labels: A-ember, C-bug, S-waiting-on-review

#2331 Remove unused `badge` CSS class assignments
  app/components/badge-appveyor.hbs
  app/components/badge-azure-devops.hbs
  app/components/badge-bitbucket-pipelines.hbs
  app/components/badge-circle-ci.hbs
  app/components/badge-cirrus-ci.hbs
  app/components/badge-codecov.hbs
  app/components/badge-coveralls.hbs
  app/components/badge-gitlab.hbs
  app/components/badge-is-it-maintained-issue-resolution.hbs
  app/components/badge-is-it-maintained-open-issues.hbs
  app/components/badge-maintenance.hbs
  app/components/badge-travis-ci.hbs
Labels: A-ember, S-waiting-on-review

#2325 Convert `my-invites` styling to CSS modules
  app/components/pending-owner-invite-row.hbs
  app/components/pending-owner-invite-row.module.scss
  app/styles/me.scss
  app/styles/me/pending-invites.module.scss
  app/templates/me/pending-invites.hbs
  tests/acceptance/invites-test.js
Labels: A-ember, S-waiting-on-review

#2332 Extract `FrontPageList` component
  app/components/category-list.hbs
  app/components/crate-list-name-only.hbs
  app/components/crate-list-newest.hbs
  app/components/front-page-list.hbs
  app/components/front-page-list.module.scss
  app/components/front-page-list/item.hbs
  app/components/front-page-list/item.module.scss
  app/components/keyword-list.hbs
  app/styles/app.scss
  app/styles/index.module.scss
Labels: A-ember, S-waiting-on-review

#2333 Extract shared `button` CSS module
  app/components/api-token-row.hbs
  app/components/api-token-row.module.scss
  app/components/email-input.hbs
  app/components/email-input.module.scss
  app/components/follow-button.hbs
  app/components/follow-button.module.scss
  app/components/pending-owner-invite-row.hbs
  app/components/pending-owner-invite-row.module.scss
  app/styles/app.scss
  app/styles/crate/owners.module.scss
  app/styles/index.module.scss
  app/styles/me/index.module.scss
  app/styles/shared/buttons.module.scss
  app/templates/index.hbs
  app/templates/me/index.hbs
Labels: A-ember, S-waiting-on-review

#2334 Extract shared `typography` CSS module
  app/components/crate-row.module.scss
  app/components/pending-owner-invite-row.module.scss
  app/components/results-count.module.scss
  app/styles/app.scss
  app/styles/crate/version.module.scss
  app/styles/crate/versions.module.scss
  app/styles/dashboard.module.scss
  app/styles/shared/typography.module.scss
  app/templates/crate/version.hbs
  app/templates/crate/versions.hbs
Labels: A-ember, S-waiting-on-review

#2335 ApiTokenRow: Replace all regular `class` assignments with CSS module
  app/components/api-token-row.hbs
  app/components/api-token-row.module.scss
Labels: A-ember, S-waiting-on-review

#2337 EmailInput: Use CSS module
  app/components/email-input.hbs
  app/components/email-input.module.scss
  app/components/owned-crate-row.hbs
  app/styles/me.scss
  app/styles/me/index.module.scss
  app/templates/me/index.hbs
Labels: A-ember, S-waiting-on-review

#2339 categories: Use CSS module classes
  app/styles/categories.module.scss
  app/templates/categories.hbs
Labels: A-ember, S-waiting-on-review

#2338 application: Convert `subtitle` to CSS module class
  app/styles/app.scss
  app/styles/application.module.scss
  app/templates/application.hbs
Labels: A-ember, S-waiting-on-review

#2340 me.index: Convert styles to CSS module classes
  app/components/owned-crate-row.hbs
  app/components/owned-crate-row.module.scss
  app/styles/app.scss
  app/styles/me.scss
  app/styles/me/index.module.scss
  app/templates/me/index.hbs
Labels: A-ember, S-waiting-on-review

#2341 Dropdown: Use CSS module for container styling
  app/components/dropdown.hbs
  app/components/dropdown.module.scss
  app/styles/app.scss
  app/styles/crate.scss
  app/templates/application.hbs
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2342 Move global element styling into `application` CSS module
  app/styles/app.scss
  app/styles/application.module.scss
Labels: A-ember, S-waiting-on-review

#2345 Dropdown::Content: Use CSS module
  app/components/dropdown/content.hbs
  app/components/dropdown/content.js
  app/components/dropdown/content.module.scss
  app/styles/app.scss
  app/styles/application.module.scss
  app/templates/application.hbs
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2343 category-slugs: Simplify `list` styles
  app/styles/category-slugs.module.scss
Labels: A-ember, S-waiting-on-review

#2344 crate.versions: Convert remaining styles to CSS module classes
  app/styles/app.scss
  app/styles/crate/versions.module.scss
  app/templates/crate/versions.hbs
  tests/acceptance/crate-test.js
Labels: A-ember, S-waiting-on-review

#2348 Remove unused `sort` CSS class assignments
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2346 Remove unused `search` CSS class assignments
  app/templates/application.hbs
  app/templates/catch-all.hbs
Labels: A-ember, S-waiting-on-review

#2347 Dropdown: Extract `Menu` subcomponent
  app/components/dropdown.hbs
  app/components/dropdown/menu-item.hbs
  app/components/dropdown/menu-item.module.scss
  app/components/dropdown/menu.hbs
  app/components/dropdown/menu.module.scss
  app/styles/app.scss
  app/templates/application.hbs
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2349 crate.reverse-dependencies: Use CSS module
  app/styles/crate.scss
  app/styles/crate/reverse-dependencies.module.scss
  app/templates/crate/reverse-dependencies.hbs
Labels: A-ember, S-waiting-on-review

#2350 Import `normalize.css` via `app.import()`
  app/styles/app.scss
  ember-cli-build.js
Labels: A-ember, S-waiting-on-review

#2351 crate.version: Remove/Replace remaining `class` assignments
  app/styles/crate/version.module.scss
  app/templates/crate/version.hbs
Labels: A-ember, S-waiting-on-review

#2352 styles/buttons: Replace mixins
  app/styles/shared/buttons.module.scss
Labels: A-ember, S-waiting-on-review

#2353 index: Extract `stats-label` CSS module class
  app/styles/index.module.scss
  app/templates/index.hbs
Labels: A-ember, S-waiting-on-review

#2354 styles: Convert // comments to /*...*/ comments
  app/styles/application.module.scss
Labels: A-ember, S-waiting-on-review

#2355 Extract `list` and `row` CSS module classes
  app/styles/category/index.module.scss
  app/styles/crate.scss
  app/styles/crates.module.scss
  app/styles/keyword/index.module.scss
  app/styles/keywords.module.scss
  app/styles/me/crates.module.scss
  app/styles/me/following.module.scss
  app/styles/search.module.scss
  app/styles/team.module.scss
  app/styles/user.module.scss
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2357 Remove more unused `id` assignments
  app/templates/application.hbs
  app/templates/category/index.hbs
  app/templates/crate/version.hbs
  app/templates/index.hbs
  tests/acceptance/crate-test.js
Labels: A-ember, S-waiting-on-review

#2356 Extract `SortDropdown` component
  app/components/sort-dropdown.hbs
  app/components/sort-dropdown.module.scss
  app/components/sort-dropdown/option.hbs
  app/styles/categories.module.scss
  app/styles/category/index.module.scss
  app/styles/crate.scss
  app/styles/crates.module.scss
  app/styles/keyword/index.module.scss
  app/styles/keywords.module.scss
  app/styles/me/crates.module.scss
  app/styles/me/following.module.scss
  app/styles/search.module.scss
  app/styles/team.module.scss
  app/styles/user.module.scss
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2360 dashboard: Convert `date` and `version` to top-level classes
  app/styles/dashboard.module.scss
  app/templates/dashboard.hbs
Labels: A-ember, S-waiting-on-review

#2358 team|user: Remove unnecessary wrapper elements
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2359 styles/app: Remove unused `small` CSS class
  app/styles/app.scss
Labels: A-ember, S-waiting-on-review

#2368 Extract `results-meta` CSS module classes
  app/styles/categories.module.scss
  app/styles/category/index.module.scss
  app/styles/crate.scss
  app/styles/crate/reverse-dependencies.module.scss
  app/styles/crates.module.scss
  app/styles/keyword/index.module.scss
  app/styles/keywords.module.scss
  app/styles/me/crates.module.scss
  app/styles/me/following.module.scss
  app/styles/search.module.scss
  app/styles/team.module.scss
  app/styles/user.module.scss
  app/templates/categories.hbs
  app/templates/category/index.hbs
  app/templates/crate/reverse-dependencies.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-ember, S-waiting-on-review

#2369 Extract `PageHeader` component
  app/components/page-header.hbs
  app/components/page-header.js
  app/components/page-header.module.scss
  app/styles/app.scss
  app/styles/category/index.module.scss
  app/styles/crate.scss
  app/styles/crate/version.module.scss
  app/styles/dashboard.module.scss
  app/styles/search.module.scss
  app/styles/team.module.scss
  app/styles/user.module.scss
  app/templates/categories.hbs
  app/templates/category-slugs.hbs
  app/templates/category/index.hbs
  app/templates/crate/owners.hbs
  app/templates/crate/version.hbs
  app/templates/crates.hbs
  app/templates/dashboard.hbs
  app/templates/data-access.hbs
  app/templates/install.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/me/index.hbs
  app/templates/me/pending-invites.hbs
  app/templates/policies.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
  tests/acceptance/search-test.js
Labels: A-ember, S-waiting-on-review

#2370 Replace SASS variables with CSS variables
  app/components/api-token-row.module.scss
  app/components/crate-row.module.scss
  app/components/crate-toml-copy.module.scss
  app/components/dropdown/menu-item.module.scss
  app/components/dropdown/menu.module.scss
  app/components/front-page-list/item.module.scss
  app/components/owned-crate-row.module.scss
  app/components/page-header.module.scss
  app/components/pagination.module.scss
  app/components/results-count.module.scss
  app/components/sort-dropdown.module.scss
  app/styles/app.scss
  app/styles/application.module.scss
  app/styles/categories.module.scss
  app/styles/category/index.module.scss
  app/styles/crate/owners.module.scss
  app/styles/crate/reverse-dependencies.module.scss
  app/styles/crate/version.module.scss
  app/styles/crates.module.scss
  app/styles/dashboard.module.scss
  app/styles/index.module.scss
  app/styles/keyword/index.module.scss
  app/styles/keywords.module.scss
  app/styles/me/crates.module.scss
  app/styles/me/following.module.scss
  app/styles/me/index.module.scss
  app/styles/shared/typography.module.scss
  app/styles/team.module.scss
  app/styles/user.module.scss
Labels: A-ember, S-waiting-on-review

#2371 css-modules: Remove `intermediateOutputPath` override
  app/styles/.gitkeep
  app/styles/app.scss
  ember-cli-build.js
Labels: A-ember, S-waiting-on-review

#2372 Use regular CSS with `postcss-nested` instead of SASS
  app/components/api-token-row.module.css
  app/components/crate-downloads-list.module.css
  app/components/crate-row.module.css
  app/components/crate-toml-copy.module.css
  app/components/dropdown.module.css
  app/components/dropdown/content.module.css
  app/components/dropdown/menu-item.module.css
  app/components/dropdown/menu.module.css
  app/components/dropdown/trigger.module.css
  app/components/email-input.module.css
  app/components/flash-message.module.css
  app/components/follow-button.module.css
  app/components/follow-button.module.scss
  app/components/front-page-list.module.css
  app/components/front-page-list/item.module.css
  app/components/link-to-dep.module.css
  app/components/owned-crate-row.module.css
  app/components/page-header.module.css
  app/components/pagination.module.css
  app/components/pending-owner-invite-row.module.css
  app/components/results-count.module.css
  app/components/sort-dropdown.module.css
  app/styles/application.module.css
  app/styles/catch-all.module.css
  app/styles/categories.module.css
  app/styles/category-slugs.module.css
  app/styles/category/index.module.css
  app/styles/crate/owners.module.css
  app/styles/crate/reverse-dependencies.module.css
  app/styles/crate/version.module.css
  app/styles/crate/versions.module.css
  app/styles/crates.module.css
  app/styles/dashboard.module.css
  app/styles/index.module.css
  app/styles/keyword/index.module.css
  app/styles/keywords.module.css
  app/styles/loading.module.css
  app/styles/me/crates.module.css
  app/styles/me/following.module.css
  app/styles/me/index.module.css
  app/styles/me/pending-invites.module.css
  app/styles/search.module.css
  app/styles/shared/buttons.module.css
  app/styles/shared/typography.module.css
  app/styles/team.module.css
  app/styles/user.module.css
  ember-cli-build.js
  package-lock.json
  package.json
  tests/acceptance/login-test.js
Labels: A-ember, S-waiting-on-review

#2376 Import `ajax()` utility from `ember-fetch`
  app/components/email-input.js
  app/components/follow-button.js
  app/controllers/dashboard.js
  app/controllers/me/index.js
  app/routes/accept-invite.js
  app/routes/confirm.js
  app/routes/crate/version.js
  app/routes/github-login.js
  app/routes/logout.js
  app/services/fetcher.js
  app/services/session.js
  app/utils/ajax.js
Labels: A-ember, S-waiting-on-review

#2374 Test and simplify `github-authorize` route
  app/routes/github-authorize.js
  tests/routes/github-authorize-test.js
Labels: A-ember, S-waiting-on-review

#2375 dashboard: Remove redundant `visibleStats` property
  .eslintrc.js
  app/controllers/dashboard.js
  app/templates/dashboard.hbs
Labels: A-ember, S-waiting-on-review

#2373 Remove unnecessary `this.get()` calls
  app/components/owned-crate-row.js
  app/controllers/category/index.js
  app/controllers/crates.js
  app/controllers/keyword/index.js
  app/controllers/me/crates.js
  app/controllers/search.js
  app/controllers/team.js
  app/controllers/user.js
  app/routes/accept-invite.js
Labels: A-ember, S-waiting-on-review

#2378 Convert async actions on components to tasks
  app/components/api-token-row.hbs
  app/components/api-token-row.js
  app/components/email-input.hbs
  app/components/email-input.js
  app/components/pending-owner-invite-row.hbs
  app/components/pending-owner-invite-row.js
Labels: A-ember, S-waiting-on-review

#2379 Simplify README loading code
  app/controllers/crate/version.js
  app/routes/crate/version.js
Labels: A-ember, S-waiting-on-review

#2140 Improve the maintenance badge user experience
  app/components/badge-maintenance.hbs
  app/components/badge-maintenance.js
Labels: A-ui, S-waiting-on-review
