Repository rust-lang/crates.io, pull requests merged in 2020-04, with the labels that each got.

#2382 routes/confirm: Simplify `email_verified` update
  app/routes/confirm.js
  app/templates/confirm.hbs
  tests/acceptance/email-confirmation-test.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2381 Convert promise chains to async/await
  app/routes/team.js
  app/routes/user.js
  app/services/session.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2336 Update ammonia to v3.1.0
  Cargo.lock
Labels: S-waiting-on-review

#2383 Move request logging near the top of the middleware stack
  src/middleware.rs
  src/middleware/log_request.rs
Labels: S-waiting-on-review

#2385 Disable global, non-passive `touchstart` and `touchmove` event listeners
  app/app.js
Labels: A-ember, C-enhancement, S-waiting-on-review

#2380 Fix owner invite error handling behavior
  app/adapters/crate.js
  mirage/route-handlers/crates.js
  tests/acceptance/crate-test.js
  tests/models/crate-test.js
Labels: A-ember, C-bug, S-waiting-on-review

#2387 Set YAML indent size to 2
  .editorconfig
Labels: S-waiting-on-review

#2384 Serve more static files from nginx
  config/nginx.conf.erb
Labels: S-waiting-on-review

#2177 Fixing issues with owner invites and renamed accounts
  src/models/owner.rs
  src/tests/owners.rs
Labels: S-waiting-on-review

#2292 Add 'unsafe-inline' for style-src CSP
  config/nginx.conf.erb
Labels: S-waiting-on-review

#2208 Bump to alpha releases of conduit-* crates
  Cargo.lock
  Cargo.toml
  src/s3/Cargo.toml
Labels: S-waiting-on-review

#2388 mirage: Add `followedCrates` relationship to the `user` model
  mirage/models/user.js
  mirage/route-handlers/crates.js
  mirage/route-handlers/me.js
  mirage/serializers/user.js
  tests/acceptance/crate-test.js
  tests/acceptance/dashboard-test.js
  tests/mirage/crates-test.js
  tests/mirage/me-test.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2396 crate.version: Remove obsolete `refreshAfterLogin` observer
  app/routes/crate/version.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2398 tests/crate: Add "unknown version" test
  tests/acceptance/crate-test.js
Labels: A-ember, S-waiting-on-review

#2397 Replace `GoogleJsapi` component with `google-charts` service
  app/components/download-graph.js
  app/components/google-jsapi.js
  app/routes/application.js
  app/services/google-charts.js
  app/templates/application.hbs
  app/utils/concurrency.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2399 crate.version: Move docs.rs request into a controller task
  app/controllers/crate/version.js
  app/routes/crate/version.js
  app/templates/crate/version.hbs
Labels: A-ember, C-cleanup, S-waiting-on-review

#2400 crate.version: Simplify `model()` hook
  app/controllers/crate/version.js
  app/routes/crate/version.js
  tests/unit/controllers/crate/version-test.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2401 Replace custom `eq` and `or` helpers with ember-truth-helpers
  app/helpers/eq.js
  app/helpers/or.js
  package-lock.json
  package.json
Labels: A-ember, C-cleanup, S-waiting-on-review

#2403 Simplify dependency loading by using an ember-concurrency task
  app/controllers/crate/version.js
  app/models/version.js
  app/routes/crate/version.js
  app/templates/crate/version.hbs
Labels: A-ember, C-cleanup, S-waiting-on-review

#2402 crate: Fix error handling in `model()` hook
  app/routes/crate.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2404 crate.version: Remove unused `isDownloading` property
  app/controllers/crate/version.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2405 Improve README loading code
  app/controllers/crate/version.js
  app/models/version.js
  app/routes/crate/version.js
  app/templates/crate/version.hbs
Labels: A-ember, C-cleanup, S-waiting-on-review

#2406 Use `ember-api-actions` to perform custom API actions
  app/adapters/crate.js
  app/adapters/user.js
  app/models/crate.js
  app/models/user.js
  package-lock.json
  package.json
Labels: A-ember, C-cleanup, S-waiting-on-review

#2407 mirage/fixtures: Add missing `updated_at` values
  mirage/fixtures/crates.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2408 ember: Enable optional `default-async-observers` feature
  config/optional-features.json
Labels: A-ember, C-cleanup, S-waiting-on-review

#2409 Convert `CrateRow` to template-only component
  app/components/crate-row.hbs
  app/components/crate-row.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2411 package.json: Adjust `build` script to build production assets
  package.json
Labels: A-ember, C-cleanup, S-waiting-on-review

#2412 Convert all models to ES6 classes
  app/models/api-token.js
  app/models/category-slug.js
  app/models/category.js
  app/models/crate-owner-invite.js
  app/models/crate.js
  app/models/dependency.js
  app/models/keyword.js
  app/models/owned-crate.js
  app/models/team.js
  app/models/user.js
  app/models/version-download.js
  app/models/version.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2413 crate.version: Replace `displayedAuthors` property with `version` model task
  app/controllers/crate/version.js
  app/models/version.js
  app/routes/crate/version.js
  app/templates/crate/version.hbs
Labels: A-ember, C-cleanup, S-waiting-on-review

#2414 crate.version: Inline a few computed properties
  app/controllers/crate/version.js
  app/templates/crate/version.hbs
  tests/unit/controllers/crate/version-test.js
Labels: A-ember, S-waiting-on-review

#2389 Use http types from `http` crate
  Cargo.lock
  Cargo.toml
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers.rs
  src/controllers/helpers/pagination.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/site_metadata.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/util.rs
  src/controllers/version.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/db.rs
  src/middleware.rs
  src/middleware/app.rs
  src/middleware/block_traffic.rs
  src/middleware/current_user.rs
  src/middleware/debug.rs
  src/middleware/ember_index_rewrite.rs
  src/middleware/ensure_well_formed_500.rs
  src/middleware/head.rs
  src/middleware/log_connection_pool_status.rs
  src/middleware/log_request.rs
  src/middleware/require_user_agent.rs
  src/middleware/static_or_continue.rs
  src/router.rs
  src/tests/all.rs
  src/tests/authentication.rs
  src/tests/krate.rs
  src/tests/owners.rs
  src/tests/read_only_mode.rs
  src/tests/server.rs
  src/tests/team.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/util.rs
  src/uploaders.rs
  src/util.rs
  src/util/errors.rs
  src/util/errors/http.rs
  src/util/request_helpers.rs
  src/util/request_proxy.rs
Labels: S-waiting-on-review

#2215 Add backend proxy to aid local fastboot testing
  src/middleware/ember_index_rewrite.rs
  src/util/errors.rs
  src/util/errors/concrete.rs
Labels: S-waiting-on-review

#2428 editorconfig: Adjust `indent_size` for CSS files
  .editorconfig
Labels: A-ember, C-cleanup, S-waiting-on-review

#2427 Update diesel related packages
  Cargo.lock
Labels: S-waiting-on-review

#2430 Update `toml` to 0.5
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2429 dashboard: Cleanup data loading code
  app/controllers/dashboard.js
  app/routes/dashboard.js
  app/styles/dashboard.module.css
  app/templates/dashboard.hbs
Labels: A-ember, C-cleanup, S-waiting-on-review

#2415 services/session: Replace manual state management with `loadUserTask`
  app/mixins/authenticated-route.js
  app/routes/application.js
  app/routes/confirm.js
  app/routes/login.js
  app/services/session.js
  tests/acceptance/login-test.js
Labels: A-ember, C-cleanup, S-waiting-on-review

#2441 Convert `AuthenticatedRoute` mixin to regular base class
  app/routes/-authenticated-route.js
  app/routes/dashboard.js
  app/routes/me/crates.js
  app/routes/me/following.js
  app/routes/me/index.js
  app/routes/me/pending-invites.js
Labels: A-ember, S-waiting-on-review

#2440 Remove Badges from the UI
  app/components/badge-appveyor.hbs
  app/components/badge-appveyor.js
  app/components/badge-azure-devops.hbs
  app/components/badge-azure-devops.js
  app/components/badge-bitbucket-pipelines.hbs
  app/components/badge-bitbucket-pipelines.js
  app/components/badge-circle-ci.hbs
  app/components/badge-circle-ci.js
  app/components/badge-cirrus-ci.hbs
  app/components/badge-cirrus-ci.js
  app/components/badge-codecov.hbs
  app/components/badge-codecov.js
  app/components/badge-coveralls.hbs
  app/components/badge-coveralls.js
  app/components/badge-gitlab.hbs
  app/components/badge-gitlab.js
  app/components/badge-is-it-maintained-issue-resolution.hbs
  app/components/badge-is-it-maintained-issue-resolution.js
  app/components/badge-is-it-maintained-open-issues.hbs
  app/components/badge-is-it-maintained-open-issues.js
  app/components/badge-maintenance.hbs
  app/components/badge-maintenance.js
  app/components/badge-travis-ci.hbs
  app/components/badge-travis-ci.js
  app/components/crate-row.hbs
  app/controllers/crate/version.js
  app/models/crate.js
  app/templates/crate/version.hbs
  tests/acceptance/search-test.js
Labels: A-ember, A-ui, S-waiting-on-review

#2448 crate.owners: Replace async actions with ember-concurrency tasks
  app/controllers/crate/owners.js
  app/templates/crate/owners.hbs
Labels: A-frontend, S-waiting-on-review

#2450 Adjust front page crate list styling
  app/components/category-list.hbs
  app/components/crate-list-name-only.hbs
  app/components/crate-list-newest.hbs
  app/components/front-page-list/item.hbs
  app/components/front-page-list/item.module.css
  app/components/keyword-list.hbs
  public/assets/chevron-right.svg
  tests/acceptance/front-page-test.js
Labels: A-frontend, S-waiting-on-review

#2454 styles: Use `:root` to define global CSS variables
  app/styles/application.module.css
Labels: A-frontend, S-waiting-on-review

#2453 CrateRow: Replace version badge with regular text
  app/components/crate-badge.hbs
  app/components/crate-badge.js
  app/components/crate-row.hbs
  app/components/crate-row.module.css
  tests/acceptance/search-test.js
Labels: A-frontend, S-waiting-on-review

#2455 Adjust styling of the "main" section
  app/styles/application.module.css
  app/templates/application.hbs
Labels: A-frontend, S-waiting-on-review

#2451 ci/prune-cache: Use `rm -f` to delete unnecessary files
  script/ci/prune-cache.sh
Labels: A-internal, S-waiting-on-review

#2464 dashboard: Convert `img` element to inline SVG icon
  app/styles/dashboard.module.css
  app/templates/dashboard.hbs
Labels: A-frontend, S-waiting-on-review

#2465 Use async/await for `model()` hooks instead of Promise chains
  app/routes/category.js
  app/routes/keyword.js
Labels: A-frontend, S-waiting-on-review

#2457 index: Replace loading spinner with list item placeholders
  app/components/category-list.hbs
  app/components/crate-list-name-only.hbs
  app/components/crate-list-newest.hbs
  app/components/front-page-list.hbs
  app/components/front-page-list.module.css
  app/components/front-page-list/item.hbs
  app/components/front-page-list/item/placeholder.hbs
  app/components/front-page-list/item/placeholder.module.css
  app/components/keyword-list.hbs
  app/controllers/index.js
  app/helpers/placeholders.js
  app/routes/index.js
  app/styles/index.module.css
  app/templates/index.hbs
Labels: A-frontend, S-waiting-on-review

#2466 Fix tests when linking with lld
  Cargo.lock
Labels: S-waiting-on-review

#2467 Update `git2` to 0.13
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2456 Shrink page header height
  app/styles/application.module.css
  app/templates/application.hbs
Labels: A-frontend, S-waiting-on-review

#2469 Fix serving `/git/index` during local development
  .env.sample
  app.json
  docker-compose.yml
  script/init-local-index.sh
  src/app.rs
  src/config.rs
  src/middleware/ember_index_rewrite.rs
  src/router.rs
  src/tests/all.rs
  src/tests/git.rs
Labels: S-waiting-on-review

#2474 index: Reuse `GET /summary` result
  app/routes/index.js
Labels: A-frontend, S-waiting-on-review

#2449 Convert a few components to template-only components
  app/components/flash-message.hbs
  app/components/flash-message.js
  app/components/page-header.hbs
  app/components/page-header.js
  app/components/user-link.hbs
  app/components/user-link.js
Labels: A-frontend, S-waiting-on-review

#2470 template-lint: Enable `no-curly-component-invocation` and `require-valid-alt-text` rules
  .template-lintrc.js
  app/templates/dashboard.hbs
Labels: A-frontend, S-waiting-on-review

#2471 category|keyword: Rethrow unhandled errors
  app/routes/category.js
  app/routes/keyword.js
  app/templates/error.hbs
  tests/routes/category-test.js
  tests/routes/keyword-test.js
Labels: A-frontend, S-waiting-on-review

#2472 Remove empty `pagination` mixin test
  tests/unit/mixins/pagination-test.js
Labels: A-frontend, S-waiting-on-review

#2473 Replace custom `format-crate-size` helper with `pretty-bytes` dependency
  app/helpers/format-crate-size.js
  app/helpers/pretty-bytes.js
  app/templates/crate/version.hbs
  package-lock.json
  package.json
  tests/unit/helpers/format-crate-size-test.js
Labels: A-frontend, S-waiting-on-review

#2475 Simplify search field handling code
  app/controllers/application.js
  app/controllers/search.js
  app/routes/index.js
  app/routes/search.js
  app/services/header.js
  app/templates/application.hbs
Labels: A-frontend, S-waiting-on-review
