Repository rust-lang/crates.io, pull requests merged in 2020-05, with the labels that each got.

#2476 Extract `Header` and `Footer` components
  app/components/footer.hbs
  app/components/footer.module.css
  app/components/header.hbs
  app/components/header.js
  app/components/header.module.css
  app/controllers/application.js
  app/styles/application.module.css
  app/templates/application.hbs
Labels: A-frontend, S-waiting-on-review

#2477 styles: use flat color for background (removes noise.png)
  app/styles/application.module.css
  public/assets/noise.png
Labels: S-waiting-on-review

#2482 Add theme switcher in development mode
  app/components/footer.module.css
  app/controllers/application.js
  app/helpers/add-html-class.js
  app/index.html
  app/services/design.js
  app/styles/application.module.css
  app/templates/application.hbs
Labels: A-frontend, S-waiting-on-review

#2432 Update Swirl, take two
  Cargo.lock
  Cargo.toml
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/db.rs
  src/git.rs
  src/render.rs
  src/tasks/update_downloads.rs
  src/tests/util.rs
  src/util/errors.rs
Labels: S-waiting-on-review

#2434 Don't page for long running jobs
  src/bin/monitor.rs
Labels: S-waiting-on-review

#2485 Update pest and derive_deref to drop old macro crates
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2487 Improve CSS for smaller displays
  app/styles/application.module.css
  app/styles/crate/version.module.css
Labels: A-frontend, S-waiting-on-review

#2483 Improve code and docs for serving Ember.js HTML
  src/middleware.rs
  src/middleware/ember_html.rs
Labels: S-waiting-on-review

#2452 summary: Fill `recent_downloads` fields
  src/controllers/krate/metadata.rs
  src/tests/krate.rs
Labels: A-backend, S-waiting-on-review

#2489 index: Fix broken summary request caching logic
  app/controllers/index.js
  app/routes/index.js
Labels: A-frontend, C-bug, S-waiting-on-review

#2479 Add middleware to prioritize download traffic
  src/app.rs
  src/bin/server.rs
  src/middleware.rs
  src/middleware/balance_capacity.rs
  src/tests/all.rs
Labels: S-waiting-on-review

#2492 ember-router-scroll: Fix deprecation warning
  config/environment.js
Labels: A-frontend, S-waiting-on-review

#2495 Add a report-only mode to the `BalanceCapacity` middleware
  src/middleware/balance_capacity.rs
Labels: S-waiting-on-review

#2488 Bump rustc and some low-level dependencies
  Cargo.lock
  RustConfig
  script/ci/cargo-clean-on-new-rustc-version.sh
  src/bin/server.rs
Labels: S-waiting-on-review

#2500 Bump to the latest `cookie` crate
  Cargo.lock
  Cargo.toml
  src/controllers/user/session.rs
Labels: S-waiting-on-review

#2493 Remove mentions about `index-co`
  docs/ARCHITECTURE.md
  docs/CONTRIBUTING.md
  script/init-local-index.sh
Labels: S-waiting-on-review

#2511 Extract `localStorage` wrappers with try/catch
  app/routes/login.js
  app/services/design.js
  app/services/session.js
  app/utils/local-storage.js
Labels: A-frontend, C-bug, S-waiting-on-review

#2512 Bump to rand 0.7
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2513 Bump to comrak 0.7
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2510 Permit '+' in feature name, as in "c++20"
  src/models/krate.rs
  src/tests/krate.rs
  src/views/krate_publish.rs
Labels: S-waiting-on-review

#2516 Update async-related dependencies
  Cargo.lock
Labels: S-waiting-on-review

#2519 Allow some google-related domains to fix CSP errors
  config/nginx.conf.erb
Labels: S-waiting-on-review

#2480 Add Access-Control-Allow-Origin: * header to allow CORS
  config/nginx.conf.erb
Labels: A-backend, C-enhancement

#2499 Sort and update the list of CloudFront IP addresses
  config/nginx.conf.erb
Labels: S-waiting-on-review

#2523 Bump to the latest conduit-hyper
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
Labels: S-waiting-on-review

#2524 Update `semver` to 0.10
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2529 Account for core_threads when setting up background threads
  src/bin/server.rs
Labels: S-waiting-on-review

#2531 Bump actions/cache from v1 to v2
  .github/workflows/ci.yml
Labels: S-waiting-on-review

#2532 Correct actions syntax
  .github/workflows/ci.yml
Labels: S-waiting-on-review

#2533 Bump to latest release of conduit-hyper
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#2535 Update transitive dependencies to fix nightly compilation
  Cargo.lock
Labels: S-waiting-on-review

#2540 Update more backend dependencies
  Cargo.lock
  Cargo.toml
  src/s3/Cargo.toml
Labels: S-waiting-on-review
