Repository rust-lang/crates.io, pull requests merged in 2020-08, with the labels that each got.

#2662 categories: Add os::linux-apis
  src/boot/categories.toml
Labels: S-waiting-on-review

#2683 Fix button alignment on mobile / narrow widths
  app/styles/index.module.css
Labels: S-waiting-on-review

#2684 Cargo update and bump rustc to latest stable
  Cargo.lock
  RustConfig
Labels: S-waiting-on-review

#2588 Replace custom flash message implemenation with ember-cli-notifications
  app/components/crate-toml-copy.hbs
  app/components/crate-toml-copy.js
  app/components/crate-toml-copy.module.css
  app/components/email-input.js
  app/components/flash-message.hbs
  app/components/flash-message.module.css
  app/controllers/application.js
  app/controllers/me/index.js
  app/routes/-authenticated-route.js
  app/routes/application.js
  app/routes/category.js
  app/routes/confirm.js
  app/routes/crate.js
  app/routes/crate/docs.js
  app/routes/crate/repo.js
  app/routes/crate/version.js
  app/routes/keyword.js
  app/routes/login.js
  app/routes/team.js
  app/routes/user.js
  app/services/flash-messages.js
  app/services/notifications.js
  app/styles/application.module.css
  app/templates/application.hbs
  app/templates/catch-all.hbs
  config/environment.js
  package-lock.json
  package.json
  tests/acceptance/crate-test.js
  tests/acceptance/dashboard-test.js
  tests/acceptance/email-confirmation-test.js
  tests/acceptance/invites-test.js
  tests/acceptance/login-test.js
  tests/routes/category-test.js
  tests/routes/keyword-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#2706 Remove dependabot config file
  .dependabot/config.yml
Labels: S-waiting-on-review

#2708 Fix heading to match page title (s/Manager/Manage/)
  app/templates/crate/owners.hbs
Labels: A-frontend, C-bug, S-waiting-on-review

#2711 Update `ember-percy` dependency to `@percy/ember`
  .github/workflows/ci.yml
  .travis.yml
  package-lock.json
  package.json
  tests/acceptance/api-token-test.js
  tests/acceptance/categories-test.js
  tests/acceptance/crate-test.js
  tests/acceptance/crates-test.js
  tests/acceptance/dashboard-test.js
  tests/acceptance/front-page-test.js
  tests/acceptance/invites-test.js
  tests/acceptance/keyword-test.js
  tests/acceptance/search-test.js
  tests/acceptance/team-page-test.js
  tests/acceptance/token-invites-test.js
  tests/acceptance/user-page-test.js
Labels: A-frontend

#2623 Add yank button to the web UI
  app/components/yank-button.hbs
  app/components/yank-button.js
  app/components/yank-button.module.css
  app/controllers/crate/versions.js
  app/models/version.js
  app/templates/crate/version.hbs
  app/templates/crate/versions.hbs
  mirage/route-handlers/crates.js
  src/tests/krate.rs
  tests/acceptance/crate-test.js
Labels: S-waiting-on-review

#2700 Set the default r2d2::Pool::max_size to 3
  src/app.rs
Labels: S-waiting-on-review

#2726 Save lockfile state after running `npm install`
  package-lock.json
Labels: S-waiting-on-review

#2727 Address new clippy suggestion
  src/config.rs
Labels: S-waiting-on-review
