Repository rust-lang/crates.io, pull requests merged in 2020-06, with the labels that each got.

#2551 Fix issue where crates.io allowed the plus sign in crate names
  src/models/krate.rs
Labels: S-waiting-on-review

#2560 Update locked dependencies to fix `npm audit` warnings
  package-lock.json
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2562 Use "Fira Sans" font from Mozilla CDN as default font
  app/index.html
  app/styles/application.module.css
  config/nginx.conf.erb
Labels: A-frontend, C-enhancement, S-waiting-on-review

#2561 Update locked dependencies
  package-lock.json
  package.json
Labels: A-frontend, C-cleanup

#2565 CI: Use `postgres` service
  .github/workflows/ci.yml
Labels: C-cleanup, S-waiting-on-review

#2549 Update more*2 backend dependencies
  Cargo.lock
Labels: S-waiting-on-review

#2543 Allow configuring the application's domain name
  .env.sample
  src/config.rs
  src/controllers/krate/publish.rs
  src/email.rs
  src/github.rs
  src/middleware/block_traffic.rs
  src/tests/all.rs
Labels: S-waiting-on-review

#2569 Replace `{{title}}` with `{{page-title}}`
  app/templates/application.hbs
  app/templates/crate/version.hbs
  app/templates/search.hbs
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2570 Replace `{{ title }}` with `{{page-title}}`
  app/templates/categories.hbs
  app/templates/category-slugs.hbs
  app/templates/category/error.hbs
  app/templates/category/index.hbs
  app/templates/crate/error.hbs
  app/templates/crate/owners.hbs
  app/templates/crates.hbs
  app/templates/dashboard.hbs
  app/templates/keyword/error.hbs
  app/templates/keyword/index.hbs
  app/templates/keywords.hbs
  app/templates/me/crates.hbs
  app/templates/me/index.hbs
  app/templates/me/pending-invites.hbs
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2571 Replace "Loading" template with progress bar
  app/components/progress-bar.hbs
  app/components/progress-bar.js
  app/components/progress-bar.module.css
  app/controllers/application.js
  app/routes/application.js
  app/services/progress.js
  app/styles/application.module.css
  app/styles/loading.module.css
  app/templates/application.hbs
  app/templates/loading.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#2575 services/progress: Remove two unnecessary properties
  app/services/progress.js
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2581 services/header: Convert `searchValue` to tracked property
  app/routes/search.js
  app/services/header.js
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2586 index: Slightly adjusted stats styling
  app/components/stats-value.hbs
  app/components/stats-value.module.css
  app/styles/index.module.css
  app/templates/index.hbs
  public/assets/box.svg
  public/assets/file-archive.svg
  tests/acceptance/front-page-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#2583 Dropdown: Convert to Glimmer component
  app/components/dropdown.js
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2584 Header: Convert to Glimmer component
  app/components/header.js
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2585 UserAvatar: Convert to Glimmer component
  app/components/user-avatar.hbs
  app/components/user-avatar.js
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2582 Simplify `CrateTomlCopy` component
  app/components/crate-toml-copy.hbs
  app/components/crate-toml-copy.js
  app/helpers/is-clipboard-supported.js
  package-lock.json
  package.json
Labels: A-frontend, C-cleanup, S-waiting-on-review

#2587 DownloadGraph: Convert to Glimmer component
  app/components/download-graph.hbs
  app/components/download-graph.js
  package.json
Labels: A-frontend, C-cleanup

#2580 Implement new `Footer` component
  app/components/footer.hbs
  app/components/footer.module.css
  app/styles/application.module.css
  app/templates/application.hbs
  public/assets/discord.svg
  public/assets/forkme.png
  public/assets/forkme.svg
  public/assets/github.svg
  public/assets/twitter.svg
Labels: A-frontend, C-enhancement, S-waiting-on-review

#2590 Temporarily Revert 2580
  app/components/footer.hbs
  app/components/footer.module.css
  app/styles/application.module.css
  app/templates/application.hbs
  public/assets/discord.svg
  public/assets/forkme.png
  public/assets/forkme.svg
  public/assets/github.svg
  public/assets/twitter.svg
Labels: S-waiting-on-review

#2592 Run `cargo update`
  Cargo.lock
Labels: S-waiting-on-review
