Repository rust-lang/crates.io, pull requests merged in 2020-10, with the labels that each got.

#2855 README: Remove Browserstack section
  README.md
Labels: S-waiting-on-review

#2850 PendingOwnerInviteRow: Convert to Glimmer component
  app/components/pending-owner-invite-row.hbs
  app/components/pending-owner-invite-row.js
Labels: A-frontend, S-waiting-on-review

#2853 tests/bugs/2329: Use mirage setup for fixtures
  tests/bugs/2329-test.js
Labels: A-frontend, S-waiting-on-review

#2859 test: add more tests for format-num
  tests/unit/helpers/format-num-test.js
Labels: S-waiting-on-review

#2861 helpers/format-num: Format numbers in the user's preferred locale
  app/helpers/format-num.js
  tests/unit/helpers/format-num-test.js
Labels: A-frontend, S-waiting-on-review

#2860 Use notification service for the email notification success message
  app/routes/confirm.js
  app/templates/confirm.hbs
  tests/acceptance/email-confirmation-test.js
Labels: A-frontend, S-waiting-on-review

#2863 README: Remove TravisCI badge
  README.md
Labels: S-waiting-on-review

#2846 Remove `login` route
  app/components/dropdown/menu-item.module.css
  app/components/header.hbs
  app/components/header.js
  app/components/header.module.css
  app/router.js
  app/routes/login.js
  tests/acceptance/front-page-test.js
  tests/acceptance/login-test.js
  tests/bugs/2329-test.js
Labels: A-frontend, S-waiting-on-review

#2800 Add Sentry error tracking for the frontend
  app/app.js
  app/sentry.js
  config/environment.js
  config/nginx.conf.erb
  package-lock.json
  package.json
Labels: A-frontend

#2870 Enable JS sourcemap output
  ember-cli-build.js
Labels: A-frontend, S-waiting-on-review

#2871 sentry: Ignore `TransitionAborted` errors
  app/sentry.js
Labels: A-frontend, S-waiting-on-review

#2872 utils/ajax: Throw an `Error` instance instead of a random object
  app/utils/ajax.js
Labels: A-frontend, S-waiting-on-review

#2873 services/google-charts: Ensure that `loadScript()` rejects with an `Error` instance
  app/services/google-charts.js
Labels: A-frontend, S-waiting-on-review

#2866 Move `logout` route code into `Header` component
  app/components/header.hbs
  app/components/header.js
  app/components/header.module.css
  app/router.js
  app/routes/logout.js
Labels: A-frontend, S-waiting-on-review

#2856 controllers/user/me: Fix typo in `update_user()` API docs
  src/controllers/user/me.rs
Labels: S-waiting-on-review

#2782 Cargo.toml: Sort dependencies alphabetically
  Cargo.toml
Labels: S-waiting-on-review

#2875 Fix broken logout button
  app/components/header.hbs
  app/components/header.js
  mirage/config.js
  mirage/route-handlers/session.js
  tests/acceptance/logout-test.js
  tests/mirage/session-test.js
Labels: A-frontend, S-waiting-on-review

#2876 Fix search field on 404 page
  app/controllers/catch-all.js
  app/templates/catch-all.hbs
  tests/acceptance/404-test.js
Labels: A-frontend, S-waiting-on-review

#2880 Improve Google Charts error handling
  app/components/download-graph.hbs
  app/components/download-graph.js
  app/routes/application.js
  app/services/google-charts.js
Labels: A-frontend, S-waiting-on-review

#2885 Load charts directly, without a redirect
  app/services/google-charts.js
  config/nginx.conf.erb
Labels: A-frontend, S-waiting-on-review

#2881 Refactor login code
  app/components/dropdown/menu-item.module.css
  app/components/dropdown/trigger.module.css
  app/components/header.hbs
  app/components/header.js
  app/components/header.module.css
  app/components/sort-dropdown.module.css
  app/router.js
  app/routes/github-authorize.js
  app/routes/github-login.js
  app/services/session.js
  config/nginx.conf.erb
  public/github-redirect.html
  tests/acceptance/login-test.js
  tests/bugs/2329-test.js
  tests/routes/github-authorize-test.js
Labels: A-frontend, S-waiting-on-review

#2878 helpers/format-num: Fall back to `en` locale if `navigator.language` causes an error
  app/helpers/format-num.js
Labels: A-frontend, S-waiting-on-review

#2857 Add "Email Change" acceptance tests
  app/components/email-input.hbs
  app/components/email-input.js
  app/templates/me/index.hbs
  mirage/factories/user.js
  mirage/route-handlers/users.js
  tests/acceptance/email-change-test.js
  tests/mirage/users-test.js
Labels: A-frontend, S-waiting-on-review

#2890 Update `node` to v14.9.0
  package.json
Labels: A-frontend, S-waiting-on-review

#2887 utils/ajax: Allow `init` argument of `HttpError` to be `undefined`
  app/utils/ajax.js
Labels: A-frontend, S-waiting-on-review

#2894 crate.version: Fix `latestUnyankedVersion` bug
  app/routes/crate/version.js
Labels: A-frontend, C-bug

#2888 QUnit: Override testing container background color
  ember-cli-build.js
  vendor/qunit.css
Labels: A-frontend, S-waiting-on-review

#2889 services/fetcher: Convert `ajax()` to async method
  app/services/fetcher.js
Labels: A-frontend, S-waiting-on-review

#2893 Implement email confirmation API calls using ember-api-actions
  app/components/email-input.js
  app/models/user.js
  tests/acceptance/email-change-test.js
  tests/models/user-test.js
Labels: A-frontend, S-waiting-on-review

#2908 Simplify and modernize the `EmailInput` component
  app/components/email-input.hbs
  app/components/email-input.js
  app/templates/me/index.hbs
  tests/acceptance/email-change-test.js
Labels: A-frontend, S-waiting-on-review

#2912 Bump rustc version and update Rust dependencies
  Cargo.lock
  Cargo.toml
  RustConfig
  src/s3/Cargo.toml
Labels: S-waiting-on-review

#2823 Add os::freebsd-apis category
  src/boot/categories.toml
Labels: S-waiting-on-review

#2892 Remove use of deprecated `set-env` and `add-path`
  .github/workflows/ci.yml
  .travis.yml
Labels: S-waiting-on-review

#2898 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: S-waiting-on-review

#2901 Switch from npm to yarn
  .github/workflows/ci.yml
  .travis.yml
  docker-compose.yml
  docs/CONTRIBUTING.md
  frontend.Dockerfile
  package-lock.json
  renovate.json
  yarn.lock
Labels: A-frontend, S-waiting-on-review

#2914 Use `ember-set-body-class` addon to set CSS classes on `<body>`
  app/helpers/add-html-class.js
  app/styles/application.module.css
  app/templates/application.hbs
  package.json
  yarn.lock
Labels: A-frontend, S-waiting-on-review

#2919 Replace `action` helper usage
  .template-lintrc.js
  app/components/dropdown.hbs
  app/components/header.hbs
  app/components/header.js
  app/components/pending-owner-invite-row.hbs
  app/controllers/me/index.js
  app/templates/crates.hbs
  app/templates/me/index.hbs
Labels: A-frontend

#2917 Convert adapters to native JS classes
  app/adapters/api-token.js
  app/adapters/application.js
  app/adapters/category-slug.js
  app/adapters/crate-owner-invite.js
  app/adapters/dependency.js
  app/adapters/team.js
  app/adapters/user.js
Labels: A-frontend, S-waiting-on-review

#2925 Simplify catch bindings
  app/adapters/application.js
  app/components/api-token-row.js
  app/components/email-input.js
  app/controllers/me/index.js
  app/helpers/format-num.js
  app/initializers/hashchange.js
  app/routes/accept-invite.js
  app/routes/category.js
  app/routes/crate.js
  app/routes/keyword.js
  app/routes/team.js
  app/routes/user.js
  app/services/session.js
  app/utils/local-storage.js
Labels: A-frontend, S-waiting-on-review

#2920 Convert routes to native JS classes
  .eslintrc.js
  app/routes/-authenticated-route.js
  app/routes/accept-invite.js
  app/routes/application.js
  app/routes/categories.js
  app/routes/category-slugs.js
  app/routes/category.js
  app/routes/category/index.js
  app/routes/confirm.js
  app/routes/crate.js
  app/routes/crate/docs.js
  app/routes/crate/index.js
  app/routes/crate/owners.js
  app/routes/crate/repo.js
  app/routes/crate/reverse-dependencies.js
  app/routes/crate/version.js
  app/routes/crates.js
  app/routes/dashboard.js
  app/routes/github-authorize.js
  app/routes/index.js
  app/routes/install.js
  app/routes/keyword.js
  app/routes/keyword/index.js
  app/routes/keywords.js
  app/routes/me/crates.js
  app/routes/me/following.js
  app/routes/me/index.js
  app/routes/me/pending-invites.js
  app/routes/search.js
  app/routes/team.js
  app/routes/user.js
Labels: A-frontend, S-waiting-on-review

#2922 ember-fetch: Enable `preferNative` option
  ember-cli-build.js
Labels: A-frontend, S-waiting-on-review

#2776 Remove unnecessary `this.get()` calls
  .eslintrc.js
  app/controllers/crate/owners.js
  app/controllers/crate/version.js
  app/controllers/crate/versions.js
  app/controllers/dashboard.js
  app/controllers/index.js
  app/controllers/me/index.js
  app/controllers/search.js
  app/models/team.js
  app/models/version.js
  app/routes/me/crates.js
Labels: A-frontend, S-waiting-on-review

#2929 styles: Prepend `normalize.css` code
  ember-cli-build.js
Labels: A-frontend

#2935 crate.owners: Use `notifications` service in tasks
  app/controllers/crate/owners.js
  app/templates/crate/owners.hbs
  tests/acceptance/crate-test.js
Labels: A-frontend, S-waiting-on-review

#2923 Add Embroider build job
  .github/workflows/ci.yml
  ember-cli-build.js
  package.json
  yarn.lock
Labels: A-frontend, S-waiting-on-review

#2931 mirage/scenarios/default: Use authenticated session by default
  mirage/scenarios/default.js
Labels: A-frontend, S-waiting-on-review

#2933 ESLint: Add `eslint-plugin-unicorn`
  .eslintrc.js
  app/components/api-token-row.js
  app/components/email-input.js
  app/components/follow-button.js
  app/controllers/crate/owners.js
  app/controllers/crate/version.js
  app/initializers/hashchange.js
  app/services/google-charts.js
  config/environment.js
  mirage/route-handlers/crates.js
  mirage/route-handlers/summary.js
  package.json
  tests/helpers/dom.js
  yarn.lock
Labels: A-frontend, S-waiting-on-review

#2939 Sentry: Disable when using `FastBoot`
  app/app.js
Labels: A-frontend

#2941 styles/application: Set minimum height for the `body` element
  app/styles/application.module.css
Labels: A-frontend, S-waiting-on-review

#2947 Replace `ember-cli-uglify` with `ember-cli-terser`
  package.json
  yarn.lock
Labels: A-frontend, S-waiting-on-review

#2796 Backfill GitHub organization IDs for teams
  Cargo.lock
  Cargo.toml
  src/bin/backfill-org-ids.rs
Labels: S-waiting-on-review

#2944 Extract and clean up `Settings::ApiTokens` component
  app/components/api-token-row.hbs
  app/components/settings/api-tokens.hbs
  app/components/settings/api-tokens.js
  app/components/settings/api-tokens.module.css
  app/controllers/me/index.js
  app/routes/me/index.js
  app/styles/me/index.module.css
  app/templates/me/index.hbs
Labels: A-frontend

#2959 Implement error handling for the search page
  app/components/page-header.hbs
  app/controllers/search.js
  app/routes/search.js
  app/styles/search.module.css
  app/templates/search.hbs
  mirage/route-handlers/crates.js
  tests/acceptance/search-test.js
Labels: A-frontend, S-waiting-on-review

#2958 Frontend tests cleanup
  tests/acceptance/categories-test.js
  tests/acceptance/crate-test.js
  tests/acceptance/crates-test.js
  tests/acceptance/front-page-test.js
  tests/acceptance/keyword-test.js
  tests/acceptance/owners-test.js
  tests/acceptance/search-test.js
  tests/acceptance/team-page-test.js
  tests/acceptance/user-page-test.js
Labels: A-frontend, S-waiting-on-review

#2960 Implement error handling for the index page
  app/controllers/index.js
  app/routes/index.js
  app/styles/index.module.css
  app/styles/shared/buttons.module.css
  app/templates/index.hbs
  mirage/route-handlers/summary.js
  tests/acceptance/front-page-test.js
Labels: A-frontend, S-waiting-on-review

#2961 Report errors and slow requests on the backend to Sentry
  .env.sample
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
  src/middleware/log_request.rs
Labels: S-waiting-on-review

#2963 services/session: Add user ids to Sentry context
  app/services/session.js
Labels: A-frontend, S-waiting-on-review

#2954 tests: Move builders into dedicated files and add `created/updated_at` properties
  src/tests/builders.rs
  src/tests/builders/dependency.rs
  src/tests/builders/krate.rs
  src/tests/builders/mod.rs
  src/tests/builders/publish.rs
  src/tests/builders/version.rs
  src/tests/krate.rs
Labels: S-waiting-on-review

#2971 Fix version logic when there are only pre-releases
  app/routes/crate/version.js
Labels: S-waiting-on-review

#2972 Address recent clippy lints
  src/bin/server.rs
  src/s3/lib.rs
Labels: S-waiting-on-review

#2975 ESLint: Add `eslint-plugin-ember-concurrency`
  .eslintrc.js
  app/controllers/crate/version.js
  app/routes/crate/version.js
  package.json
  yarn.lock
Labels: A-frontend, S-waiting-on-review

#2946 Remove turbofishes from diesel calls
  src/bin/delete-crate.rs
  src/bin/delete-version.rs
  src/bin/monitor.rs
  src/bin/render-readmes.rs
  src/bin/transfer-crates.rs
  src/boot/categories.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/search.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/version.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/git.rs
  src/models/action.rs
  src/models/category.rs
  src/models/dependency.rs
  src/models/krate.rs
  src/models/token.rs
  src/models/user.rs
  src/models/version.rs
  src/publish_rate_limit.rs
  src/render.rs
  src/tasks/update_downloads.rs
  src/tests/categories.rs
  src/tests/krate.rs
  src/tests/owners.rs
  src/tests/read_only_mode.rs
  src/tests/team.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/version.rs
Labels: S-waiting-on-review

#2977 Cleanup crate version downloads processing code
  app/controllers/crate/version.js
  app/models/version-download.js
Labels: A-frontend, S-waiting-on-review

#2982 Remove obsolete `sass` dependency
  package.json
  yarn.lock
Labels: A-frontend

#2985 config/targets: Support all browser versions released within the past year
  config/targets.js
Labels: A-frontend, S-waiting-on-review

#2962 Use `claim` to simplify assertions
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/email.rs
  src/lib.rs
  src/models/krate.rs
  src/models/token.rs
  src/tests/all.rs
  src/tests/builders/publish.rs
  src/tests/category.rs
  src/tests/krate.rs
  src/tests/record.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/util.rs
  src/tests/version.rs
  src/views.rs
  src/views/krate_publish.rs
Labels: S-waiting-on-review

#2989 Update `hmac` and `env_logger`
  Cargo.lock
  Cargo.toml
  src/s3/Cargo.toml
Labels: S-waiting-on-review

#2988 Add a log message if a download is not counted
  src/controllers/version/downloads.rs
Labels: S-waiting-on-review

#2991 Improve backend integration with Sentry
  Cargo.toml
  build.rs
  src/bin/server.rs
  src/middleware/log_request.rs
Labels: S-waiting-on-review

#2992 Use `HEROKU_SLUG_COMMIT` if available
  Cargo.toml
  build.rs
  src/bin/server.rs
Labels: S-waiting-on-review
