Repository rust-lang/crates.io, pull requests merged in 2021-11, with the labels that each got.

#4102 renovate: Update `RustConfig` and `RUST_VERSION` in CI config automatically
  .github/renovate.json
Labels: C-internal, A-backend

#4101 CI: Adjust Rust channels
  .github/workflows/ci.yml
Labels: C-internal, A-backend

#4107 SearchForm: Adjust `autocomplete` and spellchecker attributes
  app/components/search-form.hbs
Labels: C-enhancement, A-frontend

#4115 Sentry: Improve metadata collection
  src/middleware/log_request.rs
Labels: C-internal, A-backend

#4119 admin::render_readmes: Use `Result` return types
  src/admin/render_readmes.rs
  src/bin/crates-admin.rs
Labels: C-internal, A-backend

#4116 middleware::log_request: Split request timing code into dedicated middleware
  src/middleware.rs
  src/middleware/log_request.rs
  src/middleware/response_timing.rs
Labels: C-internal, A-backend

#4129 Use ember-concurrency v2 decorator syntax
  app/components/follow-button.js
  app/controllers/index.js
  app/controllers/search.js
  app/models/version.js
  app/services/chartjs.js
  app/services/playground.js
  tests/components/download-graph-test.js
Labels: A-frontend, C-internal

#4126 Replace `jemallocator` with `tikv-jemallocator`
  Cargo.lock
  Cargo.toml
  src/lib.rs
Labels: C-internal, A-backend

#4124 middleware::log_request: Move `OriginalPath` code into `NormalizePath` middleware
  src/middleware/log_request.rs
  src/middleware/normalize_path.rs
Labels: C-internal, A-backend

#4138 renovate: Group `conduit` package updates into one PR
  .github/renovate.json
Labels: C-internal

#4141 renovate: Remove `matchDatasource` from `conduit` grouping rules
  .github/renovate.json
Labels: C-internal

#3999 Implement `version_id` cache for `download` endpoint using `moka` crate
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/config.rs
  src/controllers/version/downloads.rs
  src/metrics/instance.rs
  src/tests/krate/downloads.rs
  src/tests/util/test_app.rs
Labels: C-enhancement, A-backend

#4121 metrics/service: Add `background_jobs` metric
  src/metrics/service.rs
Labels: C-internal, A-backend

#4130 services/playground: Extract loadCrates() method
  app/components/crate-sidebar.js
  app/routes/application.js
  app/services/playground.js
Labels: C-bug, A-frontend

#4145 mirage: Implement `GET /api/private/crate_owner_invitations` route handler
  mirage/config.js
  mirage/route-handlers/invites.js
  tests/mirage/private/crate-owner-invitations/get-test.js
Labels: A-frontend, C-internal

#4137 middleware::LogRequests: Extract Sentry setup into dedicated middleware struct
  src/middleware.rs
  src/middleware/log_request.rs
  src/sentry/middleware.rs
  src/sentry/mod.rs
Labels: C-internal, A-backend

#4148 Pin Node.js version
  .github/renovate.json
  .github/workflows/ci.yml
  frontend.Dockerfile
  package.json
Labels: A-frontend, C-internal

#4150 renovate: Convert to JSON5 file
  .github/renovate.json5
Labels: C-internal

#4151 renovate: Adjust `node` package grouping
  .github/renovate.json5
Labels: A-frontend, C-internal

#4152 CrateSidebar: Show detailed list for small number of owners
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/components/owners-list.hbs
  app/components/owners-list.js
  app/components/owners-list.module.css
  app/models/crate.js
  tests/acceptance/crate-test.js
Labels: C-enhancement, A-frontend

#4158 Redesign `Footer` component
  app/components/footer.hbs
  app/components/footer.module.css
  app/styles/application.module.css
  public/assets/discord.svg
  public/assets/github.svg
  public/assets/twitter.svg
Labels: C-enhancement, A-frontend

#4166 bin/server: Print HTTP server URL on startup
  src/bin/server.rs
  src/tests/server_binary.rs
Labels: C-internal, A-backend

#4170 Header: Add drop shadows to main elements
  app/components/header.module.css
  app/components/search-form.module.css
  app/styles/application.module.css
Labels: C-enhancement, A-frontend

#4171 Improve Avatar styling
  app/components/owners-list.hbs
  app/components/owners-list.module.css
  app/components/version-list/row.module.css
Labels: C-enhancement, A-frontend

#4120 worker::git: Move database update out of `yank()` job
  src/controllers/version/yank.rs
  src/worker/git.rs
Labels: C-internal, A-backend

#4154 Redesign 404 page
  app/controllers/catch-all.js
  app/styles/catch-all.module.css
  app/templates/catch-all.hbs
  public/assets/cuddlyferris.svg
  tests/acceptance/404-test.js
  tests/acceptance/token-invites-test.js
Labels: C-enhancement, A-frontend

#4162 OwnersList: Fall back to `login` if `name` is not filled
  app/components/owners-list.hbs
  app/components/owners-list.module.css
  tests/components/owners-list-test.js
Labels: C-bug, A-frontend

#4128 sentry: Use `allowUrls` option to filter out errors in injected scripts
  app/sentry.js
Labels: A-frontend, C-internal

#4165 bin/server: Simplify assignments via `match`
  src/bin/server.rs
Labels: C-internal, A-backend

#4173 TestApp: Simplify `crates_from_index_head()` method
  src/git.rs
  src/tests/krate/publish.rs
  src/tests/krate/yanking.rs
  src/tests/util/test_app.rs
  src/worker/git.rs
Labels: C-internal, A-backend

#4175 worker::git: Read `yanked` status from database
  src/controllers/version/yank.rs
  src/worker/git.rs
  src/worker/mod.rs
Labels: C-internal, A-backend

#4182 Address clippy lints on nightly
  cargo-registry-s3/lib.rs
  src/db.rs
  src/util/io_util.rs
Labels: C-internal, A-backend

#4156 Show 404 pages for unknown crates/versions
  app/controllers/catch-all.js
  app/routes/catch-all.js
  app/routes/crate.js
  app/routes/crate/version.js
  app/templates/catch-all.hbs
  tests/acceptance/404-test.js
  tests/acceptance/crate-test.js
  tests/routes/crate/version/model-test.js
Labels: C-enhancement, A-frontend
