Repository rust-lang/crates.io, pull requests merged in 2021-05, with the labels that each got.

#3581 Add index `version_downloads_not_processed`
  migrations/2021-05-03-174624_add_index_version_downloads_not_processed/down.sql
  migrations/2021-05-03-174624_add_index_version_downloads_not_processed/up.sql
Labels: S-waiting-on-review

#3582 Adjust download list icon alignment
  app/components/crate-downloads-list.hbs
  app/components/crate-downloads-list.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3583 Update comrak to 0.10.1
  Cargo.lock
  Cargo.toml
Labels: A-backend, S-waiting-on-review

#3588 Revert "Update dependency ember-source to v3.27.0"
  package.json
  yarn.lock
Labels: A-frontend, C-bug, S-waiting-on-review

#3587 Recreate the BRIN index on `version_downloads` with `pages_per_range=1`
  migrations/2021-05-05-081208_recreate_version_downloads_date_index_with_brin_pages_per_range_1/down.sql
  migrations/2021-05-05-081208_recreate_version_downloads_date_index_with_brin_pages_per_range_1/up.sql
Labels: S-waiting-on-review

#3602 CI: Cycle cargo binary cache and add `--avoid-cfg-tarpaulin` to tarpaulin
  .github/workflows/ci.yml
Labels: C-internal

#3596 Run `cargo update` and bump to latest stable on production
  Cargo.lock
  RustConfig
  src/db.rs
  src/render.rs
  src/tests/util/test_app.rs
Labels: S-waiting-on-review

#3610 Bump to rustc 1.52.1
  RustConfig
Labels: S-waiting-on-review

#3549 Remove version_authors and clean up old data
  migrations/2021-04-24-115720_remove_version_authors/down.sql
  migrations/2021-04-24-115720_remove_version_authors/up.sql
  mirage/factories/version.js
  mirage/fixtures/versions.js
  mirage/route-handlers/crates.js
  mirage/serializers/version.js
  src/bin/monitor.rs
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/models/version.rs
  src/schema.patch
  src/schema.rs
  src/tasks/dump_db/dump-db.toml
  src/tasks/update_downloads.rs
  src/tests/builders/publish.rs
  src/tests/builders/version.rs
  src/tests/krate/publish.rs
  src/views.rs
  src/views/krate_publish.rs
  tests/mirage/crates-test.js
  tests/mirage/me-test.js
Labels: S-waiting-on-review

#3612 Drop crates.textsearchable_index_col from the export
  src/tasks/dump_db/dump-db.toml
  src/tasks/dump_db/dump-import.sql.hbs
Labels: S-waiting-on-review

#3611 Include only the last 90 days of downloads in our database dumps
  src/tasks/dump_db/dump-db.toml
Labels: S-waiting-on-review

#3572 Allow the application to start without a database connection
  src/app.rs
  src/bin/server.rs
  src/db.rs
  src/tests/all.rs
  src/tests/server_binary.rs
  src/tests/util.rs
  src/tests/util/chaosproxy.rs
  src/tests/util/test_app.rs
Labels: S-waiting-on-review

#3600 Fix missing line breaks for crate name and refine sidebar layout
  app/components/crate-header.module.css
  app/components/crate-row.module.css
  app/components/crate-sidebar.module.css
  app/styles/crate/version.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3622 Add `postcss` resolution
  package.json
  yarn.lock
Labels: A-frontend, C-internal, S-waiting-on-review

#3624 Remove obsolete `babel-plugin-syntax-object-rest-spread` dependency
  package.json
  yarn.lock
Labels: A-frontend, C-internal, S-waiting-on-review

#3591 Log a message if the background worker resets HEAD
  src/git.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3609 Reject requests with large page offset
  src/config.rs
  src/controllers/helpers/pagination.rs
  src/lib.rs
  src/tests/util/test_app.rs
Labels: A-backend, S-waiting-on-review

#3637 Remove obsolete Chart.js CSS import
  ember-cli-build.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3638 Disable page offset blocking if UA blocklist is unset
  src/config.rs
Labels: S-waiting-on-review

#3646 Update ESLint config
  .eslintrc.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3650 models::Version: Change `num` field to a plain `String`
  src/controllers/krate/downloads.rs
  src/controllers/krate/metadata.rs
  src/git.rs
  src/models/version.rs
  src/views.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3648 Implement seek-based pagination for filterless sortless crates endpoint
  src/controllers/category.rs
  src/controllers/helpers/pagination.rs
  src/controllers/keyword.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/search.rs
  src/controllers/user/me.rs
  src/tests/krate/search.rs
Labels: S-waiting-on-review

#3658 ember-test-selectors: Disable obsolete/deprecated `Component.reopen()` call
  ember-cli-build.js
Labels: A-frontend, C-internal, S-waiting-on-review
