Repository rust-lang/crates.io, pull requests merged in 2021-02, with the labels that each got.

#3222 Replace Moment.js with date-fns
  app/components/crate-row.hbs
  app/components/crate-row.module.css
  app/components/download-graph.js
  app/components/pending-owner-invite-row.hbs
  app/components/settings/api-tokens.hbs
  app/controllers/crate/version.js
  app/helpers/date-format-distance-to-now.js
  app/helpers/date-format-iso.js
  app/helpers/date-format.js
  app/services/chartjs.js
  app/templates/crate/version.hbs
  app/templates/crate/versions.hbs
  app/templates/dashboard.hbs
  ember-cli-build.js
  package.json
  tests/acceptance/api-token-test.js
  tests/acceptance/crate-test.js
  tests/acceptance/invites-test.js
  yarn.lock
Labels: A-frontend, S-waiting-on-review

#3210 router: Remove unused/empty `crate.download` route
  app/router.js
Labels: A-frontend, S-waiting-on-review

#3217 tests: Move `req()` function to `util` module
  src/tests/all.rs
  src/tests/util.rs
Labels: S-waiting-on-review

#3218 Extract `GitHubClient` struct
  src/app.rs
  src/config.rs
  src/controllers/user/session.rs
  src/github.rs
  src/models/team.rs
  src/tests/all.rs
Labels: S-waiting-on-review

#3216 Move docs.rs link code from controller to `version` model
  app/controllers/crate/version.js
  app/models/version.js
  app/routes/crate/version.js
  app/templates/crate/version.hbs
Labels: A-frontend

#3220 Extract `RenderedHtml` component
  app/components/rendered-html.hbs
  app/components/rendered-html.module.css
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
Labels: A-frontend, S-waiting-on-review

#3215 Extract `CrateSidebar` component
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  app/components/crate-sidebar.module.css
  app/controllers/crate/version.js
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
Labels: A-frontend, S-waiting-on-review

#3227 Move "Copy Cargo.toml snippet" button to the sidebar
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
Labels: A-frontend, S-waiting-on-review

#3234 Move download data processing code into `DownloadGraph` component
  app/components/download-graph.js
  app/controllers/crate/version.js
  app/templates/crate/version.hbs
  tests/components/download-graph-test.js
Labels: A-frontend, S-waiting-on-review

#3226 controllers/crate.version: Move reverse dependencies link into the sidebar
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/templates/crate/version.hbs
Labels: A-frontend, S-waiting-on-review

#3237 styles: Use numeric darkness naming and HSL for color values
  app/components/header.module.css
  app/components/progress-bar.module.css
  app/styles/application.module.css
Labels: A-frontend, S-waiting-on-review

#2983 Add "compilers" category.
  src/boot/categories.toml
Labels: S-waiting-on-review

#3246 Sort versions in download graph using semverSort
  app/components/download-graph.js
  package.json
Labels: S-waiting-on-review

#3247 Implement Ember.js RFC 637
  tests/acceptance/404-test.js
  tests/acceptance/api-token-test.js
  tests/acceptance/categories-test.js
  tests/acceptance/crate-following-test.js
  tests/acceptance/crate-test.js
  tests/acceptance/crates-test.js
  tests/acceptance/dashboard-test.js
  tests/acceptance/email-change-test.js
  tests/acceptance/email-confirmation-test.js
  tests/acceptance/front-page-test.js
  tests/acceptance/invites-test.js
  tests/acceptance/keyword-test.js
  tests/acceptance/login-test.js
  tests/acceptance/logout-test.js
  tests/acceptance/owners-test.js
  tests/acceptance/reverse-dependencies-test.js
  tests/acceptance/search-test.js
  tests/acceptance/team-page-test.js
  tests/acceptance/token-invites-test.js
  tests/acceptance/user-page-test.js
  tests/bugs/2329-test.js
  tests/components/crate-row-test.js
  tests/components/download-graph-test.js
  tests/helpers/index.js
  tests/mirage/categories-test.js
  tests/mirage/crates-test.js
  tests/mirage/keywords-test.js
  tests/mirage/me-test.js
  tests/mirage/session-test.js
  tests/mirage/summary-test.js
  tests/mirage/teams-test.js
  tests/mirage/users-test.js
  tests/models/crate-test.js
  tests/models/user-test.js
  tests/modifiers/highlight-syntax-test.js
  tests/routes/category-test.js
  tests/routes/crate/version/docs-link-test.js
  tests/routes/crate/version/model-test.js
  tests/routes/github-authorize-test.js
  tests/routes/keyword-test.js
  tests/services/redirector-test.js
  tests/unit/helpers/format-num-test.js
  tests/utils/ajax-test.js
Labels: A-frontend, S-waiting-on-review

#3248 Extract and reuse `CrateHeader` component
  app/components/crate-header.hbs
  app/components/crate-header.js
  app/components/crate-header.module.css
  app/styles/crate/version.module.css
  app/templates/crate/reverse-dependencies.hbs
  app/templates/crate/version.hbs
  app/templates/crate/versions.hbs
Labels: A-frontend, S-waiting-on-review

#3241 CI: Disable `yarn test` command for `embroider` job
  .github/workflows/ci.yml
Labels: A-frontend, S-waiting-on-review

#3249 Delete obsolete "Fork Me" image
  public/assets/forkme.png
Labels: A-frontend, S-waiting-on-review

#3252 models/version: Add `published_by` relationship
  app/models/version.js
  app/serializers/version.js
  mirage/models/version.js
  mirage/serializers/version.js
  tests/mirage/crates-test.js
  tests/mirage/me-test.js
  tests/models/version-test.js
Labels: A-frontend, S-waiting-on-review

#3251 Extract and improve `VersionList::Row` component
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/components/version-list/row.module.css
  app/controllers/crate/versions.js
  app/styles/application.module.css
  app/styles/crate/versions.module.css
  app/templates/crate/versions.hbs
Labels: A-frontend, S-waiting-on-review

#3253 models/version: Add `features/featureList` properties
  app/models/version.js
  tests/models/version-test.js
Labels: A-frontend, S-waiting-on-review

#3258 Improve version list styling
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/components/version-list/row.module.css
  app/models/version.js
  app/styles/application.module.css
  app/styles/crate/versions.module.css
  public/assets/calendar.svg
  public/assets/checkbox.svg
  public/assets/license.svg
  public/assets/star.svg
  public/assets/trash.svg
  public/assets/weight.svg
  tests/models/version-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3259 Add an index on version_owner_actions.version_id
  migrations/2021-02-09-133314_add_version_owner_actions_index/down.sql
  migrations/2021-02-09-133314_add_version_owner_actions_index/up.sql
Labels: S-waiting-on-review

#3279 crate.version: Prevent `TaskCancelation` errors from being sent to Sentry
  app/routes/crate/version.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3274 models/version: Ignore yanked versions in `isHighestOfReleaseTrack` property
  app/models/version.js
  tests/models/version-test.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3275 DownloadGraph: Only call `destroy` if the `Chart` instance has been created
  app/components/download-graph.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3276 DownloadGraph: Ignore missing `version` relationships
  app/components/download-graph.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3277 routes/application: Add `routeName` tag to all issues
  app/routes/application.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3278 crate.versions: Add "Sort By" dropdown with "Date" and "SemVer" options
  app/components/sort-dropdown/option.hbs
  app/controllers/crate/versions.js
  app/styles/crate/versions.module.css
  app/templates/crate/versions.hbs
  tests/acceptance/versions-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#2951 CI: Run tests via `cargo-tarpaulin`
  .github/workflows/ci.yml
Labels: C-internal, S-waiting-on-review

#3288 yarn: Remove obsolete `ember-test-waiters` resolution
  package.json
  yarn.lock
Labels: A-frontend, C-internal, S-waiting-on-review

#3265 VersionList::Row: Show feature names in tooltip
  app/components/ember-tooltip.js
  app/components/version-list/row.hbs
  app/components/version-list/row.module.css
  package.json
  public/assets/checkbox-empty.svg
  yarn.lock
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3289 CI: Bump cargo binaries cache version
  .github/workflows/ci.yml
Labels: A-backend, C-internal, S-waiting-on-review

#3267 crate.version: Use `<article>` instead of `<section>` for the rendered README
  app/templates/crate/version.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3270 Update some crates to reduce deps
  Cargo.lock
Labels: A-backend, C-internal, S-waiting-on-review

#3271 Add COM0 and LPT0 to the list of reserved crate names
  migrations/2021-02-10-141019_reserve_com0_lpt0/down.sql
  migrations/2021-02-10-141019_reserve_com0_lpt0/up.sql
Labels: A-backend, C-enhancement, S-waiting-on-review

#3292 Address clippy lints currently in beta
  src/bin/server.rs
  src/models/action.rs
  src/models/user.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3296 DownloadGraph: Ignore SemVer parsing issues when sorting
  app/components/download-graph.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3282 FrontPageList::Item: Improve styling
  app/components/front-page-list/item.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3298 Bump dependencies and to new stable rustc
  Cargo.lock
  RustConfig
  src/email.rs
Labels: S-waiting-on-review

#3280 Remove `CaptureUserIdFromCookie` middleware in favor accessing cookie directly
  src/controllers/user/session.rs
  src/controllers/util.rs
  src/middleware.rs
  src/middleware/current_user.rs
  src/middleware/log_request.rs
  src/tests/authentication.rs
  src/tests/util.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3268 Parse license expressions and show links to choosealicense.com
  app/components/crate-sidebar.hbs
  app/components/license-expression.hbs
  app/components/version-list/row.hbs
  app/helpers/parse-license.js
  app/utils/license.js
  tests/acceptance/crate-test.js
  tests/utils/license-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3263 models/version: Use `@cached` decorator to expensive properties
  app/models/version.js
  package.json
  yarn.lock
Labels: A-frontend, C-internal, S-waiting-on-review

#3264 VersionList::Row: Improve focus styling
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/components/version-list/row.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3306 controllers::util: Clean up `verify_origin()` function
  src/controllers/util.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3317 Fix dashboard 'Load More' margin
  app/styles/dashboard.module.css
Labels: A-frontend, C-bug, S-waiting-on-review

#3261 CrateSidebar: Extract `tomlSnippet` property
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3250 CrateHeader: Move quick links into the sidebar
  app/components/crate-header.hbs
  app/components/crate-header.js
  app/components/crate-header.module.css
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar/link.hbs
  app/components/crate-sidebar/link.js
  app/components/crate-sidebar/link.module.css
  public/assets/docs-rs.svg
  public/assets/link.svg
  tests/components/crate-sidebar/link-test.js
  tests/routes/crate/version/docs-link-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3304 Improve invalid semver string handling
  app/components/download-graph.js
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/components/version-list/row.module.css
  app/models/version.js
  mirage/serializers/crate.js
  tests/components/version-list-row-test.js
  tests/models/version-test.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3320 Add SecureToken to enforce good token hygiene
  src/models/token.rs
  src/util.rs
  src/util/token.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3297 README: Allow `align` attributes
  src/render.rs
Labels: A-backend, C-enhancement, S-waiting-on-review

#3330 Add navigation tabs to the crate details pages
  app/components/crate-header.hbs
  app/components/crate-header.js
  app/components/crate-header.module.css
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  app/components/nav-tabs.hbs
  app/components/nav-tabs.module.css
  app/components/nav-tabs/tab.hbs
  app/components/nav-tabs/tab.module.css
  app/styles/crate/versions.module.css
  app/templates/crate/owners.hbs
  app/templates/crate/reverse-dependencies.hbs
  app/templates/crate/versions.hbs
  tests/acceptance/crate-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3335 Update license-exprs.
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#3334 FrontPageList::Item::Placeholder: Adjust styling to match `FrontPageList::Item` component
  app/components/front-page-list/item/placeholder.module.css
Labels: A-frontend, C-bug, S-waiting-on-review

#3123 CONTRIBUTING: Add "team meeting" section
  docs/CONTRIBUTING.md
Labels: A-cratesio-docs, S-waiting-on-review

#3333 Display crate description in the `CrateHeader` component
  app/components/crate-header.hbs
  app/components/crate-header.module.css
  app/components/loading-spinner.module.css
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3341 Bump to latest rand
  Cargo.lock
  Cargo.toml
  src/admin/populate.rs
Labels: S-waiting-on-review

#3340 Bump to latest route-recognizer and cookie crates
  Cargo.lock
  Cargo.toml
  src/router.rs
  src/tests/util.rs
Labels: S-waiting-on-review

#3331 Remove obsolete attributes from `crate` model
  app/components/crate-sidebar.hbs
  app/models/crate.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3345 Improve keyboard focus styling
  app/components/nav-tabs/tab.module.css
  app/components/version-list/row.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3299 Various CI improvements
  .github/workflows/ci.yml
  script/ci/cargo-clean-on-new-rustc-version.sh
Labels: C-internal
