Repository rust-lang/crates.io, pull requests merged in 2021-12, with the labels that each got.

#4237 CI: Run tests for Embroider job again
  .github/workflows/ci.yml
  ember-cli-build.js
Labels: A-frontend, C-internal

#4239 Fix `transitionTo()` and `replaceWith()` deprecations on routes
  app/routes/category.js
  app/routes/confirm.js
  app/routes/crate/dependencies.js
  app/routes/crate/docs.js
  app/routes/crate/owners.js
  app/routes/crate/range.js
  app/routes/crate/repo.js
  app/routes/crate/reverse-dependencies.js
  app/routes/crate/version-dependencies.js
  app/routes/keyword.js
  app/routes/team.js
  app/routes/user.js
Labels: A-frontend, C-internal

#4248 Cargo: Enable doctests again
  Cargo.toml
  src/controllers/krate/owners.rs
Labels: C-internal

#4256 Pin `@ember/string` dependency to v3.0.0
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#4257 utils/license: Add support for parentheses
  app/utils/license.js
  tests/utils/license-test.js
Labels: C-enhancement, A-frontend

#4261 Unpin and update transitive `@ember/string` dependency
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#4243 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: C-internal

#4250 Replace custom error route implementation with `ember-error-route`
  app/routes/catch-all.js
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#4255 docs: Update team meeting time
  docs/CONTRIBUTING.md
Labels: C-documentation

#4268 Update `ember-cli-fastboot` to v3.2.0-beta.5
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#4264 controllers/index: Fix `fetchData()` return value
  app/controllers/index.js
Labels: C-bug, A-frontend

#4265 models/version: Add missing `fetch` import
  app/models/version.js
Labels: C-bug, A-frontend

#4266 CrateSidebar: Fix class name
  app/components/crate-sidebar.js
Labels: A-frontend, C-internal

#4267 Update Node.js to v16.13.1
  .github/workflows/ci.yml
  frontend.Dockerfile
  package.json
Labels: A-frontend, C-internal

#4276 renovate: Adjust `node` package handling config
  .github/renovate.json5
Labels: A-frontend, C-internal

#4284 crate.version: Fix `downloads` alias
  app/controllers/crate/version.js
Labels: C-bug, A-frontend

#4292 Add tests for license expression validation
  src/models/version.rs
Labels: C-internal, A-backend

#4294 models/version: Remove unnecessary `Clone` trait bound
  src/models/version.rs
Labels: C-internal, A-backend

#4295 Adjust application test background color
  tests/helpers/index.js
  vendor/qunit.css
Labels: A-frontend, C-internal

#4296 Add "Development Mode" application test
  tests/acceptance/dev-mode-test.js
Labels: A-frontend, C-internal

#4298 Show info notification if crates.io is in read-only mode
  app/routes/application.js
  mirage/config.js
  mirage/route-handlers/metadata.js
  tests/acceptance/read-only-mode-test.js
Labels: C-enhancement, A-frontend

#4302 renovate: Pin dependency versions
  .github/renovate.json5
Labels: C-internal, A-backend

#4303 CI: Extract test coverage tracking into dedicated workflow
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: C-internal, A-backend

#4306 renovate: Keep `cargo-tarpaulin` and `diesel_cli` automatically up-to-date
  .diesel_version
  .github/renovate.json5
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: C-internal, A-backend

#4311 Adjust `/me` redirection to `/settings/tokens`
  app/routes/me/index.js
Labels: C-enhancement, A-frontend

#4293 Replace `license-exprs` crate with `spdx`
  Cargo.lock
  Cargo.toml
  src/models/version.rs
Labels: C-enhancement, A-backend

#4314 catch-all: Fix broken "Go back" and "Reload" links
  app/controllers/catch-all.js
  app/styles/application.module.css
  app/styles/catch-all.module.css
  app/templates/catch-all.hbs
Labels: C-bug, A-frontend

#4351 renovate: Disable `dependencyDashboardApproval` option
  .github/renovate.json5
Labels: C-internal, A-backend

#4315 Show "This page requires authentication" page for protected routes if unauthenticated
  app/controllers/catch-all.js
  app/routes/-authenticated-route.js
  app/styles/catch-all.module.css
  app/templates/catch-all.hbs
  tests/acceptance/dashboard-test.js
  tests/acceptance/invites-test.js
Labels: C-enhancement, A-frontend

#4356 Remove duplicate GitHub logo SVG
  app/components/crate-sidebar/link.hbs
  app/styles/team.module.css
  app/styles/user.module.css
  app/templates/team.hbs
  app/templates/user.hbs
  public/assets/GitHub-Mark.svg
  tests/acceptance/team-page-test.js
  tests/acceptance/user-page-test.js
Labels: A-frontend, C-internal

#4357 Improve "API Tokens" settings page
  app/components/settings/api-tokens.hbs
  app/components/settings/api-tokens.js
  app/components/settings/api-tokens.module.css
  app/styles/shared/buttons.module.css
  tests/acceptance/api-token-test.js
Labels: C-enhancement, A-frontend

#4359 Improve search bar styling
  app/components/search-form.hbs
  app/components/search-form.module.css
  app/styles/application.module.css
  public/assets/search.png
  public/assets/search.svg
Labels: C-enhancement, A-frontend

#4361 Use `postcss-custom-media` plugin for breakpoints
  app/components/settings-page.module.css
  app/components/settings/api-tokens.module.css
  app/styles/breakpoints.css
  ember-cli-build.js
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#4362 Header: Remove obsolete "Docs" dropdown
  app/components/header.hbs
Labels: C-enhancement, A-frontend

#4364 Repository: Add doc comments
  src/git.rs
Labels: A-backend, C-documentation

#4365 Repository: Extract `run_command()` function
  src/git.rs
  src/worker/git.rs
Labels: C-internal, A-backend

#4367 Replace `ember-set-body-class` addon
  app/helpers/set-theme.js
  app/styles/application.module.css
  app/templates/application.hbs
  package.json
  tests/helpers/index.js
  vendor/qunit.css
  yarn.lock
Labels: A-frontend, C-internal

#4377 DownloadGraph: Fix `extra` property access
  app/components/download-graph.js
  tests/components/download-graph-test.js
Labels: C-bug, A-frontend

#4380 mirage: Replace `withMeta()` utility function with object spread operator
  mirage/route-handlers/-utils.js
  mirage/route-handlers/categories.js
  mirage/route-handlers/crates.js
  mirage/route-handlers/keywords.js
  mirage/route-handlers/me.js
Labels: A-frontend, C-internal

#4381 tests/search: Add test case for query parameter forwarding
  tests/acceptance/search-test.js
Labels: A-frontend, C-internal

#4366 Repository: Use `anyhow` errors as return types
  src/git.rs
  src/worker/git.rs
Labels: C-internal, A-backend

#3867 Add support for new feature syntax (RFC 3143)
  src/controllers/krate/publish.rs
  src/git.rs
  src/models/krate.rs
  src/tests/builders/publish.rs
  src/tests/http-data/krate_publish_features_version_2
  src/tests/krate/publish.rs
Labels: C-enhancement, A-backend

#4379 search: Show "Exact Match" as regular search result
  app/components/crate-list.hbs
  app/components/crate-list.module.css
  app/controllers/search.js
  app/models/crate.js
  app/templates/search.hbs
Labels: C-enhancement, A-frontend

#4360 Remove "Filter by letter" feature
  app/controllers/crates.js
  app/routes/crates.js
  app/templates/crates.hbs
Labels: C-enhancement, A-frontend

#4384 tests: Extract `UpstreamIndex` struct
  src/tests/git.rs
  src/tests/krate/publish.rs
  src/tests/util/test_app.rs
Labels: C-internal, A-backend

#4368 Replace "Toggle Design" button with new `/settings/appearance` route
  app/components/footer.module.css
  app/components/radio-button.hbs
  app/components/settings-page.hbs
  app/components/settings-page.js
  app/components/theme-preview.hbs
  app/components/theme-preview.module.css
  app/controllers/settings/appearance.js
  app/router.js
  app/services/design.js
  app/styles/application.module.css
  app/styles/settings/appearance.module.css
  app/templates/application.hbs
  app/templates/settings/appearance.hbs
Labels: A-frontend, C-internal
