Repository rust-lang/crates.io, pull requests merged in 2021-01, with the labels that each got.

#3156 Use new conduit API when computing elapsed time
  Cargo.lock
  Cargo.toml
  src/middleware/log_request.rs
Labels: S-waiting-on-review

#3159 services/progress: Add missing `didCancel()` check
  app/services/progress.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3160 Replace `Intl.NumberFormat` usage
  app/helpers/format-num.js
  app/routes/application.js
  app/services/intl.js
  package.json
  tests/acceptance/categories-test.js
  tests/unit/helpers/format-num-test.js
  yarn.lock
Labels: A-frontend, C-bug, S-waiting-on-review

#3163 EncodableCrate: Add `max_stable_version` field
  src/models/krate.rs
  src/models/version.rs
  src/tests/krate/search.rs
  src/views.rs
Labels: C-enhancement, S-waiting-on-review

#3134 models::Dependency: Replace `encodable()` method
  src/controllers/krate/metadata.rs
  src/controllers/version/metadata.rs
  src/models/dependency.rs
  src/views.rs
Labels: S-waiting-on-review

#3151 DownloadGraph: Set `maintainAspectRatio: false` and use `min-height` instead
  app/components/download-graph.hbs
  app/components/download-graph.js
  app/components/download-graph.module.css
Labels: A-frontend, S-waiting-on-review

#3169 mirage/crate: Add derived `max_stable_version` field
  mirage/serializers/crate.js
  tests/mirage/crates-test.js
  tests/mirage/summary-test.js
Labels: A-frontend, S-waiting-on-review

#3168 CrateOwnerInvitation: Replace `encodable()` method
  src/controllers/crate_owner_invitation.rs
  src/models/crate_owner_invitation.rs
  src/views.rs
Labels: S-waiting-on-review

#3173 User: Replace `encodable_private()` method
  src/controllers/user/me.rs
  src/models/user.rs
  src/views.rs
Labels: S-waiting-on-review

#3175 Simplify `crate.version` route implementation
  app/models/crate.js
  app/routes/crate/version.js
  mirage/serializers/crate.js
  tests/acceptance/crate-test.js
  tests/routes/crate/version/model-test.js
Labels: A-frontend, S-waiting-on-review

#3174 tests/front-page: Override locale to make download count test pass
  tests/acceptance/front-page-test.js
Labels: A-frontend, S-waiting-on-review

#3178 Version|Crate: Replace `encodable()` methods
  src/controllers/krate/metadata.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/user/me.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/metadata.rs
  src/models/krate.rs
  src/models/version.rs
  src/views.rs
Labels: S-waiting-on-review

#3179 CrateRow: Use `defaultVersion` for crate version display
  app/components/crate-row.hbs
  tests/components/crate-row-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3181 Bump conduit-hyper to ensure request start time is tracked
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#3061 tests/util: Replace `Response::assert_status()` with `Response::status()`
  src/tests/account_lock.rs
  src/tests/krate/dependencies.rs
  src/tests/krate/downloads.rs
  src/tests/krate/publish.rs
  src/tests/krate/search.rs
  src/tests/krate/yanking.rs
  src/tests/owners.rs
  src/tests/read_only_mode.rs
  src/tests/server.rs
  src/tests/team.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/util.rs
Labels: S-waiting-on-review

#3182 Remove obsolete `failure` dependency
  Cargo.lock
  Cargo.toml
  src/controllers/user/session.rs
Labels: S-waiting-on-review

#3198 Block the ironframework.io documentation domain
  src/views.rs
Labels: S-waiting-on-review

#3192 Clean up `dependency` model module
  src/controllers/krate/publish.rs
  src/models/dependency.rs
  src/tests/krate/publish.rs
Labels: C-cleanup, S-waiting-on-review

#3209 CI: Allow embroider build to fail
  .github/workflows/ci.yml
Labels: S-waiting-on-review

#3193 db: Simplify `connect_now()` implementation
  src/db.rs
Labels: C-cleanup, S-waiting-on-review

#3223 Start background-worker from docker-compose.yml
  docker-compose.yml
Labels: S-waiting-on-review

#3224 Catch exceptions thrown when an anchor in a readme is invalid
  app/initializers/hashchange.js
Labels: S-waiting-on-review
