Repository rust-lang/crates.io, pull requests merged in 2021-10, with the labels that each got.

#3967 admin/render_readmes.rs to correctly identify the readme path
  src/admin/render_readmes.rs
Labels: C-bug, A-backend

#3969 Add tests for admin/render_readmes
  src/admin/render_readmes.rs
Labels: C-internal, A-backend

#3919 sentry: Enable `tracing` feature
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
Labels: C-internal, A-backend

#3970 Support admin render_readme with Cargo.toml without optional readme field
  src/admin/render_readmes.rs
Labels: C-enhancement, A-backend

#4017 Ensure the HEAD for test indexes is "master"
  src/tests/git.rs
Labels: C-internal, A-backend

#3903 Remove obsolete `EnsureWellFormed500` middleware
  src/middleware.rs
  src/middleware/ensure_well_formed_500.rs
Labels: C-internal, A-backend

#4030 admin::on_call: Work around potential Rust v1.57.0-beta.1 bug
  src/admin/on_call.rs
Labels: C-internal, A-backend

#4065 Explicitly inject the `store` service
  app/controllers/dashboard.js
  app/controllers/index.js
  app/controllers/search.js
  app/models/user.js
  app/routes/categories.js
  app/routes/category-slugs.js
  app/routes/category.js
  app/routes/category/index.js
  app/routes/crate.js
  app/routes/crate/reverse-dependencies.js
  app/routes/crates.js
  app/routes/dashboard.js
  app/routes/keyword.js
  app/routes/keyword/index.js
  app/routes/keywords.js
  app/routes/me/crates.js
  app/routes/me/following.js
  app/routes/me/index.js
  app/routes/me/pending-invites.js
  app/routes/team.js
  app/routes/user.js
Labels: A-frontend, C-internal

#4103 renovate: Adjust lockfile maintenance configuration
  .github/renovate.json
Labels: C-internal

#4108 Extract `worker` module
  src/bin/enqueue-job.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/git.rs
  src/lib.rs
  src/tasks.rs
  src/tests/dump_db.rs
  src/worker/daily_db_maintenance.rs
  src/worker/dump_db.rs
  src/worker/dump_db/configuration.rs
  src/worker/dump_db/dump-db.toml
  src/worker/dump_db/dump-export.sql.j2
  src/worker/dump_db/dump-import.sql.j2
  src/worker/dump_db/gen_scripts.rs
  src/worker/dump_db/readme_for_tarball.md
  src/worker/git.rs
  src/worker/mod.rs
  src/worker/readmes.rs
  src/worker/update_downloads.rs
Labels: C-internal, A-backend
