Repository rust-lang/crates.io, pull requests merged in 2021-04, with the labels that each got.

#3409 Topologically sort db-dump.tar.gz
  src/tasks/dump_db.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3483 Add support for testing emails
  src/app.rs
  src/controllers/user/me.rs
  src/controllers/user/session.rs
  src/downloads_counter.rs
  src/email.rs
  src/lib.rs
  src/models/krate.rs
  src/models/user.rs
  src/publish_rate_limit.rs
  src/tasks/update_downloads.rs
  src/tests/krate/search.rs
  src/tests/owners.rs
  src/tests/user.rs
  src/tests/util/test_app.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3467 Bump rustc version and dependencies
  Cargo.lock
  RustConfig
Labels: A-backend, C-internal, S-waiting-on-review

#3403 GET /me/crate_owner_invitations: Add `users` list
  src/controllers/crate_owner_invitation.rs
  src/models/crate_owner_invitation.rs
  src/tests/owners.rs
  src/views.rs
Labels: A-backend, C-enhancement, S-waiting-on-review

#3490 CrateOwnerInvite: Avoid "missing `id`" issue
  app/serializers/crate-owner-invite.js
  tests/acceptance/invites-test.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3494 Increase HTTP request timeout for background jobs
  src/bin/background-worker.rs
Labels: S-waiting-on-review

#3445 mirage/crates: Add support for `/api/v1/crates?ids[]=...`
  mirage/route-handlers/crates.js
  tests/mirage/crates-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3449 Load and show crate descriptions for dependency lists
  app/adapters/crate.js
  app/components/dependency-list/row.hbs
  app/components/dependency-list/row.js
  app/components/dependency-list/row.module.css
  app/components/rev-dep-row.hbs
  app/components/rev-dep-row.js
  app/components/rev-dep-row.module.css
  mirage/fixtures/crates.js
  mirage/route-handlers/crates.js
  tests/acceptance/crate-dependencies-test.js
  tests/acceptance/reverse-dependencies-test.js
  tests/adapters/crate-test.js
  tests/mirage/crates-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3496 Address some new clippy suggestions
  src/controllers/crate_owner_invitation.rs
  src/github.rs
  src/middleware/log_request.rs
  src/models/version.rs
Labels: S-waiting-on-review

#3487 RenderedHtml: Use `--font-monospace` for code samples
  app/components/rendered-html.module.css
Labels: A-frontend, C-bug, S-waiting-on-review

#3499 Make it possible to open the search using S
  app/components/header.hbs
  tests/acceptance/search-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3503 Add `edition=2018` to the Rust Playground link
  app/components/crate-sidebar.js
  tests/components/crate-sidebar/playground-button-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3507 Add `webp` to possible media urls
  src/render.rs
Labels: A-backend, C-enhancement, S-waiting-on-review

#3510 Allow using SecureToken in Diesel queries
  src/models/token.rs
  src/util/token.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3495 s3: Increase `put()` timeout to 60sec
  src/s3/lib.rs
Labels: A-backend, C-internal

#3493 Add an expiration to owner invitations
  app/components/pending-owner-invite-row.js
  app/routes/accept-invite.js
  app/templates/accept-invite.hbs
  src/config.rs
  src/controllers/crate_owner_invitation.rs
  src/models.rs
  src/models/crate_owner_invitation.rs
  src/models/krate.rs
  src/tests/owners.rs
  src/tests/util/test_app.rs
  src/util/errors.rs
  src/util/errors/json.rs
  src/views.rs
  tests/acceptance/invites-test.js
  tests/acceptance/token-invites-test.js
Labels: A-backend, C-enhancement, S-waiting-on-review

#3506 Upgrade `comrak` dependency
  Cargo.lock
  Cargo.toml
Labels: A-backend, C-bug, S-waiting-on-review

#3514 Log a flag for downloads with non-canonical crate names
  src/controllers/version/downloads.rs
Labels: S-waiting-on-review

#3470 Add API Token Auth restrictions on GET APIs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/follow.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/util.rs
  src/tests/krate/following.rs
  src/tests/owners.rs
  src/tests/token.rs
  src/tests/user.rs
Labels: A-backend, S-waiting-on-review

#3518 Forbid token auth on `/me` endpoint
  src/controllers/krate/search.rs
  src/controllers/user/me.rs
  src/tests/token.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3527 feat(footer): update link to privacy policy
  app/components/footer.hbs
Labels: S-waiting-on-review

#3497 Bump to ubuntu-20.04 on CI
  .github/workflows/ci.yml
Labels: A-backend, C-internal

#3528 Run `cargo update`
  Cargo.lock
Labels: S-waiting-on-review

#3539 Return the empty list for authors API
  src/controllers/version/metadata.rs
Labels: A-backend, C-enhancement, S-waiting-on-review

#3531 Add support for Prometheus metrics
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/config.rs
  src/controllers.rs
  src/controllers/metrics.rs
  src/db.rs
  src/lib.rs
  src/metrics/instance.rs
  src/metrics/macros.rs
  src/metrics/mod.rs
  src/metrics/service.rs
  src/middleware.rs
  src/middleware/update_metrics.rs
  src/router.rs
  src/tests/all.rs
  src/tests/metrics.rs
  src/tests/util/test_app.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3544 More aggressively rate limit reserving new package names
  src/publish_rate_limit.rs
Labels: S-waiting-on-review

#3550 Upgrade `oauth2` to 4.0.0
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#3555 Add `DB_OFFLINE` as a failsafe during outages
  src/app.rs
  src/bin/background-worker.rs
  src/config.rs
  src/lib.rs
  src/tests/util/test_app.rs
Labels: S-waiting-on-review

#3556 Create `crates-admin migrate` to sync categories and migrate the db
  .buildpacks
  Cargo.toml
  Procfile
  src/admin/migrate.rs
  src/admin/mod.rs
  src/bin/crates-admin.rs
  src/bin/server.rs
  src/lib.rs
Labels: S-waiting-on-review

#3558 Only log downloads_counter if a value is non-zero
  src/downloads_counter.rs
Labels: S-waiting-on-review

#3559 Include add_custom_metadata in middleware prelude
  src/middleware.rs
  src/middleware/balance_capacity.rs
  src/middleware/block_traffic.rs
  src/middleware/normalize_path.rs
  src/middleware/require_user_agent.rs
Labels: S-waiting-on-review

#3560 Avoid cloning `Config` struct
  src/admin/render_readmes.rs
  src/bin/server.rs
  src/config.rs
  src/middleware.rs
Labels: S-waiting-on-review

#3564 Do unconditional redirects for downloads when the db is broken
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/background_jobs.rs
  src/config.rs
  src/controllers/version/downloads.rs
  src/db.rs
  src/metrics/instance.rs
  src/tests/all.rs
  src/tests/dump_db.rs
  src/tests/unhealthy_database.rs
  src/tests/util.rs
  src/tests/util/chaosproxy.rs
  src/tests/util/fresh_schema.rs
  src/tests/util/test_app.rs
Labels: S-waiting-on-review

#3566 Run the Rust buildpack last
  .buildpacks
Labels: S-waiting-on-review

#3562 Ensure the release succeeds when the primary database is read-only
  src/admin/migrate.rs
  src/bin/crates-admin.rs
Labels: S-waiting-on-review
