Repository rust-lang/crates.io, pull requests merged in 2021-06, with the labels that each got.

#3678 auto-import: Fix source maps
  ember-cli-build.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3154 fix server error when adding renamed github team as owner
  src/models/team.rs
  src/tests/http-data/team_add_renamed_team
  src/tests/team.rs
Labels: A-backend, C-bug, S-waiting-on-review

#3674 Add support for logging instance-level metrics to stdout
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
  src/config.rs
  src/lib.rs
  src/metrics/instance.rs
  src/metrics/log_encoder.rs
  src/metrics/mod.rs
  src/tests/util/test_app.rs
Labels: S-waiting-on-review

#3681 Use full page width for `Header` and `Footer` components
  .template-lintrc.js
  app/components/footer.module.css
  app/components/header.hbs
  app/components/header.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3684 Add more instance-level metrics
  src/downloads_counter.rs
  src/metrics/instance.rs
  src/metrics/log_encoder.rs
  src/metrics/macros.rs
  src/metrics/mod.rs
  src/middleware/update_metrics.rs
Labels: S-waiting-on-review

#3653 Update `semver` to v1.x
  Cargo.lock
  Cargo.toml
  src/controllers/krate/publish.rs
  src/models/version.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3685 Upgrade git2 to fix compliation on nightly
  Cargo.lock
Labels: A-backend, C-internal, S-waiting-on-review

#3686 Bump to the latest stable nginx
  .buildpacks
Labels: A-backend, C-enhancement, S-waiting-on-review

#3690 Split logged instance metrics into multiple lines when necessary
  src/metrics/log_encoder.rs
Labels: S-waiting-on-review

#3691 Fix vector.dev's histograms representation
  src/metrics/log_encoder.rs
Labels: S-waiting-on-review

#3696 Revert "Use full page width for `Header` and `Footer` components"
  .template-lintrc.js
  app/components/footer.module.css
  app/components/header.hbs
  app/components/header.module.css
Labels: A-frontend, C-bug, S-waiting-on-review

#3700 Link to the dump changelog in the data access page
  app/templates/data-access.hbs
Labels: S-waiting-on-review

#3698 mirage: Untangle `crate.id` and `crate.name`
  mirage/factories/crate.js
  mirage/route-handlers/crates.js
  mirage/serializers/crate.js
  mirage/serializers/dependency.js
  mirage/serializers/version.js
  tests/acceptance/crate-dependencies-test.js
  tests/acceptance/crate-navtabs-test.js
  tests/acceptance/crate-test.js
  tests/acceptance/search-test.js
  tests/adapters/crate-test.js
  tests/mirage/crates-test.js
  tests/mirage/me-test.js
  tests/models/crate-test.js
  tests/models/version-test.js
  tests/routes/crate/version/crate-links-test.js
  tests/routes/crate/version/docs-link-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3712 Fix wrong label name and link
  docs/CONTRIBUTING.md
Labels: C-documentation, S-waiting-on-review

#3707 mirage: Implement `crate_owner_invitations` endpoints
  mirage/factories/crate-owner-invitation.js
  mirage/models/crate-owner-invitation.js
  mirage/models/crate-owner-invite.js
  mirage/route-handlers/me.js
  mirage/serializers/crate-owner-invitation.js
  tests/acceptance/invites-test.js
  tests/acceptance/token-invites-test.js
  tests/mirage/invitations-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3715 Address clippy findings
  .github/workflows/ci.yml
  src/admin/migrate.rs
  src/app.rs
  src/bin/crates-admin.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/search.rs
  src/controllers/user/session.rs
  src/controllers/util.rs
  src/controllers/version.rs
  src/downloads_counter.rs
  src/email.rs
  src/git.rs
  src/metrics/log_encoder.rs
  src/models/krate.rs
  src/models/version.rs
  src/render.rs
  src/s3/lib.rs
  src/tasks/update_downloads.rs
  src/tests/category.rs
  src/tests/krate/publish.rs
  src/tests/krate/yanking.rs
  src/tests/owners.rs
  src/tests/server_binary.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/util.rs
  src/tests/util/fresh_schema.rs
  src/tests/util/test_app.rs
  src/util/token.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3717 Cleanup unneeded lints and drop unused Debug impls
  src/app.rs
  src/background_jobs.rs
  src/bin/enqueue-job.rs
  src/bin/server.rs
  src/db.rs
  src/git.rs
  src/lib.rs
  src/middleware/app.rs
  src/middleware/block_traffic.rs
  src/middleware/head.rs
  src/middleware/require_user_agent.rs
  src/middleware/static_or_continue.rs
  src/render.rs
  src/util/request_proxy.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3235 Fix crates-admin render-readmes for local installations
  src/admin/render_readmes.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3724 Allow underscore-prefixed renamed dependency in manifest
  src/models/krate.rs
  src/tests/builders/dependency.rs
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency
  src/tests/krate/publish.rs
  src/views/krate_publish.rs
Labels: A-backend, C-bug

#3733 CrateHeader: Link to `crate.settings` so that tab gets "active" state
  app/components/crate-header.hbs
Labels: A-frontend, C-bug, S-waiting-on-review

#3729 models/team: Convert computed properties to plain getters
  app/models/team.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3731 tests/settings: Replace `loadFixtures()` calls
  mirage/factories/team.js
  mirage/serializers/team.js
  tests/acceptance/settings-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3725 Begin refactoring configuration module
  src/admin/migrate.rs
  src/admin/render_readmes.rs
  src/app.rs
  src/bin/background-worker.rs
  src/bin/server.rs
  src/config.rs
  src/config/base.rs
  src/config/database_pools.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/publish.rs
  src/controllers/version/downloads.rs
  src/lib.rs
  src/middleware.rs
  src/models/crate_owner_invitation.rs
  src/router.rs
  src/tests/authentication.rs
  src/tests/util.rs
  src/tests/util/test_app.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3740 Remove unused `ember-promise-helpers` dependency
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#3741 Remove obsolete `ember-maybe-import-regenerator` dependency
  package.json
  yarn.lock
Labels: A-frontend, C-internal, S-waiting-on-review

#3737 crate/settings: Ensure that only authenticated users can visit the route
  app/routes/crate/settings.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3738 tests: Split `settings` test suite into multiple files
  tests/acceptance/settings/add-owner-test.js
  tests/acceptance/settings/remove-owner-test.js
  tests/acceptance/settings/settings-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3745 Better docs for send email in development
  docs/CONTRIBUTING.md
Labels: C-documentation, S-waiting-on-review

#3747 Add optional expiration for rate limit overrides
  migrations/2021-06-24-143712_add_publish_rate_overrides_expires_at/down.sql
  migrations/2021-06-24-143712_add_publish_rate_overrides_expires_at/up.sql
  src/publish_rate_limit.rs
  src/schema.rs
  src/tasks/dump_db/dump-db.toml
Labels: A-backend, C-enhancement, S-waiting-on-review

#3592 Add a background job for squashing the index
  src/bin/enqueue-job.rs
  src/git.rs
Labels: A-backend, C-enhancement

#3753 Bump dependencies and rustc
  .github/workflows/ci.yml
  Cargo.lock
  RustConfig
Labels: A-backend, C-internal, S-waiting-on-review
