Repository rust-lang/crates.io, pull requests merged in 2021-08, with the labels that each got.

#3822 Fix typo in env sample: github -> GitHub
  .env.sample
Labels: C-documentation, S-waiting-on-review

#3790 Move new versions rate limits to the application
  config/nginx.conf.erb
  migrations/2021-07-18-125813_add_rate_limit_action/down.sql
  migrations/2021-07-18-125813_add_rate_limit_action/up.sql
  src/app.rs
  src/config.rs
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/lib.rs
  src/models/action.rs
  src/models/dependency.rs
  src/models/krate.rs
  src/publish_rate_limit.rs
  src/rate_limiter.rs
  src/schema.rs
  src/tasks/dump_db/dump-db.toml
  src/tasks/update_downloads.rs
  src/tests/builders/krate.rs
  src/tests/http-data/krate_publish_publish_existing_crates_rate_limit
  src/tests/http-data/krate_publish_publish_existing_crates_rate_limit_doesnt_affect_new_crates
  src/tests/http-data/krate_publish_publish_new_crates_rate_limit
  src/tests/http-data/krate_publish_publish_new_crates_rate_limit_doesnt_affect_existing_crates
  src/tests/krate/publish.rs
  src/tests/util/test_app.rs
  src/util.rs
  src/util/errors/json.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3830 Fix squash message warning.
  src/git.rs
Labels: S-waiting-on-review

#3832 Rename the json method of Response to into_json
  src/tests/account_lock.rs
  src/tests/authentication.rs
  src/tests/krate/dependencies.rs
  src/tests/krate/publish.rs
  src/tests/krate/search.rs
  src/tests/krate/yanking.rs
  src/tests/owners.rs
  src/tests/team.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/util/response.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3763 Add the `/api/private/crate-owner-invitations` endpoint
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers/pagination.rs
  src/router.rs
  src/tests/owners.rs
  src/views.rs
Labels: C-enhancement, A-backend, S-waiting-on-review

#3829 Track used database conns with an histogram
  src/app.rs
  src/db.rs
  src/metrics/histogram.rs
  src/metrics/instance.rs
  src/metrics/macros.rs
  src/metrics/mod.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3819 Update Sentry and enable `tracing` integration
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3845 test-selectors: Remove obsolete `patchClassicComponent` option
  ember-cli-build.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3846 Update renovatebot config
  renovate.json
Labels: A-frontend, C-internal, S-waiting-on-review

#3791 Add a link to report an Issue
  app/components/footer.hbs
  app/components/footer.module.css
Labels: C-enhancement, A-frontend, S-waiting-on-review

#3839 Fix "Edge for Android" compatibility
  config/targets.js
Labels: C-bug, A-frontend, S-waiting-on-review

#3843 CI: Install Rust before performing `rustc -V` call
  .github/workflows/ci.yml
Labels: C-internal, A-backend, S-waiting-on-review

#3847 Reorganize Mirage test cases
  tests/mirage/categories-test.js
  tests/mirage/categories/get-by-id-test.js
  tests/mirage/categories/list-test.js
  tests/mirage/category-slugs/list-test.js
  tests/mirage/confirm/put-by-id-test.js
  tests/mirage/crates-test.js
  tests/mirage/crates/downloads-test.js
  tests/mirage/crates/follow/delete-test.js
  tests/mirage/crates/follow/get-test.js
  tests/mirage/crates/follow/put-test.js
  tests/mirage/crates/get-by-id-test.js
  tests/mirage/crates/list-test.js
  tests/mirage/crates/owner-team-test.js
  tests/mirage/crates/owner-user-test.js
  tests/mirage/crates/reverse-dependencies-test.js
  tests/mirage/crates/versions/authors-test.js
  tests/mirage/crates/versions/dependencies-test.js
  tests/mirage/crates/versions/downloads-test.js
  tests/mirage/crates/versions/list-test.js
  tests/mirage/invitations-test.js
  tests/mirage/keywords-test.js
  tests/mirage/keywords/get-by-id-test.js
  tests/mirage/keywords/list-test.js
  tests/mirage/me-test.js
  tests/mirage/me/crate-owner-invitations/list-test.js
  tests/mirage/me/get-test.js
  tests/mirage/me/tokens/create-test.js
  tests/mirage/me/tokens/delete-by-id-test.js
  tests/mirage/me/tokens/list-test.js
  tests/mirage/me/updates/list-test.js
  tests/mirage/private/session/delete-test.js
  tests/mirage/session-test.js
  tests/mirage/summary-test.js
  tests/mirage/teams-test.js
  tests/mirage/teams/get-by-id-test.js
  tests/mirage/users-test.js
  tests/mirage/users/get-by-id-test.js
  tests/mirage/users/resend-by-id-test.js
  tests/mirage/users/update-by-id-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3850 controllers::crate_owner_invitation: Simplify `users` assignment
  src/controllers/crate_owner_invitation.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3837 Add `create-diff-link.sh` script
  script/create-diff-link.sh
Labels: C-internal, C-documentation, S-waiting-on-review

#3854 Add EditorConfig plugins
  docs/ARCHITECTURE.md
Labels: C-internal, C-documentation, S-waiting-on-review

#3851 Rename `GET /api/private/crate-owner-invitations` to `GET /api/private/crate_owner_invitations`
  src/controllers/crate_owner_invitation.rs
  src/router.rs
  src/tests/owners.rs
Labels: C-bug, A-backend, S-waiting-on-review

#3855 Revert "sentry: Enable `tracing` feature"
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3857 Revert "Track used database conns with an histogram"
  src/app.rs
  src/db.rs
  src/metrics/histogram.rs
  src/metrics/instance.rs
  src/metrics/macros.rs
  src/metrics/mod.rs
Labels: A-backend, S-waiting-on-review

#3858 Revert "Move new versions rate limits to the application"
  config/nginx.conf.erb
  migrations/2021-07-18-125813_add_rate_limit_action/down.sql
  migrations/2021-07-18-125813_add_rate_limit_action/up.sql
  src/app.rs
  src/config.rs
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/lib.rs
  src/models/action.rs
  src/models/dependency.rs
  src/models/krate.rs
  src/publish_rate_limit.rs
  src/rate_limiter.rs
  src/schema.rs
  src/tasks/dump_db/dump-db.toml
  src/tasks/update_downloads.rs
  src/tests/builders/krate.rs
  src/tests/http-data/krate_publish_publish_existing_crates_rate_limit
  src/tests/http-data/krate_publish_publish_existing_crates_rate_limit_doesnt_affect_new_crates
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/krate/publish.rs
  src/tests/util/test_app.rs
  src/util.rs
  src/util/errors/json.rs
Labels: A-backend, S-waiting-on-review

#3862 render: add HTML image tests with align support
  src/render.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3865 Clippy fixes
  src/controllers/user/me.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3869 mirage/crate-owner-invitation: Adjust fake API to match the real API
  mirage/serializers/crate-owner-invitation.js
  tests/mirage/me/crate-owner-invitations/list-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3849 Bump backend dependencies and to latest stable rustc
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  RustConfig
Labels: A-backend, S-waiting-on-review
