Repository rust-lang/crates.io, pull requests merged in 2021-09, with the labels that each got.

#3885 Update locked cargo dependencies
  Cargo.lock
Labels: C-internal, A-backend, S-waiting-on-review

#3878 Replace `ember-prism` with `highlight.js`
  app/components/rendered-html.module.css
  app/components/settings/api-tokens.hbs
  app/modifiers/highlight-syntax.js
  app/styles/application.module.css
  app/templates/error.hbs
  ember-cli-build.js
  package.json
  tests/modifiers/highlight-syntax-test.js
  yarn.lock
Labels: C-enhancement, A-frontend, S-waiting-on-review

#3889 Use `json!` macro to simplify JSON serialization code
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/search.rs
  src/controllers/site_metadata.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/util/errors/json.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3887 db: Use `thiserror` crate to derive `Error` for `PoolError`
  Cargo.lock
  Cargo.toml
  src/db.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3895 errors: Derive `Error` (and `Display`) for `AppErrToStdErr`
  src/util/errors.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3896 Update documentation on krate::downloads controller
  src/controllers/krate/downloads.rs
Labels: A-backend, C-documentation, S-waiting-on-review

#3880 render: fix center image test
  src/render.rs
Labels: C-internal, A-backend, S-waiting-on-review

#3893 Cargo: Use v2 resolver
  Cargo.toml
  src/s3/Cargo.toml
Labels: C-internal, A-backend, S-waiting-on-review

#3905 Add README rendering acceptance tests
  app/templates/crate/version.hbs
  mirage/factories/version.js
  mirage/route-handlers/crates.js
  mirage/serializers/version.js
  tests/acceptance/readme-rendering-test.js
  tests/mirage/crates/get-by-id-test.js
  tests/mirage/crates/reverse-dependencies-test.js
  tests/mirage/crates/versions/list-test.js
  tests/mirage/crates/versions/readme-test.js
  tests/mirage/me/updates/list-test.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3902 Match monospace font with main font
  app/styles/application.module.css
Labels: C-enhancement, A-frontend, S-waiting-on-review

#3904 KnownErrorToJson: Replace unit test with acceptance test
  src/middleware/known_error_to_json.rs
  src/tests/all.rs
  src/tests/not_found_error.rs
Labels: C-internal, A-backend

#3908 LogRequest: Use `at=error` for all 5xx status code responses
  src/middleware/log_request.rs
Labels: C-internal, A-backend

#3888 Cast `PoolError::UnhealthyPool` into `503 Service Unavailable` error
  src/tests/unhealthy_database.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-bug, A-backend

#3861 Leverage readme_path to support relative paths from readme's not at root
  src/render.rs
Labels: C-enhancement, A-backend

#3917 Remove unused Browserstack logo from the repo
  browserstack-logo.png
Labels: C-documentation

#3918 renovatebot: Remove `assignees` from pull requests
  renovate.json
Labels: A-frontend, C-internal

#3911 renovatebot: Enable `rust` manager, but only with dashboard approval
  .github/renovate.json
Labels: C-internal, A-backend

#3912 Update `handlebars` crate to v4.1.3
  Cargo.lock
  Cargo.toml
  src/tasks/dump_db/dump-export.sql.hbs
  src/tasks/dump_db/dump-import.sql.hbs
Labels: C-internal, A-backend

#3928 ESLint: Use `qunit-dom` plugin
  .eslintrc.js
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#3922 Split DB_POOL_SIZE & DB_MIN_IDLE environment variables
  app.json
  src/app.rs
  src/config/database_pools.rs
  src/middleware.rs
  src/tests/server_binary.rs
Labels: C-internal, A-backend

#3926 Extract `cio_markdown` subpackage
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/admin/render_readmes.rs
  src/markdown/Cargo.toml
  src/markdown/lib.rs
  src/render.rs
Labels: C-internal, A-backend

#3916 tasks::dump_db: Add debug logging
  src/tasks/dump_db.rs
  src/tasks/dump_db/gen_scripts.rs
Labels: C-internal, A-backend

#3933 markdown: Remove `README` references
  src/admin/render_readmes.rs
  src/markdown/lib.rs
  src/render.rs
Labels: C-internal, A-backend

#3932 markdown: Add output assertion to the doc test
  src/markdown/lib.rs
Labels: C-internal, A-backend

#3920 Extract Sentry initialization code into dedicated function
  src/bin/server.rs
  src/lib.rs
  src/sentry.rs
Labels: C-internal, A-backend

#3901 Remove `ChainError` trait
  src/controllers.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/util.rs
  src/router.rs
  src/uploaders.rs
  src/util/errors.rs
Labels: C-internal, A-backend

#3935 Extract `sql` module with all custom `sql_function!()` calls
  src/bin/monitor.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/search.rs
  src/controllers/user/other.rs
  src/lib.rs
  src/models/category.rs
  src/models/keyword.rs
  src/models/krate.rs
  src/models/owner.rs
  src/publish_rate_limit.rs
  src/sql.rs
Labels: C-internal, A-backend

#3949 github: add me to reviewers
  .github/renovate.json
Labels: C-internal

#3954 Remove `ember-cli-sri` addon temporarily
  package.json
  yarn.lock
Labels: A-frontend, C-internal

#3953 Update `comrak` to v0.12.1
  Cargo.lock
  src/markdown/Cargo.toml
Labels: C-internal, A-backend

#3956 Use `HeaderValue::from_static()` instead of `::from(&str)`
  src/admin/render_readmes.rs
  src/uploaders.rs
Labels: C-internal, A-backend

#3934 Move subpackages to top-level folder
  Cargo.lock
  Cargo.toml
  cargo-registry-s3/Cargo.toml
  cargo-registry-s3/lib.rs
  cio-markdown/Cargo.toml
  cio-markdown/lib.rs
Labels: C-internal, A-backend

#3892 Add `BLOCKED_ROUTES` environment variable
  src/config.rs
  src/router.rs
  src/tests/all.rs
  src/tests/blocked_routes.rs
  src/tests/util/test_app.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-internal, A-backend

#3959 prometheus: Disable `protobuf` feature
  Cargo.lock
  Cargo.toml
Labels: C-internal, A-backend

#3950 Implement basic `import-database-dump.sh` script
  script/import-database-dump.sh
Labels: C-internal, A-backend

#3965 Update `prometheus` to 0.13.0
  Cargo.lock
  Cargo.toml
Labels: A-backend

#3958 Rename `cio-markdown` package to `cargo-registry-markdown`
  Cargo.lock
  Cargo.toml
  cargo-registry-markdown/Cargo.toml
  cargo-registry-markdown/lib.rs
  src/admin/render_readmes.rs
  src/render.rs
Labels: C-internal, A-backend
