Repository rust-lang/crates.io, pull requests merged in 2021-07, with the labels that each got.

#3755 Fetch only the master branch when cloning the index
  src/git.rs
Labels: S-waiting-on-review

#3770 Improve metrics accuracy
  src/metrics/macros.rs
  src/metrics/mod.rs
Labels: S-waiting-on-review

#3764 Add note to "Account Settings" page about how to change Name/Github Account
  app/templates/me/index.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3775 Add more histograms
  src/app.rs
  src/controllers.rs
  src/controllers/version/downloads.rs
  src/db.rs
  src/metrics/instance.rs
  src/middleware/log_request.rs
Labels: A-backend, C-internal, S-waiting-on-review

#2676 Add `DELETE /tokens/current` endpoint
  src/controllers/token.rs
  src/router.rs
  src/tests/token.rs
Labels: A-backend, C-enhancement

#3785 Update weekly meeting time
  docs/CONTRIBUTING.md
Labels: S-waiting-on-review

#3793 Avoid logging request_id for successful download redirects
  src/middleware/log_request.rs
Labels: S-waiting-on-review
