Repository rust-lang/crates.io, pull requests merged in 2021-03, with the labels that each got.

#3329 Import `htmlSafe` from `@ember/template`
  app/helpers/format-email.js
  app/services/progress.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3344 VersionList::Row: Fix tooltip alignment in narrow viewport
  app/components/version-list/row.module.css
Labels: A-frontend, C-bug, S-waiting-on-review

#3349 Extract `CrateList` component and improve the styling
  app/components/crate-list.hbs
  app/components/crate-list.module.css
  app/components/crate-row.module.css
  app/controllers/search.js
  app/styles/category/index.module.css
  app/styles/crates.module.css
  app/styles/keyword/index.module.css
  app/styles/me/crates.module.css
  app/styles/me/following.module.css
  app/styles/search.module.css
  app/styles/team.module.css
  app/styles/user.module.css
  app/templates/category/index.hbs
  app/templates/crates.hbs
  app/templates/keyword/index.hbs
  app/templates/me/crates.hbs
  app/templates/me/following.hbs
  app/templates/search.hbs
  app/templates/team.hbs
  app/templates/user.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3346 Implement "Dependencies" tab
  app/components/crate-header.hbs
  app/components/crate-header.js
  app/components/crate-sidebar.hbs
  app/components/dependency-list/row.hbs
  app/components/dependency-list/row.js
  app/components/dependency-list/row.module.css
  app/components/link-to-dep.hbs
  app/components/link-to-dep.module.css
  app/components/nav-tabs/tab.hbs
  app/router.js
  app/routes/crate/dependencies.js
  app/routes/crate/version-dependencies.js
  app/routes/crate/version.js
  app/styles/crate/version-dependencies.module.css
  app/templates/crate/version-dependencies.hbs
  app/templates/crate/version.hbs
  tests/acceptance/crate-dependencies-test.js
  tests/acceptance/crate-navtabs-test.js
  tests/acceptance/crate-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3347 Move keyword list from `CrateSidebar` to `CrateHeader`
  app/components/crate-header.hbs
  app/components/crate-header.module.css
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3260 models/version: Shorten `releaseTrack` for high major versions
  app/models/version.js
  tests/models/version-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3266 Implement and use `/crates/:crate_id/range/:range` route
  app/components/dependency-list/row.hbs
  app/router.js
  app/routes/crate/range.js
  tests/routes/crate/range-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3332 Improve "external crate link" simplification logic
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  app/components/crate-sidebar/link.js
  tests/components/crate-sidebar/link-test.js
  tests/routes/crate/version/crate-links-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3211 Show "Try on Rust Playground" button for crates that are available there
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  app/components/crate-sidebar.module.css
  app/routes/application.js
  app/services/playground.js
  app/utils/ajax.js
  config/nginx.conf.erb
  tests/components/crate-sidebar/playground-button-test.js
  tests/services/playground-test.js
  tests/utils/ajax-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3328 Simplify `authenticate_user()` function
  src/controllers/util.rs
  src/tests/authentication.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3290 CI: Run `cargo fmt` and `cargo clippy` as a dedicated job
  .github/workflows/ci.yml
Labels: A-backend, C-internal, S-waiting-on-review

#3221 Docker: Improve `postgres` setup
  docker-compose.yml
  docker/docker-entrypoint-initdb.d/create-databases.sql
Labels: A-backend, C-internal, S-waiting-on-review

#3364 Upgrade `oauth2` to 4.0.0-alpha.6
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#3365 Upgrade `lettre` to 0.10.0-beta.1
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#3374 Address new clippy findings
  src/middleware/log_request.rs
  src/models/token.rs
  src/tests/builders/version.rs
  src/tests/record.rs
  src/util/token.rs
Labels: A-backend, C-internal

#3371 Extract font-family CSS variables
  app/components/crate-header.module.css
  app/components/crate-sidebar.module.css
  app/styles/application.module.css
Labels: A-frontend, C-internal, S-waiting-on-review

#3372 Remove unused `yanked` CSS classes
  app/components/crate-sidebar.module.css
  app/styles/shared/typography.module.css
Labels: A-frontend, C-internal, S-waiting-on-review

#3370 FollowButton: Avoid size changes
  app/components/follow-button.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3389 Update CloudFront IP addresses
  config/nginx.conf.erb
Labels: S-waiting-on-review

#3391 Refactor some test code
  src/render.rs
  src/tests/all.rs
  src/tests/authentication.rs
  src/tests/krate/dependencies.rs
  src/tests/krate/publish.rs
  src/tests/server.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/util.rs
  src/tests/util/response.rs
  src/tests/util/test_app.rs
Labels: S-waiting-on-review

#3392 Handle invalid docs.rs responses better (fixes #3348)
  app/models/version.js
  tests/routes/crate/version/docs-link-test.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3382 CrateSidebar: Move last update, license and crate size into new "Metadata" section
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3367 Improve README styling
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3393 DownloadGraph: Hide chart points from before a version was released
  app/components/download-graph.js
  package.json
  tests/components/download-graph-test.js
  tests/helpers/match-json.js
  tests/test-helper.js
  yarn.lock
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3366 CrateSidebar: Move Playground explanation to a tooltip
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  tests/components/crate-sidebar/playground-button-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3396 CrateSidebar::Link: Use ellipsis suffix for long URLs
  app/components/crate-sidebar.module.css
  app/components/crate-sidebar/link.hbs
  app/components/crate-sidebar/link.module.css
  app/styles/crate/version.module.css
Labels: A-frontend, C-bug, S-waiting-on-review

#3397 Log how much each step takes on slow downloads
  src/controllers.rs
  src/controllers/version/downloads.rs
  src/middleware/log_request.rs
Labels: S-waiting-on-review

#3398 Show placeholders instead of loading spinner for the README
  app/components/front-page-list/item/placeholder.hbs
  app/components/front-page-list/item/placeholder.module.css
  app/components/placeholder.hbs
  app/components/placeholder.module.css
  app/styles/application.module.css
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3399 Capture request start time in nginx for calculating response times
  config/nginx.conf.erb
  src/middleware/log_request.rs
Labels: S-waiting-on-review

#3407 Display username instead if they don't have the "name" field
  app/components/user-avatar.js
  app/templates/crate/owners.hbs
Labels: S-waiting-on-review

#3406 Remove some FIXME/TODOs
  src/background_jobs.rs
  src/tests/server.rs
  src/tests/user.rs
Labels: S-waiting-on-review

#3408 Extract VisibilityConfig from gen_scripts module
  src/tasks/dump_db.rs
  src/tasks/dump_db/configuration.rs
  src/tasks/dump_db/gen_scripts.rs
Labels: S-waiting-on-review

#3404 reverse-dependencies: Show "no results" message instead of empty list
  app/styles/crate/reverse-dependencies.module.css
  app/templates/crate/reverse-dependencies.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3411 🍱 Crop favicon
  public/favicon.ico
Labels: S-waiting-on-review

#3413 Reduce database writes for the download endpoint
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/bin/server.rs
  src/config.rs
  src/controllers/version/downloads.rs
  src/downloads_counter.rs
  src/lib.rs
  src/models/download.rs
  src/tests/krate/downloads.rs
  src/tests/util/test_app.rs
Labels: S-waiting-on-review

#3414 Prevent transaction deadlocks in DownloadsCounter
  src/downloads_counter.rs
Labels: S-waiting-on-review

#3417 Boot nginx from the backend app to fix graceful shutdown in production
  Procfile
  script/start-web.sh
  src/bin/server.rs
  src/downloads_counter.rs
Labels: S-waiting-on-review

#3421 Improve reverse dependency list styling
  app/components/rev-dep-row.hbs
  app/components/rev-dep-row.js
  app/components/rev-dep-row.module.css
  app/styles/crate/reverse-dependencies.module.css
  app/templates/crate/reverse-dependencies.hbs
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3422 chore: add the missing arg to CONTRIBUTING docs
  docs/CONTRIBUTING.md
Labels: C-documentation, S-waiting-on-review

#3431 Add labels to forms missing them
  .template-lintrc.js
  app/components/email-input.hbs
  app/components/settings/api-tokens.hbs
  app/templates/catch-all.hbs
Labels: A-frontend, C-bug, S-waiting-on-review

#3428 Redirect /owners to /settings
  app/controllers/crate/settings.js
  app/router.js
  app/routes/crate/owners.js
  app/routes/crate/settings.js
  app/styles/crate/settings.module.css
  app/templates/crate/settings.hbs
  tests/acceptance/crate-test.js
  tests/acceptance/settings-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3433 Unify `border-radius` values
  app/components/dependency-list/row.module.css
  app/components/front-page-list/item.module.css
  app/components/front-page-list/item/placeholder.module.css
  app/components/version-list/row.module.css
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3429 start accepting crates without authorship information
  src/controllers/krate/publish.rs
  src/tests/krate/publish.rs
Labels: A-backend, C-enhancement, S-waiting-on-review

#3434 gitignore: Remove .vscode directory
  .gitignore
Labels: S-waiting-on-review

#3436 Remove `civet` server option
  Cargo.lock
  Cargo.toml
  docs/BACKEND.md
  src/bin/server.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3426 krate.search: Add support for `?ids[]=foo&ids[]=bar` queries
  src/controllers/krate/search.rs
  src/tests/krate/search.rs
Labels: A-backend, C-enhancement, S-waiting-on-review

#3441 Bump some of our direct dependencies
  Cargo.lock
  Cargo.toml
Labels: S-waiting-on-review

#3440 Update debug middleware
  src/middleware.rs
  src/middleware/debug.rs
Labels: S-waiting-on-review

#3132 Remove "Authors" section from crate details page
  app/components/crate-sidebar.hbs
  app/models/version.js
  app/routes/crate/version.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3444 Extract `sentry` service
  app/components/crate-sidebar.js
  app/routes/application.js
  app/routes/crate/version.js
  app/services/progress.js
  app/services/sentry.js
  app/services/session.js
  tests/helpers/index.js
  tests/helpers/sentry.js
Labels: A-frontend, C-internal, S-waiting-on-review

#3432 reverse-dependencies: Remove unused CSS class
  app/styles/crate/reverse-dependencies.module.css
Labels: A-frontend, C-internal, S-waiting-on-review

#3442 Show generic flash message if crate data fails to load
  app/routes/crate.js
  app/routes/crate/version.js
  tests/acceptance/crate-test.js
Labels: A-frontend, C-enhancement, S-waiting-on-review

#3446 Run daily database maintenance tasks
  src/bin/enqueue-job.rs
  src/tasks.rs
  src/tasks/daily_db_maintenance.rs
Labels: S-waiting-on-review

#3423 Adds tests for DownloadsCounter
  src/bin/server.rs
  src/db.rs
  src/downloads_counter.rs
  src/tasks/update_downloads.rs
  src/tests/krate/downloads.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3456 package.json: Set `edition: octane` flag
  package.json
Labels: A-frontend, C-internal, S-waiting-on-review

#3464 Fixes #3448 Handle cargo-style semver in `/range`
  app/routes/crate/range.js
  tests/routes/crate/range-test.js
Labels: A-frontend, C-bug, S-waiting-on-review

#3468 util/errors: Fix "trait objects without an explicit `dyn`" deprecation warning/error
  src/util/errors.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3473 DownloadsCounter: Ignore flaky `test_increment_missing_version()` test for now
  src/downloads_counter.rs
Labels: A-backend, C-internal, S-waiting-on-review

#3477 Improve tests for DownloadsCounter
  src/downloads_counter.rs
Labels: A-backend, C-internal, S-waiting-on-review
