Repository rust-lang/crates.io, pull requests merged in 2022-11, with the labels that each got.

#5407 fix: diesel cli install command
  docs/CONTRIBUTING.md
Labels: C-documentation

#5411 s3: Fix `base64::encode()` call
  cargo-registry-s3/lib.rs
Labels: C-internal, A-backend

#5413 Remove unnecessary borrows
  src/controllers/krate/publish.rs
  src/email.rs
  src/tests/builders/publish.rs
  src/worker/dump_db.rs
  src/worker/git.rs
Labels: C-internal, A-backend

#5427 models::Crate: Remove unused `badges()` function
  src/models/krate.rs
  src/tests/all.rs
  src/tests/badge.rs
Labels: C-internal, A-backend

#5428 badges: Remove obsolete database calls
  src/controllers/krate/metadata.rs
  src/controllers/krate/search.rs
Labels: C-internal, A-backend

#5429 badges: Remove obsolete data structures
  src/models.rs
  src/models/badge.rs
  src/views.rs
Labels: C-internal, A-backend

#5430 mirage: Remove `badges` from fixtures
  mirage/fixtures/crates.js
Labels: A-frontend, C-internal

#5431 EncodableCrateUpload: Remove obsolete `badges` field
  src/tests/builders/publish.rs
  src/tests/krate/publish.rs
  src/views/krate_publish.rs
Labels: C-internal, A-backend

#5432 views: Move `mod` and `use` lines to the top of the file
  src/views.rs
Labels: C-internal, A-backend

#5450 Address clippy suggestions
  cargo-registry-index/lib.rs
  cargo-registry-index/testing.rs
  cargo-registry-s3/lib.rs
  src/admin/render_readmes.rs
  src/controllers/helpers/pagination.rs
  src/models/krate.rs
  src/tests/record.rs
  src/tests/util/test_app.rs
  src/uploaders.rs
  src/worker/dump_db.rs
  src/worker/dump_db/gen_scripts.rs
Labels: C-internal, A-backend

#5447 Add additional HTTP logging for cloudfront invalidation failures
  src/worker/cloudfront.rs
Labels: C-internal, A-backend

#5459 downloads_counter: Remove `hashbrown` reference
  Cargo.lock
  Cargo.toml
  src/downloads_counter.rs
Labels: C-internal, A-backend

#5426 downloads: Use `recent_downloads` as `downloads` if it is higher
  src/views.rs
Labels: C-enhancement, A-backend

#5479 cloudfront: Retry requests on server or network error
  Cargo.lock
  Cargo.toml
  src/worker/cloudfront.rs
Labels: C-internal, A-backend

#5467 CI: Remove `beta` backend scenario
  .github/workflows/ci.yml
Labels: C-internal, A-backend

#5487 background-worker: Initialize `tracing` logger
  src/bin/background-worker.rs
Labels: C-internal, A-backend

#5488 background-worker: Initialize `sentry` error reporter
  src/bin/background-worker.rs
Labels: C-internal, A-backend

#5489 cloudfront: Improve logging
  src/worker/cloudfront.rs
Labels: C-internal, A-backend

#5491 tracing: Use `tracing-logfmt` to output log messages
  Cargo.lock
  Cargo.toml
  src/bin/background-worker.rs
  src/bin/server.rs
Labels: C-internal, A-backend

#5423 sentry: Reduce trace sample rate for download endpoint
  src/sentry/mod.rs
Labels: C-internal, A-backend

#5501 me/pending-invites: Use `GET /api/private/crate_owner_invitations` endpoint
  app/adapters/crate-owner-invite.js
  app/routes/me/pending-invites.js
Labels: A-frontend, C-internal

#5503 Fix documentation URL blocking for substring domains
  src/views.rs
Labels: C-bug, A-backend

#5512 middleware::log_request: Simplify `status` check
  src/middleware/log_request.rs
Labels: C-internal, A-backend

#5513 Extract `tracing::init()` function
  src/bin/background-worker.rs
  src/bin/server.rs
  src/util.rs
  src/util/tracing.rs
Labels: C-internal, A-backend

#5517 worker: Use `tracing` macros instead of `println!()`
  src/worker/cloudfront.rs
  src/worker/daily_db_maintenance.rs
  src/worker/dump_db.rs
  src/worker/git.rs
  src/worker/update_downloads.rs
Labels: C-internal, A-backend

#5511 worker::cloudfront: Increase retry attempts
  src/worker/cloudfront.rs
Labels: C-internal, A-backend

#5516 middleware::log_request: Skip `status` logging for successful download requests
  src/middleware/log_request.rs
Labels: C-internal, A-backend

#5519 middleware::log_request: Use `tracing` macros instead of `println!()`
  src/middleware/log_request.rs
Labels: C-internal, A-backend

#5520 tests/server_binary: Use `unwrap()` to fail test instead of returning error
  src/tests/server_binary.rs
Labels: C-internal, A-backend

#5521 tests: Adjust logging
  src/tests/util/test_app.rs
Labels: C-internal, A-backend

#5518 Migrate more `println!()` calls to use `tracing` instead
  Cargo.lock
  cargo-registry-index/Cargo.toml
  cargo-registry-index/lib.rs
  src/admin/migrate.rs
  src/bin/background-worker.rs
  src/bin/server.rs
  src/config/base.rs
  src/middleware.rs
  src/tests/server_binary.rs
Labels: C-internal, A-backend

#5522 tests/server_binary: Use `.context()` to enhance error message
  src/tests/server_binary.rs
Labels: C-internal, A-backend

#5529 tests/owners: Add basic authentication tests for `PUT /crates/:name/owners`
  src/tests/owners.rs
Labels: C-internal, A-backend

#5530 Extract `auth` module
  src/auth.rs
  src/controllers.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/util.rs
  src/lib.rs
Labels: C-internal, A-backend

#5532 package.json: Migrate `pnpm.overrides` back to `resolutions`
  package.json
Labels: A-frontend, C-internal

#5537 UserAuthenticationExt: Remove obsolete `mut` keyword
  src/auth.rs
Labels: C-internal, A-backend

#5535 tests: Extract routes module
  src/tests/all.rs
  src/tests/http-data/routes_crates_new_daily_limit
  src/tests/http-data/routes_crates_read_version_size
  src/tests/krate/following.rs
  src/tests/krate/mod.rs
  src/tests/krate/publish.rs
  src/tests/pagination.rs
  src/tests/routes/categories/get.rs
  src/tests/routes/categories/list.rs
  src/tests/routes/categories/mod.rs
  src/tests/routes/categories/snapshots/all__routes__categories__get__show.snap
  src/tests/routes/categories/snapshots/all__routes__categories__list__index-2.snap
  src/tests/routes/categories/snapshots/all__routes__categories__list__index.snap
  src/tests/routes/category_slugs/list.rs
  src/tests/routes/category_slugs/mod.rs
  src/tests/routes/category_slugs/snapshots/all__routes__category_slugs__list__category_slugs_returns_all_slugs_in_alphabetical_order.snap
  src/tests/routes/crates/downloads.rs
  src/tests/routes/crates/following.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/crates/mod.rs
  src/tests/routes/crates/new.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/crates/owners/mod.rs
  src/tests/routes/crates/read.rs
  src/tests/routes/crates/reverse_dependencies.rs
  src/tests/routes/crates/versions/authors.rs
  src/tests/routes/crates/versions/dependencies.rs
  src/tests/routes/crates/versions/download.rs
  src/tests/routes/crates/versions/mod.rs
  src/tests/routes/crates/versions/read.rs
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__authors__authors.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_semver_no_published_by.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_version.snap
  src/tests/routes/keywords/list.rs
  src/tests/routes/keywords/mod.rs
  src/tests/routes/keywords/read.rs
  src/tests/routes/me/mod.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/tokens/delete.rs
  src/tests/routes/me/tokens/delete_current.rs
  src/tests/routes/me/tokens/list.rs
  src/tests/routes/me/tokens/mod.rs
  src/tests/routes/metrics.rs
  src/tests/routes/mod.rs
  src/tests/routes/summary.rs
  src/tests/routes/versions/list.rs
  src/tests/routes/versions/mod.rs
  src/tests/routes/versions/read.rs
  src/tests/routes/versions/snapshots/all__routes__versions__list__index-2.snap
  src/tests/routes/versions/snapshots/all__routes__versions__list__index.snap
  src/tests/routes/versions/snapshots/all__routes__versions__read__show_by_id.snap
  src/tests/snapshots/all__category__index.snap
  src/tests/snapshots/all__version__authors.snap
  src/tests/snapshots/all__version__index.snap
  src/tests/token.rs
  src/tests/version.rs
Labels: C-internal, A-backend

#5538 auth: Implement AuthCheck struct
  src/auth.rs
  src/controllers.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/version/yank.rs
  src/lib.rs
Labels: C-internal, A-backend

#5540 tests: Use more doc comments to describe tests and test helpers
  src/tests/owners.rs
  src/tests/record.rs
  src/tests/routes/crates/list.rs
  src/tests/team.rs
  src/tests/user.rs
Labels: A-backend, C-documentation

#5541 tests/user: Move tests into `routes` submodules
  src/tests/routes/crates/list.rs
  src/tests/routes/me/email_notifications.rs
  src/tests/routes/me/get.rs
  src/tests/routes/me/mod.rs
  src/tests/routes/me/updates.rs
  src/tests/routes/mod.rs
  src/tests/routes/session/authorize.rs
  src/tests/routes/session/begin.rs
  src/tests/routes/session/mod.rs
  src/tests/routes/users/mod.rs
  src/tests/routes/users/read.rs
  src/tests/routes/users/stats.rs
  src/tests/routes/users/update.rs
  src/tests/user.rs
Labels: C-internal, A-backend

#5555 LogRequests: Reduce amount of logged information for successful download requests
  src/middleware/log_request.rs
Labels: C-internal, A-backend
