Repository rust-lang/crates.io, pull requests merged in 2022-01, with the labels that each got.

#4400 Adding categories related to Aerospace
  src/boot/categories.toml
Labels: C-enhancement, A-backend, A-categories

#4398 Replace `timekeeper` with `@sinonjs/fake-timers`
  package.json
  tests/components/download-graph-test.js
  tests/helpers/fake-timers.js
  tests/helpers/setup-mirage.js
  tests/mirage/me/tokens/create-test.js
  tests/models/version-test.js
  yarn.lock
Labels: A-frontend, C-internal

#3973 Support relative URLs from repo-subdirectory packages
  cargo-registry-markdown/lib.rs
  src/admin/render_readmes.rs
  src/controllers/krate/publish.rs
  src/util.rs
  src/worker/readmes.rs
Labels: C-enhancement, A-backend

#4440 Use format arguments capture feature
  cargo-registry-markdown/lib.rs
  cargo-registry-s3/lib.rs
  src/admin/delete_crate.rs
  src/admin/on_call.rs
  src/admin/render_readmes.rs
  src/bin/enqueue-job.rs
  src/bin/monitor.rs
  src/bin/server.rs
  src/boot/categories.rs
  src/controllers.rs
  src/controllers/krate/search.rs
  src/controllers/token.rs
  src/controllers/util.rs
  src/email.rs
  src/git.rs
  src/github.rs
  src/middleware.rs
  src/middleware/debug.rs
  src/models/action.rs
  src/models/dependency.rs
  src/models/krate.rs
  src/models/version.rs
  src/tests/account_lock.rs
  src/tests/keyword.rs
  src/tests/krate/downloads.rs
  src/tests/krate/following.rs
  src/tests/krate/reverse_dependencies.rs
  src/tests/krate/yanking.rs
  src/tests/metrics.rs
  src/tests/owners.rs
  src/tests/record.rs
  src/tests/server_binary.rs
  src/tests/team.rs
  src/tests/token.rs
  src/tests/user.rs
  src/tests/util.rs
  src/tests/util/chaosproxy.rs
  src/tests/util/fresh_schema.rs
  src/tests/version.rs
  src/uploaders.rs
  src/util/errors/json.rs
  src/views.rs
  src/views/krate_publish.rs
  src/worker/dump_db.rs
  src/worker/dump_db/gen_scripts.rs
  src/worker/git.rs
Labels: C-internal, A-backend

#4450 use new cargo fmt check option
  .github/workflows/ci.yml
Labels: C-internal, A-backend

#4460 Use Volta to pin Node.js and yarn versions
  .github/renovate.json5
  .github/workflows/ci.yml
  package.json
Labels: A-frontend, C-internal

#4464 embroider: Remove obsolete `ember-get-config` workaround
  ember-cli-build.js
Labels: A-frontend, C-internal

#4465 Use embroider build system by default
  .github/workflows/ci.yml
  ember-cli-build.js
Labels: A-frontend, C-internal

#4382 Add support for `keyword:cli` and `category:no-std` search filters
  app/controllers/search.js
  app/styles/application.module.css
  app/styles/search.module.css
  app/templates/search.hbs
  app/utils/search.js
  tests/acceptance/search-test.js
  tests/utils/search-test.js
Labels: C-enhancement, A-frontend

#4474 Remove obsolete `ember-keyboard` options
  config/environment.js
Labels: A-frontend, C-internal

#4475 Disable `crypto` import warning in `axe-core`
  ember-cli-build.js
Labels: A-frontend, C-internal

#4476 crate.range: Show error page if data fails to load
  app/routes/crate/range.js
  tests/routes/crate/range-test.js
Labels: C-enhancement, A-frontend

#4477 Adjust error page titles
  app/routes/crate.js
  app/routes/crate/version.js
  tests/acceptance/crate-test.js
  tests/routes/crate/range-test.js
  tests/routes/crate/version/model-test.js
Labels: C-enhancement, A-frontend

#4479 crate.version-dependencies: Show error page if data loading fails
  app/routes/crate/version-dependencies.js
  tests/acceptance/crate-dependencies-test.js
Labels: C-enhancement, A-frontend

#4480 category: Show error page if data loading fails
  app/routes/category.js
  tests/routes/category-test.js
Labels: C-enhancement, A-frontend

#4481 keyword: Show error page if data loading fails
  app/controllers/keyword.js
  app/routes/keyword.js
  app/routes/keyword/index.js
  app/templates/index.hbs
  app/templates/keyword.hbs
  app/templates/keyword/error.hbs
  tests/routes/keyword-test.js
Labels: C-enhancement, A-frontend

#4507 Fix `keyword` route links
  app/components/crate-header.hbs
  app/templates/keywords.hbs
  tests/bugs/4506-test.js
Labels: C-bug, A-frontend

#4514 Ember: Use `history` location API
  config/environment.js
Labels: A-frontend, C-internal
