Repository rust-lang/crates.io, pull requests merged in 2022-12, with the labels that each got.

#5562 database/api_tokens: Add `crate_scopes` and `endpoint_scopes` columns
  migrations/2022-11-23-135139_add-token-scopes/down.sql
  migrations/2022-11-23-135139_add-token-scopes/up.sql
  src/models/token.rs
  src/schema.rs
  src/worker/dump_db/dump-db.toml
Labels: C-enhancement, A-backend

#5568 Implement `EndpointScope` enum
  src/models/token.rs
  src/models/token/scopes.rs
Labels: C-internal, A-backend

#5570 tests/owners: Add tests with token scopes
  src/models.rs
  src/models/token.rs
  src/tests/owners.rs
  src/tests/util.rs
  src/tests/util/test_app.rs
Labels: C-internal, A-backend

#5571 AuthCheck: Add `with_endpoint_scope()` and `for_crate()` options
  src/auth.rs
  src/tests/owners.rs
Labels: C-internal, A-backend

#5575 CrateScope: Remove crate name normalization
  src/models/token/scopes.rs
Labels: C-enhancement, A-backend

#5567 Add `science::neuroscience` category
  src/boot/categories.toml
Labels: A-categories

#5578 Ember Data: Fix relationship deprecation warnings
  app/models/category.js
  app/models/crate.js
  app/models/dependency.js
  app/models/keyword.js
  app/models/version-download.js
  app/models/version.js
Labels: A-frontend, C-internal

#5579 tests/krate/yanking: Move route tests into routes submodules
  src/tests/http-data/routes_crates_versions_yank_unyank_unyank_records_an_audit_action
  src/tests/http-data/routes_crates_versions_yank_unyank_yank_records_an_audit_action
  src/tests/krate/yanking.rs
  src/tests/routes/crates/versions/mod.rs
  src/tests/routes/crates/versions/yank_unyank.rs
Labels: C-internal, A-backend

#5583 tests/yank_unyank: Add authentication tests
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_cookie_user
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_unauthenticated
  src/tests/routes/crates/versions/yank_unyank.rs
Labels: C-internal, A-backend

#5584 CI: Split into frontend and backend workflows
  .github/workflows/ci-backend.yml
  .github/workflows/ci-frontend.yml
  .github/workflows/ci.yml
Labels: C-internal

#5585 tests/record: Use `.json` file extension for HTTP fixtures
  src/tests/http-data/gh-crates-tester-1.json
  src/tests/http-data/gh-crates-tester-2.json
  src/tests/http-data/krate_publish_features_version_2.json
  src/tests/http-data/krate_publish_good_badges.json
  src/tests/http-data/krate_publish_good_categories.json
  src/tests/http-data/krate_publish_good_keywords.json
  src/tests/http-data/krate_publish_ignored_badges.json
  src/tests/http-data/krate_publish_ignored_categories.json
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency.json
  src/tests/http-data/krate_publish_new_krate.json
  src/tests/http-data/krate_publish_new_krate_git_upload.json
  src/tests/http-data/krate_publish_new_krate_git_upload_appends.json
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts.json
  src/tests/http-data/krate_publish_new_krate_records_verified_email.json
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted.json
  src/tests/http-data/krate_publish_new_krate_twice.json
  src/tests/http-data/krate_publish_new_krate_weird_version.json
  src/tests/http-data/krate_publish_new_krate_with_dependency.json
  src/tests/http-data/krate_publish_new_krate_with_readme.json
  src/tests/http-data/krate_publish_new_krate_with_token.json
  src/tests/http-data/krate_publish_new_with_renamed_dependency.json
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency.json
  src/tests/http-data/krate_publish_publish_after_removing_documentation.json
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited.json
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates.json
  src/tests/http-data/krate_publish_publish_records_an_audit_action.json
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate.json
  src/tests/http-data/krate_yanking_publish_after_yank_max_version.json
  src/tests/http-data/krate_yanking_yank_max_version.json
  src/tests/http-data/krate_yanking_yank_works_as_intended.json
  src/tests/http-data/owners_new_crate_owner.json
  src/tests/http-data/routes_crates_new_daily_limit.json
  src/tests/http-data/routes_crates_read_version_size.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_cookie_user.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_unauthenticated.json
  src/tests/http-data/routes_crates_versions_yank_unyank_unyank_records_an_audit_action.json
  src/tests/http-data/routes_crates_versions_yank_unyank_yank_records_an_audit_action.json
  src/tests/http-data/team_publish_owned.json
  src/tests/http-data/team_remove_team_as_team_owner.json
  src/tests/record.rs
Labels: C-internal, A-backend

#5587 tests: Add missing slash prefixes to API requests
  src/tests/krate/following.rs
  src/tests/routes/users/read.rs
Labels: C-internal, A-backend

#5589 middleware::ember_html: Use `lookup()` to avoid unnecessary path mutation
  Cargo.lock
  Cargo.toml
  src/middleware/ember_html.rs
Labels: C-internal, A-backend

#5590 Header: Use `cargo.png` instead of redundant second image file with unwanted padding
  app/components/header.hbs
  app/components/header.module.css
  public/assets/Cargo-Logo-Small.png
Labels: A-frontend, C-internal

#5591 Move `cargo.png` into `assets` folder
  app/components/header.hbs
  app/index.html
  config/manifest.js
  config/nginx.conf.erb
  public/assets/cargo.png
  public/opensearch.xml
Labels: A-frontend, C-internal

#5593 middleware::EmberHtml: Move `fastboot_client` into the `App` struct
  src/app.rs
  src/middleware/ember_html.rs
Labels: C-internal, A-backend

#5611 tests: Replace unnecessary `conduit` imports
  src/tests/account_lock.rs
  src/tests/authentication.rs
  src/tests/blocked_routes.rs
  src/tests/owners.rs
  src/tests/read_only_mode.rs
  src/tests/routes/metrics.rs
  src/tests/server.rs
  src/tests/team.rs
  src/tests/token.rs
  src/tests/util.rs
  src/tests/util/response.rs
Labels: C-internal, A-backend

#5613 tests/util/response: Remove unnecessary `mem::swap()`
  src/tests/util/response.rs
Labels: C-internal, A-backend

#5614 tests/routes/categories/get: Avoid database connection deadlock
  src/tests/routes/categories/get.rs
Labels: C-internal, A-backend

#5615 tests/Response: Replace `conduit::Response` with `reqwest::blocking::Response`
  conduit-hyper/src/lib.rs
  conduit-hyper/src/service.rs
  conduit-hyper/src/service/blocking_handler.rs
  src/tests/util.rs
  src/tests/util/response.rs
Labels: C-internal, A-backend

#5616 tests/routes/crates/list: Fix `.search()` calls with invalid characters
  src/tests/routes/crates/list.rs
Labels: C-internal, A-backend

#5617 Run tests through `conduit-hyper` layer
  src/tests/authentication.rs
  src/tests/util.rs
  src/tests/util/test_app.rs
Labels: C-internal, A-backend

#5618 email: Remove `email_backend` metadata logging
  src/email.rs
Labels: C-internal, A-backend

#5619 tracing: Extract `init_for_test()` function
  src/tests/util/test_app.rs
  src/util/tracing.rs
Labels: C-internal, A-backend

#5620 conduit-hyper: Remove unnecessary dependency declarations
  Cargo.lock
  conduit-hyper/Cargo.toml
  conduit-hyper/src/file_stream.rs
  conduit-hyper/src/service.rs
Labels: C-internal, A-backend

#5629 CI: Run backend/frontend jobs only for changes in corresponding files
  .github/workflows/ci-backend.yml
  .github/workflows/ci-frontend.yml
  .github/workflows/ci.yml
Labels: C-internal

#5605 Migrate from raw `hyper` server to `axum`
  Cargo.lock
  Cargo.toml
  conduit-axum/Cargo.toml
  conduit-axum/LICENSE-APACHE
  conduit-axum/LICENSE-MIT
  conduit-axum/README.md
  conduit-axum/examples/server.rs
  conduit-axum/src/adaptor.rs
  conduit-axum/src/error.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/file_stream.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/server.rs
  conduit-axum/src/tests.rs
  conduit-hyper/src/service.rs
  src/bin/server.rs
  src/lib.rs
  src/tests/util.rs
  src/tests/util/test_app.rs
Labels: C-internal, A-backend

#5633 middleware: Enable `LogRequests` middleware in test mode
  src/middleware.rs
Labels: C-internal, A-backend

#5495 Add API endpoint to receive alerts of exposed API tokens from GitHub
  Cargo.lock
  Cargo.toml
  src/controllers.rs
  src/controllers/github.rs
  src/controllers/github/secret_scanning.rs
  src/email.rs
  src/github.rs
  src/router.rs
  src/tests/all.rs
  src/tests/github_secret_scanning.rs
  src/tests/util.rs
  src/tests/util/github.rs
Labels: C-enhancement, A-backend

#5638 GitHub Secret Scanning improvements
  src/controllers/github/secret_scanning.rs
  src/tests/github_secret_scanning.rs
  src/tests/util/github.rs
Labels: C-internal, A-backend

#5639 github/secret_scanning: Check for *hashed* tokens
  src/controllers/github/secret_scanning.rs
  src/tests/github_secret_scanning.rs
  src/util.rs
  src/util/token.rs
Labels: C-bug, A-backend

#5641 github/secret_scanning: Adjust logging content
  src/controllers/github/secret_scanning.rs
Labels: C-internal, A-backend

#5642 github/secret_scanning: Avoid duplicate emails
  src/controllers/github/secret_scanning.rs
  src/tests/github_secret_scanning.rs
Labels: C-bug, A-backend

#5644 github/secret_scanning: Consider revoked tokens as true positive
  src/controllers/github/secret_scanning.rs
  src/models/user.rs
  src/tests/github_secret_scanning.rs
Labels: C-enhancement, A-backend

#5572 Implement token scope restrictions for our endpoints
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_endpoint_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_wildcard_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_endpoint_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_wildcard_crate_scope.json
  src/tests/owners.rs
  src/tests/routes/crates/versions/yank_unyank.rs
Labels: C-enhancement ✨, A-backend ⚙️

#5647 Revert `base64` dependency upgrade
  Cargo.lock
  Cargo.toml
  cargo-registry-index/Cargo.toml
  cargo-registry-s3/Cargo.toml
  src/controllers/helpers/pagination.rs
  src/metrics/log_encoder.rs
Labels: C-bug 🐞, A-backend ⚙️

#5648 renovate: Update PR labels
  .github/renovate.json5
Labels: C-internal 🔧

#5652 util/tracing: Use custom `event_filter()`
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#5653 conduit-axum: Improve internal server error handling
  Cargo.lock
  conduit-axum/Cargo.toml
  conduit-axum/src/fallback.rs
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#5654 Replace `sentry-conduit` with `sentry-tower`
  Cargo.lock
  Cargo.toml
  conduit-axum/src/fallback.rs
  src/lib.rs
  src/middleware.rs
  src/sentry/middleware.rs
  src/sentry/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#5655 middleware/log_request: Add `nginx_time` field if it is non-zero
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#5658 Revert "middleware/log_request: Add `nginx_time` field if it is non-zero"
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#5660 Remove obsolete `triagebot.toml` config
  triagebot.toml
Labels: C-internal 🔧

#5659 Remove `X-Request-Start` header code
  config/nginx.conf.erb
  src/middleware.rs
  src/middleware/log_request.rs
  src/middleware/response_timing.rs
Labels: C-internal 🔧, A-backend ⚙️

#5661 email: Use `tracing` to log errors and successes
  src/email.rs
Labels: C-internal 🔧, A-backend ⚙️

#5662 Implement experimental `log_requests` axum middleware
  Cargo.lock
  Cargo.toml
  src/headers.rs
  src/lib.rs
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#5663 middleware/log_request: Add custom metadata fields to `axum` logging
  src/auth.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/publish.rs
  src/controllers/version/downloads.rs
  src/middleware/balance_capacity.rs
  src/middleware/block_traffic.rs
  src/middleware/log_request.rs
  src/middleware/normalize_path.rs
  src/middleware/require_user_agent.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5664 X_REAL_IP: Fix copy paste bug in header name
  src/headers.rs
Labels: C-bug 🐞, A-backend ⚙️

#5665 middleware/log_request: Add `error` field to `axum` logging
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#5666 middleware/log_request: Switch to axum-based logging
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#5673 middleware/debug: Convert to `axum` middleware
  src/lib.rs
  src/middleware.rs
  src/middleware/debug.rs
Labels: C-internal 🔧, A-backend ⚙️

#5672 Remove obsolete `LogConnectionPoolStatus` middleware
  src/middleware.rs
  src/middleware/log_connection_pool_status.rs
Labels: C-internal 🔧, A-backend ⚙️

#5674 middleware: Extract `apply_axum_middleware()` function
  src/lib.rs
  src/middleware.rs
Labels: C-internal 🔧, A-backend ⚙️

#5675 middleware/normalize_path: Migrate to `axum`
  src/bin/server.rs
  src/middleware.rs
  src/middleware/log_request.rs
  src/middleware/normalize_path.rs
Labels: C-internal 🔧, A-backend ⚙️

#5686 tests/unhealthy_database: Increase timeout to 2 sec
  src/tests/unhealthy_database.rs
Labels: C-internal 🔧, A-backend ⚙️

#5678 Implement axum-based `session` middleware
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/auth.rs
  src/config.rs
  src/controllers/user/session.rs
  src/lib.rs
  src/middleware.rs
  src/middleware/session.rs
  src/tests/authentication.rs
  src/tests/util.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5687 middleware/update_metrics: Migrate to `axum`
  Cargo.toml
  conduit-axum/Cargo.toml
  conduit-axum/src/fallback.rs
  src/middleware.rs
  src/middleware/update_metrics.rs
Labels: C-internal 🔧, A-backend ⚙️

#5688 middleware/require_user_agent: Move `cdn_user_agent` field into server `config`
  src/config.rs
  src/middleware/require_user_agent.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5697 middleware/log_requests: Extract `CustomMetadataRequestExt` trait
  src/auth.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/publish.rs
  src/controllers/version/downloads.rs
  src/middleware.rs
  src/middleware/balance_capacity.rs
  src/middleware/block_traffic.rs
  src/middleware/log_request.rs
  src/middleware/require_user_agent.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5698 middleware/require_user_agent: Migrate to `axum`
  src/middleware.rs
  src/middleware/require_user_agent.rs
Labels: C-internal 🔧, A-backend ⚙️

#5700 middleware/block_traffic: Migrate to `axum`
  src/middleware.rs
  src/middleware/block_traffic.rs
  src/tests/server.rs
  src/tests/snapshots/all__server__block_traffic_via_arbitrary_header_and_value.snap
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#5701 middleware/head: Migrate to `axum`
  src/middleware.rs
  src/middleware/head.rs
  src/tests/all.rs
  src/tests/middleware/head.rs
  src/tests/middleware/mod.rs
  src/util.rs
  src/util/request_proxy.rs
Labels: C-internal 🔧, A-backend ⚙️

#5707 Add a category for finance
  src/boot/categories.toml
Labels: C-enhancement ✨, A-categories

#5708 Add a description for the neuroscience category
  src/boot/categories.toml
Labels: C-enhancement ✨, A-categories

#5711 middleware/static_or_continue: Migrate to `axum`
  Cargo.lock
  Cargo.toml
  src/middleware.rs
  src/middleware/static_or_continue.rs
Labels: C-internal 🔧, A-backend ⚙️

#5712 middleware/update_metrics: Implement `GaugeGuard` struct
  src/middleware/update_metrics.rs
Labels: C-internal 🔧, A-backend ⚙️

#5714 Simplify `BalanceCapacity` middleware
  src/config.rs
  src/config/balance_capacity.rs
  src/middleware.rs
  src/middleware/balance_capacity.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5715 middleware/balance_capacity: Migrate to `axum`
  src/app.rs
  src/middleware.rs
  src/middleware/balance_capacity.rs
Labels: C-internal 🔧, A-backend ⚙️

#5717 Bump to latest nginx buildpack
  .buildpacks
Labels: C-internal 🔧, A-backend ⚙️

#5451 Vendor a portion of the `swirl` crate
  Cargo.lock
  Cargo.toml
  src/admin/yank_version.rs
  src/background_jobs.rs
  src/bin/background-worker/main.rs
  src/bin/enqueue-job.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/db.rs
  src/lib.rs
  src/swirl.rs
  src/swirl/errors.rs
  src/swirl/runner.rs
  src/swirl/runner/event.rs
  src/swirl/storage.rs
  src/tests/util/test_app.rs
  src/worker/daily_db_maintenance.rs
  src/worker/dump_db.rs
  src/worker/dump_db/gen_scripts.rs
  src/worker/git.rs
  src/worker/mod.rs
  src/worker/readmes.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#5736 Add `sentry::set_transaction` middleware
  src/middleware.rs
  src/middleware/sentry.rs
Labels: C-internal 🔧, A-backend ⚙️

#5737 Implement `block_traffic::block_routes` middleware
  src/middleware.rs
  src/middleware/block_traffic.rs
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#5730 Fix default credentials location
  app/components/settings/api-tokens.hbs
Labels: A-frontend 🐹, C-documentation 📜

#5738 GET /api/v1/site_metadata: Migrate to `axum`
  src/controllers/site_metadata.rs
  src/lib.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5741 router: Extract `build_axum_router()` function
  src/lib.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5742 sentry: Include request method in transaction name
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5743 Migrate `conduit-git-http-backend` code to `axum`
  Cargo.lock
  Cargo.toml
  src/controllers.rs
  src/controllers/git.rs
  src/lib.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5744 Remove obsolete `conduit-conditional-get` dependency
  Cargo.lock
  Cargo.toml
  src/middleware.rs
Labels: C-internal 🔧, A-backend ⚙️

#5745 middleware/static_or_continue: Extract common `serve()` function
  src/middleware/static_or_continue.rs
Labels: C-internal 🔧, A-backend ⚙️

#5746 conduit-axum: Enable missing `client` feature for `sentry-core`
  conduit-axum/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#5749 conduit-axum: Simplify `server_error_response()` function
  conduit-axum/src/fallback.rs
  conduit-axum/src/tests.rs
Labels: C-internal 🔧, A-backend ⚙️

#5747 swirl/errors: Use `thiserror`
  src/swirl/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5748 Move `AppErrToStdErr` into the only file that uses it
  src/router.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5751 metrics/instance: Narrow return types
  src/metrics/instance.rs
Labels: C-internal 🔧, A-backend ⚙️

#5752 helpers/pagination: Simplify `limit_page_numbers` API
  src/controllers/helpers/pagination.rs
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️

#5750 config: Extract `AllowedOrigins` struct
  src/config.rs
  src/controllers/util.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5753 db: Move database access methods into `impl App`
  src/app.rs
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#5754 util::errors: Replace catch-all `From` implementation with explicit implementations
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5755 middleware/app: Use `AppState` struct instead of raw `Arc<App>`
  src/controllers/krate/publish.rs
  src/lib.rs
  src/middleware.rs
  src/middleware/app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5756 Simplify `req.app()` calls
  src/controllers/krate/publish.rs
  src/controllers/user/session.rs
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#5758 controllers/github: Narrow function arguments
  src/controllers/github/secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#5757 middleware/app: Remove unnecessary `after()` block
  src/middleware/app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5759 db: Remove `RequestTransaction` trait
  src/auth.rs
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#5767 tracing: Allow `RUST_LOG` usage in test mode
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#5768 bin/enqueue-job: Use `clap` to parse commands and generate help text
  Cargo.toml
  src/bin/enqueue-job.rs
Labels: C-internal 🔧, A-backend ⚙️

#5769 bin/crates-admin: Simplify `clap` usage
  src/bin/crates-admin.rs
Labels: C-internal 🔧, A-backend ⚙️

#5771 bin/crates-admin: Add `enqueue-job` subcommand
  src/admin/enqueue_job.rs
  src/admin/mod.rs
  src/bin/crates-admin.rs
  src/bin/enqueue-job.rs
Labels: C-internal 🔧, A-backend ⚙️
