Repository rust-lang/crates.io, pull requests merged in 2022-02, with the labels that each got.

#4397 Remove obsolete `/authorize/github` route
  .env.sample
  app/router.js
  app/routes/github-authorize.js
  docs/CONTRIBUTING.md
  tests/routes/github-authorize-test.js
Labels: C-enhancement, A-frontend

#4552 Explicitly specify the branch name in init-local-index.sh
  script/init-local-index.sh
Labels: C-internal, A-backend

#4551 Fix clippy warnings
  cargo-registry-markdown/lib.rs
  src/tests/record.rs
Labels: C-internal, A-backend

#4554 controllers::krate: Protect against null bytes in query string
  src/controllers/krate/search.rs
  src/tests/krate/search.rs
Labels: C-bug, A-backend
