Repository rust-lang/crates.io, pull requests merged in 2022-05, with the labels that each got.

#4781 Disable in-browser translation
  app/index.html
Labels: A-frontend, C-internal

#4788 Sentry: Set transaction name instead of custom `routeName` tag
  app/routes/application.js
  tests/helpers/sentry.js
Labels: A-frontend, C-internal

#4794 renovate: Automatically merge linting and testing dependency updates
  .github/renovate.json5
Labels: C-internal

#4807 Add `Virtualization` category to crates.io
  src/boot/categories.toml
Labels: A-categories

#4811 Refactor `render-readmes` task to use `upload_readme` function
  src/admin/render_readmes.rs
Labels: C-internal, A-backend

#3955 Change crate file `Content-Type` to `application/gzip`
  src/tests/http-data/krate_publish_features_version_2
  src/tests/http-data/krate_publish_good_badges
  src/tests/http-data/krate_publish_good_categories
  src/tests/http-data/krate_publish_ignored_badges
  src/tests/http-data/krate_publish_ignored_categories
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency
  src/tests/http-data/krate_publish_new_krate
  src/tests/http-data/krate_publish_new_krate_git_upload
  src/tests/http-data/krate_publish_new_krate_git_upload_appends
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts
  src/tests/http-data/krate_publish_new_krate_records_verified_email
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted
  src/tests/http-data/krate_publish_new_krate_twice
  src/tests/http-data/krate_publish_new_krate_weird_version
  src/tests/http-data/krate_publish_new_krate_with_broken_dependency_requirement
  src/tests/http-data/krate_publish_new_krate_with_dependency
  src/tests/http-data/krate_publish_new_krate_with_readme
  src/tests/http-data/krate_publish_new_krate_with_token
  src/tests/http-data/krate_publish_new_with_renamed_dependency
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency
  src/tests/http-data/krate_publish_publish_after_removing_documentation
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/http-data/krate_publish_publish_records_an_audit_action
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate
  src/tests/http-data/krate_yanking_publish_after_yank_max_version
  src/tests/http-data/krate_yanking_unyank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_max_version
  src/tests/http-data/krate_yanking_yank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_works_as_intended
  src/tests/http-data/owners_new_crate_owner
  src/tests/http-data/team_publish_owned
  src/tests/http-data/team_remove_team_as_team_owner
  src/tests/http-data/version_version_size
  src/uploaders.rs
Labels: C-bug, A-backend

#4812 Refactor `upload` to avoid passing content_length
  src/uploaders.rs
  src/worker/dump_db.rs
Labels: C-internal, A-backend

#4813 catch-all: Fix `reload()` action
  app/controllers/catch-all.js
Labels: C-bug, A-frontend

#4814 search: Fix app crash without given `q` query parameter
  app/controllers/search.js
  app/templates/search.hbs
  tests/acceptance/search-test.js
Labels: C-bug, A-frontend

#4806 Use env var to support blocking IP ranges
  Cargo.lock
  Cargo.toml
  src/config.rs
  src/controllers/helpers/pagination.rs
  src/tests/krate/search.rs
  src/tests/util.rs
  src/tests/util/test_app.rs
Labels: C-internal, A-backend

#4661 Upload index metadata to `index/` when publishing new crates
  .env.sample
  cargo-registry-index/lib.rs
  src/admin/delete_crate.rs
  src/admin/mod.rs
  src/admin/upload_index.rs
  src/bin/crates-admin.rs
  src/config/base.rs
  src/controllers/krate/publish.rs
  src/tests/http-data/krate_publish_features_version_2
  src/tests/http-data/krate_publish_good_badges
  src/tests/http-data/krate_publish_good_categories
  src/tests/http-data/krate_publish_ignored_badges
  src/tests/http-data/krate_publish_ignored_categories
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency
  src/tests/http-data/krate_publish_new_krate
  src/tests/http-data/krate_publish_new_krate_git_upload
  src/tests/http-data/krate_publish_new_krate_git_upload_appends
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts
  src/tests/http-data/krate_publish_new_krate_records_verified_email
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted
  src/tests/http-data/krate_publish_new_krate_twice
  src/tests/http-data/krate_publish_new_krate_weird_version
  src/tests/http-data/krate_publish_new_krate_with_dependency
  src/tests/http-data/krate_publish_new_krate_with_readme
  src/tests/http-data/krate_publish_new_krate_with_token
  src/tests/http-data/krate_publish_new_with_renamed_dependency
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency
  src/tests/http-data/krate_publish_publish_after_removing_documentation
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/http-data/krate_publish_publish_records_an_audit_action
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate
  src/tests/http-data/krate_yanking_publish_after_yank_max_version
  src/tests/http-data/krate_yanking_unyank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_max_version
  src/tests/http-data/krate_yanking_yank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_works_as_intended
  src/tests/http-data/owners_new_crate_owner
  src/tests/http-data/team_publish_owned
  src/tests/http-data/version_version_size
  src/uploaders.rs
  src/worker/dump_db.rs
  src/worker/git.rs
Labels: C-enhancement, A-backend

#4826 Drop index/ prefix when uploading crate metadata.
  src/tests/http-data/krate_publish_features_version_2
  src/tests/http-data/krate_publish_good_badges
  src/tests/http-data/krate_publish_good_categories
  src/tests/http-data/krate_publish_ignored_badges
  src/tests/http-data/krate_publish_ignored_categories
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency
  src/tests/http-data/krate_publish_new_krate
  src/tests/http-data/krate_publish_new_krate_git_upload
  src/tests/http-data/krate_publish_new_krate_git_upload_appends
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts
  src/tests/http-data/krate_publish_new_krate_records_verified_email
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted
  src/tests/http-data/krate_publish_new_krate_twice
  src/tests/http-data/krate_publish_new_krate_weird_version
  src/tests/http-data/krate_publish_new_krate_with_dependency
  src/tests/http-data/krate_publish_new_krate_with_readme
  src/tests/http-data/krate_publish_new_krate_with_token
  src/tests/http-data/krate_publish_new_with_renamed_dependency
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency
  src/tests/http-data/krate_publish_publish_after_removing_documentation
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/http-data/krate_publish_publish_records_an_audit_action
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate
  src/tests/http-data/krate_yanking_publish_after_yank_max_version
  src/tests/http-data/krate_yanking_unyank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_max_version
  src/tests/http-data/krate_yanking_yank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_works_as_intended
  src/tests/http-data/owners_new_crate_owner
  src/tests/http-data/team_publish_owned
  src/tests/http-data/version_version_size
  src/uploaders.rs
Labels: C-enhancement, A-backend

#4825 Simplify CIDR parsing code
  src/config.rs
Labels: C-internal, A-backend

#4836 admin/upload_index: Use `indicatif` for progress reporting
  Cargo.lock
  Cargo.toml
  src/admin/upload_index.rs
Labels: C-internal, A-backend
