Repository rust-lang/crates.io, pull requests merged in 2022-10, with the labels that each got.

#5275 fix: bump to ember-data 4.6.4 to fix randomUUID polyfill bug
  package.json
  pnpm-lock.yaml
Labels: C-bug, A-frontend

#5200 Add CloudFront invalidation for index files
  .env.sample
  Cargo.lock
  Cargo.toml
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
  src/worker/cloudfront.rs
  src/worker/git.rs
  src/worker/mod.rs
Labels: C-internal, A-backend

#5216 Add FAQ on how to leave crate open for adoption
  app/templates/policies.hbs
Labels: C-documentation

#5295 clap: Derive possible values for `EventType` argument
  src/admin/test_pagerduty.rs
Labels: C-internal, A-backend

#5298 clap: Resolve deprecation warnings
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/git_import.rs
  src/admin/migrate.rs
  src/admin/populate.rs
  src/admin/render_readmes.rs
  src/admin/test_pagerduty.rs
  src/admin/transfer_crates.rs
  src/admin/upload_index.rs
  src/admin/verify_token.rs
  src/admin/yank_version.rs
  src/bin/crates-admin.rs
Labels: C-internal, A-backend

#5297 clap: Add new `wrap_help` feature flag
  Cargo.lock
  Cargo.toml
Labels: C-internal, A-backend

#5272 Prevent login flow from being disrupted by unrelated events
  app/services/session.js
Labels: C-bug, A-frontend

#5315 Ignore "exact match" for search when sorted by downloads
  src/controllers/krate/search.rs
  src/tests/krate/search.rs
Labels: C-enhancement, A-backend

#5321 Add clarification on why you can't view existing API keys
  app/components/settings/api-tokens.hbs
Labels: C-enhancement, A-frontend

#5325 CI: Remove obsolete `bors` CI jobs
  .github/workflows/ci.yml
Labels: C-internal

#5324 Remove outdated "Deploying & using a mirror" instructions
  README.md
  docs/ARCHITECTURE.md
  docs/MIRROR.md
Labels: C-documentation

#5330 docs: Reintroduce `MIRROR.md` to keep third party links to the document working
  docs/MIRROR.md
Labels: C-documentation

#5333 Heroku: Remove unused `app.json` file
  app.json
  docs/ARCHITECTURE.md
Labels: C-internal, A-backend

#5347 Use AWS_ environment variables for authenticating to AWS services
  .env.sample
  src/config/base.rs
  src/worker/cloudfront.rs
Labels: C-internal, A-backend

#5349 docs: Restrict `diesel_cli` to version 1.x
  docs/CONTRIBUTING.md
Labels: A-backend, C-documentation

#5353 styles: Extract `transition` design tokens
  app/components/crate-row.module.css
  app/components/crate-sidebar.module.css
  app/components/dependency-list/row.module.css
  app/components/footer.module.css
  app/components/front-page-list/item.module.css
  app/components/nav-tabs/tab.module.css
  app/components/owned-crate-row.module.css
  app/components/rev-dep-row.module.css
  app/components/search-form.module.css
  app/components/side-menu/item.module.css
  app/components/version-list/row.module.css
  app/styles/application.module.css
Labels: A-frontend, C-internal

#5354 footer: Add Zulip channel to "Social" link list
  app/components/footer.hbs
  public/assets/zulip.svg
Labels: C-enhancement, A-frontend

#5342 Adjust search input placeholder text
  app/components/search-form.hbs
Labels: C-enhancement, A-frontend

#5366 styles: Extract `font-body/heading` font family design tokens
  app/styles/application.module.css
Labels: A-frontend, C-internal

#5369 Remove unused CSS classes
  app/components/header.module.css
  app/styles/crate/version.module.css
Labels: A-frontend, C-internal

#5294 Introduce daily limit of published versions per crate
  src/config.rs
  src/controllers/krate/publish.rs
  src/tests/http-data/version_daily_limit
  src/tests/util/test_app.rs
  src/tests/version.rs
Labels: C-enhancement, A-backend

#5375 Remove unused CSS classes
  app/styles/crates.module.css
  app/styles/dashboard.module.css
Labels: A-frontend, C-internal

#5380 renovate: Keep pnpm version up-to-date
  .github/renovate.json5
Labels: C-internal

#5385 docs: update API routes source file name
  docs/BACKEND.md
Labels: C-documentation

#5391 Use `@mainmatter/ember-api-actions` instead of custom implementation
  app/models/crate.js
  app/models/user.js
  app/utils/custom-action.js
  package.json
  pnpm-lock.yaml
Labels: A-frontend, C-internal
