Repository rust-lang/crates.io, pull requests merged in 2022-09, with the labels that each got.

#5167 PageHeader: Remove margins on `.heading` element
  app/components/page-header.module.css
  app/styles/category/index.module.css
Labels: C-enhancement, A-frontend

#5170 Remove icons from page headers
  app/components/crate-header.hbs
  app/components/crate-header.module.css
  app/components/page-header.hbs
  app/components/page-header.module.css
  app/templates/category/index.hbs
  app/templates/crate/docs.hbs
  app/templates/dashboard.hbs
  app/templates/data-access.hbs
  app/templates/install.hbs
  app/templates/me/pending-invites.hbs
  app/templates/policies.hbs
  app/templates/search.hbs
  app/templates/settings/appearance.hbs
  app/templates/settings/email-notifications.hbs
  app/templates/settings/profile.hbs
  app/templates/settings/tokens.hbs
  public/assets/circle-with-i.svg
  public/assets/dashboard.svg
  public/assets/gear.svg
  public/assets/magnifier.svg
Labels: C-enhancement, A-frontend

#5171 ember-cli-babel: Ensure parallel builds
  ember-cli-build.js
Labels: A-frontend, C-internal

#5172 Align text in page headers properly
  app/components/crate-header.module.css
  app/components/page-header.module.css
Labels: C-enhancement, A-frontend

#5173 PageHeader: Adjust `padding` to other content on the pages
  app/components/page-header.module.css
  app/styles/category/index.module.css
Labels: C-enhancement, A-frontend

#5180 services/session: Clear in-memory data when logging out
  app/services/session.js
  tests/acceptance/logout-test.js
Labels: C-enhancement, A-frontend

#5228 Add release state to contrib docs
  docs/CONTRIBUTING.md
Labels: C-documentation

#5175 CrateHeader: Add `v` prefix to version number
  app/components/crate-header.hbs
  tests/acceptance/crate-test.js
  tests/routes/crate/range-test.js
  tests/routes/crate/version/model-test.js
Labels: C-enhancement, A-frontend

#5238 ember-get-config: Use override to update to v2.1.1
  package.json
  pnpm-lock.yaml
Labels: A-frontend, C-internal

#5244 Use slightly darker background color for header and footer
  app/styles/application.module.css
Labels: C-enhancement, A-frontend

#5243 CrateHeader: Fix narrow screen layout
  app/components/crate-header.hbs
  app/components/crate-header.module.css
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/components/crate-sidebar/link.hbs
  app/components/crate-sidebar/link.module.css
  app/components/follow-button.hbs
  app/styles/crate/version-dependencies.module.css
  app/templates/crate/version-dependencies.hbs
Labels: C-enhancement, A-frontend

#5262 CI: Replace `volta-cli/action` with builtin functionality from `actions/setup-node`
  .github/workflows/ci.yml
Labels: C-internal

#5267 Fix typo in footer
  app/components/footer.hbs
Labels: A-frontend
