Repository rust-lang/crates.io, pull requests merged in 2022-08, with the labels that each got.

#5032 Replace is_alphanumeric + is_ascii with is_ascii_alphanumeric
  src/models/keyword.rs
Labels: C-internal, A-backend

#5037 Fail tests if there are remaining exchanges in the request proxy queue
  src/tests/http-data/krate_publish_new_krate_with_broken_dependency_requirement
  src/tests/krate/publish.rs
  src/tests/record.rs
Labels: C-internal, A-backend

#5038 Remove unnecessary request proxy headers
  src/tests/http-data/krate_publish_features_version_2
  src/tests/http-data/krate_publish_good_badges
  src/tests/http-data/krate_publish_good_categories
  src/tests/http-data/krate_publish_ignored_badges
  src/tests/http-data/krate_publish_ignored_categories
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency
  src/tests/http-data/krate_publish_new_krate
  src/tests/http-data/krate_publish_new_krate_git_upload
  src/tests/http-data/krate_publish_new_krate_git_upload_appends
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts
  src/tests/http-data/krate_publish_new_krate_records_verified_email
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted
  src/tests/http-data/krate_publish_new_krate_twice
  src/tests/http-data/krate_publish_new_krate_weird_version
  src/tests/http-data/krate_publish_new_krate_with_dependency
  src/tests/http-data/krate_publish_new_krate_with_readme
  src/tests/http-data/krate_publish_new_krate_with_token
  src/tests/http-data/krate_publish_new_with_renamed_dependency
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency
  src/tests/http-data/krate_publish_publish_after_removing_documentation
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/http-data/krate_publish_publish_records_an_audit_action
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate
  src/tests/http-data/krate_yanking_publish_after_yank_max_version
  src/tests/http-data/krate_yanking_unyank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_max_version
  src/tests/http-data/krate_yanking_yank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_works_as_intended
  src/tests/http-data/owners_new_crate_owner
  src/tests/http-data/team_publish_owned
  src/tests/http-data/team_remove_team_as_team_owner
  src/tests/http-data/version_version_size
  src/tests/record.rs
Labels: C-internal, A-backend

#5039 Don't auto-generate empty http-data files
  src/tests/record.rs
Labels: C-internal, A-backend

#5040 Add an option to easily regenerate http-data files
  src/tests/record.rs
Labels: C-internal, A-backend

#5041 Sort headers of http-data files
  src/tests/http-data/krate_publish_features_version_2
  src/tests/http-data/krate_publish_good_badges
  src/tests/http-data/krate_publish_good_categories
  src/tests/http-data/krate_publish_ignored_badges
  src/tests/http-data/krate_publish_ignored_categories
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency
  src/tests/http-data/krate_publish_new_krate
  src/tests/http-data/krate_publish_new_krate_git_upload
  src/tests/http-data/krate_publish_new_krate_git_upload_appends
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts
  src/tests/http-data/krate_publish_new_krate_records_verified_email
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted
  src/tests/http-data/krate_publish_new_krate_twice
  src/tests/http-data/krate_publish_new_krate_weird_version
  src/tests/http-data/krate_publish_new_krate_with_dependency
  src/tests/http-data/krate_publish_new_krate_with_readme
  src/tests/http-data/krate_publish_new_krate_with_token
  src/tests/http-data/krate_publish_new_with_renamed_dependency
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency
  src/tests/http-data/krate_publish_publish_after_removing_documentation
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/http-data/krate_publish_publish_records_an_audit_action
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate
  src/tests/http-data/krate_yanking_publish_after_yank_max_version
  src/tests/http-data/krate_yanking_unyank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_max_version
  src/tests/http-data/krate_yanking_yank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_works_as_intended
  src/tests/http-data/owners_new_crate_owner
  src/tests/http-data/team_publish_owned
  src/tests/http-data/version_version_size
  src/tests/record.rs
Labels: C-internal, A-backend

#5042 Always run background jobs after a test publish
  src/tests/http-data/krate_publish_new_krate_git_upload_appends
  src/tests/http-data/krate_publish_publish_after_removing_documentation
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate
  src/tests/http-data/krate_yanking_publish_after_yank_max_version
  src/tests/http-data/krate_yanking_unyank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_max_version
  src/tests/http-data/krate_yanking_yank_records_an_audit_action
  src/tests/http-data/owners_new_crate_owner
  src/tests/http-data/version_version_size
  src/tests/krate/publish.rs
  src/tests/krate/yanking.rs
  src/tests/owners.rs
  src/tests/team.rs
  src/tests/util.rs
  src/tests/util/test_app.rs
  src/tests/version.rs
Labels: C-internal, A-backend

#5022 Ensure the HTTP index is updated after a yank/unyank
  src/tests/http-data/krate_yanking_publish_after_yank_max_version
  src/tests/http-data/krate_yanking_unyank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_max_version
  src/tests/http-data/krate_yanking_yank_records_an_audit_action
  src/tests/http-data/krate_yanking_yank_works_as_intended
  src/worker/git.rs
Labels: C-bug, A-backend

#5010 Toggle stacked download graph
  app/components/download-graph.hbs
  app/components/download-graph.js
  app/controllers/crate/version.js
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
Labels: C-enhancement, A-frontend

#5044 Replace `lazy_static` with `once_cell`
  Cargo.lock
  Cargo.toml
  src/tests/all.rs
  src/tests/builders/publish.rs
Labels: C-internal, A-backend

#5060 admin/upload-index: Restore "skipping file" output
  src/admin/upload_index.rs
Labels: C-internal, A-backend

#5070 Remove unnecessary derefs
  src/boot/categories.rs
  src/controllers/krate/publish.rs
  src/controllers/version/downloads.rs
  src/models/crate_owner_invitation.rs
  src/models/keyword.rs
  src/models/user.rs
  src/tests/krate/publish.rs
  src/tests/krate/search.rs
  src/tests/krate/summary.rs
  src/tests/user.rs
  src/worker/readmes.rs
Labels: C-internal, A-backend

#5074 Stop saving badges in the database
  src/controllers/krate/publish.rs
  src/tests/krate/publish.rs
Labels: C-internal, A-backend

#5077 database: Add `checksum` field
  migrations/2022-08-14-090630_checksum-column/down.sql
  migrations/2022-08-14-090630_checksum-column/up.sql
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/models/version.rs
  src/schema.rs
  src/tests/builders/version.rs
  src/worker/dump_db/dump-db.toml
  src/worker/update_downloads.rs
Labels: C-internal, A-backend

#5092 Replace Mozilla with Rust Foundation in Package Policies
  app/templates/policies.hbs
Labels: C-enhancement, A-frontend

#5095 Update Cargo links
  README.md
  app/templates/categories.hbs
Labels: C-documentation

#5091 database: Add `explicit_name` column to `dependencies` table
  migrations/2022-08-17-073805_explicit-name/down.sql
  migrations/2022-08-17-073805_explicit-name/up.sql
  src/controllers/krate/publish.rs
  src/models/dependency.rs
  src/schema.rs
  src/worker/dump_db/dump-db.toml
Labels: C-internal, A-backend

#5089 index: Use/Allow alphabetic ordering of features and dependencies
  cargo-registry-index/lib.rs
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/models/version.rs
  src/tests/builders/publish.rs
  src/tests/builders/version.rs
  src/tests/krate/publish.rs
  src/views/krate_publish.rs
  src/worker/update_downloads.rs
Labels: C-internal, A-backend

#5084 Migrate from yarn 1.x to pnpm
  .buildpacks
  .github/renovate.json5
  .github/workflows/ci.yml
  .gitignore
  docker-compose.yml
  docs/CONTRIBUTING.md
  frontend.Dockerfile
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: A-frontend, C-internal

#5046 Allow '+' in keywords
  src/models/keyword.rs
  src/tests/http-data/krate_publish_good_keywords
  src/tests/krate/publish.rs
Labels: C-enhancement, A-backend

#5100 pnpm: Ignore `postcss` peer dependency warnings
  package.json
Labels: A-frontend, C-internal

#5101 pnpm: Fix more peer dependency issues
  package.json
  pnpm-lock.yaml
Labels: A-frontend, C-internal

#5110 Fixed typo
  src/boot/categories.toml
Labels: C-bug

#5112 Add tool to import from git index into the database
  src/admin/git_import.rs
  src/admin/mod.rs
  src/bin/crates-admin.rs
Labels: C-internal, A-backend

#5116 Update discord pointer in README
  README.md
Labels: C-documentation

#5118 ESLint: Add missing `@babel/plugin-proposal-decorators` dependency
  package.json
  pnpm-lock.yaml
Labels: A-frontend, C-internal

#5120 git-import admin tool can resume partial imports
  src/admin/git_import.rs
Labels: C-internal, A-backend

#5122 admin::git_import: Improve error reporting
  src/admin/git_import.rs
Labels: C-internal, A-backend

#5123 ember-data: Replace `store.find()` calls with `store.findRecord()`
  app/routes/category.js
  app/routes/crate.js
Labels: A-frontend, C-internal

#5125 ember-data: Silence `model-save-promise` deprecation
  config/deprecation-workflow.js
  package.json
  pnpm-lock.yaml
Labels: A-frontend, C-internal

#5132 CI: Run `percy exec` with `pnpm` instead of `pnpx`
  .github/workflows/ci.yml
Labels: A-frontend, C-internal

#5126 Replace `ember-api-actions` dependency with `customAction()` function
  app/models/crate.js
  app/models/user.js
  app/utils/custom-action.js
  package.json
  pnpm-lock.yaml
Labels: A-frontend, C-internal

#5115 ember-concurrency: Migrate to new task syntax API
  app/components/dependency-list/row.js
  app/components/email-input.js
  app/components/follow-button.js
  app/components/pending-owner-invite-row.js
  app/components/rev-dep-row.js
  app/components/settings/api-tokens.js
  app/controllers/crate/settings.js
  app/controllers/crate/version.js
  app/controllers/dashboard.js
  app/controllers/index.js
  app/controllers/search.js
  app/models/version.js
  app/routes/application.js
  app/services/chartjs.js
  app/services/playground.js
  app/services/progress.js
  app/services/session.js
  tests/components/download-graph-test.js
Labels: A-frontend, C-internal

#5127 Autofill search box when browsing categories
  app/routes/category.js
  tests/routes/category-test.js
Labels: C-enhancement, A-frontend

#5134 Docker: Fix pnpm usage
  .gitignore
  frontend.Dockerfile
Labels: A-frontend, C-internal

#5133 tests: Use `insta` to assert on full version API responses
  Cargo.lock
  Cargo.toml
  src/tests/snapshots/all__version__authors.snap
  src/tests/snapshots/all__version__index-2.snap
  src/tests/snapshots/all__version__index.snap
  src/tests/snapshots/all__version__show_by_crate_name_and_semver_no_published_by.snap
  src/tests/snapshots/all__version__show_by_crate_name_and_version.snap
  src/tests/snapshots/all__version__show_by_id.snap
  src/tests/util.rs
  src/tests/util/insta.rs
  src/tests/version.rs
Labels: C-internal, A-backend

#5135 versions: Adjust `checksum` column to be `NOT NULL`
  migrations/2022-08-28-191319_non-null-checksum/down.sql
  migrations/2022-08-28-191319_non-null-checksum/up.sql
  src/models/version.rs
  src/schema.rs
Labels: C-internal, A-backend

#5146 Use snapshot testing for `category` API tests
  src/tests/category.rs
  src/tests/snapshots/all__category__category_slugs_returns_all_slugs_in_alphabetical_order.snap
  src/tests/snapshots/all__category__index-2.snap
  src/tests/snapshots/all__category__index.snap
  src/tests/snapshots/all__category__show.snap
Labels: C-internal, A-backend

#5150 renovate: Group `diesel` packages in one pull request
  .github/renovate.json5
Labels: C-internal

#5149 Adjust header foreground colors
  app/components/header.module.css
  app/styles/application.module.css
Labels: C-enhancement, A-frontend

#5148 RenderedHtml: Fix inline code styling in lists
  app/components/rendered-html.module.css
Labels: C-bug, A-frontend

#5144 Fix rustdoc link rendering in READMEs
  app/styles/application.module.css
  cargo-registry-markdown/lib.rs
Labels: C-enhancement, A-frontend, A-backend

#5145 EncodableVersion: Expose new `checksum` field on the API
  src/tests/builders/version.rs
  src/tests/snapshots/all__version__index-2.snap
  src/tests/snapshots/all__version__show_by_crate_name_and_semver_no_published_by.snap
  src/tests/snapshots/all__version__show_by_crate_name_and_version.snap
  src/tests/snapshots/all__version__show_by_id.snap
  src/tests/version.rs
  src/views.rs
Labels: C-enhancement, A-backend

#5159 Simplify setup of test recorder
  src/tests/record.rs
Labels: C-internal, A-backend

#5160 Simplify spawning the http server in production
  src/bin/server.rs
Labels: C-internal, A-backend

#5165 Migrate from `claim` to `claims`
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/tests/all.rs
Labels: C-internal, A-backend

#5166 tests/record: Fix server bind IP address
  src/tests/record.rs
Labels: C-internal, A-backend

#5164 accept-invite: Use `<LinkTo>` instead of raw `<a>`
  app/templates/accept-invite.hbs
Labels: C-bug, A-frontend
