Repository rust-lang/crates.io, pull requests merged in 2023-02, with the labels that each got.

#6032 Implement GitHub SSH certificate checks
  Cargo.lock
  cargo-registry-index/Cargo.toml
  cargo-registry-index/lib.rs
Labels: C-bug 🐞, A-backend ⚙️

#6033 Fix SSH hostkey checks for `push()`
  cargo-registry-index/lib.rs
Labels: C-bug 🐞, A-backend ⚙️

#6039 Replace custom `certificate_check()` impl with regular `known_hosts` file
  Cargo.lock
  cargo-registry-index/Cargo.toml
  cargo-registry-index/lib.rs
  src/bin/background-worker.rs
  src/lib.rs
  src/ssh/known_hosts
  src/ssh/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#6037 Bump CI to use Ubuntu 22.04
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: C-internal 🔧

#6050 Remove deprecated `ember-export-application-global` dependency
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#6043 background-worker: Speed up index cloning by 3x
  cargo-registry-index/lib.rs
  src/bin/background-worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#6021 Set backend dockerfile to install diesel version 1.4.1
  backend.Dockerfile
Labels: C-internal 🔧

#6070 Use Renovatebot regex managers for Docker files
  .github/renovate.json5
  backend.Dockerfile
  frontend.Dockerfile
Labels: C-internal 🔧

#6071 middleware: Use new `option_layer()` from `axum-extra` crate
  src/middleware.rs
Labels: C-internal 🔧, A-backend ⚙️

#6104 email: Add `Content-Type` header
  src/email.rs
Labels: C-enhancement ✨, A-backend ⚙️
