Repository rust-lang/crates.io, pull requests merged in 2023-09, with the labels that each got.

#7062 Updated outdated default branch name
  README.md
Labels: C-documentation 📜

#7052 Replace `cargo_toml` with `cargo-manifest`
  Cargo.lock
  crates_io_tarball/Cargo.toml
  crates_io_tarball/src/lib.rs
  crates_io_tarball/src/manifest.rs
  src/admin/render_readmes.rs
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7100 Remove dummy `let` assignments
  src/controllers/krate/publish.rs
  src/tests/record.rs
Labels: C-internal 🔧, A-backend ⚙️

#6958 Replace hardcoded credentials path with cargo docs link
  app/components/settings/api-tokens.hbs
Labels: C-documentation 📜

#7101 tests: Remove obsolete HTTP recorder
  src/tests/all.rs
  src/tests/record.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7105 Fix flakey ratelimit test
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7108 Remove obsolete `support_head_requests()` middleware
  src/middleware.rs
  src/middleware/head.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#7111 Split publish tests
  src/tests/krate/publish.rs
  src/tests/krate/publish/audit_action.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/build_metadata.rs
  src/tests/krate/publish/categories.rs
  src/tests/krate/publish/dependencies.rs
  src/tests/krate/publish/emails.rs
  src/tests/krate/publish/features.rs
  src/tests/krate/publish/git.rs
  src/tests/krate/publish/inheritance.rs
  src/tests/krate/publish/keywords.rs
  src/tests/krate/publish/manifest.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/mod.rs
  src/tests/krate/publish/rate_limit.rs
  src/tests/krate/publish/readme.rs
  src/tests/krate/publish/similar_names.rs
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_1.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_3.snap
  src/tests/krate/publish/tarball.rs
  src/tests/krate/publish/timestamps.rs
  src/tests/krate/publish/validation.rs
Labels: C-internal 🔧, A-backend ⚙️

#7115 views/krate_publish: Fix docs typos
  src/views/krate_publish.rs
Labels: A-backend ⚙️, C-documentation 📜

#7114 tests/builders/publish: Simplify `create_publish_body()` fn
  src/tests/builders/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7113 controllers/krate/publish: Replace `tarball_to_app_error()` fn with `From` implementation
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7118 tests/krate/publish: Use more snapshot tests for error responses
  src/controllers/krate/publish.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/snapshots/all__krate__publish__auth__new_krate_wrong_user.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-10.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-4.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-5.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-6.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-7.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-8.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-9.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required.snap
  src/tests/krate/publish/validation.rs
Labels: C-internal 🔧, A-backend ⚙️

#7119 insta: Use `json` snapshots
  Cargo.toml
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/build_metadata.rs
  src/tests/krate/publish/snapshots/all__krate__publish__auth__new_krate_wrong_user.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_1.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-10.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-4.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-5.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-6.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-7.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-8.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-9.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__license_and_description_required.snap
  src/tests/krate/publish/validation.rs
  src/tests/models/krate.rs
  src/tests/models/snapshots/all__models__krate__index_metadata-2.snap
  src/tests/models/snapshots/all__models__krate__index_metadata.snap
  src/tests/routes/categories/get.rs
  src/tests/routes/categories/list.rs
  src/tests/routes/categories/snapshots/all__routes__categories__get__show.snap
  src/tests/routes/categories/snapshots/all__routes__categories__list__index-2.snap
  src/tests/routes/categories/snapshots/all__routes__categories__list__index.snap
  src/tests/routes/category_slugs/list.rs
  src/tests/routes/category_slugs/snapshots/all__routes__category_slugs__list__category_slugs_returns_all_slugs_in_alphabetical_order.snap
  src/tests/routes/crates/versions/authors.rs
  src/tests/routes/crates/versions/read.rs
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__authors__authors.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_semver_no_published_by.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_version.snap
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/tokens/list.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__list__list_tokens.snap
  src/tests/routes/versions/list.rs
  src/tests/routes/versions/read.rs
  src/tests/routes/versions/snapshots/all__routes__versions__list__index-2.snap
  src/tests/routes/versions/snapshots/all__routes__versions__list__index.snap
  src/tests/routes/versions/snapshots/all__routes__versions__read__show_by_id.snap
Labels: C-internal 🔧, A-backend ⚙️

#7121 controllers/krate/publish: Fix copy paste mistakes in error messages
  src/controllers/krate/publish.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/snapshots/all__krate__publish__tarball__empty.snap
  src/tests/krate/publish/snapshots/all__krate__publish__tarball__json_bytes_truncated.snap
  src/tests/krate/publish/snapshots/all__krate__publish__tarball__json_len_truncated.snap
  src/tests/krate/publish/snapshots/all__krate__publish__tarball__tarball_bytes_truncated.snap
  src/tests/krate/publish/snapshots/all__krate__publish__tarball__tarball_len_truncated.snap
  src/tests/krate/publish/tarball.rs
Labels: C-bug 🐞, A-backend ⚙️

#7120 tarball: Use `BTreeMap` for `manifests`
  crates_io_tarball/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#7123 Add more tests for the publish workflow
  src/tests/krate/publish/categories.rs
  src/tests/krate/publish/dependencies.rs
  src/tests/krate/publish/features.rs
  src/tests/krate/publish/keywords.rs
  src/tests/krate/publish/manifest.rs
  src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_rename.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature_name.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap
  src/tests/krate/publish/snapshots/all__krate__publish__manifest__manifest_casing.snap
  src/tests/krate/publish/snapshots/all__krate__publish__manifest__multiple_manifests.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__empty_json.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_version.snap
  src/tests/krate/publish/validation.rs
Labels: C-internal 🔧, A-backend ⚙️

#7133 tests/util: Inline `modify_owners()` fn
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#7134 tests/util: Avoid unnecessary cloning
  src/tests/github_secret_scanning.rs
  src/tests/krate/following.rs
  src/tests/krate/publish/dependencies.rs
  src/tests/krate/publish/tarball.rs
  src/tests/krate/publish/validation.rs
  src/tests/owners.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/routes/me/email_notifications.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/updates.rs
  src/tests/routes/users/update.rs
  src/tests/user.rs
  src/tests/util.rs
  src/tests/util/mock_request.rs
  src/tests/worker/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#7135 tests/builders/publish: Decrease `krate_name` visibility
  src/tests/builders/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7138 tests/PublishBuilder: Generate correct manifests
  Cargo.lock
  Cargo.toml
  src/tests/builders/publish.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/inheritance.rs
  src/tests/krate/publish/manifest.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/tarball.rs
  src/tests/routes/crates/read.rs
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7145 EncodableKeywordList: Move keyword length validation into `EncodableKeyword` impl
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7147 tests/builders/publish: Simplify `create_publish_body()` fn by using `BytesMut` struct
  Cargo.lock
  Cargo.toml
  src/tests/builders/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7148 tarball/builder: Remove `prefix` field and associated constructor arguments
  crates_io_tarball/src/builder.rs
  crates_io_tarball/src/lib.rs
  src/admin/render_readmes.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/tarball.rs
Labels: C-internal 🔧, A-backend ⚙️

#7150 tests/utils/ajax: Add assertion description
  tests/utils/ajax-test.js
Labels: A-frontend 🐹, C-internal 🔧

#7154 Unify `assert_eq!()` argument order
  src/controllers/helpers/pagination.rs
  src/downloads_counter.rs
  src/rate_limiter.rs
  src/swirl/runner.rs
  src/tests/blocked_routes.rs
  src/tests/github_secret_scanning.rs
  src/tests/owners.rs
  src/tests/read_only_mode.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/crates/read.rs
  src/tests/routes/metrics.rs
  src/tests/routes/users/read.rs
  src/tests/user.rs
  src/tests/util/response.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7152 tests: Increase default upload size limits
  src/tests/krate/publish/max_size.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7153 tarball: Simplify `manifests.len()` condition
  crates_io_tarball/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#7116 Fix flaky yank ratelimit test
  src/tests/krate/yanking.rs
Labels: C-internal 🔧, A-backend ⚙️

#7158 Remove unnecessary `with_database()` calls
  src/tests/krate/publish/rate_limit.rs
Labels: C-internal 🔧, A-backend ⚙️

#7161 EncodableCrateUpload: Rename struct to `PublishMetadata`
  src/controllers/krate/publish.rs
  src/tests/builders/publish.rs
  src/views.rs
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7174 tests/utils/ajax: Adjust error message assertion for new Chrome release
  tests/utils/ajax-test.js
Labels: A-frontend 🐹, C-internal 🔧

#7176 controllers/krate/publish: Remove `metadata_length` field from request logs
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7181 controllers/token: Order by `id` instead of `created_at`
  src/controllers/token.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__list__list_tokens.snap
Labels: C-internal 🔧, A-backend ⚙️

#7182 controllers/krate/publish: Remove unnecessary string allocations
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7183 Ember Data: Fix `toArray()` deprecation warnings in the test suite code
  tests/components/version-list-row-test.js
  tests/models/version-test.js
Labels: A-frontend 🐹, C-internal 🔧

#7185 models/krate: Move URL and name validation out of `create_or_update()`
  src/controllers/krate/publish.rs
  src/models/krate.rs
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_urls.snap
  src/tests/krate/publish/validation.rs
Labels: C-internal 🔧, A-backend ⚙️

#7188 Use `db_write()` instead of the `primary_database` field
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/tests/all.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7192 tests/krate/publish: Add missing `description` and `license` fields to generated `Cargo.toml` files
  src/tests/krate/publish/manifest.rs
  src/tests/krate/publish/max_size.rs
Labels: C-internal 🔧, A-backend ⚙️

#7193 controllers/krate/publish: Remove obsolete `license.clone()` call
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7194 publish: Use `description`, `license` and `license_file` fields from embedded `Cargo.toml` file
  src/controllers/krate/publish.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7195 models/version: Move license validation into publish endpoint
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/models.rs
  src/models/version.rs
  src/tests/builders/version.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7199 Extract `licenses` module
  src/controllers/krate/publish.rs
  src/lib.rs
  src/licenses.rs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#7201 publish: Use `homepage`, `documentation` and `repository` fields from embedded `Cargo.toml` file
  src/controllers/krate/publish.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7204 publish: Use `links` field from embedded `Cargo.toml` file
  src/controllers/krate/publish.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7208 views/krate_publish: Remove unnecessary `EncodableCategory` struct
  src/tests/builders/publish.rs
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7207 views/krate_publish: Reorder file contents
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7209 publish: Read `categories` metadata from embedded `Cargo.toml` file
  src/controllers/krate/publish.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish/snapshots/all__krate__publish__categories__too_many_categories.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7214 publish: Read `keywords` metadata from embedded `Cargo.toml` file
  src/controllers/krate/publish.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__bad_keywords.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__too_many_keywords.snap
  src/views/krate_publish.rs
Labels: C-internal 🔧, A-backend ⚙️
