Repository rust-lang/crates.io, pull requests merged in 2023-11, with the labels that each got.

#7407 dump_db: improve README based on #7030
  src/worker/dump_db/readme_for_tarball.md
Labels: A-infrastructure 📡, C-documentation 📜

#7406 worker: Extract job structs
  Cargo.lock
  Cargo.toml
  src/background_jobs.rs
  src/worker/daily_db_maintenance.rs
  src/worker/dump_db.rs
  src/worker/git.rs
  src/worker/mod.rs
  src/worker/readmes.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7317 SQL: Fix metadata handling in to_semver_no_prerelease() function
  migrations/2023-10-19-092709_fix_semver_no_prerelease_fn/down.sql
  migrations/2023-10-19-092709_fix_semver_no_prerelease_fn/up.sql
  src/db/sql_types/semver.rs
  src/sql.rs
Labels: C-bug 🐞, A-backend ⚙️

#7390 tests: Replace `FreshSchema` architecture with `TestDatabase`
  docs/CONTRIBUTING.md
  src/tests/dump_db.rs
  src/tests/server_binary.rs
  src/tests/util.rs
  src/tests/util/fresh_schema.rs
  src/tests/util/test_app.rs
  src/tests/util/test_database.rs
Labels: C-internal 🔧, A-backend ⚙️

#7411 background_jobs: Extract `BackgroundJob` trait
  src/background_jobs.rs
  src/worker/daily_db_maintenance.rs
  src/worker/dump_db.rs
  src/worker/git.rs
  src/worker/readmes.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7412 worker: Extract `...Job::new()` fns
  src/background_jobs.rs
  src/worker/dump_db.rs
  src/worker/git.rs
  src/worker/readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#7413 background_jobs: Inline `sync_to_git/sparse_index()` fns
  src/background_jobs.rs
Labels: C-internal 🔧, A-backend ⚙️

#7414 background_jobs: Move `enqueue()` fn into `BackgroundJob` trait
  src/admin/enqueue_job.rs
  src/background_jobs.rs
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#7417 background_jobs: Add `PRIORITY` constant to `BackgroundJob` trait
  src/background_jobs.rs
  src/controllers/krate/publish.rs
  src/worker/git.rs
  src/worker/readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#7419 tests/read_only_mode: Use real `read_only_mode` setting
  src/tests/read_only_mode.rs
  src/tests/util/test_app.rs
  src/tests/util/test_database.rs
Labels: C-internal 🔧, A-backend ⚙️

#7418 swirl/runner: Add `register_job_type()` fn
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/yank_version.rs
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/swirl/runner.rs
  src/tests/util/test_app.rs
  src/tests/worker/git.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#7421 swirl: Simplify `Event` enum code
  src/swirl/runner.rs
  src/swirl/runner/event.rs
Labels: C-internal 🔧, A-backend ⚙️

#7425 swirl/runner: Make `Runner` generic over `Context`
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/swirl/runner.rs
  src/tests/util/test_app.rs
  src/worker/daily_db_maintenance.rs
  src/worker/dump_db.rs
  src/worker/git.rs
  src/worker/mod.rs
  src/worker/readmes.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7426 Restructure `worker` module
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/enqueue_job.rs
  src/admin/yank_version.rs
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/cloudfront.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/fastly.rs
  src/lib.rs
  src/swirl.rs
  src/tests/dump_db.rs
  src/tests/util/test_app.rs
  src/tests/worker/git.rs
  src/util/errors.rs
  src/worker/environment.rs
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/dump_db/configuration.rs
  src/worker/jobs/dump_db/dump-db.toml
  src/worker/jobs/dump_db/dump-export.sql.j2
  src/worker/jobs/dump_db/dump-import.sql.j2
  src/worker/jobs/dump_db/gen_scripts.rs
  src/worker/jobs/dump_db/readme_for_tarball.md
  src/worker/jobs/git.rs
  src/worker/jobs/mod.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/update_downloads.rs
  src/worker/mod.rs
  src/worker/swirl/background_job.rs
  src/worker/swirl/errors.rs
  src/worker/swirl/mod.rs
  src/worker/swirl/perform_state.rs
  src/worker/swirl/runner.rs
  src/worker/swirl/storage.rs
Labels: C-internal 🔧, A-backend ⚙️

#7427 Reduce panic usage in admin commands
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/enqueue_job.rs
  src/admin/git_import.rs
  src/admin/migrate.rs
  src/admin/populate.rs
  src/admin/render_readmes.rs
  src/admin/transfer_crates.rs
  src/admin/upload_index.rs
  src/admin/verify_token.rs
  src/admin/yank_version.rs
  src/bin/crates-admin.rs
Labels: C-internal 🔧, A-backend ⚙️

#7370 Remove obsolete nginx wrapper
  .buildpacks
  config/nginx.conf.erb
  src/bin/server.rs
  src/config/server.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7428 Change "Just Updated" links to point to the corresponding crate version
  app/templates/index.hbs
  tests/acceptance/crate-test.js
  tests/acceptance/front-page-test.js
Labels: C-bug 🐞, A-frontend 🐹

#7430 config/server: Wrap tests in `tests` module
  src/config/server.rs
Labels: C-internal 🔧, A-backend ⚙️

#7431 Return `anyhow::Result` from more functions instead of panicking
  crates_io_index/repo.rs
  src/admin/git_import.rs
  src/admin/migrate.rs
  src/admin/upload_index.rs
  src/bin/background-worker.rs
  src/bin/server.rs
  src/config/balance_capacity.rs
  src/config/base.rs
  src/config/database_pools.rs
  src/config/sentry.rs
  src/config/server.rs
  src/db.rs
  src/sentry/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#7432 Extract `real_ip` middleware
  src/middleware.rs
  src/middleware/log_request.rs
  src/middleware/real_ip.rs
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#7434 Fix IP-based request blocking for large page numbers
  src/config/server.rs
  src/controllers/helpers/pagination.rs
  src/tests/util.rs
Labels: C-bug 🐞, A-backend ⚙️

#7435 Fix IP-based request blocking
  src/config/server.rs
  src/middleware.rs
  src/middleware/block_traffic.rs
  src/tests/server.rs
  src/tests/snapshots/all__server__block_traffic_via_ip.snap
  src/tests/util/test_app.rs
Labels: C-bug 🐞, A-backend ⚙️

#7436 Extract `crates_io_env_vars` package
  Cargo.lock
  Cargo.toml
  crates_io_env_vars/Cargo.toml
  crates_io_env_vars/src/lib.rs
  crates_io_index/Cargo.toml
  crates_io_index/repo.rs
  crates_io_test_db/Cargo.toml
  crates_io_test_db/src/lib.rs
  src/admin/on_call.rs
  src/bin/background-worker.rs
  src/bin/monitor.rs
  src/config/balance_capacity.rs
  src/config/base.rs
  src/config/database_pools.rs
  src/config/sentry.rs
  src/config/server.rs
  src/lib.rs
  src/storage.rs
  src/test_util.rs
  src/tests/categories.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7443 middleware/block_traffic: Combine middleware functions
  src/middleware.rs
  src/middleware/block_traffic.rs
Labels: C-internal 🔧, A-backend ⚙️

#7442 test_db: Reuse existing template database instead of recreating it
  crates_io_test_db/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#7441 cloudfront: Use official AWS SDK
  Cargo.lock
  Cargo.toml
  src/cloudfront.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#7444 fastly: Remove unnecessary `Clone` impl
  src/fastly.rs
Labels: C-internal 🔧, A-backend ⚙️

#7447 worker/swirl/runner: Use public APIs for tests
  src/admin/enqueue_job.rs
  src/worker/swirl/background_job.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7452 worker/swirl/runner: Inline `get_single_job()` fn
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7453 worker/swirl/runner: Simplify `AssertUnwindSafe` usage
  src/cloudfront.rs
  src/worker/environment.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7454 worker/swirl/runner: Extract `with_sentry_transaction()` fn
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7456 worker/swirl/runner: Remove unnecessary `Context` restriction
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7455 worker/swirl/runner: Use `Box` instead of `Arc` for task fns
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7459 bin/background-worker: Simplify restart behavior
  src/bin/background-worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#7461 worker: Clone index repository in the background
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
  src/worker/environment.rs
Labels: C-internal 🔧, A-backend ⚙️

#7465 db: Return error from `DieselPool::get()` if test connection is still locked
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#7466 worker/swirl/runner: Extract `Worker` struct
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7468 worker/swirl/runner: Improve logging
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7467 worker: Move database connection pool into the `Environment` struct
  src/bin/background-worker.rs
  src/db.rs
  src/tests/util/test_app.rs
  src/worker/environment.rs
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/update_downloads.rs
  src/worker/swirl/perform_state.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7470 controllers/github/secret_scanning: Replace `unwrap()` usage with `is_some_and()`
  src/controllers/github/secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#7471 test_db: Use the force when dropping databases
  crates_io_test_db/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#7473 downloads_counter: Improve doc comment
  src/downloads_counter.rs
Labels: A-backend ⚙️, C-documentation 📜

#7472 worker/swirl: Use `anyhow::Error` instead of `Box<dyn Error>`
  src/worker/environment.rs
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/update_downloads.rs
  src/worker/swirl/background_job.rs
  src/worker/swirl/errors.rs
  src/worker/swirl/mod.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7474 Simplify `reqwest::Client` usage
  src/app.rs
  src/bin/background-worker.rs
  src/fastly.rs
  src/tests/util/test_app.rs
  src/worker/environment.rs
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#7475 fastly: Use async `reqwest` client
  src/bin/background-worker.rs
  src/fastly.rs
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#7477 Port `crates_io_smoke_test` package to async/await
  Cargo.lock
  crates_io_smoke_test/Cargo.toml
  crates_io_smoke_test/src/api.rs
  crates_io_smoke_test/src/cargo.rs
  crates_io_smoke_test/src/main.rs
Labels: C-internal 🔧, A-backend ⚙️

#7480 tests/util: Use `oneshot()` for testing
  Cargo.lock
  Cargo.toml
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#7485 tests/github_secret_scanning: Use snapshot assertions
  src/tests/github_secret_scanning.rs
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_revoked_token.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_unknown_token.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token.snap
Labels: C-internal 🔧, A-backend ⚙️

#7491 Simplify `UpstreamIndex` and make it `Send + Sync`
  crates_io_index/testing.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7487 tests/krate/following: Simplify test code
  src/tests/all.rs
  src/tests/krate/following.rs
Labels: C-internal 🔧, A-backend ⚙️

#7488 tests/util/chaosproxy: Simplify `spawn()` call
  src/tests/util/chaosproxy.rs
Labels: C-internal 🔧, A-backend ⚙️

#7484 Simplify `controllers/version/downloads` module
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7478 github: Use async `reqwest` client
  Cargo.toml
  src/app.rs
  src/bin/server.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/user/session.rs
  src/controllers/version/yank.rs
  src/github.rs
  src/models/team.rs
  src/models/user.rs
  src/tests/util/github.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7493 Reduce `OkBool` usage in tests
  src/tests/routes/me/email_notifications.rs
  src/tests/routes/users/update.rs
  src/tests/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#7494 Simplify `ChaosProxy` code
  src/tests/server_binary.rs
  src/tests/unhealthy_database.rs
  src/tests/util/chaosproxy.rs
Labels: C-internal 🔧, A-backend ⚙️

#7496 Improve styling of the policy pages
  app/components/rendered-html.hbs
  app/components/text-content.hbs
  app/components/text-content.module.css
  app/templates/data-access.hbs
  app/templates/policies.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#7495 controllers/user/session: Simplify `authorize()` endpoint fn
  src/controllers/user/session.rs
  src/tests/routes/session/authorize.rs
Labels: C-internal 🔧, A-backend ⚙️

#7498 worker/environment: Use `parking_lot::Mutex` instead of `std::sync::Mutex`
  src/worker/environment.rs
Labels: C-internal 🔧, A-backend ⚙️

#7497 tests/util/response: Replace `unwrap/expect()` calls with assertions
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#7501 tests/util: Move `Runtime` creation into `TestAppBuilder::empty()` fn
  src/tests/util.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7422 Use fresh databases for all tests
  Cargo.toml
  build.rs
  src/app.rs
  src/config/server.rs
  src/db.rs
  src/tests/read_only_mode.rs
  src/tests/routes/summary.rs
  src/tests/util/test_app.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7505 tracing: Disable colored log output on Heroku
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#7464 Integrate "crates.io Policy Update" RFC
  app/components/footer.hbs
  app/templates/data-access.hbs
  app/templates/policies.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#7486 Use `googletest` crate for assertions
  Cargo.lock
  Cargo.toml
  src/models/token/scopes.rs
Labels: C-internal 🔧, A-backend ⚙️

#7508 googletest: Extract `is_success()` and `is_redirection()` matchers for `StatusCode`
  src/tests/server_binary.rs
  src/tests/util.rs
  src/tests/util/matchers.rs
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#7509 googletest: Use `starts/ends_with()` matchers
  src/tests/server_binary.rs
  src/tests/util/insta.rs
  src/tests/util/response.rs
  src/util/token.rs
Labels: C-internal 🔧, A-backend ⚙️

#7510 googletest: Use `len()` and `empty()` matchers
  src/tests/github_secret_scanning.rs
  src/tests/krate/following.rs
  src/tests/krate/publish/audit_action.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/categories.rs
  src/tests/krate/publish/dependencies.rs
  src/tests/krate/publish/emails.rs
  src/tests/krate/publish/features.rs
  src/tests/krate/publish/keywords.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/similar_names.rs
  src/tests/krate/publish/snapshots/all__krate__publish__tarball__empty_body.snap
  src/tests/krate/publish/tarball.rs
  src/tests/krate/publish/validation.rs
  src/tests/krate/yanking.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/updates.rs
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#7507 worker: Remove `PerformState` struct
  src/tests/all.rs
  src/tests/util/test_app.rs
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/update_downloads.rs
  src/worker/swirl/background_job.rs
  src/worker/swirl/mod.rs
  src/worker/swirl/perform_state.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7519 Add CI system detection for requests
  Cargo.lock
  Cargo.toml
  src/ci.rs
  src/lib.rs
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#7526 Revert "tracing: Disable colored log output on Heroku"
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#7521 Add debug assert to crates-admin cli
  src/bin/crates-admin.rs
Labels: C-internal 🔧, A-backend ⚙️

#7506 Add language spec to code blocks
  docs/CONTRIBUTING.md
Labels: C-documentation 📜

#7532 real_ip: Replace hardcoded CIDR list with `aws-ip-ranges` crate
  Cargo.lock
  Cargo.toml
  src/real_ip.rs
Labels: C-internal 🔧, A-backend ⚙️

#7533 CI: Update `PERCY_TOKEN`
  .github/workflows/ci.yml
Labels: A-frontend 🐹, C-internal 🔧

#7534 Use `JOB_NAME` constant instead of string literals
  src/admin/enqueue_job.rs
  src/bin/monitor.rs
Labels: C-internal 🔧, A-backend ⚙️

#7500 Use the same feature name validation rule from Cargo
  Cargo.lock
  Cargo.toml
  src/controllers/krate/publish.rs
  src/models/krate.rs
  src/tests/krate/publish/features.rs
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_feature_name.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__empty_feature_name.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__feature_name_start_with_number_and_underscore.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__feature_name_with_dot.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__feature_name_with_unicode_chars.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature_name.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature_name1.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature_name2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__invalid_feature_name_start_with_hyphen.snap
Labels: C-enhancement ✨, A-backend ⚙️

#7537 models/krate: Improve feature validation
  src/controllers/krate/publish.rs
  src/models/krate.rs
  src/tests/krate/publish/snapshots/all__krate__publish__features__empty_feature_name.snap
Labels: C-internal 🔧, A-backend ⚙️

#7538 crate-header: correctly pluralise the number of crate versions
  app/components/crate-header.hbs
Labels: C-bug 🐞, A-frontend 🐹

#7548 Move lint rule configuration into `Cargo.toml` file
  Cargo.toml
  crates_io_env_vars/Cargo.toml
  crates_io_index/Cargo.toml
  crates_io_markdown/Cargo.toml
  crates_io_smoke_test/Cargo.toml
  crates_io_smoke_test/src/cargo.rs
  crates_io_smoke_test/src/main.rs
  crates_io_tarball/Cargo.toml
  crates_io_test_db/Cargo.toml
  src/bin/background-worker.rs
  src/bin/crates-admin.rs
  src/bin/monitor.rs
  src/bin/server.rs
  src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#7549 Disable non-canonical downloads if `REJECT_NON_CANONICAL_DOWNLOADS` env var is set
  src/config/server.rs
  src/controllers/version/downloads.rs
  src/tests/routes/crates/downloads.rs
  src/tests/routes/crates/versions/download.rs
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__download__rejected_non_canonical_download.snap
  src/tests/unhealthy_database.rs
  src/tests/util/test_app.rs
Labels: C-enhancement ✨, A-backend ⚙️

#7561 Revert "Update dependency pnpm to v8.10.5"
  .github/workflows/ci.yml
  frontend.Dockerfile
  package.json
Labels: A-frontend 🐹, C-internal 🔧

#7563 cloudfront: Fix AWS SDK panic
  src/cloudfront.rs
Labels: C-bug 🐞, A-backend ⚙️

#7555 Better error message for invalid dep names
  src/controllers/krate/publish.rs
  src/models/krate.rs
  src/tests/krate/publish/dependencies.rs
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__empty_dependency_name.snap
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_name_contains_unicode_chars.snap
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_name_starts_with_digit.snap
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_rename.snap
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_too_long_dependency_name.snap
Labels: C-enhancement ✨, A-backend ⚙️

#7573 util/errors: Simplify error function arguments
  src/controllers/github/secret_scanning.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/token.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/models/krate.rs
  src/models/owner.rs
  src/models/team.rs
  src/models/version.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#7571 typosquat: add suffix checks
  src/typosquat/cache.rs
  src/typosquat/checks.rs
  src/typosquat/config.rs
  src/typosquat/mod.rs
Labels: C-enhancement ✨, C-internal 🔧, A-backend ⚙️

#7576 Add `nebulanet.cc` to list of blocked external domains
  src/views.rs
Labels: C-enhancement ✨, A-backend ⚙️

#7578 Add blog post link to `max_features` error messages
  src/controllers/krate/publish.rs
  src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_enabled_features.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_enabled_features_with_custom_limit.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_features.snap
  src/tests/krate/publish/snapshots/all__krate__publish__features__too_many_features_with_custom_limit.snap
Labels: C-enhancement ✨, A-backend ⚙️

#7580 Extract `external_urls` module
  src/external_urls.rs
  src/lib.rs
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#7582 tarball: Extract variables to simplify the code
  crates_io_tarball/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#7583 worker/swirl/runner: Improve tracing information
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7585 Heroku: Update crates.io buildpack
  .buildpacks
Labels: C-internal 🔧, A-backend ⚙️

#7584 worker/swirl/runner: Remove obsolete transaction code
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7589 worker/swirl Rename `environment` to `context`
  src/worker/swirl/background_job.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7590 worker/environment: Replace six-argument constructor with builder pattern
  Cargo.lock
  Cargo.toml
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
  src/worker/environment.rs
Labels: C-internal 🔧, A-backend ⚙️

#7586 Rearchitect `swirl::Runner` implementation
  Cargo.lock
  Cargo.toml
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
  src/worker/swirl/errors.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7596 Rename and refactor `conduit_compat()` fn
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/conduit_axum.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/lib.rs
  src/tasks.rs
Labels: C-internal 🔧, A-backend ⚙️

#7597 worker/swirl/runner: Spawn worker threads on tokio runtime
  src/bin/background-worker.rs
  src/cloudfront.rs
  src/tests/util/test_app.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
  src/worker/jobs/readmes.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7599 worker/swirl/background_job: Pass owned `Context` to the `run()` fn
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/typosquat.rs
  src/worker/jobs/update_downloads.rs
  src/worker/swirl/background_job.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7600 cloudfront: Make async and use built-in retry behavior of the AWS SDK
  Cargo.lock
  Cargo.toml
  src/cloudfront.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#7602 Simplify GitHub client assignment
  src/app.rs
  src/bin/server.rs
  src/github.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7601 worker/swirl/background_job: Change `run()` fn to be async
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/typosquat.rs
  src/worker/jobs/update_downloads.rs
  src/worker/swirl/background_job.rs
  src/worker/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7614 app: Change `new()` fn to accept `Emails` argument
  src/app.rs
  src/bin/server.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7613 Adjust "crates.io" usage to lowercase
  README.md
  crates_io_markdown/lib.rs
  docs/ARCHITECTURE.md
  docs/CONTRIBUTING.md
  src/email.rs
  src/util/errors/json.rs
Labels: C-internal 🔧

#7618 worker: Convert tests to async/await integration tests
  crates_io_worker/src/runner.rs
  crates_io_worker/tests/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7619 worker: Extract 'JobRegistry` struct
  crates_io_worker/src/job_registry.rs
  crates_io_worker/src/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7629 VersionList::Row: Limit version number size
  app/components/version-list/row.module.css
Labels: C-bug 🐞, A-frontend 🐹

#7630 controllers/crate/versions: Fix null error in `sortedVersions`
  app/controllers/crate/versions.js
Labels: C-bug 🐞, A-frontend 🐹

#7621 worker: Move `block_on()` call further outside
  crates_io_worker/Cargo.toml
  crates_io_worker/src/background_job.rs
  crates_io_worker/src/job_registry.rs
  crates_io_worker/src/util.rs
  crates_io_worker/src/worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#7633 models/krate: Fix unintentional `max_features` reset after publishing
  src/models/krate.rs
  src/tests/krate/publish/features.rs
Labels: C-bug 🐞, A-backend ⚙️

#7640 Add support for running multiple background worker queues
  crates_io_worker/src/background_job.rs
  crates_io_worker/src/job_registry.rs
  crates_io_worker/src/runner.rs
  crates_io_worker/src/storage.rs
  crates_io_worker/src/worker.rs
  crates_io_worker/tests/runner.rs
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
  src/worker/jobs/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#7603 Add better error message for invalid crate names
  src/controllers/krate/publish.rs
  src/models/krate.rs
  src/models/token/scopes.rs
  src/tests/krate/publish/snapshots/all__krate__publish__dependencies__invalid_dependency_name.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-4.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names-5.snap
  src/tests/krate/publish/snapshots/all__krate__publish__validation__invalid_names.snap
Labels: C-enhancement ✨, A-backend ⚙️
