Repository rust-lang/crates.io, pull requests merged in 2023-07, with the labels that each got.

#6725 admin/delete_version: Add ability to delete multiple versions with one command
  src/admin/delete_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#6724 admin/delete_crate: Add ability to delete multiple crates with one command
  src/admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#6727 admin/delete_version: Delete crate and readme files from S3 too
  Cargo.lock
  Cargo.toml
  src/admin/delete_version.rs
  src/uploaders.rs
Labels: C-internal 🔧, A-backend ⚙️

#6732 Show newest version if all versions are yanked
  app/routes/crate/version.js
  mirage/route-handlers/crates.js
  tests/mirage/crates/get-by-id-test.js
Labels: C-bug 🐞, A-frontend 🐹

#6734 admin/delete_crate: Delete files from S3 too
  src/admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#6745 Fix `cargo doc` warnings
  src/controllers/util.rs
  src/util/rfc3339.rs
  src/worker/fastly.rs
Labels: A-backend ⚙️, C-documentation 📜

#6746 CI: Run `cargo doc` to check for documentation warnings/errors
  .github/workflows/ci.yml
Labels: C-internal 🔧, A-backend ⚙️

#6765 admin/delete_crate: Simplify `object_store::Path` code
  src/admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#6764 Extract and improve `storage::from_environment()` fn
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/lib.rs
  src/storage.rs
Labels: C-internal 🔧, A-backend ⚙️

#6766 admin/delete_version: Simplify `object_store::Path` code
  src/admin/delete_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#6767 tests/publish: Merge redundant tests
  src/tests/http-data/krate_publish_new_krate_twice.json
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6775 bin/background-worker: Replace unnecessary clones with `Arc` usage
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#6778 Extract `Storage` abstraction and add tests
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/storage.rs
Labels: C-internal 🔧, A-backend ⚙️

#6780 storage: Extract helper functions
  src/storage.rs
Labels: C-internal 🔧, A-backend ⚙️

#6783 Use `Storage` system to upload README files
  src/app.rs
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/storage.rs
  src/tests/http-data/krate_publish_new_krate_with_readme.json
  src/tests/http-data/krate_publish_new_krate_with_readme_and_plus_version.json
  src/tests/krate/publish.rs
  src/tests/util/test_app.rs
  src/worker/readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#6788 admin/render_readmes: Use `Storage` system for uploading readme files to S3
  src/admin/render_readmes.rs
  src/uploaders.rs
Labels: C-internal 🔧, A-backend ⚙️

#6789 worker/dump_db: Add debug logging
  src/worker/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#6794 Skip upload for empty README files
  src/admin/render_readmes.rs
  src/controllers/krate/publish.rs
  src/storage.rs
  src/tests/http-data/krate_publish_new_krate_with_empty_readme.json
  src/tests/krate/publish.rs
  src/worker/readmes.rs
Labels: C-bug 🐞, A-backend ⚙️

#6795 Handle crates without versions gracefully
  src/worker/git.rs
Labels: C-bug 🐞, A-backend ⚙️

#6787 Use `Storage` system to sync to the sparse index
  src/admin/upload_index.rs
  src/storage.rs
  src/tests/http-data/krate_publish_features_version_2.json
  src/tests/http-data/krate_publish_good_categories.json
  src/tests/http-data/krate_publish_good_keywords.json
  src/tests/http-data/krate_publish_ignored_categories.json
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency.json
  src/tests/http-data/krate_publish_new_krate.json
  src/tests/http-data/krate_publish_new_krate_git_upload.json
  src/tests/http-data/krate_publish_new_krate_git_upload_appends.json
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts.json
  src/tests/http-data/krate_publish_new_krate_records_verified_email.json
  src/tests/http-data/krate_publish_new_krate_sorts_deps.json
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted.json
  src/tests/http-data/krate_publish_new_krate_twice.json
  src/tests/http-data/krate_publish_new_krate_weird_version.json
  src/tests/http-data/krate_publish_new_krate_with_dependency.json
  src/tests/http-data/krate_publish_new_krate_with_readme.json
  src/tests/http-data/krate_publish_new_krate_with_readme_and_plus_version.json
  src/tests/http-data/krate_publish_new_krate_with_token.json
  src/tests/http-data/krate_publish_new_with_renamed_dependency.json
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency.json
  src/tests/http-data/krate_publish_publish_after_removing_documentation.json
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited.json
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates.json
  src/tests/http-data/krate_publish_publish_records_an_audit_action.json
  src/tests/http-data/krate_publish_tarball_between_default_axum_limit_and_max_upload_size.json
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate.json
  src/tests/http-data/krate_publish_version_with_build_metadata_1.json
  src/tests/http-data/krate_publish_version_with_build_metadata_2.json
  src/tests/http-data/krate_publish_version_with_build_metadata_3.json
  src/tests/http-data/krate_yanking_publish_after_yank_max_version.json
  src/tests/http-data/krate_yanking_yank_max_version.json
  src/tests/http-data/krate_yanking_yank_works_as_intended.json
  src/tests/http-data/owners_new_crate_owner.json
  src/tests/http-data/routes_crates_new_daily_limit.json
  src/tests/http-data/routes_crates_read_version_size.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_cookie_user.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_expired.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_not_expired.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_endpoint_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_wildcard_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_endpoint_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_wildcard_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_unauthenticated.json
  src/tests/http-data/routes_crates_versions_yank_unyank_unyank_records_an_audit_action.json
  src/tests/http-data/routes_crates_versions_yank_unyank_yank_records_an_audit_action.json
  src/tests/http-data/team_publish_owned.json
  src/tests/http-data/worker_git_index_smoke_test.json
  src/tests/krate/publish.rs
  src/uploaders.rs
  src/worker/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#6796 tests/publish: Fix broken assertion
  src/tests/http-data/krate_publish_new_krate_with_empty_readme.json
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6790 worker/dump_db: Use `Storage` system to upload database dump tarball
  src/storage.rs
  src/worker/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#6802 Uploader: Remove obsolete code
  src/uploaders.rs
Labels: C-internal 🔧, A-backend ⚙️

#6666 Stop uploading to S3 with unescaped paths
  src/storage.rs
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6803 Update `semver` JS dependency
  pnpm-lock.yaml
Labels: A-frontend 🐹

#6804 RenderedHtml: Ignore syntax highlighting for mermaid blocks
  app/components/rendered-html.hbs
Labels: A-frontend 🐹, C-internal 🔧

#6810 Fastly: Mark API token as secret/sensitive information
  src/worker/fastly.rs
Labels: C-internal 🔧, A-backend ⚙️

#6828 tracing: Use `INFO` as default level
  src/bin/crates-admin.rs
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#6829 Show which crate violating wildcard dependency
  src/controllers/krate/publish.rs
  src/tests/krate/publish.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6835 Purge all domains on Fastly
  src/worker/fastly.rs
Labels: C-bug 🐞, A-backend ⚙️

#6834 Migrate remaining `Uploaders` code into `Storage` system
  src/admin/render_readmes.rs
  src/background_jobs.rs
  src/bin/background-worker.rs
  src/config/base.rs
  src/config/server.rs
  src/controllers/krate/metadata.rs
  src/controllers/version/downloads.rs
  src/lib.rs
  src/storage.rs
  src/tests/util/test_app.rs
  src/uploaders.rs
Labels: C-internal 🔧, A-backend ⚙️

#6838 tarball: Implement `process_tarball()` for any `Read` impl
  crates_io_tarball/examples/read_file.rs
  crates_io_tarball/src/lib.rs
  src/admin/backfill/rust_version.rs
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6839 tarball: Add `check_all_crates` example
  Cargo.lock
  crates_io_tarball/Cargo.toml
  crates_io_tarball/examples/check_all_crates.rs
Labels: C-internal 🔧, A-backend ⚙️

#6841 admin/backfill: Remove `rust-version` backfill code
  src/admin/backfill/mod.rs
  src/admin/backfill/rust_version.rs
  src/admin/mod.rs
  src/bin/crates-admin.rs
Labels: C-internal 🔧, A-backend ⚙️

#6842 Remove obsolete `crates_io_s3` package
  Cargo.lock
  Cargo.toml
  crates_io_s3/Cargo.toml
  crates_io_s3/lib.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#6844 tests/krate/publish: Use text file for upload size check
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6845 Use `TarballBuilder` in more tests
  crates_io_tarball/src/builder.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6846 tarball/Package: Change `readme` field to `Option<PathBuf>`
  crates_io_markdown/lib.rs
  crates_io_tarball/src/lib.rs
  crates_io_tarball/src/manifest.rs
  src/admin/render_readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#6848 Fix `readme` field parsing of `Cargo.toml` files
  Cargo.lock
  crates_io_tarball/Cargo.toml
  crates_io_tarball/src/lib.rs
  crates_io_tarball/src/manifest.rs
  src/admin/render_readmes.rs
  src/tests/krate/publish.rs
Labels: C-bug 🐞, A-backend ⚙️

#6851 Fix download URL generation
  src/storage.rs
  src/tests/util/test_app.rs
Labels: C-bug 🐞, A-backend ⚙️

#6868 settings/tokens/new: Disable autocomplete for "Name" field
  app/templates/settings/tokens/new.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#6873 tarball: Allow lowercase `cargo.toml` files for now
  crates_io_tarball/src/lib.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6880 Replace `#[macro_use]` with explicit imports
  src/lib.rs
  src/metrics/instance.rs
  src/metrics/macros.rs
  src/metrics/mod.rs
  src/metrics/service.rs
  src/models/action.rs
  src/models/dependency.rs
  src/rate_limiter.rs
  src/sql.rs
Labels: C-internal 🔧, A-backend ⚙️

#6859 Job::enqueue_sync_to_index: Only insert new jobs if no similar unlocked jobs exist
  src/background_jobs.rs
Labels: C-internal 🔧, A-backend ⚙️

#6882 metrics/service: Fix `background_jobs` label order
  src/metrics/service.rs
Labels: C-bug 🐞, A-backend ⚙️

#6883 CI: Use `CARGO_TERM_COLOR: always` to enable colorful cargo output
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: C-internal 🔧, A-backend ⚙️

#6884 Implement basic smoke test setup
  .github/workflows/smoke-test.yml
  Cargo.lock
  Cargo.toml
  crates_io_smoke_test/Cargo.toml
  crates_io_smoke_test/src/main.rs
Labels: A-infrastructure 📡, C-internal 🔧

#6889 Extend smoke testing setup
  Cargo.lock
  crates_io_smoke_test/Cargo.toml
  crates_io_smoke_test/src/api.rs
  crates_io_smoke_test/src/cargo.rs
  crates_io_smoke_test/src/exit_status_ext.rs
  crates_io_smoke_test/src/main.rs
Labels: A-infrastructure 📡, C-internal 🔧

#6890 smoke_test: Add index checks
  Cargo.lock
  crates_io_smoke_test/Cargo.toml
  crates_io_smoke_test/src/api.rs
  crates_io_smoke_test/src/main.rs
Labels: A-infrastructure 📡, C-internal 🔧

#6892 tests/builders/publish: Inline `files_with_io()` and simplify `files()` fn
  src/tests/builders/publish.rs
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6893 PublishBuilder: Provide `version` upfront
  src/tests/builders/publish.rs
  src/tests/krate/publish.rs
  src/tests/krate/yanking.rs
  src/tests/owners.rs
  src/tests/routes/crates/new.rs
  src/tests/routes/crates/read.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/team.rs
  src/tests/worker/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#6900 Migrate from docs.rs' builds API to status API
  app/models/version.js
  app/routes/crate/version.js
  mirage/route-handlers/docs-rs.js
  tests/routes/crate/version/docs-link-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#6897 tarball: Fail if `Cargo.toml` manifest is missing or invalid
  crates_io_tarball/src/lib.rs
  src/controllers/krate/publish.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish.rs
  src/tests/routes/crates/read.rs
Labels: C-bug 🐞, A-backend ⚙️

#6909 tests/builders/publish: Simplify `files()` fn
  src/tests/builders/publish.rs
Labels: C-internal 🔧, A-backend ⚙️
