Repository rust-lang/crates.io, pull requests merged in 2023-12, with the labels that each got.

#7648 worker/jobs/git: Push squash snapshot branches to `GIT_ARCHIVE_REPO_URL` too
  crates_io_index/repo.rs
  src/worker/jobs/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#7656 tests/util/response: Replace `reqwest::blocking::Response` with `hyper::Response`
  src/tests/util.rs
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#7651 worker/worker: Convert `run()` fns to async
  crates_io_worker/src/job_registry.rs
  crates_io_worker/src/runner.rs
  crates_io_worker/src/util.rs
  crates_io_worker/src/worker.rs
  crates_io_worker/tests/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7660 util/bytes_request: Simplify test code
  src/util/bytes_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#7664 Fix `reqwest` imports
  src/fastly.rs
  src/storage.rs
Labels: C-internal 🔧, A-backend ⚙️

#7665 middleware: Move compression and timeout layers out of the `ServiceBuilder`
  src/middleware.rs
Labels: C-internal 🔧, A-backend ⚙️

#7666 tests/server_binary: Convert `u64` constant to `Duration`
  src/tests/server_binary.rs
Labels: C-internal 🔧, A-backend ⚙️

#7676 util/bytes_request: Simplify `LengthLimitError` downcast
  src/util/bytes_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#7677 tests/util/response: Avoid unnecessary `.clone()` call
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#7678 Fix `User-Agent` header requirement error responses
  src/middleware/log_request.rs
  src/tests/server.rs
Labels: C-bug 🐞, A-backend ⚙️

#7683 tests/util: Accept all `Into<Body>` implementations in `run()` fn
  src/tests/server.rs
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#7699 clippy: Warn about `todo!()` usage
  Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#7709 middleware: Split `ServiceBuilder` stacks
  src/middleware.rs
Labels: C-internal 🔧, A-backend ⚙️

#7708 Ensure that API endpoints return JSON errors
  src/middleware.rs
  src/middleware/errors.rs
  src/tests/routes/crates/versions/download.rs
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__download__rejected_non_canonical_download.snap
  src/tests/routes/session/authorize.rs
  src/tests/server.rs
  src/tests/snapshots/all__server__block_traffic_via_arbitrary_header_and_value.snap
  src/tests/snapshots/all__server__block_traffic_via_ip.snap
Labels: C-bug 🐞, A-backend ⚙️

#7712 bin/server: Improve router wrapping comment with docs URL
  src/bin/server.rs
Labels: A-backend ⚙️, C-documentation 📜

#7717 Clippy: Enable `dbg!()` warnings
  Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#7715 Ensure `200 OK` status codes for cargo endpoints
  src/middleware.rs
  src/middleware/cargo_compat.rs
  src/tests/krate/publish/auth.rs
  src/tests/owners.rs
  src/tests/pagination.rs
  src/tests/read_only_mode.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/server.rs
  src/tests/snapshots/all__read_only_mode__cannot_hit_endpoint_which_writes_db_in_read_only_mode.snap
  src/tests/snapshots/all__server__user_agent_is_required-2.snap
  src/tests/snapshots/all__server__user_agent_is_required.snap
  src/tests/util/response.rs
Labels: C-bug 🐞, A-backend ⚙️

#7719 router: Move tests to `util/errors` module
  src/router.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#7720 util/errors/json: Move structs closer to their impl blocks
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#7721 worker: Enable missing `tokio` feature
  crates_io_worker/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#7723 worker/tests: Use `TestDatabase::connect()` for DB interactions
  crates_io_worker/tests/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7724 auth: Simplify `ensure_not_locked()` fn
  src/auth.rs
Labels: C-internal 🔧, A-backend ⚙️

#7726 github: Use `Bearer` authorization scheme instead of `token`
  src/github.rs
Labels: C-internal 🔧, A-backend ⚙️

#7725 github: Extract `GitHubError` enum
  src/github.rs
  src/models/team.rs
  src/tests/util/github.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#7729 Extract `crates_io_github` package
  Cargo.lock
  Cargo.toml
  crates_io_github/Cargo.toml
  crates_io_github/src/lib.rs
  src/app.rs
  src/bin/server.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/user/session.rs
  src/lib.rs
  src/models/team.rs
  src/tests/util/github.rs
  src/util/errors.rs
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#7734 models/owner: Simplify `Owner` fns
  src/models/owner.rs
Labels: C-internal 🔧, A-backend ⚙️

#7733 Fix error handling for optional SQL results
  src/controllers/user/me.rs
  src/models/krate.rs
  src/models/owner.rs
Labels: C-bug 🐞, A-backend ⚙️

#7735 Extract `find_by_login()` fns
  src/models/owner.rs
  src/models/team.rs
  src/models/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#7737 email: Extract `EmailError` enum
  src/controllers/user/me.rs
  src/email.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#7736 controllers/github/secret_scanning: Simplify `PUBLIC_KEY_CACHE_LIFETIME` usage
  src/controllers/github/secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#7739 Simplify `metrics` controller
  src/controllers/metrics.rs
Labels: C-internal 🔧, A-backend ⚙️

#7738 email: Add `domain` field
  src/config.rs
  src/config/server.rs
  src/email.rs
Labels: C-internal 🔧, A-backend ⚙️

#7740 controllers/github/secret_scanning: Only obtain database connection once per request
  src/controllers/github/secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#7743 email: Change default "From" address to "noreply@crates.io"
  src/email.rs
Labels: C-internal 🔧, A-backend ⚙️

#7744 email: Add `from` field to `Emails` struct
  src/email.rs
Labels: C-internal 🔧, A-backend ⚙️

#7745 email: Use `Transport` implementations in all backend variants
  src/email.rs
  src/tests/owners.rs
  src/util/errors.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#7747 models: Use `QueryResult` instead of `AppResult` where possible
  src/models/crate_owner_invitation.rs
  src/models/krate.rs
  src/models/token.rs
Labels: C-internal 🔧, A-backend ⚙️

#7750 bin/server: Use `anyhow` instead of `AppResult`
  src/bin/server.rs
Labels: C-internal 🔧, A-backend ⚙️

#7751 Remove `reject_non_canonical_downloads` feature flag
  src/config/server.rs
  src/controllers/version/downloads.rs
  src/tests/routes/crates/downloads.rs
  src/tests/routes/crates/versions/download.rs
  src/tests/server_binary.rs
  src/tests/unhealthy_database.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7752 controllers/version/downloads: Return regular 404 error for non-canonical downloads
  src/controllers/version/downloads.rs
  src/tests/routes/crates/versions/download.rs
Labels: C-internal 🔧, A-backend ⚙️

#7755 Extract `Email` trait
  src/controllers/github/secret_scanning.rs
  src/controllers/user/me.rs
  src/email.rs
  src/models/krate.rs
  src/models/user.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#7763 models/email: Remove unused `AsChangeset` impl from `Email` struct
  src/models/email.rs
Labels: C-internal 🔧, A-backend ⚙️

#7764 models/crate_owner_invitation: Remove unused `Eq` impls from `CrateOwnerInvitation` struct
  src/models/crate_owner_invitation.rs
Labels: C-internal 🔧, A-backend ⚙️

#7766 Use `SecretString` for `token` fields
  src/controllers/user/me.rs
  src/models/crate_owner_invitation.rs
  src/models/email.rs
  src/models/krate.rs
  src/models/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#7765 email: Merge `TransportError` variants
  src/email.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#7772 controllers/version/downloads: Use regular 404 error instead of custom `NonCanonicalDownload` struct
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7773 controllers/version/downloads: Remove canonical crate name from query
  src/controllers/version/downloads.rs
  src/metrics/instance.rs
Labels: C-internal 🔧, A-backend ⚙️

#7774 controllers/version/downloads: Move `app.version_id_cacher.insert()` call outside `spawn_blocking()`
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7777 util/errors: Remove unused `From<...> for BoxedAppError` impls
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#7776 Implement cargo compatibility status code enforcement feature flag
  src/config/server.rs
  src/middleware.rs
  src/middleware/cargo_compat.rs
  src/tests/krate/publish/auth.rs
  src/tests/owners.rs
  src/tests/pagination.rs
  src/tests/read_only_mode.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/server.rs
  src/tests/util/response.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#7802 Update Open Graph Image URL to Absolute Path for Compatibility
  app/index.html
Labels: C-bug 🐞, A-frontend 🐹

#7801 Enhance Accessibility and User Experience: Add inputmode attribute to search input and implement smooth scroll-behavior in CSS 📜
  app/components/search-form.hbs
  app/styles/application.module.css
Labels: C-enhancement ✨, A-frontend 🐹

#7800 Enhance Image Rendering: Introduce Async Decoding Attribute
  app/components/user-avatar.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#7817 controllers/helpers/pagination: Add data access page link to high page offset error message
  src/controllers/helpers/pagination.rs
  src/tests/pagination.rs
Labels: C-enhancement ✨, A-backend ⚙️

#7812 util/errors: Extract `CustomApiError` struct
  src/controllers/metrics.rs
  src/middleware/block_traffic.rs
  src/models/crate_owner_invitation.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#7819 Revert "Update Rust crate thiserror to v1.0.52 (#7808)"
  Cargo.lock
  Cargo.toml
  crates_io_github/Cargo.toml
  crates_io_smoke_test/Cargo.toml
  crates_io_tarball/Cargo.toml
  crates_io_worker/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#7821 Revert "Update Rust crate anyhow to v1.0.77"
  Cargo.lock
  Cargo.toml
  crates_io_env_vars/Cargo.toml
  crates_io_github/Cargo.toml
  crates_io_index/Cargo.toml
  crates_io_smoke_test/Cargo.toml
  crates_io_tarball/Cargo.toml
  crates_io_worker/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#7823 env_vars: Add basic test suite
  Cargo.lock
  crates_io_env_vars/Cargo.toml
  crates_io_env_vars/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#7825 env_vars: Extract `list()` and `list_parsed()` fns
  crates_io_env_vars/src/lib.rs
  src/config/server.rs
Labels: C-internal 🔧, A-backend ⚙️

#7827 typosquat/test_util: Remove `conn` field from `Faker` struct
  src/typosquat/database.rs
  src/typosquat/test_util.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#7818 Remove `AppError::chain()` method
  src/auth.rs
  src/controllers/krate/publish.rs
  src/controllers/user/session.rs
  src/controllers/util.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#7834 controllers: Remove unused import
  src/controllers.rs
Labels: C-internal 🔧, A-backend ⚙️

#7611 Use `async fn` and return-position `impl Trait` from std library for background jobs
  crates_io_worker/src/background_job.rs
  crates_io_worker/src/job_registry.rs
  crates_io_worker/tests/runner.rs
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/git.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/typosquat.rs
  src/worker/jobs/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#7841 bin/server: Use `axum::serve(...).with_graceful_shutdown(...)`
  Cargo.lock
  Cargo.toml
  src/bin/server.rs
Labels: C-internal 🔧, A-backend ⚙️

#7843 models/user: Simplify `NewUser::gh_access_token` type
  src/models/user.rs
  src/tests/all.rs
  src/tests/owners.rs
Labels: C-internal 🔧, A-backend ⚙️
