Repository rust-lang/crates.io, pull requests merged in 2023-05, with the labels that each got.

#6375 Remove index sync feature flag
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/yank_version.rs
  src/background_jobs.rs
  src/config.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/tests/util/test_app.rs
  src/worker/git.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#6422 Fix typo in token.rs
  src/util/token.rs
Labels: A-backend ⚙️, C-documentation 📜

#6415 Show README and metadata for yanked crates/versions
  app/components/crate-header.hbs
  app/components/crate-header.module.css
  app/styles/application.module.css
  app/templates/crate/version.hbs
  tests/routes/crate/version/model-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#6423 README: Add styling for `<kbd>` tags
  app/components/rendered-html.module.css
  cargo-registry-markdown/lib.rs
Labels: C-enhancement ✨, A-frontend 🐹

#6425 docs: Replace Discord channel links with Zulip
  README.md
  docs/CONTRIBUTING.md
Labels: C-documentation 📜

#6427 settings/tokens/new: Fix broken `<input>` id
  app/templates/settings/tokens/new.hbs
Labels: C-bug 🐞, A-frontend 🐹

#6428 settings/tokens/new: Add "Scopes" section
  app/controllers/settings/tokens/new.js
  app/models/api-token.js
  app/styles/settings/tokens/new.module.css
  app/templates/settings/tokens/new.hbs
  tests/routes/settings/tokens/new-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#6431 settings/tokens/new: Add help button to "Scopes" section
  app/styles/settings/tokens/new.module.css
  app/templates/settings/tokens/new.hbs
  public/assets/circle-question.svg
Labels: C-enhancement ✨, A-frontend 🐹

#6432 settings/tokens/new: Add "Crates" section
  app/controllers/settings/tokens/new.js
  app/styles/settings/tokens/new.module.css
  app/templates/settings/tokens/new.hbs
  tests/routes/settings/tokens/new-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#6426 Footer: Remove Discord link
  app/components/footer.hbs
  public/assets/discord.svg
Labels: C-enhancement ✨, A-frontend 🐹

#6447 utils/license: Fix `replace()` calls
  app/utils/license.js
  tests/utils/license-test.js
Labels: C-bug 🐞, A-frontend 🐹

#6437 Migrate dev server reverse proxying to custom middleware
  config/environment.js
  docs/CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  server/index.js
Labels: C-internal 🔧

#6449 settings/tokens: Make sure to always reload API tokens from the server
  app/routes/settings/tokens/index.js
  tests/routes/settings/tokens/index-test.js
Labels: C-bug 🐞, A-frontend 🐹

#6450 settings/tokens: Display endpoint/crate scopes if they exist
  app/components/settings/api-tokens.hbs
  app/components/settings/api-tokens.js
  app/components/settings/api-tokens.module.css
  app/controllers/settings/tokens/new.js
  app/styles/shared/typography.module.css
  app/templates/settings/tokens/new.hbs
  app/utils/token-scopes.js
  tests/routes/settings/tokens/new-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#6452 Remove confusing comment fragments about mirror mode
  src/config/base.rs
Labels: C-documentation 📜

#6455 Remove obsolete `RustConfig` file
  .github/renovate.json5
  .github/workflows/ci.yml
  RustConfig
Labels: C-internal 🔧, A-backend ⚙️

#6458 Revert "Update Rust crate tracing to v0.1.38 (#6387)"
  Cargo.lock
  Cargo.toml
  cargo-registry-index/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#6463 chrono: Disable default features
  Cargo.lock
  Cargo.toml
  cargo-registry-s3/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#6464 Integrate `cargo-deny`
  .github/workflows/ci.yml
  deny.toml
Labels: C-internal 🔧, A-backend ⚙️

#6442 Front Page: adding "see all" to every list
  app/templates/index.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#6466 cargo-deny: Run for all push events to the main branch
  .github/workflows/ci.yml
Labels: C-internal 🔧, A-backend ⚙️

#6467 Update `heroku-buildpack-rust` to custom fork
  .buildpacks
Labels: C-internal 🔧, A-backend ⚙️

#6469 Front Page: remove `see all` buttons
  app/styles/index.module.css
  app/templates/index.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#6468 Fix "Sort by" label positioning
  app/styles/categories.module.css
  app/styles/crates.module.css
  app/styles/keywords.module.css
  app/styles/search.module.css
  app/styles/shared/sort-by.module.css
  app/templates/categories.hbs
  app/templates/crates.hbs
  app/templates/keywords.hbs
  app/templates/search.hbs
Labels: C-bug 🐞, A-frontend 🐹

#6471 Split `index` crate into submodules
  cargo-registry-index/credentials.rs
  cargo-registry-index/data.rs
  cargo-registry-index/lib.rs
  cargo-registry-index/repo.rs
  cargo-registry-index/ser.rs
Labels: C-internal 🔧, A-backend ⚙️

#6472 index: Fix file deletion
  cargo-registry-index/repo.rs
  cargo-registry-index/testing.rs
  src/tests/all.rs
  src/tests/http-data/worker_git_index_smoke_test.json
  src/tests/worker/git.rs
  src/tests/worker/mod.rs
Labels: C-bug 🐞, A-backend ⚙️

#6479 renovate: Delay `pnpm` updates by 24 hours
  .github/renovate.json5
Labels: A-frontend 🐹, C-internal 🔧

#6470 Replace `abbr` with `EmberTooltips`
  app/components/crate-row.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#6497 sentry: Replace custom axum middleware with `tower-axum-matched-path` feature
  Cargo.lock
  Cargo.toml
  src/middleware.rs
  src/middleware/sentry.rs
Labels: C-internal 🔧, A-backend ⚙️

#6501 Update some version requirements in CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: C-documentation 📜

#6507 Update `ember-cli-mirage` to v3 alpha
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#6509 Search: make status svg's always the same size
  app/components/crate-row.module.css
Labels: C-bug 🐞, A-frontend 🐹

#6512 Remove unnecessary `postcss-custom-media` plugin
  app/components/settings-page.module.css
  app/components/settings/api-tokens.module.css
  app/styles/breakpoints.css
  ember-cli-build.js
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#6513 Remove obsolete `postcss` version resolution
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#6526 Dashboard: remove black background from following.svg
  public/assets/following.svg
Labels: C-bug 🐞, A-frontend 🐹

#6524 db/background_jobs: Add `priority` column
  migrations/2023-05-25-104708_add-background-job-priority/down.sql
  migrations/2023-05-25-104708_add-background-job-priority/up.sql
  src/background_jobs.rs
  src/bin/monitor.rs
  src/controllers/krate/publish.rs
  src/schema.rs
  src/swirl/storage.rs
  src/tests/http-data/krate_publish_new_krate_with_readme.json
  src/worker/dump_db/dump-db.toml
Labels: C-internal 🔧, A-backend ⚙️

#6525 Use `secrecy` crate for database URLs and git credentials
  Cargo.lock
  cargo-registry-index/Cargo.toml
  cargo-registry-index/credentials.rs
  cargo-registry-index/repo.rs
  src/bin/background-worker.rs
  src/config/database_pools.rs
  src/db.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#6518 Prevent similar versions that only differ in build metadata from being published
  src/models/version.rs
  src/sql.rs
  src/tests/http-data/krate_publish_version_with_build_metadata_1.json
  src/tests/http-data/krate_publish_version_with_build_metadata_2.json
  src/tests/http-data/krate_publish_version_with_build_metadata_3.json
  src/tests/krate/publish.rs
  src/tests/krate/snapshots/all__krate__publish__version_with_build_metadata@build_metadata_1.snap
  src/tests/krate/snapshots/all__krate__publish__version_with_build_metadata@build_metadata_2.snap
  src/tests/krate/snapshots/all__krate__publish__version_with_build_metadata@build_metadata_3.snap
Labels: C-bug 🐞, A-backend ⚙️

#6547 Extract `cargo-registry-tarball` crate
  Cargo.lock
  Cargo.toml
  cargo-registry-tarball/Cargo.toml
  cargo-registry-tarball/src/builder.rs
  cargo-registry-tarball/src/lib.rs
  cargo-registry-tarball/src/limit_reader.rs
  cargo-registry-tarball/src/manifest.rs
  cargo-registry-tarball/src/vcs_info.rs
  src/admin/render_readmes.rs
  src/controllers/krate/publish.rs
  src/util.rs
  src/util/io_util.rs
Labels: C-internal 🔧, A-backend ⚙️
