Repository rust-lang/crates.io, pull requests merged in 2023-03, with the labels that each got.

#6143 Updates nginx config to always send Access-Control-Allow-Origin header
  config/nginx.conf.erb
Labels: C-enhancement ✨, A-backend ⚙️

#6163 add panic-handling axum middleware
  Cargo.toml
  src/middleware.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6179 updated x-xss-protection header to follow owasp best practice
  config/nginx.conf.erb
Labels: A-backend ⚙️

#6195 Fix typo in downloads.rs
  src/controllers/version/downloads.rs
Labels: A-backend ⚙️, C-documentation 📜

#6198 Update CONTRIBUTING.md to install diesel_cli 2.x
  docs/CONTRIBUTING.md
Labels: C-documentation 📜

#6201 Update the import script to handle a couple of problematic scenarios
  script/import-database-dump.sh
Labels: C-internal 🔧, A-backend ⚙️

#6204 Fix download charts after a DST transition
  app/components/download-graph.js
Labels: C-bug 🐞, A-frontend 🐹
