Repository rust-lang/crates.io, pull requests merged in 2023-04, with the labels that each got.

#6273 ssh/known_hosts: Update RSA fingerprint for github.com
  src/ssh/known_hosts
Labels: C-internal 🔧, A-backend ⚙️

#6274 Heroku: Update `pnpm` buildpack
  .buildpacks
  package.json
Labels: A-frontend 🐹, C-internal 🔧

#6282 Add missing `@ember/string` dependency
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#6289 worker/git: Fix duplicate log message
  src/worker/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#6290 hyper: Enable `backports` and `deprecated` features
  Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#6302 Heroku: Update `pnpm` buildpack
  .buildpacks
Labels: A-frontend 🐹, C-internal 🔧

#6303 Fix `undefined` in user avatar title
  app/components/user-avatar.js
Labels: C-bug 🐞, A-frontend 🐹

#6304 Improve debugability of the `dump_db` background worker task
  src/tests/dump_db.rs
  src/worker/dump_db.rs
  src/worker/dump_db/gen_scripts.rs
Labels: C-internal 🔧, A-backend ⚙️

#6305 tracing: Remove obsolete `conduit_axum::fallback` filter
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#6311 embroider: Enable `staticAddonTrees` option
  ember-cli-build.js
Labels: A-frontend 🐹, C-internal 🔧

#6310 GET /me/tokens: Add `crate_scopes` and `endpoint_scopes` fields
  src/models/token.rs
  src/models/token/scopes.rs
  src/tests/routes/me/tokens/list.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__list__list_tokens.snap
Labels: C-enhancement ✨, A-backend ⚙️

#6314 renovate: Throttle `tj-actions/changed-files` action updates
  .github/renovate.json5
Labels: C-internal 🔧

#6317 Sort crate dependencies before adding to index
  cargo-registry-index/lib.rs
  src/controllers/krate/publish.rs
  src/tests/http-data/krate_publish_new_krate_sorts_deps.json
  src/tests/krate/publish.rs
Labels: C-bug 🐞, A-backend ⚙️

#6318 Make it easier to debug test failures due to incorrect http-data
  src/tests/record.rs
Labels: C-internal 🔧, A-backend ⚙️

#6316 PUT /me/token: Remove unused `revoked` field from response payload
  src/models/token.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes.snap
  src/views.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6325 mirage: Add crate and endpoint scope fields
  mirage/factories/api-token.js
  mirage/route-handlers/me.js
  tests/mirage/me/tokens/create-test.js
  tests/mirage/me/tokens/list-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#6324 EncodableApiTokenWithToken: Use `serde(flatten)` to reuse `ApiToken` serialization
  src/models/token.rs
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#6330 Modify the git-import tool to only import the `links` field
  src/admin/git_import.rs
Labels: C-internal 🔧, A-backend ⚙️

#6343 krate/search: Avoid unnecessary `.clone()` call in pagination code
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️

#6354 tests: Introduce `slow-tests` feature
  Cargo.toml
  src/tests/server_binary.rs
Labels: C-internal 🔧, A-backend ⚙️

#5066 Generate index metadata files from the database
  Cargo.lock
  cargo-registry-index/Cargo.toml
  cargo-registry-index/lib.rs
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/yank_version.rs
  src/background_jobs.rs
  src/config.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/models/dependency.rs
  src/models/krate.rs
  src/tests/all.rs
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted.json
  src/tests/http-data/krate_publish_new_krate_twice.json
  src/tests/http-data/krate_publish_publish_after_removing_documentation.json
  src/tests/http-data/team_publish_owned.json
  src/tests/models/krate.rs
  src/tests/models/mod.rs
  src/tests/models/snapshots/all__models__krate__index_metadata-2.snap
  src/tests/models/snapshots/all__models__krate__index_metadata.snap
  src/tests/util/test_app.rs
  src/worker/git.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#6360 Move `Job` constructors into `Job` impl
  src/admin/enqueue_job.rs
  src/admin/yank_version.rs
  src/background_jobs.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/worker/daily_db_maintenance.rs
  src/worker/dump_db.rs
  src/worker/git.rs
  src/worker/mod.rs
  src/worker/readmes.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#6361 background_jobs: Rename variants to match their `job_type` column values
  src/background_jobs.rs
Labels: C-internal 🔧, A-backend ⚙️

#6363 settings/tokens: Delete plaintext tokens from memory after leaving API tokens settings page
  app/routes/settings/tokens.js
  tests/acceptance/api-token-test.js
Labels: C-bug 🐞, A-frontend 🐹

#6365 Fix broken URL in error message
  src/controllers/krate/publish.rs
  src/tests/krate/publish.rs
Labels: C-bug 🐞, A-backend ⚙️

#6374 worker::update_downloads: Replace `println!()` call with `info!()`
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#6376 sentry: Fix `is_download_endpoint` logic
  src/sentry/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#6377 admin/enqueue-job: Redact `database_url` in `Debug` output
  Cargo.lock
  Cargo.toml
  src/admin/enqueue_job.rs
Labels: C-internal 🔧, A-backend ⚙️

#6378 tracing: Instrument background job runner
  src/background_jobs.rs
  src/bin/crates-admin.rs
  src/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#6379 sentry: Adjust `trace_sampler` implementation
  src/sentry/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#6362 background_jobs: Use macros to generate `as_type_str()`, `to_value()` and `from_value()`
  Cargo.lock
  Cargo.toml
  src/background_jobs.rs
Labels: C-internal 🔧, A-backend ⚙️

#6380 Add more `tracing` instrumentation
  cargo-registry-index/lib.rs
  src/app.rs
  src/auth.rs
  src/background_jobs.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/db.rs
  src/models/krate.rs
  src/uploaders.rs
  src/worker/readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#6381 worker::git: Use imperative style commit messages
  src/worker/git.rs
Labels: C-internal 🔧, A-backend ⚙️

#6382 swirl: Improve Sentry scoping
  src/bin/background-worker.rs
  src/sentry/mod.rs
  src/swirl/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#6383 version/downloads: Add `tracing` instrumentation
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#6384 sentry: Adjust `trace_sampler` implementation
  src/bin/server.rs
  src/sentry/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#6267 Add `rust-version` field to the database and index
  cargo-registry-index/lib.rs
  migrations/2023-03-23-211241_add_rust_version_to_versions/down.sql
  migrations/2023-03-23-211241_add_rust_version_to_versions/up.sql
  src/admin/render_readmes.rs
  src/controllers/krate/publish.rs
  src/downloads_counter.rs
  src/models/krate.rs
  src/models/version.rs
  src/schema.rs
  src/tests/builders/version.rs
  src/tests/krate/versions.rs
  src/tests/routes/crates/versions/read.rs
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_semver_no_published_by.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_version.snap
  src/tests/routes/versions/snapshots/all__routes__versions__list__index-2.snap
  src/tests/routes/versions/snapshots/all__routes__versions__read__show_by_id.snap
  src/util.rs
  src/util/manifest.rs
  src/views.rs
  src/worker/dump_db/dump-db.toml
  src/worker/update_downloads.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6389 rust-version: Use "kebab-case" for `Cargo.toml` field name
  src/controllers/krate/publish.rs
  src/util/manifest.rs
Labels: C-bug 🐞, A-backend ⚙️

#6390 Display `rust-version` data in the crate page sidebar
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/models/version.js
  mirage/factories/version.js
  mirage/serializers/version.js
  public/assets/rust.svg
  tests/acceptance/crate-test.js
  tests/mirage/crates/get-by-id-test.js
  tests/mirage/crates/reverse-dependencies-test.js
  tests/mirage/crates/versions/list-test.js
  tests/mirage/me/updates/list-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#6394 models/version: Fix `msrv` regex
  app/models/version.js
  tests/models/version-test.js
Labels: C-bug 🐞, A-frontend 🐹

#6395 Add new `settings/tokens/new` page
  app/components/header.hbs
  app/components/settings-page.hbs
  app/components/settings/api-tokens.js
  app/components/side-menu/item.hbs
  app/controllers/settings/tokens/new.js
  app/router.js
  app/routes/settings/tokens.js
  app/routes/settings/tokens/index.js
  app/routes/settings/tokens/new.js
  app/styles/settings/tokens/new.module.css
  app/styles/shared/buttons.module.css
  app/templates/settings/tokens.hbs
  app/templates/settings/tokens/index.hbs
  app/templates/settings/tokens/new.hbs
  tests/routes/settings/tokens/new-test.js
Labels: C-enhancement ✨, A-frontend 🐹
