Repository rust-lang/crates.io, pull requests merged in 2023-08, with the labels that each got.

#6905 tarball/Package: Add `name` and `version` as required fields
  crates_io_tarball/src/lib.rs
  crates_io_tarball/src/manifest.rs
  src/admin/render_readmes.rs
  src/tests/builders/publish.rs
  src/tests/krate/publish.rs
  src/tests/routes/crates/read.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6875 Add application-level rate limits for crate updates, yanking and unyanking
  config/nginx.conf.erb
  src/app.rs
  src/config/server.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/downloads_counter.rs
  src/lib.rs
  src/models/krate.rs
  src/rate_limiter.rs
  src/sql.rs
  src/tests/builders/krate.rs
  src/tests/krate/publish.rs
  src/tests/krate/yanking.rs
  src/tests/util/response.rs
  src/tests/util/test_app.rs
  src/util/errors/json.rs
  src/worker/update_downloads.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6912 tests/krate/publish: Add invalid `rust-version` test
  src/tests/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#6913 tarball: Simplify test assertions
  crates_io_tarball/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#6914 tarball: Use `cargo_toml` to parse `Cargo.toml` file
  crates_io_tarball/src/lib.rs
  crates_io_tarball/src/manifest.rs
  src/admin/render_readmes.rs
  src/controllers/krate/publish.rs
  src/tests/krate/publish.rs
Labels: C-enhancement ✨, A-backend ⚙️

#6984 CI/smoke-test: Simplify `cargo` CLI flags
  .github/workflows/smoke-test.yml
Labels: C-internal 🔧, A-backend ⚙️

#6993 Remove obsolete `ArcStore` implementation
  src/storage.rs
  src/storage/arc_store.rs
Labels: C-internal 🔧, A-backend ⚙️

#6966 Improve correctness of the reverse dependencies query
  migrations/2023-08-13-175220_to_semver_no_prerelease_parallel_safe/down.sql
  migrations/2023-08-13-175220_to_semver_no_prerelease_parallel_safe/up.sql
  src/models/krate_reverse_dependencies.sql
Labels: C-internal 🔧, A-backend ⚙️

#6910 Optimize reverse dependencies query
  Cargo.lock
  Cargo.toml
  migrations/2023-08-13-175221_faster_reverse_dependencies_query/down.sql
  migrations/2023-08-13-175221_faster_reverse_dependencies_query/up.sql
  migrations/2023-08-13-175222_indexed_reverse_dependency_query/down.sql
  migrations/2023-08-13-175222_indexed_reverse_dependency_query/up.sql
  src/db.rs
  src/db/sql_types.rs
  src/db/sql_types/semver.rs
  src/models/krate_reverse_dependencies.sql
  src/models/version.rs
  src/schema.rs
  src/worker/dump_db/dump-db.toml
Labels: C-enhancement ✨, A-backend ⚙️

#7008 crates_io_tarball: error if multiple manifests are found
  crates_io_tarball/src/lib.rs
  src/controllers/krate/publish.rs
Labels: C-enhancement ✨, A-backend ⚙️

#7043 Revert "Update Rust crate dashmap to v5.5.1"
  Cargo.lock
  Cargo.toml
Labels: C-bug 🐞, A-backend ⚙️

#7048 Update the data access page on crates.io
  app/templates/data-access.hbs
Labels: A-frontend 🐹, C-documentation 📜
