Repository rust-lang/crates.io, pull requests merged in 2023-01, with the labels that each got.

#5772 Delete obsolete `enqueue-job` binary
  Justfile
  src/bin/enqueue-job.rs
Labels: C-internal 🔧, A-backend ⚙️

#5773 CI: Cancel obsolete runs for the same branch
  .github/workflows/ci.yml
Labels: C-internal 🔧, A-backend ⚙️

#5774 background-worker: Decrease file nesting
  src/bin/background-worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#5775 renovate: Simplify regex managers config
  .github/renovate.json5
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: C-internal 🔧

#5778 renovate: Add missing `versioning=semver` instructions
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
Labels: C-internal 🔧

#5779 Remove redundant `charset` from `application/json` content type response header
  src/tests/util/response.rs
  src/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5781 conduit-axum: Move `RoutePattern` insertion out of `conduit_into_axum()`
  conduit-axum/src/fallback.rs
Labels: C-internal 🔧, A-backend ⚙️

#5780 util/errors: Implement `response()` for all `AppError`
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  src/controllers/helpers/pagination.rs
  src/middleware.rs
  src/middleware/log_request.rs
  src/router.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#5782 Use `CauseField` response extension to set `cause` log field
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  src/middleware/log_request.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5783 Migrate `GET /keywords/:keyword_id` route to `axum`
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tokio_utils.rs
  src/controllers.rs
  src/controllers/conduit_axum.rs
  src/controllers/keyword.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5784 Simplify JSON serialization in `json_response()`
  src/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5788 axum: Simplify `conduit_compat()` function
  src/controllers/conduit_axum.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5790 helpers/pagination: Remove unnecessary `mut` keyword
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#5789 RequestUtils: Move `redirect()` and `json()` implementation into the trait
  src/controllers.rs
Labels: C-internal 🔧, A-backend ⚙️

#5792 middleware/block_traffic: Remove unnecessary str conversion
  src/middleware/block_traffic.rs
Labels: C-internal 🔧, A-backend ⚙️

#5791 Replace `request_header()` fn with `HeaderMapExt` trait
  src/controllers/helpers/pagination.rs
  src/util/request_helpers.rs
Labels: C-internal 🔧, A-backend ⚙️

#5796 helpers/pagination: Simplify `is_useragent_or_ip_blocked()` signature
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#5797 conduit-axum: Remove obsolete `SocketAddr` handling code
  conduit-axum/src/adaptor.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/tests.rs
Labels: C-internal 🔧, A-backend ⚙️

#5798 conduit-axum: Use `ConduitAxumHandler` struct to save `conduit::Handler`
  conduit-axum/src/fallback.rs
Labels: C-internal 🔧, A-backend ⚙️

#5800 conduit-axum/examples: Use `ConduitAxumHandler` to implement route handlers
  conduit-axum/examples/server.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/server.rs
Labels: C-internal 🔧, A-backend ⚙️

#5799 conduit-axum: Remove `StartInstant` extension
  conduit-axum/src/adaptor.rs
  conduit-axum/src/fallback.rs
Labels: C-internal 🔧, A-backend ⚙️

#5801 Extract `RequestParamExt::param()` extension fn
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/util.rs
  src/controllers/version.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#5802 RequestParamExt: Use `axum` path parameters if available
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  src/controllers/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5803 Use `axum` router
  src/middleware/app.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5804 Handle 404 errors in `axum`
  src/lib.rs
  src/middleware.rs
  src/middleware/app.rs
  src/middleware/known_error_to_json.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5805 Remove `conduit-router` and `conduit-middleware` dependencies
  Cargo.lock
  Cargo.toml
  conduit-axum/Cargo.toml
  conduit-axum/examples/server.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/server.rs
  src/controllers/util.rs
  src/middleware.rs
  src/middleware/update_metrics.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5811 conduit-axum: Remove obsolete `ConduitFallback` trait
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tests.rs
Labels: C-internal 🔧, A-backend ⚙️

#5812 pagination: Simplify `assert_pagination_error()` fn
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#5813 conduit: Remove obsolete functions from the `RequestExt` trait
  conduit-axum/src/adaptor.rs
  conduit-test/src/lib.rs
  conduit/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5814 conduit-axum: Extract `request`, `response` and `body` modules
  conduit-axum/src/body.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/request.rs
  conduit-axum/src/response.rs
  conduit-axum/src/tests.rs
Labels: C-internal 🔧, A-backend ⚙️

#5815 tests/util: Remove redundant `get_query()` fn
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5816 conduit::Body: Remove obsolete `File` variant
  conduit-axum/src/body.rs
  conduit-axum/src/file_stream.rs
  conduit-axum/src/lib.rs
  conduit-test/src/lib.rs
  conduit/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5817 conduit: Replace `path()` and `query_string()` with `uri()`
  conduit-axum/src/request.rs
  conduit-axum/src/tests.rs
  conduit-test/src/lib.rs
  conduit/src/lib.rs
  src/controllers.rs
  src/controllers/krate/search.rs
  src/controllers/version/deprecated.rs
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5819 conduit: Simplify `Extensions` export
  conduit/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5818 conduit-test: Remove unused `with_method()` and `with_path()` fns
  conduit-test/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5820 conduit: Remove obsolete `http_version()` fn from `RequestExt` trait
  conduit-axum/src/request.rs
  conduit-test/src/lib.rs
  conduit/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5823 conduit-test: Remove `with_query()` fn
  conduit-test/src/lib.rs
  src/controllers/helpers/pagination.rs
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5824 conduit: Remove unused `HttpResult` type
  conduit/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5825 conduit-axum: Remove `ConduitRequest` wrapper
  Cargo.lock
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/request.rs
  conduit/Cargo.toml
  conduit/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5827 tests/util: Remove unnecessary `ConnectInfo` extension usage
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5826 conduit: Replace custom `Body` enum with `bytes::Bytes`
  conduit-axum/examples/server.rs
  conduit-axum/src/body.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/response.rs
  conduit-axum/src/tests.rs
  conduit-test/src/lib.rs
  conduit/src/lib.rs
  src/controllers.rs
  src/controllers/helpers/pagination.rs
  src/controllers/metrics.rs
  src/controllers/token.rs
  src/middleware.rs
  src/util.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5828 conduit-test: Simplify `MockRequest` conversion code
  Cargo.lock
  conduit-test/Cargo.toml
  conduit-test/src/lib.rs
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5829 conduit-axum: Simplify `bad_request()` fn
  conduit-axum/src/fallback.rs
Labels: C-internal 🔧, A-backend ⚙️

#5831 conduit-test: Remove `conduit` dependency
  Cargo.lock
  conduit-test/Cargo.toml
  conduit-test/src/lib.rs
  src/controllers/helpers/pagination.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5833 conduit::Handler: Use fixed request type
  conduit-axum/examples/server.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tests.rs
  conduit/src/lib.rs
  src/auth.rs
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/helpers/pagination.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/util.rs
  src/controllers/version.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/middleware.rs
  src/middleware/app.rs
  src/middleware/log_request.rs
  src/middleware/session.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5834 conduit::RequestExt: Remove redundant accessor methods
  conduit/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#5835 middleware: Remove obsolete `prelude` module
  src/middleware.rs
  src/middleware/block_traffic.rs
  src/middleware/require_user_agent.rs
Labels: C-internal 🔧, A-backend ⚙️

#5838 conduit: Remove `RequestExt` trait
  conduit/src/lib.rs
  src/controllers.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
Labels: C-internal 🔧, A-backend ⚙️

#5840 req.json(): Take ownership of the JSON data
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/helpers.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5839 conduit: Move remaining code into `conduit-axum` package
  Cargo.lock
  Cargo.toml
  conduit-axum/Cargo.toml
  conduit-axum/examples/server.rs
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tests.rs
  conduit/Cargo.toml
  conduit/LICENSE
  src/auth.rs
  src/controllers.rs
  src/router.rs
  src/tests/github_secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#5841 helpers/pagination: Simplify `assert_pagination_error()` fn
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#5842 conduit::Handler: Expect `axum::Response` return values
  conduit-axum/examples/server.rs
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tests.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5843 AppError: Return `axum::Response` from `response()` fn
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#5844 Change request handler return type to `axum::Response`
  conduit-axum/examples/server.rs
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tests.rs
  src/controllers.rs
  src/controllers/helpers.rs
  src/controllers/metrics.rs
  src/controllers/token.rs
  src/router.rs
  src/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5845 Pass `request` ownership into the request handlers
  conduit-axum/examples/server.rs
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tests.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5846 Clean up type aliases
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/conduit_axum.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/helpers.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/github.rs
  src/router.rs
  src/util.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#5847 Allow request handlers to return any `impl IntoResponse`
  src/controllers.rs
  src/controllers/helpers.rs
  src/controllers/version/metadata.rs
  src/middleware.rs
  src/router.rs
  src/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#5851 RequestUtils: Replace `json()` fn with direct `axum::Json` usage
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#5853 ConduitRequest: Convert into struct with `FromRequest` implementation
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  src/controllers/helpers/pagination.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5854 conduit_compat(): Remove unnecessary `into_response()` calls
  src/controllers/conduit_axum.rs
  src/controllers/keyword.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5855 controllers/keyword: Convert `index()` to native `axum` request handler
  src/controllers/keyword.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5859 Convert all request handlers to async functions
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5860 conduit-axum: Migrate to async request handler functions
  conduit-axum/examples/server.rs
  conduit-axum/src/tests.rs
Labels: C-internal 🔧, A-backend ⚙️

#5863 router: Simplify error status code tests
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5865 GET /crates/:crate_id/:version/download: Remove `log_metadata` variable
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#5864 conduit-axum: Remove obsolete code
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#5558 Add normalize-index background job
  cargo-registry-index/lib.rs
  src/admin/enqueue_job.rs
  src/background_jobs.rs
  src/tests/http-data/krate_publish_features_version_2.json
  src/tests/http-data/krate_publish_good_badges.json
  src/tests/http-data/krate_publish_good_categories.json
  src/tests/http-data/krate_publish_good_keywords.json
  src/tests/http-data/krate_publish_ignored_badges.json
  src/tests/http-data/krate_publish_ignored_categories.json
  src/tests/http-data/krate_publish_new_crate_allow_empty_alternative_registry_dependency.json
  src/tests/http-data/krate_publish_new_krate.json
  src/tests/http-data/krate_publish_new_krate_git_upload.json
  src/tests/http-data/krate_publish_new_krate_git_upload_appends.json
  src/tests/http-data/krate_publish_new_krate_git_upload_with_conflicts.json
  src/tests/http-data/krate_publish_new_krate_records_verified_email.json
  src/tests/http-data/krate_publish_new_krate_too_big_but_whitelisted.json
  src/tests/http-data/krate_publish_new_krate_twice.json
  src/tests/http-data/krate_publish_new_krate_weird_version.json
  src/tests/http-data/krate_publish_new_krate_with_dependency.json
  src/tests/http-data/krate_publish_new_krate_with_readme.json
  src/tests/http-data/krate_publish_new_krate_with_token.json
  src/tests/http-data/krate_publish_new_with_renamed_dependency.json
  src/tests/http-data/krate_publish_new_with_underscore_renamed_dependency.json
  src/tests/http-data/krate_publish_publish_after_removing_documentation.json
  src/tests/http-data/krate_publish_publish_new_crate_rate_limited.json
  src/tests/http-data/krate_publish_publish_rate_limit_doesnt_affect_existing_crates.json
  src/tests/http-data/krate_publish_publish_records_an_audit_action.json
  src/tests/http-data/krate_publish_uploading_new_version_touches_crate.json
  src/tests/http-data/krate_yanking_publish_after_yank_max_version.json
  src/tests/http-data/krate_yanking_yank_max_version.json
  src/tests/http-data/krate_yanking_yank_works_as_intended.json
  src/tests/http-data/owners_new_crate_owner.json
  src/tests/http-data/routes_crates_new_daily_limit.json
  src/tests/http-data/routes_crates_read_version_size.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_cookie_user.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_endpoint_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_correct_wildcard_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_endpoint_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_token_user_with_incorrect_wildcard_crate_scope.json
  src/tests/http-data/routes_crates_versions_yank_unyank_auth_unauthenticated.json
  src/tests/http-data/routes_crates_versions_yank_unyank_unyank_records_an_audit_action.json
  src/tests/http-data/routes_crates_versions_yank_unyank_yank_records_an_audit_action.json
  src/tests/http-data/team_publish_owned.json
  src/worker/git.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#5770 background_jobs: Remove empty structs
  src/background_jobs.rs
  src/worker/daily_db_maintenance.rs
  src/worker/git.rs
  src/worker/update_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#5869 MockRequest: Remove unnecessary `Cursor` wrapper
  conduit-test/src/lib.rs
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#5870 Use `Path` extractor in request handlers
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/util.rs
  src/controllers/version.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
Labels: C-internal 🔧, A-backend ⚙️

#5871 Simplify and move `content_length()` function
  conduit-axum/src/conduit.rs
  src/controllers.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/krate/publish.rs
  src/controllers/token.rs
Labels: C-internal 🔧, A-backend ⚙️

#5872 Use generic `Request` parameters where possible
  src/auth.rs
  src/controllers.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/util.rs
  src/controllers/version/yank.rs
Labels: C-internal 🔧, A-backend ⚙️

#5873 controllers/token: Remove obsolete `content_length()` check
  src/controllers/token.rs
  src/tests/routes/me/tokens/create.rs
Labels: C-internal 🔧, A-backend ⚙️

#5874 controllers/github: Use `axum` extractors
  src/controllers/github/secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#5875 Add `cargo add` instruction to crate-sidebar
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  app/templates/crate/version.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#5877 Clean up `AuthenticatedUser` accessor methods
  src/auth.rs
  src/controllers/krate/owners.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
Labels: C-internal 🔧, A-backend ⚙️

#5879 auth: Move authentication-related code back into `authenticate_user()` fn
  src/auth.rs
Labels: C-internal 🔧, A-backend ⚙️

#5878 util/errors: Simplify `internal()` fn
  src/controllers/crate_owner_invitation.rs
  src/github.rs
  src/uploaders.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5881 auth: Convert `AuthenticatedUser` struct to `Authentication` enum
  src/auth.rs
  src/controllers/crate_owner_invitation.rs
Labels: C-internal 🔧, A-backend ⚙️

#5885 Implement `RequestPartsExt` trait
  src/auth.rs
  src/controllers.rs
  src/controllers/helpers/pagination.rs
  src/controllers/util.rs
  src/middleware/app.rs
  src/middleware/log_request.rs
  src/middleware/session.rs
Labels: C-internal 🔧, A-backend ⚙️

#5886 auth: Extract `authenticate_via_cookie/token()` fns
  src/auth.rs
Labels: C-internal 🔧, A-backend ⚙️

#5888 publish: Skip unnecessary `String::from_utf8()` call
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#5889 auth: Reuse existing database connections
  src/auth.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/version/yank.rs
Labels: C-internal 🔧, A-backend ⚙️

#5890 controllers/github: Reuse existing database connection in `send_notification_email()` call
  src/controllers/github/secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#5891 controllers/crate_owner_invitations: Avoid second database connection request
  src/controllers/crate_owner_invitation.rs
Labels: C-internal 🔧, A-backend ⚙️

#5837 Reuse existing connection when executing each background job
  src/background_jobs.rs
  src/db.rs
  src/swirl/runner.rs
  src/tests/all.rs
Labels: C-internal 🔧, A-backend ⚙️

#5898 conduit-axum: Inline `content_length()` method
  conduit-axum/src/conduit.rs
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#5899 controllers/publish: Remove redundant `LimitErrorReader` usage
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#5903 publish: Avoid redundant buffer copies
  cargo-registry-s3/lib.rs
  src/controllers/krate/publish.rs
  src/uploaders.rs
Labels: C-internal 🔧, A-backend ⚙️

#5906 ConduitRequest: Remove `Cursor` wrapper
  conduit-axum/src/conduit.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
Labels: C-internal 🔧, A-backend ⚙️

#5907 Use `Parts` where request body is irrelevant
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
Labels: C-internal 🔧, A-backend ⚙️

#5908 Use `State` extractor where request metadata is irrelevant
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/team.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#5913 RealGitHubClient: Remove obsolete `base_url` field
  src/app.rs
  src/config.rs
  src/github.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5914 config: Use `ClientId` and `ClientSecret` wrappers for GitHub OAuth fields
  src/app.rs
  src/config.rs
  src/controllers/github/secret_scanning.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#5920 Use `parking_lot::Mutex` and `RwLock`
  src/controllers/github/secret_scanning.rs
  src/middleware/log_request.rs
  src/middleware/session.rs
Labels: C-internal 🔧, A-backend ⚙️

#5921 Simplify session extension usage
  src/auth.rs
  src/controllers/user/session.rs
  src/middleware/session.rs
Labels: C-internal 🔧, A-backend ⚙️

#5923 conduit-axum: Replace `AxumResponse` and `HandlerResult` type aliases
  conduit-axum/examples/server.rs
  conduit-axum/src/conduit.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/response.rs
  conduit-axum/src/tests.rs
Labels: C-internal 🔧, A-backend ⚙️

#5924 MockRequest: Move into `src/tests/util` and remove obsolete `conduit-test` package
  Cargo.lock
  Cargo.toml
  conduit-test/Cargo.toml
  conduit-test/LICENSE
  src/controllers/helpers/pagination.rs
  src/tests/util.rs
  src/tests/util/mock_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#5925 MockRequest: Convert to type alias with extension methods on `MockRequestExt` trait
  src/tests/authentication.rs
  src/tests/github_secret_scanning.rs
  src/tests/routes/metrics.rs
  src/tests/token.rs
  src/tests/util.rs
  src/tests/util/mock_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#5929 index/Dependency: Change `Ord` order
  cargo-registry-index/lib.rs
Labels: C-bug 🐞, A-backend ⚙️

#5930 conduit-axum: Move remaining content into the main package
  Cargo.lock
  Cargo.toml
  conduit-axum/Cargo.toml
  conduit-axum/LICENSE-APACHE
  conduit-axum/LICENSE-MIT
  conduit-axum/README.md
  conduit-axum/examples/server.rs
  conduit-axum/src/conduit.rs
  conduit-axum/src/error.rs
  conduit-axum/src/fallback.rs
  conduit-axum/src/lib.rs
  conduit-axum/src/tests.rs
  conduit-axum/src/tokio_utils.rs
  src/controllers.rs
  src/controllers/conduit_axum.rs
  src/middleware/log_request.rs
  src/router.rs
  src/util.rs
  src/util/bytes_request.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#5931 moka: Use future-aware cache
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#5933 Use `AppState` in request handlers
  src/app.rs
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/metrics.rs
  src/controllers/site_metadata.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/deprecated.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/middleware/app.rs
  src/middleware/balance_capacity.rs
  src/middleware/block_traffic.rs
  src/middleware/ember_html.rs
  src/middleware/require_user_agent.rs
  src/middleware/update_metrics.rs
Labels: C-internal 🔧, A-backend ⚙️

#5934 Avoid worker thread for cached download requests
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#5951 GET /crates/:crate_id/:version/readme: Remove unnecessary `conduit_compat()` call
  src/controllers/krate/metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#5952 GET /api/private/session/begin: Remove unnecessary `conduit_compat()` call
  src/controllers/user/session.rs
Labels: C-internal 🔧, A-backend ⚙️

#5954 Simplify `parse_traffic_patterns()` fn
  src/config.rs
Labels: C-internal 🔧, A-backend ⚙️

#5918 Share the existing background job connection with (only) some jobs
  src/background_jobs.rs
  src/db.rs
  src/swirl/runner.rs
  src/tests/all.rs
Labels: C-internal 🔧, A-backend ⚙️

#5949 Add category no-std::no-alloc
  src/boot/categories.toml
Labels: A-categories

#5964 Add Geography category
  src/boot/categories.toml
Labels: A-categories

#5973 Add `crate_scopes` and `endpoint_scopes` fields to the `PUT /me/tokens` API endpoint
  src/controllers/token.rs
  src/tests/routes/me/tokens/create.rs
Labels: C-enhancement ✨, A-backend ⚙️

#5980 Revert "Update Rust crate git2 to v0.16.1 [SECURITY]"
  Cargo.lock
  cargo-registry-index/Cargo.toml
Labels: C-bug 🐞, A-backend ⚙️

#5984 Add a basic `og:image` for social link previews
  app/index.html
  public/assets/og-image.png
Labels: C-enhancement ✨

#6004 Simplify `format!()` call
  src/github.rs
Labels: C-internal 🔧, A-backend ⚙️
