Repository rust-lang/crates.io, pull requests merged in 2024-07, with the labels that each got.

#8970 Use `#[diesel::dsl::auto_type]` in some places
  src/models/category.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#8994 tests: Increase database pool size
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#9003 rss: Invalidate Fastly cache too
  src/worker/jobs/rss/sync_updates_feed.rs
Labels: C-bug 🐞, A-backend ⚙️

#8946 Prefill "New API Token" page with existing values if requested
  app/controllers/settings/tokens/new.js
  app/routes/settings/tokens/new.js
  app/templates/settings/tokens/new.hbs
  e2e/routes/settings/tokens/new.spec.ts
  mirage/route-handlers/me.js
  tests/routes/settings/tokens/new-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#7889 controllers/crates: default to sort by recent downloads
  app/controllers/crates.js
  e2e/acceptance/crates.spec.ts
  mirage/route-handlers/crates.js
  tests/acceptance/crates-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#8986 Create `crates.xml` RSS feed
  src/admin/enqueue_job.rs
  src/controllers/krate/publish.rs
  src/storage.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/git.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/rate_limit.rs
  src/tests/krate/publish/readme.rs
  src/tests/worker/rss/mod.rs
  src/tests/worker/rss/snapshots/all__worker__rss__sync_crates_feed__sync_crates_feed-2.snap
  src/tests/worker/rss/sync_crates_feed.rs
  src/worker/jobs/rss/mod.rs
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crates_feed__tests__load_version_updates-2.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crates_feed__tests__load_version_updates-3.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crates_feed__tests__load_version_updates.snap
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9049 Update expiry notification to use the copy token link
  src/worker/jobs/expiry_notification.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9054 Separate e2e snapshots and enable parallel test suites for percy
  .github/workflows/ci.yml
  e2e/fixtures/percy.ts
Labels: A-frontend 🐹

#9062 Remove obsolete `ember-cli-deprecation-workflow` addon
  config/deprecation-workflow.js
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#9063 Change the README security link to crates.io's security page
  README.md
Labels: C-documentation 📜

#9095 UI: Use `created_at` instead of `updated_at`
  app/components/crate-sidebar.hbs
  app/components/version-list/row.hbs
  app/models/version.js
Labels: C-bug 🐞, A-frontend 🐹

#9106 CrateSidebar: Fix `@hasLib` assignment
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar/install-instructions.module.css
Labels: C-bug 🐞, A-frontend 🐹

#9113 Add support for pictures that react to the user's color scheme choice
  app/components/rendered-html.hbs
  app/components/rendered-html.js
  app/modifiers/update-source-media.js
  crates/crates_io_markdown/lib.rs
Labels: C-enhancement ✨, A-frontend 🐹, A-backend ⚙️

#9064 Create `crates/{name}.xml` RSS feeds
  src/admin/delete_crate.rs
  src/controllers/krate/publish.rs
  src/storage.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/git.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/rate_limit.rs
  src/tests/krate/publish/readme.rs
  src/tests/worker/rss/mod.rs
  src/tests/worker/rss/snapshots/all__worker__rss__sync_crate_feed__sync_crate_feed-2.snap
  src/tests/worker/rss/sync_crate_feed.rs
  src/worker/jobs/rss/mod.rs
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates-2.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates-3.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates.snap
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9118 Revert "jobs/rss/sync_crate_feed: Introduce temporary `SKIP_RSS_CLOUDFRONT_INVALIDATION` env var"
  src/worker/jobs/rss/sync_crate_feed.rs
Labels: C-internal 🔧, A-backend ⚙️

#9122 Add support for regenerating the token
  app/components/settings/api-tokens.hbs
  app/components/settings/api-tokens.module.css
  e2e/acceptance/api-token.spec.ts
  tests/acceptance/api-token-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#9143 models/user: Inline `find_by_api_token()` fn
  src/admin/verify_token.rs
  src/models/user.rs
  src/tests/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#9144 models/user: Move `HashedToken::parse()` call outside `find_by_api_token()` fn
  src/admin/verify_token.rs
  src/auth.rs
  src/models/token.rs
  src/tests/user.rs
  src/util/token.rs
Labels: C-internal 🔧, A-backend ⚙️

#9158 editorconfig: Adjust indentation for JSON files
  .editorconfig
Labels: A-frontend 🐹, C-internal 🔧

#9159 Avoid mutations while still borrowed
  src/controllers/krate/versions.rs
  src/typosquat/database.rs
Labels: C-internal 🔧, A-backend ⚙️

#9157 Revert "Merge pull request #6437 from LawnGnome/proxy-admin-routes"
  config/environment.js
  docs/CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  server/index.js
Labels: A-frontend 🐹, C-internal 🔧

#9176 clippy: Remove `all = "warn"` override
  Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#9177 Remove obsolete `once_cell` dependency
  Cargo.lock
  Cargo.toml
  crates/crates_io_env_vars/Cargo.toml
  crates/crates_io_env_vars/src/lib.rs
  crates/crates_io_test_db/Cargo.toml
  crates/crates_io_test_db/src/lib.rs
  src/ci.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/krate/search.rs
  src/real_ip.rs
  src/tests/dump_db.rs
  src/tests/routes/crates/list.rs
Labels: C-internal 🔧, A-backend ⚙️

#9192 Use `postgres-native-tls` to connect to the database with TLS
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/bin/background-worker.rs
  src/certs/crunchy.pem
  src/certs/mod.rs
  src/db.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#9180 Change version downloads archive location to static S3 bucket
  src/bin/background-worker.rs
  src/storage.rs
  src/worker/jobs/archive_version_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#9195 jobs/downloads/process_log: Decrease batch size
  src/worker/jobs/downloads/process_log.rs
Labels: C-bug 🐞, A-backend ⚙️

#9197 tests/krate/publish/rate_limit: Increase rate limit duration
  src/tests/krate/publish/rate_limit.rs
Labels: C-internal 🔧, A-backend ⚙️
