Repository rust-lang/crates.io, pull requests merged in 2024-12, with the labels that each got.

#10108 components: don't infer MSRV based on edition
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/components/edition.hbs
  app/components/edition.module.css
  app/components/msrv.hbs
  app/components/msrv.module.css
  app/components/version-list/row.hbs
  app/components/version-list/row.module.css
  app/models/version.js
  tests/models/version-test.js
Labels: A-frontend 🐹

#10122 tests/acceptance/support-test: Fix QUnit warning
  tests/acceptance/support-test.js
Labels: A-frontend 🐹, C-internal 🔧

#9904 Implement `DELETE /api/v1/crates/:crate_id` endpoint
  src/controllers/krate.rs
  src/controllers/krate/delete.rs
  src/router.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10144 Include email address in support buttons
  app/components/support/crate-report-form.hbs
  app/components/support/crate-report-form.module.css
  app/styles/support.module.css
  app/templates/support.hbs
  e2e/acceptance/support.spec.ts
  tests/acceptance/support-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#10155 Docker: Remove deprecated `version` attribute
  docker-compose.yml
  docs/CONTRIBUTING.md
Labels: C-internal 🔧

#10169 controllers/krate/delete: Adjust HTTP status code
  src/controllers/krate/delete.rs
Labels: C-bug 🐞, A-backend ⚙️

#10173 ember-data: Fix `ember-data:deprecate-array-like` warning
  app/controllers/categories.js
  app/controllers/category/index.js
  app/controllers/crate/reverse-dependencies.js
  app/controllers/crates.js
  app/controllers/keyword.js
  app/controllers/keywords.js
  app/controllers/me/crates.js
  app/controllers/me/following.js
  app/controllers/search.js
  app/controllers/team.js
  app/controllers/user.js
Labels: A-frontend 🐹, C-internal 🔧

#10175 mirage: Implement `DELETE /api/v1/crates/:name` endpoint
  mirage/route-handlers/crates.js
  tests/mirage/crates/delete-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10176 CI: Fix zizmor issues
  .github/workflows/ci.yml
  .github/workflows/smoke-test.yml
Labels: C-internal 🔧

#10178 styles/buttons: Fix font color in disabled state
  app/styles/shared/buttons.module.css
Labels: C-bug 🐞, A-frontend 🐹

#10182 crate-header: Fix deprecation warnings
  app/components/crate-header.hbs
  app/components/crate-header.js
Labels: A-frontend 🐹, C-internal 🔧

#10179 styles/buttons: Use `not-allowed` cursor for disabled buttons
  app/styles/shared/buttons.module.css
Labels: C-enhancement ✨, A-frontend 🐹

#10177 UI: Implement `/crates/:name/delete` route
  app/adapters/application.js
  app/controllers/crate/delete.js
  app/router.js
  app/routes/crate/delete.js
  app/styles/application.module.css
  app/styles/crate/delete.module.css
  app/templates/crate/delete.hbs
  e2e/routes/crate/delete.spec.ts
  public/assets/triangle-exclamation.svg
  tests/routes/crate/delete-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#10189 Fix pagination field generation for duplicate keys
  src/tests/routes/crates/list.rs
  src/util/request_helpers.rs
Labels: C-bug 🐞, A-backend ⚙️

#10190 controllers/helpers/pagination: Remove generic parameter from `gather()` fn
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#10192 Replace `derive_deref` with `derive_more`
  Cargo.lock
  Cargo.toml
  crates/crates_io_cdn_logs/Cargo.toml
  crates/crates_io_cdn_logs/src/download_map.rs
  src/lib.rs
  src/middleware/log_request.rs
  src/middleware/real_ip.rs
Labels: C-internal 🔧, A-backend ⚙️

#10186 Use `utoipa` crates to generate and serve basic OpenAPI description
  Cargo.lock
  Cargo.toml
  src/controllers/krate/search.rs
  src/lib.rs
  src/openapi.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-enhancement ✨, A-backend ⚙️, C-documentation 📜

#10191 controllers/helpers/pagination: Remove generic parameter from `is_useragent_or_ip_blocked()` fn
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#10195 Derive `Deref` for more structs
  Cargo.toml
  src/app.rs
  src/middleware/session.rs
  src/tests/util/response.rs
  src/util/bytes_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#10197 router: Remove obsolete `DefaultBodyLimit` override
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#10201 utoipa: Add annotations to (almost) all endpoints
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/krate.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/versions.rs
  src/controllers/site_metadata.rs
  src/controllers/summary.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/resend.rs
  src/controllers/user/session.rs
  src/controllers/user/update.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/blocked_routes.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10198 Fix frontend deprecations
  app/components/crate-header.js
  app/components/crate-sidebar.hbs
  app/components/version-list/row.js
  app/controllers/crate/settings.js
  app/controllers/crate/version.js
  app/models/crate.js
  app/routes/crate.js
  app/routes/crate/version.js
  app/routes/crate/versions.js
  tests/components/crate-sidebar/playground-button-test.js
  tests/components/crate-sidebar/toml-snippet-test.js
  tests/components/owners-list-test.js
  tests/components/version-list-row-test.js
  tests/models/version-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10207 utoipa: Rename route handler fns to remove `operation_id` attributes
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/site_metadata.rs
  src/controllers/summary.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/resend.rs
  src/controllers/user/session.rs
  src/controllers/user/update.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-internal 🔧, A-backend ⚙️

#10208 Extract `CratePath` and `CrateVersionPath` structs
  src/controllers/krate.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/versions.rs
  src/controllers/version.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/routes/crates/downloads.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10213 utoipa: Add remaining `Path` params
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/resend.rs
  src/controllers/user/update.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10221 chrono: Use strftime shortcut specifiers
  src/bin/crates-admin/render_readmes.rs
  src/rate_limiter.rs
  src/util/errors.rs
  src/util/errors/json.rs
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/index/squash.rs
Labels: C-internal 🔧, A-backend ⚙️

#10216 controllers/krate/search: Read query parameters via axum extractor
  Cargo.lock
  Cargo.toml
  src/controllers/krate/search.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/krate/following.rs
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-2.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-3.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-4.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes-5.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__list__invalid_params_with_null_bytes.snap
  src/util.rs
  src/util/string_excl_null.rs
Labels: C-internal 🔧, A-backend ⚙️, C-documentation 📜

#10223 Replace `unwrap()` with `?`
  crates/crates_io_tarball/examples/check_all_crates.rs
  src/bin/background-worker.rs
  src/bin/server.rs
  src/rate_limiter.rs
Labels: C-internal 🔧, A-backend ⚙️

#10214 controllers/krate/versions: Add `release_tracks` meta for non-paginated versions
  src/controllers/krate/versions.rs
  src/tests/routes/crates/versions/list.rs
  src/tests/routes/crates/versions/snapshots/crates_io__tests__routes__crates__versions__list__versions.snap
Labels: C-enhancement ✨, A-backend ⚙️

#10224 controllers/krate/search: Simplify `auth_user_id` code
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️

#10225 controllers/krate/search: Derive `Deref` for `FilterParams`
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️

#10226 controllers/krate/search: Move `letter` validation out of `make_query()` fn
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️

#10230 Replace `BytesRequest` with `Json` and `Parts` extractors
  src/controllers/crate_owner_invitation.rs
  src/controllers/user/me.rs
  src/controllers/util.rs
  src/util.rs
  src/util/bytes_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#10231 Extract more controller modules
  src/controllers.rs
  src/controllers/krate.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/rev_deps.rs
  src/controllers/session.rs
  src/controllers/user.rs
  src/controllers/user/email_notifications.rs
  src/controllers/user/email_verification.rs
  src/controllers/user/me.rs
  src/controllers/user/snapshots/crates_io__controllers__user__email_verification__tests__happy_path-2.snap
  src/controllers/version.rs
  src/controllers/version/authors.rs
  src/controllers/version/dependencies.rs
  src/controllers/version/metadata.rs
  src/controllers/version/readme.rs
  src/controllers/version/update.rs
  src/controllers/version/yank.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#10233 utoipa: Add pagination query params to `list_crates()` documentation
  src/controllers/helpers/pagination.rs
  src/controllers/krate/search.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10238 Extract `QueryParams` structs
  Cargo.toml
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/versions.rs
  src/controllers/version/downloads.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/util/request_helpers.rs
Labels: C-internal 🔧, A-backend ⚙️, C-documentation 📜

#10244 components/email-input: fix the dark theme border by using gray-border
  app/components/email-input.module.css
Labels: C-bug 🐞, A-frontend 🐹

#10249 real_ip: Remove Heroku router workaround
  src/real_ip.rs
Labels: C-internal 🔧, A-backend ⚙️

#10267 Extract `crates_io_session` crate
  Cargo.lock
  Cargo.toml
  crates/crates_io_session/Cargo.toml
  crates/crates_io_session/src/lib.rs
  src/auth.rs
  src/controllers/session.rs
  src/middleware.rs
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#10264 OpenAPI: Describe authentication requirements
  crates/crates_io_session/src/lib.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/session.rs
  src/controllers/token.rs
  src/controllers/user/email_notifications.rs
  src/controllers/user/email_verification.rs
  src/controllers/user/me.rs
  src/controllers/user/update.rs
  src/controllers/version/update.rs
  src/controllers/version/yank.rs
  src/openapi.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10277 e2e/acceptance/versions: Fix potential flaky test case
  e2e/acceptance/versions.spec.ts
Labels: A-frontend 🐹, C-internal 🔧

#10266 Raise crate deletion download limit
  app/templates/crate/delete.hbs
  src/controllers/krate/delete.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-enhancement ✨, A-backend ⚙️

#10253 crate/delete: tinker with the requirements styling
  app/styles/crate/delete.module.css
  app/templates/crate/delete.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#10265 controllers/krate/delete: Send deletion notification email after successful deletion
  src/controllers/krate/delete.rs
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_new_crate-2.snap
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_old_crate-2.snap
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_really_old_crate-2.snap
Labels: C-enhancement ✨, A-backend ⚙️

#10276 mirage: Respect `include` query params in `GET /api/v1/crates/:id`
  mirage/route-handlers/crates.js
  mirage/serializers/crate.js
  tests/mirage/crates/get-by-id-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10283 controllers/krate/versions: Extract `ListQueryParams::include()` fn
  src/controllers/krate/versions.rs
Labels: C-internal 🔧, A-backend ⚙️

#10292 cdn_logs: Use `README.md` as module documentation
  crates/crates_io_cdn_logs/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#10291 Extract `crates_io_diesel_helpers` crate
  Cargo.lock
  Cargo.toml
  crates/crates_io_diesel_helpers/Cargo.toml
  crates/crates_io_diesel_helpers/README.md
  crates/crates_io_diesel_helpers/src/fns.rs
  crates/crates_io_diesel_helpers/src/lib.rs
  crates/crates_io_diesel_helpers/src/pg_enum.rs
  crates/crates_io_diesel_helpers/src/semver.rs
  src/bin/monitor.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/user/other.rs
  src/lib.rs
  src/models/action.rs
  src/models/category.rs
  src/models/default_versions.rs
  src/models/dependency.rs
  src/models/keyword.rs
  src/models/krate.rs
  src/models/owner.rs
  src/models/user.rs
  src/rate_limiter.rs
Labels: C-internal 🔧, A-backend ⚙️

#10295 Fix prettier issues
  crates/crates_io_diesel_helpers/README.md
Labels: C-documentation 📜

#10294 mirage: Add `meta` field in `GET /api/v1/crates/:id/versions`
  mirage/route-handlers/-utils.js
  mirage/route-handlers/crates.js
  tests/mirage/crates/versions/list-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10293 Add `README.md` files to subpackages
  crates/crates_io_database/README.md
  crates/crates_io_database/src/lib.rs
  crates/crates_io_database_dump/README.md
  crates/crates_io_database_dump/src/lib.rs
  crates/crates_io_env_vars/README.md
  crates/crates_io_env_vars/src/lib.rs
  crates/crates_io_github/README.md
  crates/crates_io_github/src/lib.rs
  crates/crates_io_index/README.md
  crates/crates_io_index/lib.rs
  crates/crates_io_markdown/README.md
  crates/crates_io_markdown/lib.rs
  crates/crates_io_pagerduty/README.md
  crates/crates_io_pagerduty/src/lib.rs
  crates/crates_io_session/README.md
  crates/crates_io_session/src/lib.rs
  crates/crates_io_smoke_test/README.md
  crates/crates_io_smoke_test/src/main.rs
  crates/crates_io_tarball/README.md
  crates/crates_io_tarball/src/lib.rs
  crates/crates_io_team_repo/README.md
  crates/crates_io_team_repo/src/lib.rs
  crates/crates_io_test_db/README.md
  crates/crates_io_test_db/src/lib.rs
  crates/crates_io_worker/README.md
  crates/crates_io_worker/src/lib.rs
Labels: A-backend ⚙️, C-documentation 📜

#10288 controllers/krate/metadata: Add support for `default_version` include mode
  src/controllers/krate/metadata.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/routes/crates/read.rs
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__include_default_version.snap
Labels: A-backend ⚙️
