Repository rust-lang/crates.io, pull requests merged in 2024-04, with the labels that each got.

#8385 worker: Replace `r2d2` with `deadpool`
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
  src/worker/environment.rs
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/downloads/queue/job.rs
  src/worker/jobs/git.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/sync_admins.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#8420 Simplify `expired_at` filtering using `assume_not_null`
  src/controllers/token.rs
Labels: C-internal 🔧, A-backend ⚙️

#8421 models/krate: Remove unused `downloads` field
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#8427 tests/util/test_app: Simplify `test_database` field
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8428 tests/util/test_app: Remove duplicate background job assertion
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8429 util/errors: Convert `deadpool` errors to "503 Service Unavailable" responses
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#8430 util/errors: Convert `ClosedConnection` errors to "503 Service Unavailable" responses
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#8425 metrics/instance: Add async connection pools
  src/metrics/instance.rs
Labels: C-internal 🔧, A-backend ⚙️

#8424 crates_io_worker: Replace `r2d2` with `deadpool`
  Cargo.lock
  crates/crates_io_worker/Cargo.toml
  crates/crates_io_worker/src/runner.rs
  crates/crates_io_worker/src/util.rs
  crates/crates_io_worker/src/worker.rs
  crates/crates_io_worker/tests/runner.rs
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8431 controllers: Replace `r2d2` with `deadpool`
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/metrics.rs
  src/controllers/summary.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
Labels: C-internal 🔧, A-backend ⚙️

#8439 tests/util/test_app: Use `test_database.connect()` for `background_jobs` query
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8441 tests/unhealthy_database: Migrate from sync to async database pools
  src/tests/unhealthy_database.rs
Labels: C-internal 🔧, A-backend ⚙️

#8440 controllers/user/session: Replace `r2d2` with `deadpool`
  src/controllers/user/session.rs
Labels: C-internal 🔧, A-backend ⚙️

#8442 Remove `r2d2` database connection pools
  Cargo.toml
  src/app.rs
  src/db.rs
  src/metrics/instance.rs
  src/util/errors.rs
Labels: C-internal 🔧, A-backend ⚙️

#8447 deadpool: Drop obsolete `async` suffixes
  src/app.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/metrics.rs
  src/controllers/summary.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/metrics/instance.rs
  src/tests/unhealthy_database.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8450 tracing: Enable time output in tests
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#8452 config/database_pools: Remove sync database pools
  src/app.rs
  src/config/database_pools.rs
  src/middleware/balance_capacity.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8453 middleware/log_requests: Remove special casing for download requests
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#8451 Remove `balance_capacity` middleware
  src/app.rs
  src/config.rs
  src/config/balance_capacity.rs
  src/config/server.rs
  src/middleware.rs
  src/middleware/balance_capacity.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8233 Remove `crates.downloads` column
  migrations/2024-04-12-144026_change-crates-updated-at-trigger/down.sql
  migrations/2024-04-12-144026_change-crates-updated-at-trigger/up.sql
  migrations/2024-04-12-144536_remove-downloads-column/down.sql
  migrations/2024-04-12-144536_remove-downloads-column/up.sql
  src/schema.rs
  src/worker/jobs/dump_db/dump-db.toml
Labels: C-internal 🔧, A-backend ⚙️

#8481 database: Remove obsolete `set_updated_at_ignore_downloads()` fn
  migrations/2024-04-17-083100_remove-obsolete-fn/down.sql
  migrations/2024-04-17-083100_remove-obsolete-fn/up.sql
Labels: C-internal 🔧, A-backend ⚙️

#8486 renovate: Automerge `aws-ip-ranges` and `github-meta` crate updates
  .github/renovate.json5
Labels: C-internal 🔧, A-backend ⚙️

#8490 worker/runner: Remove `tokio` runtime handle parameter
  crates/crates_io_worker/src/runner.rs
  crates/crates_io_worker/tests/runner.rs
  src/bin/background-worker.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8482 Improve "403 Forbidden" error messages
  src/auth.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/metrics.rs
  src/controllers/util.rs
  src/tests/authentication.rs
  src/tests/krate/following.rs
  src/tests/krate/publish/auth.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/routes/me/get.rs
  src/tests/routes/me/tokens/delete_current.rs
  src/tests/routes/users/update.rs
  src/util/errors.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8495 util/tracing: Enable debug tracing by default for tests
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#8496 chaosproxy: Remove internal tokio runtime
  src/tests/server_binary.rs
  src/tests/util/chaosproxy.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8499 tests/krate/publish/max_size: Reduce stack size
  src/tests/krate/publish/max_size.rs
Labels: C-internal 🔧, A-backend ⚙️

#8513 policies: Fix indent of sublist items
  app/templates/policies.hbs
Labels: C-bug 🐞, A-frontend 🐹

#8514 Add test for the `categories.toml` file
  src/tests/categories.rs
Labels: C-internal 🔧, A-backend ⚙️

#8388 Add bioinformatics category and related subcategories
  src/boot/categories.toml
Labels: A-categories

#8531 Fix some typos in comments
  src/controllers/user/me.rs
  src/tests/routes/crates/versions/list.rs
Labels: C-documentation 📜

#8517 storage: Use `Attributes` API to reduce the amount of `ObjectStore` instances
  src/storage.rs
Labels: C-internal 🔧, A-backend ⚙️

#8484 Add `default_versions` database table
  migrations/2024-04-17-135931_default-versions-table/down.sql
  migrations/2024-04-17-135931_default-versions-table/up.sql
  src/admin/delete_version.rs
  src/admin/mod.rs
  src/admin/update_default_versions.rs
  src/admin/yank_version.rs
  src/bin/crates-admin.rs
  src/controllers/krate/publish.rs
  src/controllers/version/yank.rs
  src/models.rs
  src/models/default_versions.rs
  src/schema.rs
  src/sql.rs
  src/sql/semver.rs
  src/tests/schema_details.rs
  src/worker/jobs/dump_db/dump-db.toml
  src/worker/jobs/mod.rs
  src/worker/jobs/update_default_version.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#8553 Footer: Update the team link
  app/components/footer.hbs
Labels: C-bug 🐞, A-frontend 🐹

#8558 Add `os::android-apis` category for Android bindings
  src/boot/categories.toml
Labels: A-categories

#8569 Revert "Fix "Edge for Android" compatibility"
  config/targets.js
Labels: C-enhancement ✨, A-frontend 🐹
