Repository rust-lang/crates.io, pull requests merged in 2024-02, with the labels that each got.

#8036 Implement `ProcessCdnLog` and `ProcessCdnLogQueue` background jobs
  .env.sample
  Cargo.lock
  Cargo.toml
  src/admin/enqueue_job.rs
  src/app.rs
  src/bin/background-worker.rs
  src/config.rs
  src/config/cdn_log_queue.rs
  src/config/cdn_log_storage.rs
  src/config/server.rs
  src/lib.rs
  src/sqs.rs
  src/tests/util/test_app.rs
  src/worker/environment.rs
  src/worker/jobs/downloads.rs
  src/worker/jobs/downloads/fixtures/empty-event.json
  src/worker/jobs/downloads/fixtures/multi-event.json
  src/worker/jobs/downloads/fixtures/valid-event.json
  src/worker/jobs/downloads/message.rs
  src/worker/jobs/downloads/snapshots/crates_io__worker__jobs__downloads__message__tests__parse-2.snap
  src/worker/jobs/downloads/snapshots/crates_io__worker__jobs__downloads__message__tests__parse-3.snap
  src/worker/jobs/downloads/snapshots/crates_io__worker__jobs__downloads__message__tests__parse.snap
  src/worker/jobs/mod.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#8045 env: Remove obsolete `TEST` environment variables
  .env.sample
Labels: C-internal 🔧, A-backend ⚙️

#8046 worker/jobs/downloads: Ignore log files from the index domain
  src/worker/jobs/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#8047 team_repo: Query permission instead of team
  src/team_repo.rs
  src/tests/worker/sync_admins.rs
  src/worker/jobs/sync_admins.rs
Labels: C-internal 🔧, A-backend ⚙️

#8053 Re-introducing improve crates endpoint performance (#7941)
  src/controllers/helpers/pagination.rs
  src/controllers/krate/search.rs
  src/tests/routes/crates/list.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8070 worker/jobs/downloads: Split file into multiple modules
  src/worker/jobs/downloads/mod.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/downloads/queue/fixtures/empty-event.json
  src/worker/jobs/downloads/queue/fixtures/multi-event.json
  src/worker/jobs/downloads/queue/fixtures/valid-event.json
  src/worker/jobs/downloads/queue/job.rs
  src/worker/jobs/downloads/queue/message.rs
  src/worker/jobs/downloads/queue/mod.rs
  src/worker/jobs/downloads/queue/snapshots/crates_io__worker__jobs__downloads__queue__message__tests__parse-2.snap
  src/worker/jobs/downloads/queue/snapshots/crates_io__worker__jobs__downloads__queue__message__tests__parse-3.snap
  src/worker/jobs/downloads/queue/snapshots/crates_io__worker__jobs__downloads__queue__message__tests__parse.snap
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#8056 Reduce versions page load time
  app/components/version-list/row.hbs
  app/controllers/crate/versions.js
  app/models/crate.js
  app/models/version.js
  tests/models/version-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#8072 worker/jobs/downloads/queue: Delete messages *after* processing them
  src/worker/jobs/downloads/queue/job.rs
Labels: C-internal 🔧, A-backend ⚙️

#8079 codecov: Use `informational: true` for `patch` status too
  codecov.yml
Labels: C-internal 🔧

#8082 Remove build metadata within the toml snippet
  app/components/crate-sidebar.js
  tests/components/crate-sidebar/toml-snippet-test.js
Labels: C-bug 🐞, A-frontend 🐹

#8085 Simplify and extend `DownloadMap` API
  Cargo.lock
  crates_io_cdn_logs/Cargo.toml
  crates_io_cdn_logs/examples/count_downloads.rs
  crates_io_cdn_logs/src/download_map.rs
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8086 worker/jobs/downloads/queue: Skip `spawn_blocking()` call if there are no jobs to enqueue
  src/worker/jobs/downloads/queue/job.rs
Labels: C-internal 🔧, A-backend ⚙️

#8087 worker/jobs/downloads/queue: Improve `message_id` logging
  src/sqs.rs
  src/worker/jobs/downloads/queue/job.rs
Labels: C-internal 🔧, A-backend ⚙️

#8089 cdn_logs: Instrument `count_downloads()` fn
  crates_io_cdn_logs/examples/count_downloads.rs
  crates_io_cdn_logs/src/lib.rs
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8090 worker/jobs/downloads/process_log: Avoid unnecessary `Arc<Box<dyn ObjectStore>>`
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8091 worker/jobs/downloads/process_log: Use realistic path for tests
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8092 worker/jobs/downloads/process_log: Split code into more reusable/testable functions
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8093 worker/jobs/downloads/process_log: Instrument `run()` fn
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8094 worker/jobs/downloads/process_log: Improve `build_store()` tests
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8096 Implement writing CDN log counted downloads to the database
  src/config/server.rs
  src/controllers/version/downloads.rs
  src/tests/routes/crates/downloads.rs
  src/tests/util/test_app.rs
  src/worker/jobs/downloads/process_log.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8081 Use `processed_log_files` table to deduplicate log file processing
  migrations/2024-02-07-112955_add_log_files_table/down.sql
  migrations/2024-02-07-112955_add_log_files_table/up.sql
  src/schema.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/dump_db/dump-db.toml
Labels: C-internal 🔧, A-backend ⚙️

#8119 Move `process_cdn_log` background job to a dedicated worker queue
  src/bin/background-worker.rs
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8121 worker: Improve job failure error logging
  crates_io_worker/src/worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#8122 worker/jobs/downloads/process_log: Insert downloads in batches
  src/worker/jobs/downloads/process_log.rs
Labels: C-bug 🐞, A-backend ⚙️

#8131 worker/jobs/downloads/update_metadata: Implement optional batch processing
  src/config/server.rs
  src/tests/util/test_app.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8137 Remove unused dependencies
  Cargo.lock
  Cargo.toml
  crates_io_index/Cargo.toml
  crates_io_tarball/Cargo.toml
  crates_io_worker/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#8127 downloads: Avoid `spawn_blocking()` and database query if `cdn_log_counting_enabled` is set
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#8112 database: Remove unused `index_follows_user_id` index
  migrations/2024-02-12-120203_remove_unused_index/down.sql
  migrations/2024-02-12-120203_remove_unused_index/up.sql
Labels: C-internal 🔧, A-backend ⚙️

#8139 database: Use `CONCURRENTLY IF EXISTS` to drop the `index_follows_user_id` index
  migrations/2024-02-12-120203_remove_unused_index/metadata.toml
  migrations/2024-02-12-120203_remove_unused_index/up.sql
Labels: C-internal 🔧, A-backend ⚙️

#8143 worker/jobs/downloads/update_metadata: Use `SELECT ... FOR UPDATE` in `batch_update()`
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8144 Revert "worker/jobs/downloads/update_metadata: Use `SELECT ... FOR UPDATE` in `batch_update()`"
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8145 worker/jobs/downloads/process_log: Remove unused `RETURNING` expression
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8146 Use a consistent update order for the `version_downloads` table
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8140 CI: Run prettier
  .github/workflows/ci.yml
  crates_io_cdn_logs/README.md
  package.json
  src/worker/jobs/dump_db/readme_for_tarball.md
Labels: C-internal 🔧

#8155 database: Drop `badges` table
  migrations/2024-02-19-113226_delete-badges-table/down.sql
  migrations/2024-02-19-113226_delete-badges-table/up.sql
  src/schema.patch
  src/schema.rs
  src/worker/jobs/dump_db/dump-db.toml
Labels: C-internal 🔧, A-backend ⚙️

#7983 Expand the scope of seek-based pagination on search
  Cargo.lock
  Cargo.toml
  src/controllers/helpers/pagination.rs
  src/controllers/krate/search.rs
  src/tests/routes/crates/list.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8161 components/crate-sidebar: Use `=` prefixes if exact versions are shown
  app/components/crate-sidebar.js
  tests/components/crate-sidebar/toml-snippet-test.js
Labels: C-bug 🐞, A-frontend 🐹

#8165 smoke-test: Check crate file downloads directly from the CDN too
  crates_io_smoke_test/src/api.rs
  crates_io_smoke_test/src/main.rs
Labels: C-internal 🔧

#8166 Replace deprecated `initCustomEvent()` usage
  app/controllers/crate/version.js
Labels: C-bug 🐞, A-frontend 🐹

#8167 Remove obsolete `copy-text-to-clipboard` dependency
  app/components/copy-button.hbs
  app/components/copy-button.js
  app/helpers/is-clipboard-supported.js
  package.json
  pnpm-lock.yaml
Labels: C-enhancement ✨, A-frontend 🐹

#8168 components/crate-sidebar: Allow text selection in install snippets
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
Labels: C-enhancement ✨, A-frontend 🐹

#7361 Mention concerns for "the first person who asks" for ownership transfer
  app/templates/policies.hbs
Labels: C-documentation 📜

#8178 Remove obsolete `PoolError::TestConnectionUnavailable` variant
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8179 db: Extract `ConnectionConfig::apply()` fn
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8181 app: Use let-else to simplify match statements
  src/app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8182 Add async database connection pools based on `deadpool`
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/bin/background-worker.rs
  src/config/database_pools.rs
  src/controllers/team.rs
  src/db.rs
  src/tests/util/test_app.rs
  src/util/errors.rs
  src/worker/environment.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8194 Fix the issue of relevant search not working with spaces in them when using seek pagination
  src/controllers/krate/search.rs
  src/tests/routes/crates/list.rs
Labels: C-bug 🐞, A-backend ⚙️

#8195 Ensure `per_page` query parameter is not less than 1
  src/controllers/helpers/pagination.rs
Labels: C-bug 🐞, A-backend ⚙️

#8200 Remove `BATCH_UPDATE_DOWNLOADS` feature flag
  src/config/server.rs
  src/tests/util/test_app.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️
