Repository rust-lang/crates.io, pull requests merged in 2024-10, with the labels that each got.

#9529 Add a support page
  app/components/crate-sidebar.hbs
  app/components/footer.hbs
  app/components/footer.js
  app/components/support/crate-report-form.hbs
  app/components/support/crate-report-form.js
  app/components/support/crate-report-form.module.css
  app/controllers/support.js
  app/router.js
  app/routes/support.js
  app/services/pristine-query.js
  app/styles/support.module.css
  app/templates/support.hbs
  e2e/acceptance/support.spec.ts
  e2e/routes/support.spec.ts
  playwright.config.ts
  tests/acceptance/support-test.js
  tests/routes/support-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#9557 Add `triagebot` config file
  triagebot.toml
Labels: C-internal 🔧

#9560 tracing: Disable `tokio_postgres` debug logs for tests
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#9564 controllers/token: Replace `BytesRequest` with `Json` extractor
  src/controllers/token.rs
  src/tests/routes/me/tokens/create.rs
Labels: C-internal 🔧, A-backend ⚙️

#9549 Extract `DeleteCrateFromStorage` background job
  src/admin/delete_crate.rs
  src/worker/jobs/delete_crate.rs
  src/worker/jobs/mod.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#9574 controllers/token: Move `name` check outside of `spawn_blocking()` callback
  src/controllers/token.rs
Labels: C-internal 🔧, A-backend ⚙️

#9575 Correct frontend source dir
  docs/FRONTEND.md
Labels: C-documentation 📜

#9551 Move `features` to `feature2` that depend on features that use new feature syntax
  src/models.rs
  src/models/feature.rs
  src/models/krate.rs
  src/models/snapshots/crates_io__models__feature__tests__split_features_clap.snap
  src/models/version.rs
Labels: C-bug 🐞, A-backend ⚙️

#9577 admin/enqueue_job: Add `sync_to_git/sparse_index` subcommands
  src/admin/enqueue_job.rs
Labels: C-internal 🔧, A-backend ⚙️

#9580 models/feature: Add iteration limit warning
  src/models/feature.rs
Labels: C-internal 🔧, A-backend ⚙️

#9578 bin/monitor: Convert to async
  src/bin/monitor.rs
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#9579 bin/crates-admin: Convert to async
  src/admin/default_versions.rs
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/enqueue_job.rs
  src/admin/migrate.rs
  src/admin/populate.rs
  src/admin/render_readmes.rs
  src/admin/test_pagerduty.rs
  src/admin/transfer_crates.rs
  src/admin/upload_index.rs
  src/admin/verify_token.rs
  src/admin/yank_version.rs
  src/bin/crates-admin.rs
Labels: C-internal 🔧, A-backend ⚙️

#9581 admin/on_call: Convert `Event::send()` to async fn
  src/admin/on_call.rs
  src/admin/test_pagerduty.rs
  src/bin/monitor.rs
Labels: C-internal 🔧, A-backend ⚙️

#9582 admin/transfer_crates: Remove unnecessary database transaction
  src/admin/transfer_crates.rs
Labels: C-internal 🔧, A-backend ⚙️

#9584 admin/dialoguer: Remove `.unwrap()` call from `confirm()` fn
  src/admin/delete_crate.rs
  src/admin/delete_version.rs
  src/admin/dialoguer.rs
  src/admin/transfer_crates.rs
  src/admin/upload_index.rs
  src/admin/yank_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9583 admin/populate: Convert to async
  src/admin/populate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9598 admin/delete_version: Reduce `spawn_blocking()` usage
  src/admin/delete_version.rs
  src/admin/dialoguer.rs
Labels: C-internal 🔧, A-backend ⚙️

#9617 admin/delete_crate: Reduce `spawn_blocking()` usage
  src/admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9558 controllers/version/metadata: Simplify `validate_yank_update()` fn
  src/controllers/version/metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#9621 models/default_versions: Fix `conn` argument type
  src/models/default_versions.rs
Labels: C-internal 🔧, A-backend ⚙️

#9620 admin/transfer_crates: Replace `spawn_blocking()` with `diesel_async` usage
  src/admin/transfer_crates.rs
Labels: C-internal 🔧, A-backend ⚙️

#9627 worker: Add `DEDUPLICATED` flag to the `BackgroundJob` trait
  Cargo.lock
  crates/crates_io_worker/Cargo.toml
  crates/crates_io_worker/src/background_job.rs
  crates/crates_io_worker/tests/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#9628 worker/jobs: Use `DEDUPLICATED` for jobs where it makes sense
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/daily_db_maintenance.rs
  src/worker/jobs/delete_crate.rs
  src/worker/jobs/downloads/clean_processed_log_files.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/index/squash.rs
  src/worker/jobs/index/sync.rs
  src/worker/jobs/index_version_downloads_archive/mod.rs
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
  src/worker/jobs/send_publish_notifications.rs
  src/worker/jobs/sync_admins.rs
  src/worker/jobs/typosquat.rs
  src/worker/jobs/update_default_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9630 worker: Extract `enqueue_simple/deduplicated()` fns
  crates/crates_io_worker/src/background_job.rs
Labels: C-internal 🔧, A-backend ⚙️

#9631 worker: Inline `enqueue_with_priority()` fns
  crates/crates_io_worker/src/background_job.rs
Labels: C-internal 🔧, A-backend ⚙️

#9639 Revert "Update Rust crate async-compression to v0.4.14"
  Cargo.lock
  crates/crates_io_cdn_logs/Cargo.toml
Labels: C-bug 🐞, A-backend ⚙️

#9642 Remove `slow-tests` feature
  Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#9644 Remove unused `scheduled-thread-pool` dependency
  Cargo.lock
  Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#9645 worker/jobs/rss: Remove `spawn_blocking()` usage
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
Labels: C-internal 🔧, A-backend ⚙️

#9632 worker: Implement async `enqueue()` fn
  crates/crates_io_worker/src/background_job.rs
  src/admin/delete_crate.rs
  src/admin/enqueue_job.rs
Labels: C-internal 🔧, A-backend ⚙️

#9647 tests/models/krate: Replace `TestApp` usage with `TestDatabase`
  src/tests/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9649 Move `split_features()` fn into `crates_io_index` crate
  Cargo.lock
  crates/crates_io_index/Cargo.toml
  crates/crates_io_index/data.rs
  crates/crates_io_index/features.rs
  crates/crates_io_index/lib.rs
  crates/crates_io_index/snapshots/crates_io_index__features__tests__split_features_clap.snap
  src/models.rs
  src/models/krate.rs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9651 Extract `index` module
  src/index.rs
  src/lib.rs
  src/models/krate.rs
  src/snapshots/crates_io__index__tests__index_metadata-2.snap
  src/snapshots/crates_io__index__tests__index_metadata.snap
  src/tests/mod.rs
  src/tests/models/krate.rs
  src/tests/models/mod.rs
  src/worker/jobs/index/sync.rs
Labels: C-internal 🔧, A-backend ⚙️

#9650 index/features: Simplify `split_features()` fn
  crates/crates_io_index/features.rs
Labels: C-internal 🔧, A-backend ⚙️

#9652 index: Convert `get_index_data()` fn to async
  src/index.rs
  src/worker/jobs/index/sync.rs
Labels: C-internal 🔧, A-backend ⚙️

#9653 worker/jobs/daily_db_maintenance: Remove `spawn_blocking()` usage
  src/worker/jobs/daily_db_maintenance.rs
Labels: C-internal 🔧, A-backend ⚙️

#9654 worker/jobs/sync_admins: Reduce `spawn_blocking()` usage
  src/worker/jobs/sync_admins.rs
Labels: C-internal 🔧, A-backend ⚙️

#9655 admin/yank_version: Remove `spawn_blocking()` usage
  src/admin/yank_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9662 Extract `tests::util::github::next_gh_id()` fn
  src/lib.rs
  src/tests/mod.rs
  src/tests/util.rs
  src/tests/util/github.rs
  src/typosquat/test_util.rs
Labels: C-internal 🔧, A-backend ⚙️

#9666 tests/util/test_app: Simplify `db_new_user()` fn
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#9643 Remove CI system detection
  .github/renovate.json5
  Cargo.lock
  Cargo.toml
  src/ci.rs
  src/lib.rs
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#9665 typosquat/test_util: Simplify `Faker`
  src/typosquat/database.rs
  src/typosquat/test_util.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#9674 Fix "unconfigured TLS" panic in `db::oneoff_async_connection()` fn
  src/db.rs
Labels: C-bug 🐞, A-backend ⚙️

#9648 Extract `crates_io_database` crate
  Cargo.lock
  Cargo.toml
  crates/crates_io_database/Cargo.toml
  crates/crates_io_database/src/lib.rs
  crates/crates_io_database/src/schema.patch
  crates/crates_io_database/src/schema.rs
  diesel.toml
  src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#9687 worker: Adjust "Failed to run job" error logging
  crates/crates_io_worker/src/worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#9686 models/team: Replace `String` with `&str` for `NewTeam` struct fields
  src/models/team.rs
  src/typosquat/test_util.rs
Labels: C-internal 🔧, A-backend ⚙️

#9697 models/version: Replace `String` with `&str` for `NewVersion` struct fields
  src/controllers/krate/publish.rs
  src/models/version.rs
  src/tests/builders/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9698 worker/jobs/downloads/queue: Remove `spawn_blocking()` usage
  src/worker/jobs/downloads/queue/job.rs
Labels: C-internal 🔧, A-backend ⚙️

#9699 worker/jobs/archive_version_downloads: Reduce `spawn_blocking()` usage
  src/worker/jobs/archive_version_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#9702 Extract `crates_io_team_repo` crate
  Cargo.lock
  Cargo.toml
  crates/crates_io_team_repo/Cargo.toml
  crates/crates_io_team_repo/examples/basic.rs
  crates/crates_io_team_repo/src/certs.rs
  crates/crates_io_team_repo/src/isrg-root-x1.pem
  crates/crates_io_team_repo/src/isrg-root-x2.pem
  crates/crates_io_team_repo/src/lib.rs
  src/bin/background-worker.rs
  src/certs/mod.rs
  src/lib.rs
  src/tests/util/test_app.rs
  src/tests/worker/sync_admins.rs
  src/worker/environment.rs
Labels: C-internal 🔧, A-backend ⚙️

#9703 tests/builders/version: Simplify code by adding fields to `NewVersion` struct
  src/models/version.rs
  src/tests/builders/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9708 tracing: Use `json-subscriber` crate for JSON logging
  Cargo.lock
  Cargo.toml
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#9624 Add `release_tracks` meta to pagination versions
  src/controllers/krate/versions.rs
  src/tests/routes/crates/versions/list.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9709 controllers/krate/search: Add some type aliases
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️

#9712 Replace `derive_builder` with `bon`
  Cargo.lock
  Cargo.toml
  src/bin/background-worker.rs
  src/controllers/krate/publish.rs
  src/models/version.rs
  src/tests/builders/version.rs
  src/tests/util/test_app.rs
  src/typosquat/test_util.rs
  src/worker/environment.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#9721 tests/schema_details: Move into `crates_io_database` crate
  Cargo.lock
  crates/crates_io_database/Cargo.toml
  crates/crates_io_database/tests/load_foreign_key_constraints.sql
  crates/crates_io_database/tests/schema_details.rs
  src/tests/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#9715 Inline `NewCategory::create_or_update()`
  src/models/category.rs
  src/tests/krate/publish/categories.rs
  src/tests/routes/categories/get.rs
  src/tests/routes/categories/list.rs
  src/tests/routes/category_slugs/list.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/summary.rs
Labels: C-internal 🔧, A-backend ⚙️

#9723 models/default_version: Implement `Ord` for `Version`
  src/models/default_versions.rs
Labels: C-internal 🔧, A-backend ⚙️

#9722 `default_version` for publish
  src/controllers/krate/publish.rs
  src/models.rs
  src/models/default_versions.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9726 worker/jobs/index/sync: Fix `krate.name` logging
  src/worker/jobs/index/sync.rs
Labels: C-internal 🔧, A-backend ⚙️

#9731 worker/jobs/archive_version_downloads: Simplify function arguments
  src/worker/jobs/archive_version_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#9735 Migrate tests from sync to async database connection
  src/tests/account_lock.rs
  src/tests/github_secret_scanning.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/categories.rs
  src/tests/krate/publish/emails.rs
  src/tests/krate/publish/rate_limit.rs
  src/tests/krate/publish/timestamps.rs
  src/tests/krate/yanking.rs
  src/tests/routes/categories/list.rs
  src/tests/routes/category_slugs/list.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/tokens/delete.rs
  src/tests/routes/me/tokens/delete_current.rs
  src/tests/token.rs
  src/tests/util/test_app.rs
  src/tests/worker/git.rs
  src/tests/worker/rss/sync_crate_feed.rs
  src/tests/worker/rss/sync_crates_feed.rs
  src/tests/worker/rss/sync_updates_feed.rs
  src/tests/worker/sync_admins.rs
Labels: C-internal 🔧, A-backend ⚙️

#9734 Replace `&Crate` arguments with `crate_id: i32`
  src/controllers/krate/publish.rs
  src/models/category.rs
  src/models/keyword.rs
  src/tests/builders/krate.rs
  src/tests/routes/categories/get.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/keywords/read.rs
Labels: C-internal 🔧, A-backend ⚙️

#9737 Avoid unnecessary allocations
  src/controllers/krate/metadata.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/summary.rs
  src/controllers/user/me.rs
  src/models/action.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9736 admin/delete_crate: Improve crate listing
  Cargo.lock
  Cargo.toml
  src/admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9764 Fix the broken entrypoint for frontend service
  docker-compose.yml
  package.json
Labels: C-internal 🔧

#9755 views: Remove `badges` arguments from `EncodableCrate` constructors
  src/controllers/krate/metadata.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/summary.rs
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_twice.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_twice_alt.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_weird_version.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate_with_token.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_1.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_2.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__build_metadata__version_with_build_metadata@build_metadata_3.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__categories__good_categories.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__dependencies__dep_limit-2.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__keywords__good_keywords.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__links__crate_with_links_field.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__boolean_readme.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__lib_and_bin_crate.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__max_size__tarball_between_default_axum_limit_and_max_upload_size.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_empty_readme.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_readme.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__readme__new_krate_with_readme_and_plus_version.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__new_name.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show_minimal.snap
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#9766 database: Add `versions.num_no_build` column
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
  migrations/2024-10-24-133507_add-num-no-build-column/down.sql
  migrations/2024-10-24-133507_add-num-no-build-column/up.sql
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9767 database: Change `num_no_build` to be `NOT NULL`
  crates/crates_io_database/src/schema.rs
  migrations/2024-10-24-134209_make-unique-num-not-null/down.sql
  migrations/2024-10-24-134209_make-unique-num-not-null/up.sql
  src/models/default_versions.rs
  src/models/version.rs
  src/tests/worker/rss/sync_crate_feed.rs
  src/tests/worker/rss/sync_updates_feed.rs
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
Labels: C-internal 🔧, A-backend ⚙️

#9768 diesel: Replace `all_columns` with `as_select()`
  src/admin/render_readmes.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/versions.rs
  src/controllers/user/me.rs
  src/index.rs
  src/models.rs
  src/models/category.rs
  src/models/dependency.rs
  src/models/keyword.rs
  src/models/krate.rs
  src/models/team.rs
  src/models/user.rs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9777 CI: Run only frontend jobs for changes in the `e2e` folder
  .github/workflows/ci.yml
Labels: C-internal 🔧

#9783 models/category: Convert to async/await
  src/controllers/category.rs
  src/controllers/summary.rs
  src/models/category.rs
Labels: C-internal 🔧, A-backend ⚙️

#9784 worker/jobs/downloads: Remove `spawn_blocking()` usage
  src/worker/jobs/downloads/clean_processed_log_files.rs
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#9786 Exclude num_no_build from versions.csv db-dump
  crates/crates_io_database_dump/src/dump-db.toml
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
Labels: A-backend ⚙️

#9785 worker: Remove `spawn_blocking()` usage
  crates/crates_io_worker/src/runner.rs
  crates/crates_io_worker/src/storage.rs
  crates/crates_io_worker/src/worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#9788 mirage: Fix yank/unyank route handlers
  mirage/route-handlers/crates.js
  tests/mirage/crates/versions/yank/unyank-test.js
  tests/mirage/crates/versions/yank/yank-test.js
Labels: A-frontend 🐹, C-internal 🔧

#9789 mirage: Add `yank_message` to `version` factory and serializer
  mirage/factories/version.js
  mirage/serializers/version.js
  tests/mirage/crates/get-by-id-test.js
  tests/mirage/crates/reverse-dependencies-test.js
  tests/mirage/crates/versions/list-test.js
  tests/mirage/me/updates/list-test.js
Labels: A-frontend 🐹, C-internal 🔧

#9791 mirage: Implement `PATCH /crates/:name/:version` route handler
  mirage/route-handlers/crates.js
  tests/mirage/crates/versions/patch-test.js
  tests/mirage/crates/versions/yank/unyank-test.js
Labels: A-frontend 🐹, C-internal 🔧

#9798 mirage: Fix `PUT /api/v1/crates/:name/owners` implementation
  mirage/route-handlers/crates.js
  tests/adapters/crate-test.js
  tests/helpers/index.js
  tests/mirage/crates/add-owner-test.js
  tests/models/crate-test.js
  tests/models/version-test.js
  tests/services/playground-test.js
Labels: A-frontend 🐹, C-internal 🔧

#9765 Migrate the frontend to use the new yank API
  app/adapters/version.js
  app/models/version.js
  e2e/acceptance/sudo.spec.ts
  tests/acceptance/sudo-test.js
Labels: C-enhancement ✨, A-frontend 🐹
