Repository rust-lang/crates.io, pull requests merged in 2024-09, with the labels that each got.

#9377 controllers/user: Move `PUT /user/:user_id` endpoints to a dedicated module
  src/controllers/user.rs
  src/controllers/user/me.rs
  src/controllers/user/update.rs
  src/models/user.rs
  src/router.rs
Labels: C-internal 🔧, A-backend ⚙️

#9378 user/update: Use `axum::Json` extractor
  src/controllers/user/update.rs
  src/tests/routes/users/update.rs
Labels: C-internal 🔧, A-backend ⚙️

#9396 FeedId: Remove unnecessary allocations
  src/admin/delete_crate.rs
  src/storage.rs
  src/worker/jobs/rss/sync_crate_feed.rs
Labels: C-internal 🔧, A-backend ⚙️

#9405 smoke_test: Run `git commit` to work around cargo bug
  crates/crates_io_smoke_test/src/cargo.rs
  crates/crates_io_smoke_test/src/git.rs
  crates/crates_io_smoke_test/src/main.rs
Labels: C-internal 🔧, A-backend ⚙️

#9406 smoke_test: Set git username and email before committing
  crates/crates_io_smoke_test/src/git.rs
  crates/crates_io_smoke_test/src/main.rs
Labels: C-internal 🔧, A-backend ⚙️

#9408 docs: add downloads archive `version_id` explanation
  src/worker/jobs/index_version_downloads_archive/index.html.j2
  src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__generate_html.snap
  src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__generate_html_empty.snap
  src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__template_context.snap
Labels: C-enhancement ✨, A-backend ⚙️

#9414 Change default API token expiration to 90 days
  app/controllers/settings/tokens/new.js
  app/templates/settings/tokens/new.hbs
  e2e/routes/settings/tokens/new.spec.ts
  tests/routes/settings/tokens/new-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#9437 Add `yank_message` field to API version responses
  src/tests/krate/publish/snapshots/all__krate__publish__links__crate_with_links_field-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__manifest__boolean_readme-2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__manifest__lib_and_bin_crate-2.snap
  src/tests/routes/crates/snapshots/all__routes__crates__read__show.snap
  src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__prerelease_versions_not_included_in_reverse_dependencies.snap
  src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies.snap
  src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_includes_published_by_user_when_present.snap
  src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_query_supports_u64_version_number_parts.snap
  src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__reverse_dependencies_when_old_version_doesnt_depend_but_new_does.snap
  src/tests/routes/crates/snapshots/all__routes__crates__reverse_dependencies__yanked_versions_not_included_in_reverse_dependencies.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__list__versions.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_semver_no_published_by.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__read__show_by_crate_name_and_version.snap
  src/views.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9445 Fix display for text in new token page
  app/styles/settings/tokens/new.module.css
  app/templates/settings/tokens/new.hbs
Labels: C-bug 🐞, A-frontend 🐹

#9461 footer: Move Zulip link above X/Twitter
  app/components/footer.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#9473 search: check for null bytes before querying
  src/controllers/krate/search.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-2.snap
  src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-3.snap
  src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-4.snap
  src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes-5.snap
  src/tests/routes/crates/snapshots/all__routes__crates__list__invalid_params_with_null_bytes.snap
Labels: C-bug 🐞, A-backend ⚙️

#9489 Update `tower` and `axum` dependencies
  Cargo.lock
  Cargo.toml
Labels: A-backend ⚙️

#9503 Add CORS tests
  src/config/server.rs
  src/tests/all.rs
  src/tests/cors.rs
  src/tests/util/mock_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#9506 insta: Update outdated `expression` fields in snapshots
  src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate.snap
  src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate_twice.snap
  src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate_weird_version.snap
  src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate_with_token.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_1.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_2.snap
  src/tests/krate/publish/snapshots/all__krate__publish__build_metadata__version_with_build_metadata@build_metadata_3.snap
  src/tests/krate/publish/snapshots/all__krate__publish__categories__good_categories.snap
  src/tests/krate/publish/snapshots/all__krate__publish__keywords__good_keywords.snap
  src/tests/krate/publish/snapshots/all__krate__publish__manifest__boolean_readme.snap
  src/tests/krate/publish/snapshots/all__krate__publish__max_size__tarball_between_default_axum_limit_and_max_upload_size.snap
  src/tests/krate/publish/snapshots/all__krate__publish__readme__new_krate_with_empty_readme.snap
  src/tests/krate/publish/snapshots/all__krate__publish__readme__new_krate_with_readme.snap
  src/tests/krate/publish/snapshots/all__krate__publish__readme__new_krate_with_readme_and_plus_version.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__list__list_tokens.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_revoked_token.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_for_unknown_token.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token.snap
  src/tests/snapshots/all__read_only_mode__cannot_hit_endpoint_which_writes_db_in_read_only_mode.snap
  src/tests/snapshots/all__server__user_agent_is_required-2.snap
  src/tests/snapshots/all__server__user_agent_is_required.snap
Labels: C-internal 🔧, A-backend ⚙️

#9519 admin/delete_crate: Improve logging output
  src/admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9530 Change crates.io policy to not offer crate transfer mediation
  app/templates/policies/index.hbs
Labels: C-documentation 📜
