Repository rust-lang/crates.io, pull requests merged in 2024-08, with the labels that each got.

#9206 Unify CDN invalidation into a single method on `Environment`
  src/worker/environment.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
Labels: C-internal 🔧, A-backend ⚙️

#9236 docs: Remove deprecated lines from ARCHITECTURE.md#Backend
  docs/ARCHITECTURE.md
Labels: C-documentation 📜

#9246 Don't read .psqlrc for automated DB export
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#9245 Add API token creation notifications
  src/controllers/token.rs
  src/tests/routes/me/tokens/create.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9295 storage: Adjust content types for version downloads archive files
  src/storage.rs
Labels: C-bug 🐞, A-backend ⚙️

#9274 database: Add `versions.yank_message` column
  migrations/2024-08-17-152408_add-yank-message/down.sql
  migrations/2024-08-17-152408_add-yank-message/up.sql
  src/models/version.rs
  src/schema.rs
  src/worker/jobs/dump_db/dump-db.toml
Labels: C-enhancement ✨, A-backend ⚙️

#9301 fix: send co-owner invite emails after txn commit
  src/controllers/krate/owners.rs
  src/models/krate.rs
  src/tests/routes/crates/owners/add.rs
Labels: C-bug 🐞, A-backend ⚙️

#9306 styles: Fix button text color when hovering
  app/styles/shared/buttons.module.css
Labels: C-bug 🐞, A-frontend 🐹

#9310 models/user: Move `impl` block closer to the `struct`
  src/models/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#9311 Remove controller preludes
  src/controllers.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/helpers.rs
  src/controllers/helpers/pagination.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/metrics.rs
  src/controllers/summary.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/util.rs
  src/controllers/version.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/util/request_helpers.rs
Labels: C-internal 🔧, A-backend ⚙️

#9307 Add a "Report crate" button
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/styles/shared/buttons.module.css
Labels: C-enhancement ✨, A-frontend 🐹

#9322 test: generate per-user email
  src/tests/krate/publish/basics.rs
  src/tests/routes/me/snapshots/all__routes__me__get__me-2.snap
  src/tests/routes/me/snapshots/all__routes__me__get__me-3.snap
  src/tests/user.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#9324 tests: Extract `TestApp::emails()` and `TestApp::emails_snapshot()` fns
  src/tests/github_secret_scanning.rs
  src/tests/owners.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes-2.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap
  src/tests/util/test_app.rs
  src/tests/worker/snapshots/all__worker__sync_admins__sync_admins_job.snap
  src/tests/worker/sync_admins.rs
Labels: C-internal 🔧, A-backend ⚙️

#9327 github/secret_scanning: Fix email formatting
  src/controllers/github/secret_scanning.rs
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap
Labels: C-bug 🐞, A-backend ⚙️

#9328 Use dynamic email subjects where useful
  src/controllers/github/secret_scanning.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/email.rs
  src/models/krate.rs
  src/tests/owners.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes-2.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/sync_admins.rs
  src/worker/jobs/typosquat.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9340 tests/owners: Add invite email snapshot assertions
  src/tests/owners.rs
  src/tests/snapshots/all__owners__modify_multiple_owners-2.snap
  src/tests/snapshots/all__owners__modify_multiple_owners.snap
  src/tests/snapshots/all__owners__new_crate_owner.snap
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#9342 email: Change `from` to `crates.io <no-reply@crates.io>`
  src/email.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_success-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_expiry_date-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_null_scopes-2.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__create__create_token_with_scopes-2.snap
  src/tests/snapshots/all__github_secret_scanning__github_secret_alert_revokes_token-2.snap
  src/tests/snapshots/all__owners__modify_multiple_owners-2.snap
  src/tests/snapshots/all__owners__modify_multiple_owners.snap
  src/tests/snapshots/all__owners__new_crate_owner.snap
  src/tests/worker/snapshots/all__worker__sync_admins__sync_admins_job.snap
Labels: C-enhancement ✨, A-backend ⚙️

#9345 Fix links without href being hard to read on dark theme
  app/styles/application.module.css
Labels: C-bug 🐞, A-frontend 🐹

#9341 Implement publish notification emails
  src/controllers/krate/publish.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/emails.rs
  src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate-4.snap
  src/tests/owners.rs
  src/tests/snapshots/all__owners__new_crate_owner-2.snap
  src/tests/snapshots/all__owners__new_crate_owner.snap
  src/tests/snapshots/all__team__publish_owned.snap
  src/tests/team.rs
  src/tests/util/test_app.rs
  src/worker/jobs/mod.rs
  src/worker/jobs/send_publish_notifications.rs
  src/worker/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9356 Fix broken snapshots
  src/tests/krate/publish/snapshots/all__krate__publish__basics__new_krate-4.snap
  src/tests/snapshots/all__owners__new_crate_owner-2.snap
  src/tests/snapshots/all__owners__new_crate_owner.snap
  src/tests/snapshots/all__team__publish_owned.snap
Labels: C-internal 🔧, A-backend ⚙️

#9357 jobs/send_publish_notifications: Add logging calls
  src/worker/jobs/send_publish_notifications.rs
Labels: C-internal 🔧, A-backend ⚙️

#9360 jobs/send_publish_notifications: Skip `spawn_blocking()` call if no valid recipients are found
  src/worker/jobs/send_publish_notifications.rs
Labels: C-internal 🔧, A-backend ⚙️

#9361 dump-db: Remove `version_downloads` export filter
  src/tests/snapshots/all__dump_db__sql_scripts@export.sql.snap
  src/worker/jobs/dump_db/dump-db.toml
Labels: C-internal 🔧, A-backend ⚙️

#9366 user/me: Remove unnecessary `transaction()` call
  src/controllers/user/me.rs
Labels: C-internal 🔧, A-backend ⚙️

#9367 tests/users/update: Remove obsolete parts of the payload
  src/tests/routes/users/update.rs
Labels: C-internal 🔧, A-backend ⚙️

#9332 refactor: separate `Crate::owner_add` model concerns
  src/controllers/krate/owners.rs
  src/models/krate.rs
  src/tests/owners.rs
Labels: C-internal 🔧, A-backend ⚙️
