Repository rust-lang/crates.io, pull requests merged in 2024-03, with the labels that each got.

#8214 Rewrite the README document
  README.md
  docs/categories.md
  docs/readme-logo-dark.png
  docs/readme-logo.png
Labels: C-documentation 📜

#8037 Add basic support for seek-based pagination to versions endpoint
  src/controllers/krate.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/versions.rs
  src/router.rs
  src/tests/routes/crates/versions/list.rs
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__list__invalid_seek_parameter-2.snap
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__list__invalid_seek_parameter.snap
Labels: C-enhancement ✨, A-backend ⚙️

#8218 Disable `download_counter_thread` if CDN log download counting is enabled
  src/bin/server.rs
Labels: C-internal 🔧, A-backend ⚙️

#8210 Add sudo mode for admins
  app/components/header.hbs
  app/components/header.js
  app/components/header.module.css
  app/components/privileged-action.hbs
  app/components/privileged-action.js
  app/components/privileged-action.module.css
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/services/session.js
  tests/components/privileged-action-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#8235 controllers/util: Remove unused `extensions_mut()` fn
  src/controllers/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#8232 Extract `crate_downloads` table
  migrations/2024-03-04-092044_crate-downloads-table/down.sql
  migrations/2024-03-04-092044_crate-downloads-table/up.sql
  src/schema.patch
  src/schema.rs
  src/tests/builders/krate.rs
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/dump_db/dump-db.toml
Labels: C-internal 🔧, A-backend ⚙️

#8242 database: Add index on `crate_downloads` table
  migrations/2024-03-05-120032_add-crate-downloads-index/down.sql
  migrations/2024-03-05-120032_add-crate-downloads-index/metadata.toml
  migrations/2024-03-05-120032_add-crate-downloads-index/up.sql
Labels: C-enhancement ✨, A-backend ⚙️

#8237 Add sudo mode acceptance tests, per #8210 feedback
  app/components/header.hbs
  app/components/privileged-action.hbs
  tests/acceptance/sudo-test.js
Labels: A-frontend 🐹, C-internal 🔧

#8244 controllers/krate/search: Read downloads from `crate_downloads` table
  src/controllers/krate/metadata.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/summary.rs
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#8251 typosquat/database: Sort by downloads from `crate_downloads` table
  src/typosquat/database.rs
  src/typosquat/test_util.rs
Labels: C-internal 🔧, A-backend ⚙️

#8254 controllers/krate/publish: Read downloads from `crate_downloads` table
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#8249 controllers/summary: Read downloads from `crate_downloads` table
  src/controllers/summary.rs
Labels: C-internal 🔧, A-backend ⚙️

#8250 controllers/user/other: Read downloads from `crate_downloads` table
  Cargo.lock
  Cargo.toml
  src/controllers/user/other.rs
  src/tests/routes/users/stats.rs
Labels: C-internal 🔧, A-backend ⚙️

#8252 models/krate_reverse_dependencies.sql: Read downloads from `crate_downloads` table
  src/models/dependency.rs
  src/models/krate_reverse_dependencies.sql
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#8253 controllers/krate/metadata: Read downloads from `crate_downloads` table
  src/controllers/krate/metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8260 Convert seek to named fields
  src/controllers/helpers/pagination.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
Labels: C-internal 🔧, A-backend ⚙️

#8262 opensearch: Adjust search engine name and description
  public/opensearch.xml
Labels: C-bug 🐞

#8277 controllers/helpers/pagination: Return errors early to reduce indentation levels
  src/controllers/helpers/pagination.rs
Labels: C-internal 🔧, A-backend ⚙️

#8289 CI: Fix `changed-files` job
  .github/workflows/ci.yml
Labels: C-internal 🔧

#8288 index: Fix broken `git reset --hard`
  crates/crates_io_index/repo.rs
  crates/crates_io_index/testing.rs
  src/tests/worker/git.rs
Labels: C-bug 🐞, A-backend ⚙️

#8278 Add `clean_processed_log_files` background job
  src/admin/enqueue_job.rs
  src/worker/jobs/downloads/clean_processed_log_files.rs
  src/worker/jobs/downloads/mod.rs
  src/worker/jobs/mod.rs
  src/worker/mod.rs
Labels: C-internal 🔧, A-backend ⚙️

#8295 worker/jobs/downloads/update_metadata: Remove `crates.downloads` column writes
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8294 Remove `CDN_LOG_COUNTING_ENABLED` feature flag and related code
  Cargo.lock
  Cargo.toml
  src/app.rs
  src/bin/server.rs
  src/config/server.rs
  src/controllers/version/downloads.rs
  src/downloads_counter.rs
  src/lib.rs
  src/metrics/instance.rs
  src/tests/routes/crates/downloads.rs
  src/tests/routes/crates/versions/download.rs
  src/tests/unhealthy_database.rs
  src/tests/util/test_app.rs
  src/worker/jobs/downloads/process_log.rs
Labels: C-internal 🔧, A-backend ⚙️

#8305 cdn_logs/paths: Add support for `/:crate/:version/download` URLs
  crates/crates_io_cdn_logs/src/paths.rs
Labels: C-bug 🐞, A-backend ⚙️

#8334 chore: fix some comments
  app/modifiers/render-mermaids.js
  deny.toml
  docs/CONTRIBUTING.md
  src/tests/routes/crates/versions/list.rs
Labels: C-documentation 📜

#8362 cargo-deny: Migrate to advisories & licenses v2 config
  deny.toml
Labels: C-internal 🔧, A-backend ⚙️

#8377 controllers/version/downloads: Remove unused `get_version_id()` fn
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#8379 Revert "tests: Use `tracing::subscriber::DefaultGuard` to set subscriber (#8023)"
  src/tests/dump_db.rs
  src/tests/util/test_app.rs
  src/util/tracing.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/downloads/queue/job.rs
Labels: C-internal 🔧, A-backend ⚙️

#8382 tests: Explicitly close async database pools within the context of a tokio runtime
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8381 tests: Reduce pool sizes
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#8384 worker: Inline `connection()` fn
  crates/crates_io_worker/src/runner.rs
Labels: C-internal 🔧, A-backend ⚙️
