Repository rust-lang/crates.io, pull requests merged in 2024-05, with the labels that each got.

#8566 Support typing '/' to search
  app/components/search-form.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#8582 CI: Replace Docker-based PostgreSQL server with `apt-get` install
  .github/workflows/ci.yml
Labels: C-internal 🔧, A-backend ⚙️

#8593 Improve GitHub team error message, and link to docs.
  src/models/team.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/team.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8594 worker/jobs/downloads: Extract long query into SQL file
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/downloads/update_metadata.sql
Labels: C-internal 🔧, A-backend ⚙️

#8596 Implement `ArchiveVersionDownloads` background job
  .env.sample
  Cargo.lock
  Cargo.toml
  src/admin/enqueue_job.rs
  src/bin/background-worker.rs
  src/worker/environment.rs
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/mod.rs
  src/worker/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8640 Revert "Merge pull request #8610 from rust-lang/renovate/aws-sdk-rust-monorepo"
  Cargo.lock
  Cargo.toml
  src/cloudfront.rs
  src/sqs.rs
Labels: C-bug 🐞, A-backend ⚙️

#8643 Sentry: Fix broken `configureScope()` call
  app/routes/application.js
  app/services/sentry.js
  tests/helpers/sentry.js
Labels: C-bug 🐞, A-backend ⚙️

#8644 Revert "Update sentry-javascript monorepo to v8 (major)"
  package.json
  pnpm-lock.yaml
Labels: C-bug 🐞, A-frontend 🐹

#8649 Remove/replace references to the "crawler policy"
  app/templates/data-access.hbs
  src/middleware/block_traffic.rs
  src/tests/snapshots/all__server__block_traffic_via_arbitrary_header_and_value.snap
  src/tests/snapshots/all__server__block_traffic_via_ip.snap
Labels: C-documentation 📜

#8290 Send API token expiry notification emails
  migrations/2024-03-06-123525_add_expiry_notification_at/down.sql
  migrations/2024-03-06-123525_add_expiry_notification_at/up.sql
  src/admin/enqueue_job.rs
  src/schema.rs
  src/worker/jobs/dump_db/dump-db.toml
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/mod.rs
  src/worker/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8656 worker/jobs/expiry_notification: Adjust `JOB_NAME` to match struct name
  src/worker/jobs/expiry_notification.rs
Labels: C-internal 🔧, A-backend ⚙️

#8657 worker/jobs/expiry_notification: Add more logging statements
  src/worker/jobs/expiry_notification.rs
Labels: C-internal 🔧, A-backend ⚙️

#8658 worker/jobs/expiry_notification: Reduce log level for missing email addresses
  src/worker/jobs/expiry_notification.rs
Labels: C-internal 🔧, A-backend ⚙️

#8559 Implement dark mode via `light-dark()` fn
  app/components/color-scheme-menu.hbs
  app/components/color-scheme-menu.js
  app/components/color-scheme-menu.module.css
  app/components/crate-downloads-list.module.css
  app/components/crate-row.module.css
  app/components/crate-sidebar.module.css
  app/components/dependency-list/row.module.css
  app/components/dropdown/menu.module.css
  app/components/dropdown/trigger.hbs
  app/components/front-page-list/item.module.css
  app/components/front-page-list/item/placeholder.module.css
  app/components/header.hbs
  app/components/header.module.css
  app/components/pagination.module.css
  app/components/rev-dep-row.module.css
  app/components/search-form.module.css
  app/components/settings/api-tokens.module.css
  app/components/side-menu/item.module.css
  app/components/text-content.module.css
  app/components/version-list/row.module.css
  app/controllers/application.js
  app/helpers/set-color-scheme.js
  app/services/color-scheme.js
  app/styles/application.module.css
  app/styles/categories.module.css
  app/styles/category/index.module.css
  app/styles/crate/settings.module.css
  app/styles/crate/version.module.css
  app/styles/dashboard.module.css
  app/styles/keywords.module.css
  app/styles/me/pending-invites.module.css
  app/styles/settings/appearance.module.css
  app/styles/settings/tokens/new.module.css
  app/templates/application.hbs
  public/assets/color-mode.svg
  public/assets/moon.svg
  public/assets/sun.svg
Labels: C-enhancement ✨, A-frontend 🐹

#8672 styles/category-slugs: Fix dark-mode styling
  app/styles/category-slugs.module.css
Labels: C-bug 🐞, A-frontend 🐹

#8678 components/search-form: Work around gap between focus shadow and submit button
  app/components/search-form.module.css
Labels: C-bug 🐞, A-frontend 🐹

#8680 Implement dark mode for syntax highlighted code blocks
  app/components/text-content.module.css
  app/modifiers/highlight-syntax.js
Labels: C-bug 🐞, A-frontend 🐹

#8696 Switch default color scheme to "System"
  app/services/color-scheme.js
Labels: C-enhancement ✨, A-frontend 🐹

#8697 Remove obsolete "Appearance" settings page
  app/components/footer.module.css
  app/components/settings-page.hbs
  app/components/settings-page.js
  app/controllers/application.js
  app/controllers/settings/appearance.js
  app/router.js
  app/services/design.js
  app/styles/application.module.css
  app/templates/application.hbs
  app/templates/settings/appearance.hbs
Labels: A-frontend 🐹, C-internal 🔧

#8521 Add e2e tests with Playwright
  .editorconfig
  .gitignore
  app/consts.js
  app/initializers/app-hook.js
  e2e/.gitkeep
  e2e/README.md
  e2e/acceptance/404.spec.ts
  e2e/acceptance/api-token.spec.ts
  e2e/acceptance/categories.spec.ts
  e2e/acceptance/crate-dependencies.spec.ts
  e2e/acceptance/crate-following.spec.ts
  e2e/acceptance/crate-navtabs.spec.ts
  e2e/acceptance/crate.spec.ts
  e2e/acceptance/crates.spec.ts
  e2e/acceptance/dashboard.spec.ts
  e2e/acceptance/email-change.spec.ts
  e2e/acceptance/email-confirmation.spec.ts
  e2e/acceptance/front-page.spec.ts
  e2e/acceptance/invites.spec.ts
  e2e/acceptance/keyword.spec.ts
  e2e/acceptance/login.spec.ts
  e2e/acceptance/logout.spec.ts
  e2e/acceptance/read-only-mode.spec.ts
  e2e/acceptance/readme-rendering.spec.ts
  e2e/acceptance/reverse-dependencies.spec.ts
  e2e/acceptance/search.spec.ts
  e2e/acceptance/settings/add-owner.spec.ts
  e2e/acceptance/settings/remove-owner.spec.ts
  e2e/acceptance/settings/settings.spec.ts
  e2e/acceptance/sudo.spec.ts
  e2e/acceptance/team-page.spec.ts
  e2e/acceptance/token-invites.spec.ts
  e2e/acceptance/user-page.spec.ts
  e2e/acceptance/versions.spec.ts
  e2e/bugs/2329.spec.ts
  e2e/bugs/4506.spec.ts
  e2e/fixtures/a11y.ts
  e2e/fixtures/ember.ts
  e2e/fixtures/fake-timers.ts
  e2e/fixtures/mirage.ts
  e2e/fixtures/percy.ts
  e2e/helper.ts
  e2e/routes/category.spec.ts
  e2e/routes/crate/range.spec.ts
  e2e/routes/crate/version/crate-links.spec.ts
  e2e/routes/crate/version/docs-link.spec.ts
  e2e/routes/crate/version/model.spec.ts
  e2e/routes/keyword.spec.ts
  e2e/routes/settings/tokens/index.spec.ts
  e2e/routes/settings/tokens/new.spec.ts
  e2e/tsconfig.json
  mirage/config.js
  package.json
  playwright.config.ts
  pnpm-lock.yaml
  tests/helpers/sentry.js
Labels: A-frontend 🐹, C-internal 🔧

#8703 admin/default_versions: Implement `verify` mode
  src/admin/default_versions.rs
  src/admin/mod.rs
  src/bin/crates-admin.rs
  src/models.rs
  src/models/default_versions.rs
Labels: C-internal 🔧, A-backend ⚙️

#8704 Move `MockSentryService` class into the `app` folder
  app/initializers/app-hook.js
  app/utils/sentry.js
  tests/helpers/sentry.js
Labels: C-bug 🐞, A-frontend 🐹

#8705 metrics/service: Reset `background_jobs` metric before setting new values
  src/metrics/service.rs
Labels: C-internal 🔧, A-backend ⚙️

#8715 Remove obsolete `postcss-nested` plugin
  ember-cli-build.js
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#8716 Remove unused `RadioButton` and `ThemePreview` components
  app/components/radio-button.hbs
  app/components/theme-preview.hbs
  app/components/theme-preview.module.css
Labels: A-frontend 🐹, C-internal 🔧

#8719 workers/jobs/dump_db: Remove unnecessary `target_name` field
  src/admin/enqueue_job.rs
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8721 workers/jobs/dump_db: Use `Storage` from background job context
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8722 workers/jobs/dump_db: Use `insta` for tarball testing
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8714 CI: Add e2e test
  .github/workflows/ci.yml
  playwright.config.ts
Labels: A-frontend 🐹, C-internal 🔧

#8738 dump_db: Remove excessive whitespace
  Cargo.lock
  Cargo.toml
  src/tests/dump_db.rs
  src/tests/snapshots/all__dump_db__sql_scripts@export.sql.snap
  src/tests/snapshots/all__dump_db__sql_scripts@import.sql.snap
  src/worker/jobs/dump_db/dump-export.sql.j2
  src/worker/jobs/dump_db/dump-import.sql.j2
Labels: C-internal 🔧, A-backend ⚙️

#8742 tests/dump_db: Add `schema.sql` to the test
  crates/crates_io_test_db/src/lib.rs
  src/tests/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8745 dump_db: Use `tempfile` for temporary file/folder creation
  src/tests/dump_db.rs
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8747 workers/jobs/dump_db: Apply date prefix when creating tarball
  src/tests/dump_db.rs
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8746 Introduce length limit on the `description` field
  src/controllers/krate/publish.rs
  src/tests/krate/publish/validation.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8763 Update "Twitter" logo ...
  public/assets/twitter.svg
Labels: C-enhancement ✨, A-frontend 🐹

#8766 Improve renovatebot config
  .github/renovate.json5
Labels: C-internal 🔧

#8768 renovate: Disable `node` version pinning in frontend Dockerfile
  .github/renovate.json5
Labels: C-internal 🔧
