Repository rust-lang/crates.io, pull requests merged in 2024-06, with the labels that each got.

#8748 Create `db-dump.zip` file too
  Cargo.lock
  Cargo.toml
  deny.toml
  src/storage.rs
  src/tests/dump_db.rs
  src/worker/jobs/dump_db.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8779 Sentry: Fix staging URL in `allowUrls`
  app/sentry.js
Labels: C-bug 🐞, A-frontend 🐹

#8784 Settings: Remove "Email Notifications" link
  app/components/settings-page.hbs
Labels: A-frontend 🐹

#8785 Playwright: Skip "Email Notifications" test
  e2e/bugs/2329.spec.ts
Labels: A-frontend 🐹

#8786 crates_io_tarball: Use `insta` snapshots to simplify test code
  Cargo.lock
  crates/crates_io_tarball/Cargo.toml
  crates/crates_io_tarball/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#8787 crates_io_tarball: Extract constants
  crates/crates_io_tarball/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#8788 crates_io_tarball: Disallow paths differing only by case
  crates/crates_io_tarball/src/lib.rs
  src/controllers/krate/publish.rs
  src/tests/krate/publish/snapshots/all__krate__publish__manifest__multiple_manifests.snap
Labels: C-bug 🐞, A-backend ⚙️

#8794 Postgres: Set `application_name` to crates.io
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8791 Add a crates.io-specific security page
  app/components/footer.hbs
  app/router.js
  app/routes/security.js
  app/templates/policies/index.hbs
  app/templates/policies/security.hbs
Labels: A-frontend 🐹, C-documentation 📜

#8835 Remove unused `ember-cli-app-version` dependency
  config/environment.js
  package.json
  pnpm-lock.yaml
Labels: C-enhancement ✨, A-frontend 🐹

#8832 Add supports_attributes Flag to Storage Struct to Support ObjectStore Implementations
  src/storage.rs
Labels: C-bug 🐞, A-backend ⚙️

#8836 worker/jobs/dump_db: Remove `database_url` field
  src/admin/enqueue_job.rs
  src/tests/dump_db.rs
  src/worker/jobs/dump_db.rs
Labels: C-internal 🔧, A-backend ⚙️

#8847 real_ip: Add debug logging
  src/middleware/real_ip.rs
  src/real_ip.rs
Labels: C-internal 🔧, A-backend ⚙️

#8869 models/version: Reorder impl blocks and structs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#8867 Remove obsolete `versions.semver_no_prerelease` database column
  migrations/2024-06-14-084455_remove-semver-no-prerelease-column/down.sql
  migrations/2024-06-14-084455_remove-semver-no-prerelease-column/up.sql
  src/db.rs
  src/db/sql_types.rs
  src/db/sql_types/semver.rs
  src/models/version.rs
  src/schema.rs
  src/sql.rs
  src/worker/jobs/dump_db/dump-db.toml
Labels: C-internal 🔧, A-backend ⚙️

#8870 tests/builders/version: Simplify `license` field
  src/tests/builders/krate.rs
  src/tests/builders/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#8873 Remove background color from preformatted code blocks within lists
  app/components/text-content.module.css
  e2e/acceptance/readme-rendering.spec.ts
  tests/acceptance/readme-rendering-test.js
Labels: C-bug 🐞, A-frontend 🐹

#8876 styles: Fix `:global { ... }` block usage
  app/styles/application.module.css
Labels: C-bug 🐞, A-frontend 🐹

#8871 models/version: Derive `NewVersion` builder struct
  src/controllers/krate/publish.rs
  src/models/version.rs
  src/tests/builders/version.rs
  src/typosquat/test_util.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#8875 tracing: Use JSON log format if `RUST_LOG_FORMAT=json` is set
  Cargo.lock
  Cargo.toml
  src/util/tracing.rs
Labels: C-internal 🔧, A-backend ⚙️

#8877 Use tracing fields for `http` logs
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#8878 Add `http.matched_path` field to HTTP request logs
  src/middleware/log_request.rs
Labels: C-internal 🔧, A-backend ⚙️

#8882 Fix `@type` annotations
  app/models/api-token.js
  app/models/version.js
Labels: C-bug 🐞, A-frontend 🐹

#8885 Add `GET /api/v1/me/tokens/:id` API endpoint
  src/controllers/token.rs
  src/router.rs
  src/tests/routes/me/tokens/get.rs
  src/tests/routes/me/tokens/mod.rs
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__get__show.snap
  src/tests/routes/me/tokens/snapshots/all__routes__me__tokens__get__show_token_with_scopes.snap
Labels: C-enhancement ✨, A-backend ⚙️

#8909 Use snapshot tests for `app.stored_files()` assertions
  src/tests/dump_db.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/git.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/rate_limit.rs
  src/tests/krate/publish/readme.rs
Labels: C-internal 🔧, A-backend ⚙️

#8910 Remove obsolete insta snapshot
  src/tests/routes/crates/versions/snapshots/all__routes__crates__versions__download__rejected_non_canonical_download.snap
Labels: C-internal 🔧, A-backend ⚙️

#8911 Support `c`/`xml`/`rs` languages for syntax highlighting in codeblocks
  crates/crates_io_markdown/lib.rs
Labels: C-enhancement ✨, A-backend ⚙️

#8920 renovate: Disable `pinDigest` updates for the whole `docker` datasource
  .github/renovate.json5
Labels: C-internal 🔧

#8923 crates_io_test_db: Reduce connection timeout to 5 sec.
  crates/crates_io_test_db/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#8930 publish: Change "unknown categories" warning to error
  src/controllers/krate/publish.rs
  src/models/category.rs
  src/tests/krate/publish/categories.rs
  src/tests/krate/publish/snapshots/all__krate__publish__categories__ignored_categories.snap
Labels: C-enhancement ✨, A-backend ⚙️

#8883 Show `cargo install` for crates with binaries
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  app/components/crate-sidebar.module.css
  app/components/crate-sidebar/install-instructions.hbs
  app/components/crate-sidebar/install-instructions.js
  app/components/crate-sidebar/install-instructions.module.css
  app/helpers/sum.js
  app/models/version.js
Labels: C-enhancement ✨, A-frontend 🐹

#8938 Remove `GitImport` admin command
  src/admin/git_import.rs
  src/admin/mod.rs
  src/bin/crates-admin.rs
Labels: C-internal 🔧, A-backend ⚙️

#8908 Create `updates.xml` RSS feed
  Cargo.lock
  Cargo.toml
  src/admin/enqueue_job.rs
  src/controllers/krate/publish.rs
  src/storage.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/git.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/rate_limit.rs
  src/tests/krate/publish/readme.rs
  src/tests/worker/mod.rs
  src/tests/worker/rss/mod.rs
  src/tests/worker/rss/snapshots/all__worker__rss__sync_updates_feed__sync_updates_feed-2.snap
  src/tests/worker/rss/sync_updates_feed.rs
  src/worker/jobs/mod.rs
  src/worker/jobs/rss/mod.rs
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates-2.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates-3.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates.snap
  src/worker/jobs/rss/sync_updates_feed.rs
  src/worker/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️
