Repository rust-lang/crates.io, pull requests merged in 2024-11, with the labels that each got.

#9822 worker: Migrate tests suite to async database queries
  crates/crates_io_worker/Cargo.toml
  crates/crates_io_worker/tests/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#9826 Migrate to `AsyncPgConnection::try_from_client_and_connection()`
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#9827 Move `admin::on_call` module to `pagerduty`
  src/admin/mod.rs
  src/admin/test_pagerduty.rs
  src/bin/monitor.rs
  src/lib.rs
  src/pagerduty.rs
Labels: C-internal 🔧, A-backend ⚙️

#9828 Move `admin` modules into `crates-admin` binary
  src/admin/mod.rs
  src/bin/crates-admin/default_versions.rs
  src/bin/crates-admin/delete_crate.rs
  src/bin/crates-admin/delete_version.rs
  src/bin/crates-admin/dialoguer.rs
  src/bin/crates-admin/enqueue_job.rs
  src/bin/crates-admin/main.rs
  src/bin/crates-admin/migrate.rs
  src/bin/crates-admin/populate.rs
  src/bin/crates-admin/render_readmes.rs
  src/bin/crates-admin/test_pagerduty.rs
  src/bin/crates-admin/transfer_crates.rs
  src/bin/crates-admin/upload_index.rs
  src/bin/crates-admin/verify_token.rs
  src/bin/crates-admin/yank_version.rs
  src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#9829 admin: Migrate to async database connections
  src/bin/crates-admin/default_versions.rs
  src/bin/crates-admin/migrate.rs
  src/bin/crates-admin/render_readmes.rs
  src/bin/crates-admin/verify_token.rs
  src/boot/categories.rs
Labels: C-internal 🔧, A-backend ⚙️

#9831 Extract `crates_io_pagerduty` crate
  Cargo.lock
  Cargo.toml
  crates/crates_io_pagerduty/Cargo.toml
  crates/crates_io_pagerduty/examples/test_pagerduty.rs
  crates/crates_io_pagerduty/src/lib.rs
  src/bin/crates-admin/main.rs
  src/bin/monitor.rs
  src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#9830 db: Remove unused `oneoff_connection()` fns
  src/bin/crates-admin/default_versions.rs
  src/bin/crates-admin/delete_crate.rs
  src/bin/crates-admin/delete_version.rs
  src/bin/crates-admin/enqueue_job.rs
  src/bin/crates-admin/migrate.rs
  src/bin/crates-admin/populate.rs
  src/bin/crates-admin/render_readmes.rs
  src/bin/crates-admin/transfer_crates.rs
  src/bin/crates-admin/verify_token.rs
  src/bin/crates-admin/yank_version.rs
  src/bin/monitor.rs
  src/db.rs
Labels: C-internal 🔧, A-backend ⚙️

#9833 pagerduty: Extract `PagerdutyClient` struct
  Cargo.lock
  crates/crates_io_pagerduty/Cargo.toml
  crates/crates_io_pagerduty/examples/test_pagerduty.rs
  crates/crates_io_pagerduty/src/lib.rs
  src/bin/monitor.rs
Labels: C-internal 🔧, A-backend ⚙️

#9834 pagerduty/example: Read environment variables via `clap`
  Cargo.lock
  crates/crates_io_pagerduty/Cargo.toml
  crates/crates_io_pagerduty/examples/test_pagerduty.rs
Labels: C-internal 🔧, A-backend ⚙️

#9842 frontend: Migrate to use `default_version` and `yanked`
  app/components/crate-row.hbs
  app/models/crate.js
  app/routes/crate/dependencies.js
  app/routes/crate/version.js
Labels: A-frontend 🐹, C-internal 🔧

#9846 chore: Add some comments
  src/models/krate.rs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9850 util/diesel: Add diesel prelude excluding `RunQueryDsl`
  src/bin/crates-admin/render_readmes.rs
  src/boot/categories.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/update.rs
  src/controllers/version.rs
  src/controllers/version/downloads.rs
  src/models/action.rs
  src/models/crate_owner_invitation.rs
  src/models/default_versions.rs
  src/models/keyword.rs
  src/models/krate.rs
  src/models/team.rs
  src/models/token.rs
  src/models/user.rs
  src/models/version.rs
  src/rate_limiter.rs
  src/util/diesel.rs
Labels: C-internal 🔧, A-backend ⚙️

#9851 controllers/keyword: Reduce `spawn_blocking()` usage
  src/controllers/keyword.rs
  src/models/keyword.rs
Labels: C-internal 🔧, A-backend ⚙️

#9856 Inline `CrateVersions` trait fns
  src/controllers/krate/metadata.rs
  src/controllers/krate/search.rs
  src/controllers/summary.rs
  src/index.rs
  src/models.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9862 controllers/summary: Remove unnecessary `.is_empty()` conditions
  src/controllers/summary.rs
Labels: C-internal 🔧, A-backend ⚙️

#9865 worker/tests: Fix flaky deduplication test
  crates/crates_io_worker/tests/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#9863 team_repo: Avoid `automock` for release builds
  Cargo.toml
  crates/crates_io_team_repo/Cargo.toml
  crates/crates_io_team_repo/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#9866 Show "Retry" button for README loading errors
  app/controllers/crate/version.js
  app/models/version.js
  app/styles/crate/version.module.css
  app/templates/crate/version.hbs
  e2e/acceptance/readme-rendering.spec.ts
  mirage/route-handlers/crates.js
  tests/acceptance/readme-rendering-test.js
  tests/mirage/crates/versions/readme-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#9868 controllers/version: Convert `version_and_crate()` to async
  src/controllers/version.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9869 Remove `spawn_blocking()` call from `GET /crates/:crate_id/:version/dependencies` endpoint
  src/controllers/version/metadata.rs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9871 models/version: Convert `record_readme_rendering()` to async fn
  src/bin/crates-admin/render_readmes.rs
  src/models/version.rs
  src/tests/version.rs
  src/worker/jobs/readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#9870 models/version: Fix `published_by()` error handling
  src/controllers/version/metadata.rs
  src/models/version.rs
Labels: C-bug 🐞, A-backend ⚙️

#9876 Heroku: Update buildpack
  .buildpacks
Labels: A-infrastructure 📡, C-internal 🔧

#9877 Reduce `spawn_blocking()` usage
  src/controllers/krate/follow.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
Labels: C-internal 🔧, A-backend ⚙️

#9878 tests/user: Simplify `new_user()` usage
  src/tests/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#9889 Revert "admin/render_readmes: Remove redundant tokio runtime"
  src/bin/crates-admin/render_readmes.rs
Labels: C-bug 🐞, A-backend ⚙️

#9890 models/crate_owner_invitation: Convert to async/await
  src/controllers/crate_owner_invitation.rs
  src/models/crate_owner_invitation.rs
Labels: C-internal 🔧, A-backend ⚙️

#9892 admin/render_readmes: Use async `reqwest` client and `diesel-async` queries
  Cargo.toml
  src/bin/crates-admin/render_readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#9894 admin/render_readmes: Simplify `total_pages` calculation
  src/bin/crates-admin/render_readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#9900 Show error page if team or user is missing or fails to load
  app/routes/team.js
  app/routes/user.js
  e2e/routes/team.spec.ts
  e2e/routes/user.spec.ts
  tests/routes/team-test.js
  tests/routes/user-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#9901 models/krate: Add `async_owners()` fn
  src/controllers/krate/owners.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9905 controllers/krate/owners: Remove `spawn_blocking()` from `GET /crates/:crate_id/owner_team` endpoint
  src/controllers/krate/owners.rs
  src/models/team.rs
Labels: C-internal 🔧, A-backend ⚙️

#9911 admin/delete_crate: Simplify SQL query code by deriving `Queryable` and `Selectable`
  src/bin/crates-admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9919 admin/upload_index: Reduce `spawn_blocking()` scope
  src/bin/crates-admin/upload_index.rs
Labels: C-internal 🔧, A-backend ⚙️

#9921 admin/dialoguer: Rename `async_confirm()` fn to `confirm()`
  src/bin/crates-admin/delete_crate.rs
  src/bin/crates-admin/delete_version.rs
  src/bin/crates-admin/dialoguer.rs
  src/bin/crates-admin/transfer_crates.rs
  src/bin/crates-admin/upload_index.rs
  src/bin/crates-admin/yank_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#9934 admin/verify-token: Remove obsolete `spawn_blocking()` call
  src/bin/crates-admin/verify_token.rs
Labels: C-internal 🔧, A-backend ⚙️

#9938 controllers/krate/metadata: Migrate reverse dependencies endpoint to `diesel-async`
  src/controllers/krate/metadata.rs
  src/models/action.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#9936 boot/categories: Migrate `sync_with_connection()` to `diesel-async` queries
  src/bin/crates-admin/migrate.rs
  src/boot/categories.rs
  src/tests/categories.rs
Labels: C-internal 🔧, A-backend ⚙️

#9946 github: Use mockall to generate `MockGitHubClient` implementation
  Cargo.lock
  Cargo.toml
  crates/crates_io_github/Cargo.toml
  crates/crates_io_github/src/lib.rs
  src/tests/github_secret_scanning.rs
  src/tests/util/github.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#9943 Add regression test for #1205
  src/models/krate.rs
  src/tests/issues/issue1205.rs
  src/tests/issues/mod.rs
  src/tests/mod.rs
Labels: C-bug 🐞, A-backend ⚙️

#9950 tests/util: Move `add/remove_owner()` fns into `RequestHelper` trait
  src/tests/issues/issue1205.rs
  src/tests/mod.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/crates/owners/remove.rs
  src/tests/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#9951 tests/routes/crates/owners/remove: Add uppercase test cases
  src/tests/routes/crates/owners/remove.rs
Labels: C-internal 🔧, A-backend ⚙️

#9930 Fix owner removal for duplicate logins
  src/models/krate.rs
  src/models/owner.rs
  src/tests/issues/issue1205.rs
  src/tests/issues/issue2736.rs
  src/tests/issues/mod.rs
  src/tests/routes/crates/owners/remove.rs
  src/tests/team.rs
Labels: C-bug 🐞, A-backend ⚙️

#9926 database: Change `versions.crate_size` to be `NOT NULL`
  crates/crates_io_database/src/schema.rs
  migrations/2024-11-14-094209_make-crate-size-not-null/down.sql
  migrations/2024-11-14-094209_make-crate-size-not-null/up.sql
  src/models/default_versions.rs
  src/models/version.rs
  src/tests/routes/crates/read.rs
  src/tests/worker/rss/sync_crate_feed.rs
  src/tests/worker/rss/sync_updates_feed.rs
  src/views.rs
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
Labels: C-internal 🔧, A-backend ⚙️

#9960 axum-extra: Use `json!()` macro
  Cargo.lock
  Cargo.toml
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers.rs
  src/controllers/keyword.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/site_metadata.rs
  src/controllers/summary.rs
  src/controllers/team.rs
  src/controllers/token.rs
  src/controllers/user/me.rs
  src/controllers/user/other.rs
  src/controllers/user/session.rs
  src/controllers/version/downloads.rs
  src/controllers/version/metadata.rs
  src/lib.rs
  src/tests/krate/following.rs
  src/tests/krate/publish/build_metadata.rs
  src/tests/owners.rs
  src/tests/routes/crates/versions/list.rs
  src/tests/routes/me/email_notifications.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/tokens/list.rs
  src/tests/routes/private/crate_owner_invitations.rs
  src/tests/routes/users/update.rs
  src/tests/routes/users/update/publish_notifications.rs
  src/tests/user.rs
  src/tests/util.rs
  src/util/errors/json.rs
  src/worker/jobs/downloads/queue/job.rs
Labels: C-internal 🔧, A-backend ⚙️

#9961 Use async `lettre` transports for sending emails
  Cargo.lock
  Cargo.toml
  src/controllers/user/resend.rs
  src/email.rs
  src/tests/github_secret_scanning.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/emails.rs
  src/tests/owners.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/users/update/publish_notifications.rs
  src/tests/team.rs
  src/tests/user.rs
  src/tests/util/test_app.rs
  src/tests/worker/sync_admins.rs
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/sync_admins.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#9963 worker/jobs/expiry_notification: Migrate to `diesel-async` queries
  src/models/user.rs
  src/worker/jobs/expiry_notification.rs
Labels: C-internal 🔧, A-backend ⚙️

#9965 worker/jobs/send_publish_notifications: Migrate to `Emails::async_send()`
  src/worker/jobs/send_publish_notifications.rs
Labels: C-internal 🔧, A-backend ⚙️

#9968 Remove `ReadOnlyMode` error struct
  src/controllers/user/session.rs
  src/util/diesel.rs
  src/util/errors.rs
  src/util/errors/json.rs
Labels: C-internal 🔧, A-backend ⚙️

#9971 tests: Avoid `NewUser::create_or_update()` calls
  src/rate_limiter.rs
  src/tests/owners.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/me/email_notifications.rs
  src/tests/routes/users/read.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#9972 controllers/user/session: Remove `spawn_blocking()` usage
  src/controllers/user/session.rs
  src/models/user.rs
  src/tests/user.rs
  src/worker/jobs/expiry_notification.rs
Labels: C-internal 🔧, A-backend ⚙️

#9973 rss: Remove explicit/duplicate XML escaping
  Cargo.lock
  Cargo.toml
  src/tests/worker/rss/snapshots/crates_io__tests__worker__rss__sync_crates_feed__sync_crates_feed-2.snap
  src/tests/worker/rss/snapshots/crates_io__tests__worker__rss__sync_updates_feed__sync_updates_feed-2.snap
  src/tests/worker/rss/sync_crates_feed.rs
  src/tests/worker/rss/sync_updates_feed.rs
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
Labels: C-bug 🐞, A-backend ⚙️

#9976 Inline `test_db_connection()` fn
  src/lib.rs
  src/models/default_versions.rs
  src/models/keyword.rs
  src/rate_limiter.rs
  src/test_util.rs
  src/typosquat/database.rs
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#9978 insta: Compile with `opt-level = 3`
  Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#9979 insta: Update snapshots
  src/controllers/user/snapshots/crates_io__controllers__user__resend__tests__happy_path-2.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate-4.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_success-2.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_expiry_date-2.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_null_scopes-2.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_scopes-2.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-3.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-4.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-6.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe.snap
  src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_revokes_token-2.snap
  src/tests/snapshots/crates_io__tests__owners__modify_multiple_owners-6.snap
  src/tests/snapshots/crates_io__tests__owners__modify_multiple_owners.snap
  src/tests/snapshots/crates_io__tests__owners__new_crate_owner-2.snap
  src/tests/snapshots/crates_io__tests__owners__new_crate_owner.snap
  src/tests/snapshots/crates_io__tests__team__publish_owned.snap
  src/tests/worker/rss/snapshots/crates_io__tests__worker__rss__sync_crate_feed__sync_crate_feed-2.snap
  src/tests/worker/snapshots/crates_io__tests__worker__sync_admins__sync_admins_job.snap
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/downloads/process_log.rs
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates-2.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates-3.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_crate_feed__tests__load_version_updates.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates-2.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates-3.snap
  src/worker/jobs/rss/snapshots/crates_io__worker__jobs__rss__sync_updates_feed__tests__load_version_updates.snap
Labels: C-internal 🔧, A-backend ⚙️

#9980 tests/util/github: Fix test flakyness
  src/tests/util/github.rs
Labels: C-internal 🔧, A-backend ⚙️

#9981 models/token: Remove sync `find_by_api_token()` fn
  src/auth.rs
  src/bin/crates-admin/verify_token.rs
  src/models/token.rs
  src/tests/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#9937 typosquat: Asyncify all the things
  src/typosquat/cache.rs
  src/typosquat/database.rs
  src/worker/environment.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#9983 models/user: Remove unused sync `find()` fn
  src/auth.rs
  src/bin/crates-admin/verify_token.rs
  src/controllers/github/secret_scanning.rs
  src/models/user.rs
  src/tests/user.rs
  src/worker/jobs/expiry_notification.rs
Labels: C-internal 🔧, A-backend ⚙️

#9912 Add `deleted_crates` database table
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  migrations/2024-11-12-125605_create-deleted-crates-table/down.sql
  migrations/2024-11-12-125605_create-deleted-crates-table/up.sql
  src/bin/crates-admin/delete_crate.rs
  src/controllers/krate/publish.rs
  src/models.rs
  src/models/deleted_crate.rs
  src/models/user.rs
  src/tests/krate/publish/deleted_crates.rs
  src/tests/krate/publish/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️

#9990 models/team: Replace `NewTeam::new()` fn with `Builder` pattern
  src/models/team.rs
  src/tests/mod.rs
  src/tests/team.rs
  src/typosquat/test_util.rs
Labels: C-internal 🔧, A-backend ⚙️

#9991 tests/owners: Migrate to `diesel-async` queries
  src/tests/owners.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/private/crate_owner_invitations.rs
Labels: C-internal 🔧, A-backend ⚙️

#9999 models/action: Extract `NewVersionOwnerAction` struct
  src/controllers/krate/publish.rs
  src/controllers/version/metadata.rs
  src/models.rs
  src/models/action.rs
Labels: C-internal 🔧, A-backend ⚙️

#10001 controllers/version: Remove more `spawn_blocking()` fns
  src/controllers/version/metadata.rs
  src/controllers/version/yank.rs
  src/models/action.rs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#10002 Simplify `spawn_blocking()` wrapper fn
  src/bin/crates-admin/default_versions.rs
  src/bin/crates-admin/delete_version.rs
  src/bin/crates-admin/dialoguer.rs
  src/bin/crates-admin/migrate.rs
  src/bin/crates-admin/render_readmes.rs
  src/bin/crates-admin/upload_index.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/metrics.rs
  src/controllers/user/me.rs
  src/controllers/version/downloads.rs
  src/tasks.rs
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/dump_db.rs
  src/worker/jobs/index/normalize.rs
  src/worker/jobs/index/squash.rs
  src/worker/jobs/index/sync.rs
  src/worker/jobs/readmes.rs
  src/worker/jobs/update_default_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#10003 controllers/krate/publish: Reduce `spawn_blocking()` scope
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#10004 controllers/krate/metadata: Remove `spawn_blocking()` usage
  src/controllers/krate/metadata.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#10005 admin/delete_crate: Replace raw SQL with diesel subquery builder
  src/bin/crates-admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#10009 test_db: Extract `async_connect()` fn
  Cargo.lock
  crates/crates_io_test_db/Cargo.toml
  crates/crates_io_test_db/src/lib.rs
  src/controllers/user/session.rs
  src/index.rs
  src/models/category.rs
  src/rate_limiter.rs
  src/tests/categories.rs
  src/tests/util/test_app.rs
  src/typosquat/database.rs
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/downloads/clean_processed_log_files.rs
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#10012 typosquat/test_util: Remove duplicate `add_crate_to_team()` fn
  src/tests/mod.rs
  src/typosquat/database.rs
  src/typosquat/test_util.rs
Labels: C-internal 🔧, A-backend ⚙️

#10011 database_dump/gen_scripts: Use async queries
  Cargo.lock
  crates/crates_io_database_dump/Cargo.toml
  crates/crates_io_database_dump/src/gen_scripts.rs
Labels: C-internal 🔧, A-backend ⚙️

#10015 admin/delete-crate: Use configurable 24 hour availability delay
  src/bin/crates-admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#10017 Migrate `add_team_to_crate()` to async queries
  src/tests/mod.rs
  src/tests/owners.rs
  src/tests/team.rs
  src/typosquat/database.rs
Labels: C-internal 🔧, A-backend ⚙️

#10020 controllers/krate/versions: Remove `spawn_blocking()` call
  src/controllers/krate/versions.rs
Labels: C-internal 🔧, A-backend ⚙️

#10022 controllers/crate_owner_invitations: Remove `spawn_blocking()` call
  src/controllers/crate_owner_invitation.rs
Labels: C-internal 🔧, A-backend ⚙️

#10021 Implement async pagination
  src/controllers/helpers/pagination.rs
  src/controllers/keyword.rs
  src/controllers/krate/search.rs
  src/controllers/user/me.rs
Labels: C-internal 🔧, A-backend ⚙️

#10029 controllers/version/downloads: Remove `spawn_blocking()` call
  src/controllers/version/downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#10030 worker/jobs/downloads/update_metadata: Remove `spawn_blocking()` call
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#10035 controllers/krate/search: Use `.contains()` fn
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️

#10036 models/default_versions: Add async fn variants
  src/bin/crates-admin/default_versions.rs
  src/models.rs
  src/models/default_versions.rs
Labels: C-internal 🔧, A-backend ⚙️

#10040 tests/builders: Migrate to async/await
  src/index.rs
  src/models/category.rs
  src/models/keyword.rs
  src/models/krate.rs
  src/models/team.rs
  src/models/version.rs
  src/tests/blocked_routes.rs
  src/tests/builders/krate.rs
  src/tests/builders/version.rs
  src/tests/dump_db.rs
  src/tests/issues/issue1205.rs
  src/tests/issues/issue2736.rs
  src/tests/krate/following.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/basics.rs
  src/tests/krate/publish/dependencies.rs
  src/tests/krate/publish/features.rs
  src/tests/krate/publish/max_size.rs
  src/tests/krate/publish/readme.rs
  src/tests/krate/publish/similar_names.rs
  src/tests/owners.rs
  src/tests/pagination.rs
  src/tests/read_only_mode.rs
  src/tests/routes/categories/get.rs
  src/tests/routes/crates/downloads.rs
  src/tests/routes/crates/following.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/crates/owners/add.rs
  src/tests/routes/crates/owners/remove.rs
  src/tests/routes/crates/read.rs
  src/tests/routes/crates/reverse_dependencies.rs
  src/tests/routes/crates/versions/authors.rs
  src/tests/routes/crates/versions/dependencies.rs
  src/tests/routes/crates/versions/download.rs
  src/tests/routes/crates/versions/list.rs
  src/tests/routes/crates/versions/read.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/routes/keywords/list.rs
  src/tests/routes/keywords/read.rs
  src/tests/routes/me/email_notifications.rs
  src/tests/routes/me/get.rs
  src/tests/routes/me/updates.rs
  src/tests/routes/private/crate_owner_invitations.rs
  src/tests/routes/summary.rs
  src/tests/routes/users/stats.rs
  src/tests/server.rs
  src/tests/team.rs
  src/tests/unhealthy_database.rs
  src/tests/version.rs
  src/typosquat/database.rs
  src/typosquat/test_util.rs
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#10046 Update `rss` dependency
  Cargo.lock
  Cargo.toml
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
Labels: C-internal 🔧, A-backend ⚙️

#10047 models/default_versions: Remove sync fns
  src/bin/crates-admin/default_versions.rs
  src/bin/crates-admin/delete_version.rs
  src/models.rs
  src/models/default_versions.rs
  src/tests/builders/krate.rs
  src/worker/jobs/update_default_version.rs
Labels: C-internal 🔧, A-backend ⚙️

#10048 Remove unused sync fns
  crates/crates_io_worker/src/background_job.rs
  crates/crates_io_worker/tests/runner.rs
  src/bin/crates-admin/delete_crate.rs
  src/bin/crates-admin/delete_version.rs
  src/bin/crates-admin/enqueue_job.rs
  src/bin/crates-admin/yank_version.rs
  src/controllers/krate/metadata.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/versions.rs
  src/controllers/user/me.rs
  src/controllers/version/metadata.rs
  src/models/action.rs
  src/models/category.rs
  src/models/keyword.rs
  src/models/krate.rs
  src/models/version.rs
  src/tests/builders/krate.rs
  src/tests/builders/version.rs
  src/tests/dump_db.rs
  src/tests/krate/publish/audit_action.rs
  src/tests/routes/categories/get.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/keywords/list.rs
  src/tests/routes/keywords/read.rs
  src/tests/worker/git.rs
  src/tests/worker/rss/sync_crate_feed.rs
  src/tests/worker/rss/sync_crates_feed.rs
  src/tests/worker/rss/sync_updates_feed.rs
  src/tests/worker/sync_admins.rs
  src/worker/jobs/archive_version_downloads.rs
  src/worker/jobs/downloads/queue/job.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#10049 controllers/krate/owners: Convert remaining endpoints to async/await
  src/controllers/krate/owners.rs
  src/models/crate_owner_invitation.rs
  src/models/krate.rs
  src/models/owner.rs
  src/models/team.rs
  src/models/user.rs
  src/tests/owners.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/me/get.rs
  src/tests/routes/users/stats.rs
  src/tests/team.rs
Labels: C-internal 🔧, A-backend ⚙️

#10054 Remove unused sync fns
  src/bin/crates-admin/delete_crate.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/github/secret_scanning.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/token.rs
  src/controllers/user/resend.rs
  src/controllers/user/update.rs
  src/controllers/version/metadata.rs
  src/email.rs
  src/models/krate.rs
  src/models/owner.rs
  src/models/team.rs
  src/models/user.rs
  src/tests/issues/issue1205.rs
  src/tests/issues/issue2736.rs
  src/tests/owners.rs
  src/tests/team.rs
  src/typosquat/database.rs
  src/typosquat/test_util.rs
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/send_publish_notifications.rs
  src/worker/jobs/sync_admins.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#10055 typosquat/test_util: Migrate `user()` fn to `diesel-async`
  src/typosquat/database.rs
  src/typosquat/test_util.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#9998 Add description, homepage, documentation and repository fields for versions
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
  migrations/2024-11-19-095931_add-version-columns/down.sql
  migrations/2024-11-19-095931_add-version-columns/up.sql
  src/controllers/krate/publish.rs
  src/models/version.rs
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__edition__edition_is_saved-2.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__links__crate_with_links_field-2.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__boolean_readme-2.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__manifest__lib_and_bin_crate-2.snap
  src/tests/krate/snapshots/crates_io__tests__krate__yanking__patch_version_yank_unyank-2.snap
  src/tests/krate/snapshots/crates_io__tests__krate__yanking__patch_version_yank_unyank-3.snap
  src/tests/krate/snapshots/crates_io__tests__krate__yanking__patch_version_yank_unyank-4.snap
  src/tests/krate/snapshots/crates_io__tests__krate__yanking__patch_version_yank_unyank-5.snap
  src/tests/krate/snapshots/crates_io__tests__krate__yanking__patch_version_yank_unyank-6.snap
  src/tests/krate/snapshots/crates_io__tests__krate__yanking__patch_version_yank_unyank.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show_all_yanked.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__reverse_dependencies__prerelease_versions_not_included_in_reverse_dependencies.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__reverse_dependencies__reverse_dependencies.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__reverse_dependencies__reverse_dependencies_includes_published_by_user_when_present.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__reverse_dependencies__reverse_dependencies_query_supports_u64_version_number_parts.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__reverse_dependencies__reverse_dependencies_when_old_version_doesnt_depend_but_new_does.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__reverse_dependencies__yanked_versions_not_included_in_reverse_dependencies.snap
  src/tests/routes/crates/versions/snapshots/crates_io__tests__routes__crates__versions__list__versions.snap
  src/tests/routes/crates/versions/snapshots/crates_io__tests__routes__crates__versions__read__show_by_crate_name_and_semver_no_published_by.snap
  src/tests/routes/crates/versions/snapshots/crates_io__tests__routes__crates__versions__read__show_by_crate_name_and_version.snap
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#10076 Use `Version::as_select()` to allow skipping columns
  src/bin/crates-admin/yank_version.rs
  src/controllers/krate/downloads.rs
  src/controllers/krate/search.rs
  src/controllers/summary.rs
  src/index.rs
  src/models/krate.rs
  src/models/version.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#10069 controllers/krate/publish: Validate JSON metadata before reading tarball
  Cargo.lock
  Cargo.toml
  src/controllers/krate/publish.rs
  src/tests/krate/publish/tarball.rs
Labels: C-internal 🔧, A-backend ⚙️

#10079 controllers/summary: Convert `Record` to named struct
  src/controllers/summary.rs
Labels: C-internal 🔧, A-backend ⚙️

#10082 controllers/summary: Use `tokio::try_join!()` to perform database queries in parallel
  src/controllers/summary.rs
  src/models/category.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10070 admin/render_readmes: Migrate `render_pkg_readme()` and `find_file_by_path()` fns to async/await
  Cargo.lock
  Cargo.toml
  src/bin/crates-admin/render_readmes.rs
Labels: C-internal 🔧, A-backend ⚙️

#10090 controllers/krate/publish: Add more tracing instrumentation
  src/controllers/krate/publish.rs
Labels: C-internal 🔧, A-backend ⚙️

#10094 Infer MSRV for Rust Edition 2024
  app/models/version.js
Labels: C-enhancement ✨, A-backend ⚙️

#10095 Remove outdated code comments
  src/controllers/krate/publish.rs
  src/worker/jobs/send_publish_notifications.rs
Labels: A-backend ⚙️, C-documentation 📜

#10096 Inline `Maximums` struct
  src/config/server.rs
  src/controllers/krate/publish.rs
  src/models/krate.rs
  src/tests/krate/publish/max_size.rs
  src/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#10102 Revert "Merge pull request #10069 from Turbo87/publish-stream"
  src/controllers/krate/publish.rs
  src/tests/krate/publish/tarball.rs
Labels: C-bug 🐞, A-backend ⚙️

#10104 smoke_test: Add "publish with invalid authentication" check
  crates/crates_io_smoke_test/src/cargo.rs
  crates/crates_io_smoke_test/src/main.rs
Labels: C-internal 🔧, A-backend ⚙️

#10106 smoke_test: Check failed publish with large payload
  Cargo.lock
  crates/crates_io_smoke_test/Cargo.toml
  crates/crates_io_smoke_test/src/main.rs
Labels: C-internal 🔧, A-backend ⚙️

#10078 database: Add `categories` and `keywords` columns to the `versions` table
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
  migrations/2024-11-26-155931_add-cats-and-keys-to-version/down.sql
  migrations/2024-11-26-155931_add-cats-and-keys-to-version/up.sql
  src/controllers/krate/publish.rs
  src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#10107 Revert "Exclude num_no_build from versions.csv db-dump (#9786)"
  crates/crates_io_database_dump/src/dump-db.toml
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
Labels: C-internal 🔧, A-backend ⚙️
