Repository rust-lang/crates.io, pull requests merged in 2025-03, with the labels that each got.

#10725 Improve OpenAPI documentation
  src/controllers/crate_owner_invitation.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/rev_deps.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10731 Move tooltips to a dedicated container element
  app/components/dependency-list/row.module.css
  app/components/tooltip.hbs
  app/components/tooltip.js
  app/components/tooltip.module.css
  app/components/version-list/row.hbs
  app/components/version-list/row.module.css
  app/modifiers/attach-tooltip.js
  app/styles/shared/typography.module.css
  app/templates/application.hbs
Labels: C-bug 🐞, A-frontend 🐹

#10737 settings/api-tokens: Fix `margin-top` for buttons
  app/components/settings/api-tokens.module.css
Labels: C-bug 🐞, A-frontend 🐹

#10741 Improve OpenAPI documentation for session API
  src/controllers/session.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10749 Improve OpenAPI documentation for summary and metadata API endpoints
  src/controllers/site_metadata.rs
  src/controllers/summary.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10750 Update Heroku buildpack
  .buildpacks
Labels: A-infrastructure 📡, C-internal 🔧, A-backend ⚙️

#10743 Fix flaky tests
  tests/acceptance/support-test.js
Labels: C-bug 🐞, A-frontend 🐹

#10751 Improve OpenAPI documentation for `GET /api/v1/teams/{team}` endpoint
  src/controllers/team.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10752 Improve OpenAPI documentation for API tokens endpoints
  Cargo.lock
  crates/crates_io_database/Cargo.toml
  crates/crates_io_database/src/models/token.rs
  crates/crates_io_database/src/models/token/scopes.rs
  src/controllers/token.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10740 versions: Improve the loading indicator
  app/styles/crate/versions.module.css
  app/templates/crate/versions.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#10762 crates_io_database: Fix `utoipa` dependency declaration
  crates/crates_io_database/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#10764 pg_enum: Add support for additional attributes
  crates/crates_io_diesel_helpers/src/pg_enum.rs
Labels: C-internal 🔧, A-backend ⚙️

#10774 Update `ring` to v0.17.12
  Cargo.lock
Labels: C-internal 🔧, A-backend ⚙️

#10776 Adjust styles for crate row
  app/components/crate-row.hbs
  app/components/crate-row.module.css
Labels: C-bug 🐞, A-frontend 🐹

#10777 controllers/krate/delete: remove the temporary language from #10591
  app/templates/crate/delete.hbs
  src/controllers/krate/delete.rs
Labels: A-frontend 🐹, C-internal 🔧, A-backend ⚙️

#10780 Exclude deleted crate owners from admin tool output
  src/bin/crates-admin/delete_crate.rs
Labels: C-internal 🔧, A-backend ⚙️

#10755 VersionList::Row: Limit the length of the features list
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/components/version-list/row.module.css
Labels: C-bug 🐞, A-frontend 🐹

#10794 cargo-deny: Ignore "paste is unmaintained" "advisory"
  deny.toml
Labels: C-internal 🔧, A-backend ⚙️

#10763 Add `semver_ord(num)` SQL function and `version.semver_ord` column
  crates/crates_io_database/tests/semver_ord.rs
  crates/crates_io_database_dump/src/dump-db.toml
  migrations/2025-03-06-060640_semver_ord/down.sql
  migrations/2025-03-06-060640_semver_ord/up.sql
Labels: C-enhancement ✨, A-backend ⚙️

#10795 tests/acceptance/support-test: Add debugging information for flaky tests
  tests/acceptance/support-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10819 Use `semver_ord` column for sorting versions
  crates/crates_io_diesel_helpers/src/fns.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/versions.rs
  src/tests/routes/crates/versions/list.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10824 controllers/krate/versions: Use `semver_ord` for `release_tracks` where applicable
  src/controllers/krate/versions.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10806 Adjust loading spinner color
  app/components/follow-button.hbs
  app/components/loading-spinner.hbs
  app/components/loading-spinner.module.css
  app/templates/index.hbs
  app/templates/settings/tokens/new.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#10838 Replace `krata-tokio-tar` with `astral-tokio-tar`
  Cargo.lock
  Cargo.toml
  crates/crates_io_tarball/Cargo.toml
Labels: dependencies

#10849 controllers/category: Pipeline SQL queries
  crates/crates_io_database/src/models/category.rs
  src/controllers/category.rs
Labels: C-internal 🔧, A-backend ⚙️

#10873 tests/api-token: Add action button visibility assertions
  app/components/settings/api-tokens.hbs
  e2e/acceptance/api-token.spec.ts
  tests/acceptance/api-token-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#10868 Make regenerate button visible for expired tokens
  app/components/settings/api-tokens.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#10882 Pin `ember-data` to `5.3.11`
  package.json
  pnpm-lock.yaml
Labels: C-bug 🐞, A-frontend 🐹, dependencies

#10888 Ensure CDN invalidations occur when crates or crate versions are deleted
  src/bin/crates-admin/delete_version.rs
  src/cloudfront.rs
  src/storage.rs
  src/worker/jobs/delete_crate.rs
  src/worker/jobs/invalidate_cdns.rs
  src/worker/jobs/mod.rs
  src/worker/mod.rs
Labels: C-bug 🐞, A-backend ⚙️
