Repository rust-lang/crates.io, pull requests merged in 2025-10, with the labels that each got.

#12022 me/crates: Redirect to user profile page to eliminate duplication
  app/controllers/dashboard.js
  app/controllers/me/crates.js
  app/routes/me/crates.js
  app/routes/user.js
  app/templates/dashboard.gjs
  app/templates/me/crates.css
  app/templates/me/crates.gjs
  e2e/routes/me/crates.spec.ts
  tests/routes/me/crates-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#12028 Downgrade axum-extra to v0.10.3
  Cargo.lock
  Cargo.toml
  crates/crates_io_session/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#12034 Fix <picture> sources not follow color scheme preference
  app/components/rendered-html.gjs
Labels: C-bug 🐞, A-frontend 🐹

#12031 Raise crate deletion downloads limit to 1000/month
  app/templates/crate/delete.gjs
  app/templates/policies/index.gjs
  src/controllers/krate/delete.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot-2.snap
Labels: C-enhancement ✨, A-frontend 🐹, A-backend ⚙️

#12043 support/crate-report-form: Split `security` checkbox into `malicious-code` and `vulnerability`
  app/components/support/crate-report-form.css
  app/components/support/crate-report-form.gjs
  e2e/acceptance/support.spec.ts
  tests/acceptance/support-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#12051 Add missing `.select()` and `.returning()` calls
  crates/crates_io_database/src/models/action.rs
  crates/crates_io_database/src/models/category.rs
  crates/crates_io_database/src/models/cloudfront_invalidation_queue.rs
  crates/crates_io_database/src/models/keyword.rs
  crates/crates_io_database/src/models/team.rs
  crates/crates_io_database/src/models/trustpub/gitlab_config.rs
  src/controllers/category.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/keyword.rs
  src/controllers/summary.rs
  src/controllers/team.rs
  src/controllers/trustpub/tokens/exchange/gitlab_tests.rs
  src/rate_limiter.rs
Labels: C-internal 🔧, A-backend ⚙️

#12065 renovate: Include `diesel-` prefixed package in "diesel packages" group
  .github/renovate.json5
Labels: C-internal 🔧, A-backend ⚙️
