Repository rust-lang/crates.io, pull requests merged in 2025-02, with the labels that each got.

#10490 msw: Add seek pagination support for `GET /api/v1/crates/:name/versions`
  packages/crates-io-msw/handlers/versions/list.js
  packages/crates-io-msw/handlers/versions/list.test.js
  tests/models/version-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10489 fix: only autofocus search form on hero header
  app/components/header.hbs
  app/components/search-form.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#10510 Add `ember-auto-import` resolution override
  ember-cli-build.js
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#10520 Use `cargo-machete` to remove unused dependency declarations
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  crates/crates_io_worker/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#10344 Include `default_version` by default
  app/adapters/crate.js
  app/adapters/version.js
  app/models/crate.js
  app/routes/crate/dependencies.js
  app/routes/crate/version-dependencies.js
  app/routes/crate/version.js
  e2e/acceptance/crate-dependencies.spec.ts
  tests/acceptance/crate-dependencies-test.js
  tests/adapters/crate-test.js
Labels: A-frontend 🐹

#10513 Replace `ember-tooltips` with `floating-ui`
  app/components/crate-header.hbs
  app/components/crate-row.hbs
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.module.css
  app/components/dependency-list/row.hbs
  app/components/dependency-list/row.module.css
  app/components/edition.hbs
  app/components/ember-tooltip.js
  app/components/msrv.hbs
  app/components/privileged-action.hbs
  app/components/settings/api-tokens.hbs
  app/components/tooltip.hbs
  app/components/tooltip.js
  app/components/tooltip.module.css
  app/components/version-list/row.hbs
  app/components/version-list/row.module.css
  app/modifiers/attach-tooltip.js
  app/styles/application.module.css
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#10521 Improve OpenAPI description
  src/openapi.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10522 capitalize first sentence of crate delete mail
  src/controllers/krate/delete.rs
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_new_crate-2.snap
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_old_crate-2.snap
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_really_old_crate-2.snap
Labels: C-enhancement ✨, A-backend ⚙️

#10527 Include status page URL in read-only mode error message
  src/tests/snapshots/crates_io__tests__read_only_mode__cannot_hit_endpoint_which_writes_db_in_read_only_mode.snap
  src/util/errors.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10519 Add `default_versions.num_versions` column
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@export.sql.snap
  crates/crates_io_database_dump/src/snapshots/crates_io_database_dump__tests__sql_scripts@import.sql.snap
  migrations/2025-02-05-083109_add-num-versions-column/down.sql
  migrations/2025-02-05-083109_add-num-versions-column/up.sql
  src/controllers/krate/publish.rs
  src/tests/krate/publish/basics.rs
Labels: C-internal 🔧, A-backend ⚙️

#10548 Remove unused `crate_owner_invitations.token_generated_at` column
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  migrations/2025-02-11-115609_remove-token-generated-at-column/down.sql
  migrations/2025-02-11-115609_remove-token-generated-at-column/up.sql
  src/models/crate_owner_invitation.rs
Labels: C-internal 🔧, A-backend ⚙️

#10550 Extract `NewCrateOwnerInvitation` struct
  src/models.rs
  src/models/crate_owner_invitation.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#10552 model/owner: Extract `CrateOwner::from_invite()` fn
  src/models/crate_owner_invitation.rs
  src/models/owner.rs
Labels: C-internal 🔧, A-backend ⚙️

#10558 db: Fix incorrect Upsert for `num_versions`
  migrations/2025-02-11-163554_fix-num-versions-trigger/down.sql
  migrations/2025-02-11-163554_fix-num-versions-trigger/up.sql
  src/tests/krate/publish/basics.rs
Labels: C-bug 🐞, A-backend ⚙️

#10557 models/token: Extract `NewApiToken` struct
  src/controllers/token.rs
  src/models.rs
  src/models/token.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/tokens/get.rs
  src/tests/routes/me/tokens/list.rs
  src/tests/util.rs
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#10556 models/krate: Remove `PaginationOptions` dependency
  src/controllers/krate/rev_deps.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#10553 database: Add `crate_owner_invitations.expires_at` column
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  migrations/2025-02-11-122509_add-expires-at-column/down.sql
  migrations/2025-02-11-122509_add-expires-at-column/up.sql
  src/models/crate_owner_invitation.rs
  src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#10554 Simplify `crate_owner_invitations` expiry checks
  crates/crates_io_database/src/schema.rs
  migrations/2025-02-11-122510_not-null-expires-at-column/down.sql
  migrations/2025-02-11-122510_not-null-expires-at-column/up.sql
  src/controllers/crate_owner_invitation.rs
  src/models/crate_owner_invitation.rs
  src/models/krate.rs
  src/tests/owners.rs
Labels: C-internal 🔧, A-backend ⚙️

#10564 CI: Remove broken CodeCov integration
  .github/workflows/ci.yml
Labels: C-internal 🔧, A-backend ⚙️

#10565 models/owners: Remove `App` dependency
  src/controllers/krate/owners.rs
  src/models/owner.rs
Labels: C-internal 🔧, A-backend ⚙️

#10566 models/email: Improve `NewEmail` struct
  src/controllers/user/update.rs
  src/models/email.rs
  src/models/user.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#10573 models/user: Change `gh_access_token` field to `SecretString`
  src/models/team.rs
  src/models/user.rs
  src/tests/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#10575 Derive `bon::Builder` for `CrateOwner` struct and add `insert()` fn
  src/controllers/krate/owners.rs
  src/models/crate_owner_invitation.rs
  src/models/krate.rs
  src/models/owner.rs
  src/tests/issues/issue2736.rs
  src/tests/mod.rs
  src/tests/routes/crates/owners/remove.rs
Labels: C-internal 🔧, A-backend ⚙️

#10574 models/download: Add a slim `Version` model to reduce data loading
  src/controllers/krate/downloads.rs
  src/models.rs
  src/models/download.rs
Labels: C-internal 🔧, A-backend ⚙️

#10577 controllers/krate/downloads: Perform queries in parallel
  src/controllers/krate/downloads.rs
Labels: C-enhancement ✨, A-backend ⚙️

#10578 models/team: Simplify fn return types
  src/models/team.rs
  src/models/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#10586 github: Adjust `org/team_membership()` to return `Result<Option<_>, _>`
  crates/crates_io_github/src/lib.rs
  src/models/team.rs
  src/tests/issues/issue1205.rs
  src/tests/routes/crates/owners/remove.rs
  src/tests/util/github.rs
Labels: C-internal 🔧, A-backend ⚙️

#10589 models/team: Avoid repeated `AccessToken` instantiation
  src/models/team.rs
  src/models/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#10587 CI: Fix caching
  .github/workflows/ci.yml
Labels: C-internal 🔧, A-backend ⚙️

#10591 controllers/krate/delete: prevent any crates with rdeps from deletion
  app/templates/crate/delete.hbs
  src/controllers/krate/delete.rs
Labels: C-bug 🐞, A-frontend 🐹, A-backend ⚙️

#10529 Add `?include=versions` support for `GET /api/v1/crates/{name}/downloads` endpoint
  app/adapters/crate.js
  app/routes/crate/version.js
  e2e/acceptance/crate.spec.ts
  packages/crates-io-msw/handlers/crates/downloads.js
  packages/crates-io-msw/handlers/crates/downloads.test.js
  src/controllers/krate/downloads.rs
  src/models/action.rs
  src/models/version.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  tests/acceptance/crate-test.js
Labels: C-enhancement ✨, A-backend ⚙️

#10596 models: Remove remaining `GitHubClient` usage
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers.rs
  src/controllers/helpers/authorization.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/owners.rs
  src/controllers/krate/publish.rs
  src/controllers/version/update.rs
  src/models.rs
  src/models/rights.rs
  src/models/team.rs
  src/models/user.rs
Labels: C-internal 🔧, A-backend ⚙️

#10597 Move `models` into `crates_io_database` crate
  Cargo.lock
  Cargo.toml
  crates/crates_io_database/Cargo.toml
  crates/crates_io_database/src/lib.rs
  crates/crates_io_database/src/models/action.rs
  crates/crates_io_database/src/models/category.rs
  crates/crates_io_database/src/models/crate_owner_invitation.rs
  crates/crates_io_database/src/models/default_versions.rs
  crates/crates_io_database/src/models/deleted_crate.rs
  crates/crates_io_database/src/models/dependency.rs
  crates/crates_io_database/src/models/download.rs
  crates/crates_io_database/src/models/email.rs
  crates/crates_io_database/src/models/follow.rs
  crates/crates_io_database/src/models/helpers.rs
  crates/crates_io_database/src/models/helpers/with_count.rs
  crates/crates_io_database/src/models/keyword.rs
  crates/crates_io_database/src/models/krate.rs
  crates/crates_io_database/src/models/krate_reverse_dependencies.sql
  crates/crates_io_database/src/models/mod.rs
  crates/crates_io_database/src/models/owner.rs
  crates/crates_io_database/src/models/parent_categories.sql
  crates/crates_io_database/src/models/subcategories.sql
  crates/crates_io_database/src/models/team.rs
  crates/crates_io_database/src/models/token.rs
  crates/crates_io_database/src/models/token/scopes.rs
  crates/crates_io_database/src/models/toplevel.sql
  crates/crates_io_database/src/models/user.rs
  crates/crates_io_database/src/models/version.rs
  crates/crates_io_database/src/utils/mod.rs
  crates/crates_io_database/src/utils/rfc3339.rs
  crates/crates_io_database/src/utils/token.rs
  src/lib.rs
  src/util.rs
Labels: C-internal 🔧, A-backend ⚙️

#10604 Use timestamps with timezones
  crates/crates_io_database/src/models/action.rs
  crates/crates_io_database/src/models/category.rs
  crates/crates_io_database/src/models/crate_owner_invitation.rs
  crates/crates_io_database/src/models/email.rs
  crates/crates_io_database/src/models/keyword.rs
  crates/crates_io_database/src/models/krate.rs
  crates/crates_io_database/src/models/token.rs
  crates/crates_io_database/src/models/user.rs
  crates/crates_io_database/src/models/version.rs
  crates/crates_io_database/src/schema.patch
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database/src/utils/mod.rs
  crates/crates_io_database/src/utils/rfc3339.rs
  crates/crates_io_diesel_helpers/src/fns.rs
  migrations/2025-02-17-133723_timezones/down.sql
  migrations/2025-02-17-133723_timezones/up.sql
  src/auth.rs
  src/bin/crates-admin/delete_crate.rs
  src/bin/monitor.rs
  src/controllers/crate_owner_invitation.rs
  src/controllers/helpers/pagination.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/publish.rs
  src/controllers/krate/search.rs
  src/controllers/krate/versions.rs
  src/controllers/token.rs
  src/index.rs
  src/rate_limiter.rs
  src/tests/account_lock.rs
  src/tests/builders/krate.rs
  src/tests/builders/version.rs
  src/tests/krate/publish/rate_limit.rs
  src/tests/routes/crates/list.rs
  src/tests/routes/crates/versions/yank_unyank.rs
  src/tests/routes/me/tokens/get.rs
  src/tests/routes/me/tokens/list.rs
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_expiry_date.snap
  src/tests/routes/summary.rs
  src/tests/user.rs
  src/tests/util.rs
  src/util.rs
  src/util/errors.rs
  src/util/errors/json.rs
  src/views.rs
  src/worker/jobs/downloads/update_metadata.rs
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/rss/sync_crate_feed.rs
  src/worker/jobs/rss/sync_crates_feed.rs
  src/worker/jobs/rss/sync_updates_feed.rs
  src/worker/jobs/send_publish_notifications.rs
Labels: C-internal 🔧, A-backend ⚙️

#10613 OpenAPI: Add link to our "Data Access Policy" in the description
  src/openapi.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-enhancement ✨, C-documentation 📜

#10616 app: Migrate the overlooked `versions.length` to `num_versions`
  app/templates/crate/version.hbs
Labels: A-frontend 🐹

#10621 ESLint: Migrate to flat config format
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  app/services/color-scheme.js
  app/services/session.js
  docs/ARCHITECTURE.md
  eslint.config.mjs
  package.json
  packages/crates-io-msw/handlers/summary.js
  pnpm-lock.yaml
  script/precompress-assets.mjs
Labels: A-frontend 🐹, C-internal 🔧

#10623 Update SPDX license list
  app/utils/license.js
Labels: C-enhancement ✨, A-frontend 🐹

#10644 services/session: Add `debug` logs
  app/services/session.js
Labels: A-frontend 🐹, C-internal 🔧

#10656 cargo-deny: Ignore `ring` maintenance advisory
  deny.toml
Labels: C-internal 🔧, A-backend ⚙️

#10648 Fix low contrast of "Load More" on dashboard
  app/styles/dashboard.module.css
Labels: C-bug 🐞, A-frontend 🐹

#10658 pnpm: Allow msw to run postinstall script
  package.json
Labels: A-frontend 🐹, C-internal 🔧

#10657 Use async closures where applicable
  crates/crates_io_tarball/src/lib.rs
  crates/crates_io_worker/src/worker.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/publish.rs
  src/middleware/cargo_compat.rs
  src/router.rs
  src/worker/jobs/archive_version_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#10672 Improve `/crates` route error handling
  app/routes/crates.js
  app/templates/catch-all.hbs
  e2e/acceptance/crates.spec.ts
  tests/acceptance/crates-test.js
Labels: C-bug 🐞, A-frontend 🐹

#10684 controllers/keyword: Add query params documentation
  src/controllers/keyword.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10685 Add OpenAPI documentation for keyword API responses
  src/controllers/keyword.rs
  src/openapi.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10691 openapi: Remove unnecessary `schema` declaration
  src/openapi.rs
Labels: C-internal 🔧, A-backend ⚙️

#10692 Merge `EncodableCategoryWithSubcategories` into `EncodableCategory`
  src/controllers/category.rs
  src/tests/mod.rs
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#10693 Add OpenAPI documentation for category API responses
  src/controllers/category.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10694 Remove unused `EncodableCrateOwnerInvitationV1::from()` fn
  src/views.rs
Labels: C-internal 🔧, A-backend ⚙️

#10698 Add OpenAPI documentation for `GET /api/v1/users/{user}` endpoint
  src/controllers/user/other.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10697 controllers/krate/metadata: Pipeline SQL queries
  src/controllers/krate/metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#10659 Migrate versions page to paginated list
  app/adapters/version.js
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/controllers/crate/versions.js
  app/models/crate.js
  app/models/version.js
  app/routes/crate/versions.js
  app/styles/crate/versions.module.css
  app/templates/crate/versions.hbs
  e2e/acceptance/crate.spec.ts
  tests/acceptance/crate-test.js
  tests/components/version-list-row-test.js
  tests/models/version-test.js
Labels: A-frontend 🐹

#10702 Add OpenAPI documentation for `GET /api/v1/users/{id}/stats` response payload
  src/controllers/user/other.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10703 Add OpenAPI documentation for `crate_owner_invitation` response payloads
  src/controllers/crate_owner_invitation.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10704 Replace `ok_true()` fn with `OkResponse` struct
  src/controllers/helpers.rs
  src/controllers/krate/follow.rs
  src/controllers/user/email_notifications.rs
  src/controllers/user/email_verification.rs
  src/controllers/user/update.rs
  src/controllers/version/yank.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-internal 🔧, A-backend ⚙️, C-documentation 📜

#10706 controllers/user/me: Pipeline SQL queries
  src/controllers/user/me.rs
Labels: C-internal 🔧, A-backend ⚙️

#10709 Add OpenAPI documentation for `GET /api/v1/crates/{name}/{version}` response payload
  src/controllers/version/metadata.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10716 Add OpenAPI documentation for `GET /api/v1/me/updates` response payload
  src/controllers/user/me.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10717 Add OpenAPI documentation for `GET /api/v1/crates/{name}/{version}/dependencies` response payload
  src/controllers/version/dependencies.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10718 Improve OpenAPI documentation for version endpoints
  src/controllers/version/downloads.rs
  src/controllers/version/readme.rs
  src/controllers/version/update.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10719 Fix OpenAPI documentation for `DELETE /api/v1/crates/{name}` endpoint
  src/controllers/krate/delete.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: A-backend ⚙️, C-documentation 📜

#10720 Improve OpenAPI documentation for crates API endpoints
  src/controllers/krate/downloads.rs
  src/controllers/krate/follow.rs
  src/controllers/krate/metadata.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/views.rs
Labels: A-backend ⚙️, C-documentation 📜

#10721 serializers/crate: Prevent `categories` and `keywords` from being cleared
  app/serializers/crate.js
  e2e/acceptance/crate.spec.ts
  tests/acceptance/crate-test.js
Labels: C-bug 🐞, A-frontend 🐹
