Repository rust-lang/crates.io, pull requests merged in 2025-01, with the labels that each got.

#10301 mirage: Add `include=default_version` support for `GET /api/v1/crates/:id`
  mirage/route-handlers/crates.js
  mirage/serializers/crate.js
  tests/mirage/crates/get-by-id-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10304 email: Reduce monomorphization overhead for the `Emails::build_message()` fn
  src/email.rs
Labels: C-internal 🔧, A-backend ⚙️

#10305 tests/util: Reduce monomorphization overhead for the `RequestHelper` code
  src/tests/util.rs
  src/tests/util/mock_request.rs
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#10306 controllers/version: Pipelining database queries
  src/controllers/version/metadata.rs
  src/controllers/version/update.rs
  src/models/action.rs
Labels: C-internal 🔧, A-backend ⚙️

#10311 Reverse `versions` ordering in `GET /api/v1/crates/{name}` endpoint
  src/controllers/krate/metadata.rs
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show.snap
  src/tests/routes/crates/snapshots/crates_io__tests__routes__crates__read__show_all_yanked.snap
Labels: A-backend ⚙️

#10326 controllers/krate/metadata: Pipelining database queries
  src/controllers/krate/metadata.rs
Labels: A-backend ⚙️

#10296 app: Make separate requests for crate and versions
  app/adapters/crate.js
  app/models/crate.js
  app/routes/crate/dependencies.js
  app/routes/crate/range.js
  app/routes/crate/version-dependencies.js
  app/routes/crate/version.js
  e2e/acceptance/crate-dependencies.spec.ts
  e2e/routes/crate/range.spec.ts
  tests/acceptance/crate-dependencies-test.js
  tests/adapters/crate-test.js
  tests/models/version-test.js
  tests/routes/crate/range-test.js
Labels: A-frontend 🐹

#10332 mirage: Maintains crate version-related handling
  mirage/route-handlers/crates.js
  tests/mirage/crates/versions/authors-test.js
  tests/mirage/crates/versions/dependencies-test.js
  tests/mirage/crates/versions/downloads-test.js
  tests/mirage/crates/versions/get-by-num-test.js
  tests/mirage/crates/versions/list-test.js
  tests/mirage/crates/versions/patch-test.js
  tests/mirage/crates/versions/readme-test.js
  tests/mirage/crates/versions/yank/unyank-test.js
  tests/mirage/crates/versions/yank/yank-test.js
Labels: A-frontend 🐹, C-internal 🔧

#10314 Add multiple `nums[]` parameters support for `GET /api/v1/crates/:name/versions`
  mirage/route-handlers/crates.js
  src/controllers/krate/versions.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/routes/crates/versions/list.rs
  tests/mirage/crates/versions/list-test.js
Labels: A-backend ⚙️

#10342 Add support for `message` query parameter when deleting crates
  src/controllers/krate/delete.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-enhancement ✨, A-backend ⚙️

#10343 Add "Delete this crate" button to the crate settings page
  app/styles/crate/settings.module.css
  app/templates/crate/settings.hbs
  e2e/acceptance/crate-deletion.spec.ts
  tests/acceptance/crate-deletion-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#10356 Fix deprecations
  app/models/dependency.js
  app/services/store.js
  app/transforms/date.js
Labels: A-frontend 🐹, C-internal 🔧

#10363 router: update dev-mode /git/index path to Axum 0.8 format
  src/router.rs
Labels: A-backend ⚙️

#10367 mirage: Replace `assert()` from `@ember/debug` with conditional `throw`
  mirage/serializers/crate.js
Labels: A-frontend 🐹, C-internal 🔧

#10369 Fix non-canonical crate name pages
  app/adapters/crate.js
  app/routes/crate.js
  e2e/acceptance/crate.spec.ts
  mirage/route-handlers/crates.js
  tests/acceptance/crate-test.js
  tests/mirage/crates/get-by-id-test.js
Labels: C-bug 🐞, A-frontend 🐹

#10380 crate/delete: Add required reason input field
  app/adapters/crate.js
  app/controllers/crate/delete.js
  app/routes/crate/delete.js
  app/styles/crate/delete.module.css
  app/templates/crate/delete.hbs
  e2e/acceptance/crate-deletion.spec.ts
  e2e/routes/crate/delete.spec.ts
  tests/acceptance/crate-deletion-test.js
  tests/routes/crate/delete-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#10385 adapters/crate: Fix query parameter name
  app/adapters/crate.js
  app/controllers/crate/delete.js
Labels: C-bug 🐞, A-frontend 🐹

#10392 Update "Usage Policy" regarding crate deletions
  app/templates/policies/index.hbs
Labels: C-enhancement ✨

#10405 tests/routes/crates/list: Remove duplicated `decode_seek()` fn
  src/tests/routes/crates/list.rs
Labels: C-internal 🔧, A-backend ⚙️

#10410 Improving the readability of search test cases
  src/tests/routes/crates/list.rs
Labels: C-internal 🔧, A-backend ⚙️

#10411 controllers/krate/search: Use provided `plainto_tsquery_with_search_config()` fn
  src/controllers/krate/search.rs
Labels: C-internal 🔧, A-backend ⚙️
