Repository rust-lang/crates.io, pull requests merged in 2025-05, with the labels that each got.

#11062 Create "Trusted Publishing" database tables
  crates/crates_io_database/src/schema.patch
  crates/crates_io_database/src/schema.rs
  crates/crates_io_database_dump/src/dump-db.toml
  migrations/2025-04-25-090000_trusted-publishing/down.sql
  migrations/2025-04-25-090000_trusted-publishing/up.sql
Labels: C-enhancement ✨, A-backend ⚙️

#11101 Revert "GitHub: Add support for "Get a repository" requests"
  crates/crates_io_github/examples/test_github_client.rs
  crates/crates_io_github/src/lib.rs
Labels: C-internal 🔧, A-backend ⚙️

#11102 Fix "Github" spelling
  crates/crates_io_database/src/models/team.rs
  crates/crates_io_github/src/lib.rs
  docs/CONTRIBUTING.md
  src/controllers/krate/owners.rs
  src/controllers/session.rs
  src/tests/user.rs
  src/tests/util/github.rs
Labels: C-internal 🔧, A-backend ⚙️

#11113 Implement `PUT /api/v1/trusted_publishing/github_configs` API endpoint
  Cargo.lock
  Cargo.toml
  crates/crates_io_database/src/models/mod.rs
  crates/crates_io_database/src/models/trustpub/github_config.rs
  crates/crates_io_database/src/models/trustpub/mod.rs
  crates/crates_io_github/examples/test_github_client.rs
  crates/crates_io_github/src/lib.rs
  crates/crates_io_trustpub/Cargo.toml
  crates/crates_io_trustpub/README.md
  crates/crates_io_trustpub/src/github/mod.rs
  crates/crates_io_trustpub/src/github/validation.rs
  crates/crates_io_trustpub/src/lib.rs
  src/controllers.rs
  src/controllers/trustpub/github_configs/create/mod.rs
  src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__happy_path-2.snap
  src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__happy_path.snap
  src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__happy_path_with_environment.snap
  src/controllers/trustpub/github_configs/create/tests.rs
  src/controllers/trustpub/github_configs/emails.rs
  src/controllers/trustpub/github_configs/json.rs
  src/controllers/trustpub/github_configs/mod.rs
  src/controllers/trustpub/mod.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/util/errors.rs
Labels: C-enhancement ✨, A-backend ⚙️

#11164 Remove `Arc` around `AsyncFileTransport`
  src/email.rs
Labels: C-internal 🔧, A-backend ⚙️

#11167 Use same database pool creation code for API server and background worker
  src/app.rs
  src/bin/background-worker.rs
  src/config/database_pools.rs
  src/db.rs
  src/lib.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#11184 config/database_pools: Change `tcp_timeout` field to `Duration`
  src/config/database_pools.rs
  src/db.rs
  src/tests/util/test_app.rs
Labels: C-internal 🔧, A-backend ⚙️

#11185 config/database_pools: Extract magic numbers into named constants
  src/config/database_pools.rs
Labels: C-internal 🔧, A-backend ⚙️

#11186 config/database_pools: Fix broken `connection_timeout`
  src/config/database_pools.rs
Labels: C-bug 🐞, A-backend ⚙️

#11187 bin/background-worker: Increase database statement timeout to one hour
  src/bin/background-worker.rs
Labels: C-bug 🐞, A-backend ⚙️

#11198 benches: Use `black_box()` from `std::hint`
  crates/crates_io_cdn_logs/benches/count_downloads.rs
Labels: C-internal 🔧, A-backend ⚙️

#11203 CI: Add `zizmor` job
  .github/workflows/ci.yml
  .github/workflows/smoke-test.yml
Labels: C-internal 🔧

#11169 Add `POST /api/v1/crates/{name}/{version}/rebuild_docs` API endpoint
  Cargo.lock
  Cargo.toml
  crates/crates_io_docs_rs/Cargo.toml
  crates/crates_io_docs_rs/README.md
  crates/crates_io_docs_rs/examples/test_docs_rs_client.rs
  crates/crates_io_docs_rs/src/lib.rs
  src/bin/background-worker.rs
  src/controllers/version.rs
  src/controllers/version/docs.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/util.rs
  src/tests/util/test_app.rs
  src/worker/environment.rs
  src/worker/jobs/docs_rs_queue_rebuild.rs
  src/worker/jobs/mod.rs
  src/worker/mod.rs
Labels: C-enhancement ✨, A-backend ⚙️

#11208 Migrate subcrates to Rust Edition 2024
  crates/crates_io_cdn_logs/Cargo.toml
  crates/crates_io_cdn_logs/benches/count_downloads.rs
  crates/crates_io_cdn_logs/examples/count_downloads.rs
  crates/crates_io_cdn_logs/src/cloudfront.rs
  crates/crates_io_cdn_logs/src/fastly/mod.rs
  crates/crates_io_database/Cargo.toml
  crates/crates_io_database/src/models/category.rs
  crates/crates_io_database/src/models/token.rs
  crates/crates_io_database_dump/Cargo.toml
  crates/crates_io_database_dump/src/configuration.rs
  crates/crates_io_database_dump/src/lib.rs
  crates/crates_io_diesel_helpers/Cargo.toml
  crates/crates_io_diesel_helpers/src/semver.rs
  crates/crates_io_env_vars/Cargo.toml
  crates/crates_io_env_vars/src/lib.rs
  crates/crates_io_github/Cargo.toml
  crates/crates_io_github/src/lib.rs
  crates/crates_io_index/Cargo.toml
  crates/crates_io_index/credentials.rs
  crates/crates_io_index/repo.rs
  crates/crates_io_index/ser.rs
  crates/crates_io_markdown/Cargo.toml
  crates/crates_io_markdown/lib.rs
  crates/crates_io_pagerduty/Cargo.toml
  crates/crates_io_pagerduty/src/lib.rs
  crates/crates_io_session/Cargo.toml
  crates/crates_io_session/src/lib.rs
  crates/crates_io_smoke_test/Cargo.toml
  crates/crates_io_smoke_test/src/main.rs
  crates/crates_io_tarball/Cargo.toml
  crates/crates_io_tarball/examples/check_all_crates.rs
  crates/crates_io_tarball/examples/read_file.rs
  crates/crates_io_tarball/src/builder.rs
  crates/crates_io_team_repo/Cargo.toml
  crates/crates_io_test_db/Cargo.toml
  crates/crates_io_worker/Cargo.toml
  crates/crates_io_worker/src/background_job.rs
  crates/crates_io_worker/src/runner.rs
  crates/crates_io_worker/tests/runner.rs
Labels: C-internal 🔧, A-backend ⚙️

#11211 background-worker: bump timeout to 4h
  src/bin/background-worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#11221 controllers/site_metadata: Avoid unnecessary allocation
  src/controllers/site_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#11209 Add `DELETE /api/v1/trusted_publishing/github_configs/{id}` API endpoint
  src/controllers/trustpub/github_configs/delete/mod.rs
  src/controllers/trustpub/github_configs/delete/snapshots/crates_io__controllers__trustpub__github_configs__delete__tests__happy_path.snap
  src/controllers/trustpub/github_configs/delete/tests.rs
  src/controllers/trustpub/github_configs/emails.rs
  src/controllers/trustpub/github_configs/mod.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-enhancement ✨, A-backend ⚙️

#11230 Add `GET /api/v1/trusted_publishing/github_configs` API endpoint
  src/controllers/trustpub/github_configs/json.rs
  src/controllers/trustpub/github_configs/list/mod.rs
  src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__crate_with_no_configs.snap
  src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__happy_path-2.snap
  src/controllers/trustpub/github_configs/list/snapshots/crates_io__controllers__trustpub__github_configs__list__tests__happy_path.snap
  src/controllers/trustpub/github_configs/list/tests.rs
  src/controllers/trustpub/github_configs/mod.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
Labels: C-enhancement ✨, A-backend ⚙️
