Repository rust-lang/crates.io, pull requests merged in 2025-07, with the labels that each got.

#11441 Add support for rendering alerts in README
  app/styles/crate/version.module.css
  crates/crates_io_markdown/lib.rs
  e2e/acceptance/readme-rendering.spec.ts
  public/assets/alert-caution.svg
  public/assets/alert-important.svg
  public/assets/alert-note.svg
  public/assets/alert-tip.svg
  public/assets/alert-warning.svg
  tests/acceptance/readme-rendering-test.js
Labels: C-enhancement ✨

#11436 Add OpenGraph image generation crate
  .github/workflows/ci.yml
  Cargo.lock
  crates/crates_io_og_image/Cargo.toml
  crates/crates_io_og_image/README.md
  crates/crates_io_og_image/examples/test_generator.rs
  crates/crates_io_og_image/src/error.rs
  crates/crates_io_og_image/src/formatting.rs
  crates/crates_io_og_image/src/lib.rs
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image.snap
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_escaping.snap
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_escaping.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_minimal.snap
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_minimal.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_overflow.snap
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_overflow.snap.png
  crates/crates_io_og_image/template/assets/cargo.png
  crates/crates_io_og_image/template/assets/code-branch.svg
  crates/crates_io_og_image/template/assets/code.svg
  crates/crates_io_og_image/template/assets/rust-logo.svg
  crates/crates_io_og_image/template/assets/scale-balanced.svg
  crates/crates_io_og_image/template/assets/tag.svg
  crates/crates_io_og_image/template/assets/test-avatar.png
  crates/crates_io_og_image/template/assets/weight-hanging.svg
  crates/crates_io_og_image/template/og-image.typ
Labels: C-enhancement ✨, A-backend ⚙️

#11482 emails: Standardize branding with template inheritance and polish content
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_new_crate-3.snap
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_old_crate-3.snap
  src/controllers/krate/snapshots/crates_io__controllers__krate__delete__tests__happy_path_really_old_crate-3.snap
  src/controllers/trustpub/github_configs/create/snapshots/crates_io__controllers__trustpub__github_configs__create__tests__happy_path-3.snap
  src/controllers/trustpub/github_configs/delete/snapshots/crates_io__controllers__trustpub__github_configs__delete__tests__happy_path-2.snap
  src/controllers/user/snapshots/crates_io__controllers__user__email_verification__tests__happy_path-3.snap
  src/email.rs
  src/email/templates/admin_account/body.txt.j2
  src/email/templates/base.txt.j2
  src/email/templates/config_created/body.txt.j2
  src/email/templates/config_deleted/body.txt.j2
  src/email/templates/crate_deletion/body.txt.j2
  src/email/templates/expiry_notification/body.txt.j2
  src/email/templates/new_token/body.txt.j2
  src/email/templates/owner_invite/body.txt.j2
  src/email/templates/possible_typosquat/body.txt.j2
  src/email/templates/publish_notification/body.txt.j2
  src/email/templates/token_exposed/body.txt.j2
  src/email/templates/trustpub_token_exposed/body.txt.j2
  src/email/templates/unsubscribe_notifications/body.txt.j2
  src/email/templates/user_confirm/body.txt.j2
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__basics__new_krate-5.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__full_flow-11.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_success-3.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_expiry_date-3.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_null_scopes-3.snap
  src/tests/routes/me/tokens/snapshots/crates_io__tests__routes__me__tokens__create__create_token_with_scopes-3.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-11.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-2.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-5.snap
  src/tests/routes/users/update/snapshots/crates_io__tests__routes__users__update__publish_notifications__unsubscribe_and_resubscribe-7.snap
  src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_revokes_token-3.snap
  src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_revokes_trustpub_token-3.snap
  src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_revokes_trustpub_token_multiple_users-3.snap
  src/tests/snapshots/crates_io__tests__owners__modify_multiple_owners-10.snap
  src/tests/snapshots/crates_io__tests__owners__modify_multiple_owners.snap
  src/tests/snapshots/crates_io__tests__owners__new_crate_owner-2.snap
  src/tests/snapshots/crates_io__tests__owners__new_crate_owner.snap
  src/tests/snapshots/crates_io__tests__team__publish_owned.snap
  src/tests/worker/snapshots/crates_io__tests__worker__sync_admins__sync_admins_job.snap
Labels: C-enhancement ✨, A-backend ⚙️

#11484 tests: Fix rate limit test flakiness by using database reset instead of sleep
  src/tests/krate/publish/rate_limit.rs
Labels: C-internal 🔧, A-backend ⚙️

#11486 e2e/crate/settings: Move Percy snapshot to fix snapshot flakiness
  e2e/routes/crate/settings.spec.ts
Labels: A-frontend 🐹, C-internal 🔧

#11503 Dedupe expired JTI deletion job
  src/worker/jobs/trustpub/delete_jtis.rs
Labels: C-internal 🔧, A-backend ⚙️

#11509 trustpub: Improve config creation form
  app/styles/crate/settings/new-trusted-publisher.module.css
  app/templates/crate/settings/new-trusted-publisher.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#11506 db-dump: Reset sequences after data import
  script/import-database-dump.sh
  script/reset-sequences.sql
Labels: C-internal 🔧, A-backend ⚙️

#11516 og_image: Add support for JPEG avatars
  crates/crates_io_og_image/examples/test_generator.rs
  crates/crates_io_og_image/src/lib.rs
Labels: C-bug 🐞, A-backend ⚙️

#11517 og-image: Handle 404 errors from avatar downloads gracefully
  crates/crates_io_og_image/src/lib.rs
  crates/crates_io_og_image/template/og-image.typ
Labels: C-bug 🐞, A-backend ⚙️

#11519 og_image: Use mockito to test avatar downloading code
  Cargo.lock
  crates/crates_io_og_image/Cargo.toml
  crates/crates_io_og_image/src/lib.rs
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__404-avatar.snap
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__404-avatar.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_overflow.snap.png
  crates/crates_io_og_image/template/assets/test-avatar.jpg
  crates/crates_io_og_image/template/assets/test-avatar.webp
Labels: C-internal 🔧, A-backend ⚙️

#11520 Heroku: Update buildpack
  .buildpacks
Labels: C-internal 🔧

#11521 og_image: Ignore CDN invalidation errors
  src/worker/jobs/generate_og_image.rs
Labels: C-internal 🔧, A-backend ⚙️

#11522 og_image: Skip CDN invalidations for backfill operation
  src/bin/crates-admin/backfill_og_images.rs
  src/worker/jobs/generate_og_image.rs
Labels: C-internal 🔧, A-backend ⚙️

#11526 og_image: Replace byte-based slicing with character-based for Unicode safety
  crates/crates_io_og_image/src/lib.rs
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__unicode-truncation.snap
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__unicode-truncation.snap.png
  crates/crates_io_og_image/template/og-image.typ
Labels: C-bug 🐞, A-backend ⚙️

#11527 tracing: Consistently use `krate.name` field naming convention
  crates/crates_io_og_image/src/lib.rs
  src/worker/jobs/generate_og_image.rs
Labels: C-internal 🔧, A-backend ⚙️

#11534 Force `@babel/runtime` to 7.27.6 to resolve security vulnerability
  package.json
  pnpm-lock.yaml
Labels: A-frontend 🐹, C-internal 🔧

#11535 worker/delete_crate: Delete OG images when deleting crates
  src/worker/jobs/delete_crate.rs
Labels: C-bug 🐞, A-backend ⚙️

#11531 og_image: Use binary prefixes for `format_bytes`
  crates/crates_io_og_image/src/formatting.rs
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__404-avatar.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_escaping.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_minimal.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__generated_og_image_overflow.snap.png
  crates/crates_io_og_image/src/snapshots/crates_io_og_image__tests__unicode-truncation.snap.png
Labels: C-enhancement ✨, A-backend ⚙️

#11508 Replace rebuild docs button with dedicated confirmation page
  app/components/version-list/row.hbs
  app/components/version-list/row.js
  app/controllers/crate/rebuild-docs.js
  app/router.js
  app/routes/crate/rebuild-docs.js
  app/styles/crate/rebuild-docs.module.css
  app/templates/crate/rebuild-docs.hbs
  e2e/acceptance/rebuild-docs.spec.ts
  e2e/acceptance/versions.spec.ts
  tests/acceptance/rebuild-docs-test.js
  tests/acceptance/versions-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#11538 crate/settings: Improve "Trusted Publishing" section styling on mobile devices
  app/styles/crate/settings/index.module.css
Labels: C-bug 🐞, A-frontend 🐹

#11540 crate/settings: Add links back to the repository
  app/controllers/crate/settings/new-trusted-publisher.js
  app/templates/crate/settings/index.hbs
  app/templates/crate/settings/new-trusted-publisher.hbs
Labels: C-enhancement ✨, A-frontend 🐹

#11567 trustpub: Improve token exchange error messages
  src/controllers/trustpub/tokens/exchange/mod.rs
  src/controllers/trustpub/tokens/exchange/tests.rs
Labels: C-enhancement ✨, A-backend ⚙️

#11576 email: Simplify `token_exposed` context
  src/controllers/github/secret_scanning.rs
Labels: C-internal 🔧, A-backend ⚙️

#11626 database/models/krate: Remove unused `QueryableByName` trait
  crates/crates_io_database/src/models/krate.rs
Labels: C-internal 🔧, A-backend ⚙️

#11646 Update/Remove outdated documentation
  docs/ARCHITECTURE.md
  docs/BACKEND.md
  docs/CONTRIBUTING.md
  docs/FRONTEND.md
Labels: C-documentation 📜
