Repository rust-lang/crates.io, pull requests merged in 2025-06, with the labels that each got.

#11131 Add `PUT /api/v1/trusted_publishing/tokens` API endpoint
  Cargo.lock
  Cargo.toml
  crates/crates_io_database/src/models/category.rs
  crates/crates_io_diesel_helpers/src/fns.rs
  crates/crates_io_trustpub/Cargo.toml
  crates/crates_io_trustpub/src/access_token.rs
  crates/crates_io_trustpub/src/github/claims.rs
  crates/crates_io_trustpub/src/github/mod.rs
  crates/crates_io_trustpub/src/github/snapshots/crates_io_trustpub__github__test_helpers__tests__github_claims.snap
  crates/crates_io_trustpub/src/github/test_helpers.rs
  crates/crates_io_trustpub/src/github/workflows.rs
  crates/crates_io_trustpub/src/keystore/impl.rs
  crates/crates_io_trustpub/src/keystore/load_jwks.rs
  crates/crates_io_trustpub/src/keystore/mod.rs
  crates/crates_io_trustpub/src/keystore/snapshots/crates_io_trustpub__keystore__load_jwks__tests__load_jwks.snap
  crates/crates_io_trustpub/src/lib.rs
  crates/crates_io_trustpub/src/test_keys.rs
  crates/crates_io_trustpub/src/unverified.rs
  src/app.rs
  src/bin/server.rs
  src/config/server.rs
  src/controllers/trustpub/mod.rs
  src/controllers/trustpub/tokens/exchange/mod.rs
  src/controllers/trustpub/tokens/exchange/tests.rs
  src/controllers/trustpub/tokens/json.rs
  src/controllers/trustpub/tokens/mod.rs
  src/router.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/util/test_app.rs
Labels: C-enhancement ✨, A-backend ⚙️

#11290 Simplify `NewVersion::save()` fn
  crates/crates_io_database/src/models/mod.rs
  crates/crates_io_database/src/models/version.rs
  crates/crates_io_database/src/models/versions_published_by.rs
  src/controllers/krate/publish.rs
  src/tests/builders/version.rs
  src/worker/jobs/downloads/update_metadata.rs
Labels: C-internal 🔧, A-backend ⚙️

#11291 database/models/version: Remove unnecessary `pub` specifiers
  crates/crates_io_database/src/models/version.rs
Labels: C-internal 🔧, A-backend ⚙️

#11298 crate/settings: Remove unnecessary `.me-email` container
  app/templates/crate/settings.hbs
Labels: A-frontend 🐹, C-internal 🔧

#11301 crate/settings: Hide "Add Owner" form behind "Add Owner" button
  app/controllers/crate/settings.js
  app/styles/crate/settings.module.css
  app/templates/crate/settings.hbs
  e2e/acceptance/settings/add-owner.spec.ts
  tests/acceptance/settings/add-owner-test.js
  tests/routes/crate/settings-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#11308 crate/settings: Fix "Save" button caption to read "Add" instead
  app/templates/crate/settings.hbs
Labels: C-bug 🐞, A-frontend 🐹

#11294 controllers/krate/publish: Add support for Trusted Publishing access tokens
  crates/crates_io_database/src/models/version.rs
  src/controllers/krate/publish.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot.snap
  src/tests/krate/publish/mod.rs
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__full_flow-3.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__full_flow-4.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__full_flow-5.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__happy_path.snap
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__trustpub__happy_path_with_fancy_auth_header.snap
  src/tests/krate/publish/trustpub.rs
Labels: C-enhancement ✨, A-backend ⚙️

#11314 Set `theme-color` to `header-bg-color`
  app/index.html
  config/manifest.js
Labels: C-bug 🐞, A-frontend 🐹

#11344 tests: Inline `assert_not_found()` and `assert_forbidden()` fns
  src/tests/owners.rs
  src/tests/routes/categories/get.rs
  src/tests/routes/crates/following.rs
  src/tests/routes/keywords/read.rs
  src/tests/routes/me/tokens/create.rs
  src/tests/routes/me/tokens/get.rs
  src/tests/routes/me/tokens/list.rs
  src/tests/routes/me/updates.rs
  src/tests/token.rs
  src/tests/util/response.rs
Labels: C-internal 🔧, A-backend ⚙️

#11345 insta: Update snapshots
  crates/crates_io_database/tests/semver_ord.rs
  crates/crates_io_trustpub/src/github/claims.rs
  src/tests/krate/publish/dependencies.rs
Labels: C-internal 🔧, A-backend ⚙️

#11358 worker: Fix tracing instrumentation
  crates/crates_io_worker/src/worker.rs
Labels: C-internal 🔧, A-backend ⚙️

#11350 Allow empty and `Bearer` auth schemes in `Authorization` headers
  crates/crates_io_trustpub/src/access_token.rs
  src/auth.rs
  src/controllers/krate/publish.rs
  src/controllers/trustpub/tokens/exchange/tests.rs
  src/controllers/trustpub/tokens/revoke/mod.rs
  src/controllers/trustpub/tokens/revoke/tests.rs
  src/tests/krate/publish/auth.rs
  src/tests/krate/publish/snapshots/crates_io__tests__krate__publish__auth__new_krate_with_bearer_token-2.snap
  src/tests/krate/publish/trustpub.rs
Labels: C-bug 🐞, C-enhancement ✨, A-backend ⚙️

#11366 Replace yank button with a drop down menu
  app/components/privileged-action.hbs
  app/components/version-list/row.hbs
  app/components/version-list/row.module.css
  app/components/yank-button.hbs
  e2e/acceptance/sudo.spec.ts
  e2e/acceptance/versions.spec.ts
  public/assets/ellipsis-circle.svg
  tests/acceptance/sudo-test.js
  tests/acceptance/versions-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#11385 db-dump: document the location of historical version download CSVs
  crates/crates_io_database_dump/src/readme_for_tarball.md
Labels: A-backend ⚙️, C-documentation 📜

#11390 trustpub: Change `PUT /api/v1/trusted_publishing/github_configs` endpoint to `POST`
  src/controllers/trustpub/github_configs/create/mod.rs
  src/controllers/trustpub/github_configs/create/tests.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot-2.snap
  src/tests/krate/publish/trustpub.rs
Labels: C-bug 🐞, A-backend ⚙️

#11392 trustpub: Change `PUT /api/v1/trusted_publishing/tokens` endpoint to `POST`
  src/controllers/trustpub/tokens/exchange/mod.rs
  src/controllers/trustpub/tokens/exchange/tests.rs
  src/snapshots/crates_io__openapi__tests__openapi_snapshot-2.snap
  src/tests/krate/publish/trustpub.rs
Labels: C-bug 🐞, A-backend ⚙️

#11381 msw: Implement relevant Trusted Publishing endpoints
  packages/crates-io-msw/handlers/trustpub.js
  packages/crates-io-msw/handlers/trustpub/github-configs.js
  packages/crates-io-msw/handlers/trustpub/github-configs/create.js
  packages/crates-io-msw/handlers/trustpub/github-configs/create.test.js
  packages/crates-io-msw/handlers/trustpub/github-configs/delete.js
  packages/crates-io-msw/handlers/trustpub/github-configs/delete.test.js
  packages/crates-io-msw/handlers/trustpub/github-configs/list.js
  packages/crates-io-msw/handlers/trustpub/github-configs/list.test.js
  packages/crates-io-msw/index.js
  packages/crates-io-msw/models/trustpub/github-config.js
  packages/crates-io-msw/serializers/trustpub/github-config.js
Labels: A-frontend 🐹, C-internal 🔧

#11389 Improve trusted publishing error message
  src/controllers/krate/publish.rs
  src/tests/krate/publish/trustpub.rs
Labels: C-enhancement ✨, A-backend ⚙️

#11387 index_version_downloads_archive: add table headings
  src/worker/jobs/index_version_downloads_archive/index.html.j2
  src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__generate_html.snap
  src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__generate_html_empty.snap
  src/worker/jobs/index_version_downloads_archive/snapshots/crates_io__worker__jobs__index_version_downloads_archive__tests__template_context.snap
Labels: C-internal 🔧, A-backend ⚙️

#11397 e2e: Add missing `Route | crate.settings` tests
  e2e/routes/crate/settings.spec.ts
Labels: A-frontend 🐹, C-internal 🔧

#11398 Implement Trusted Publishing user interface
  app/adapters/trustpub-github-config.js
  app/controllers/crate/settings/index.js
  app/controllers/crate/settings/new-trusted-publisher.js
  app/models/trustpub-github-config.js
  app/router.js
  app/routes/crate/settings.js
  app/routes/crate/settings/index.js
  app/routes/crate/settings/new-trusted-publisher.js
  app/serializers/trustpub-github-config.js
  app/styles/crate/settings/index.module.css
  app/styles/crate/settings/new-trusted-publisher.module.css
  app/templates/crate/settings/index.hbs
  app/templates/crate/settings/new-trusted-publisher.hbs
  e2e/routes/crate/settings.spec.ts
  e2e/routes/crate/settings/new-trusted-publisher.spec.ts
  tests/models/trustpub-github-config-test.js
  tests/routes/crate/settings-test.js
  tests/routes/crate/settings/new-trusted-publisher-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#11413 msw: Implement simplified docs rebuild endpoint
  packages/crates-io-msw/handlers/versions.js
  packages/crates-io-msw/handlers/versions/rebuild-docs.js
  packages/crates-io-msw/handlers/versions/rebuild-docs.test.js
Labels: A-frontend 🐹, C-internal 🔧

#11405 controllers/github/secret_scanning: Add support for Trusted Publishing tokens
  src/controllers/github/secret_scanning.rs
  src/tests/github_secret_scanning.rs
  src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_for_unknown_trustpub_token-2.snap
  src/tests/snapshots/crates_io__tests__github_secret_scanning__github_secret_alert_revokes_trustpub_token-2.snap
Labels: C-enhancement ✨, A-backend ⚙️

#11414 Add Trusted Publishing documentation
  app/router.js
  app/styles/crate/settings/index.module.css
  app/templates/crate/settings/index.hbs
  app/templates/docs/trusted-publishing.hbs
Labels: C-documentation 📜

#11442 database: Enable `postgres` feature of `diesel-async`
  crates/crates_io_database/Cargo.toml
Labels: C-internal 🔧, A-backend ⚙️

#11420 Use `minijinja` templates for emails
  src/controllers/github/secret_scanning.rs
  src/controllers/krate/delete.rs
  src/controllers/krate/owners.rs
  src/controllers/session.rs
  src/controllers/token.rs
  src/controllers/trustpub/github_configs/create/mod.rs
  src/controllers/trustpub/github_configs/delete/mod.rs
  src/controllers/trustpub/github_configs/emails.rs
  src/controllers/trustpub/github_configs/mod.rs
  src/controllers/user/email_verification.rs
  src/controllers/user/update.rs
  src/email.rs
  src/email/templates/admin_account/body.txt.j2
  src/email/templates/admin_account/subject.txt.j2
  src/email/templates/config_created/body.txt.j2
  src/email/templates/config_created/subject.txt.j2
  src/email/templates/config_deleted/body.txt.j2
  src/email/templates/config_deleted/subject.txt.j2
  src/email/templates/crate_deletion/body.txt.j2
  src/email/templates/crate_deletion/subject.txt.j2
  src/email/templates/expiry_notification/body.txt.j2
  src/email/templates/expiry_notification/subject.txt.j2
  src/email/templates/new_token/body.txt.j2
  src/email/templates/new_token/subject.txt.j2
  src/email/templates/owner_invite/body.txt.j2
  src/email/templates/owner_invite/subject.txt.j2
  src/email/templates/possible_typosquat/body.txt.j2
  src/email/templates/possible_typosquat/subject.txt.j2
  src/email/templates/publish_notification/body.txt.j2
  src/email/templates/publish_notification/subject.txt.j2
  src/email/templates/token_exposed/body.txt.j2
  src/email/templates/token_exposed/subject.txt.j2
  src/email/templates/trustpub_token_exposed/body.txt.j2
  src/email/templates/trustpub_token_exposed/subject.txt.j2
  src/email/templates/unsubscribe_notifications/body.txt.j2
  src/email/templates/unsubscribe_notifications/subject.txt.j2
  src/email/templates/user_confirm/body.txt.j2
  src/email/templates/user_confirm/subject.txt.j2
  src/worker/jobs/expiry_notification.rs
  src/worker/jobs/send_publish_notifications.rs
  src/worker/jobs/sync_admins.rs
  src/worker/jobs/typosquat.rs
Labels: C-internal 🔧, A-backend ⚙️

#11470 prettier: Fix markdown issues
  crates/crates_io_test_db/README.md
  crates/crates_io_worker/README.md
Labels: C-documentation 📜

#11416 Add Package URL (PURL) display to crate sidebar
  app/components/crate-sidebar.hbs
  app/components/crate-sidebar.js
  app/components/crate-sidebar.module.css
  app/models/version.js
  app/utils/purl.js
  tests/models/version-test.js
  tests/utils/purl-test.js
Labels: C-enhancement ✨, A-frontend 🐹

#11472 CI: Use `cargo-binstall` for pre-compiled binary installation
  .github/workflows/ci.yml
Labels: C-internal 🔧, A-backend ⚙️
